### ISSUE TITLE
Cannot reconnect after Pi reboots

### ISSUE THREAD

**Issue by pecirep** [mariusmotea/diyHue#10]
If I reboot my Pi and rerun the python script I get following error: 

`Exception happened during processing of request from ('192.168.0.33', 44660)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_nobloc                                                                                                                                                             k
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/diyHue/BridgeEmulator/HueEmulator.py", line 643, in do_POST
    bridge_config["config"]["whitelist"][username] = {"last use date": datetime.                                                                                                                                                             utcnow().strftime("%Y-%m-%dT%H:%M:%S"),"create date": datetime.utcnow().strftime                                                                                                                                                             ("%Y-%m-%dT%H:%M:%S"),"name": post_dictionary["devicetype"]}
TypeError: 'str' object does not support item assignment
`

The Hue app then wants me to press the Push-link button on the Hue bridge to authenticate. Would it be possible to have the button press added to the python script or can the issue be resolved otherwise?

**Comment by mariusmotea** [comment]
Hi,

What startup method did you use? Very likely the script is started from a different location and for this reason config files are searched in that locations, not in the script location.

Look here my rc.local file:
cd /home/pi
./HueEmulator.py

as you can see first i change the location to /home/pi, then i execute the HueEmulator script

Marius.

**Comment by pecirep** [comment]
That is how my rc.local file looks as well, but somehow the script won't run this way and the bridge can't be found in the Hue App. In the situation above I just startet the script manually, inside the folder.

**Comment by pecirep** [comment]
I actually had a bash file that would do what your rc.local file does, which my rc.local would start, but now I changed my rc.local file to be exactly like yours and it still does not work. When I run my rc.local file manually to see the output this is what I get:
`My IP address is 192.168.0.23
config loaded
lights adress file was not loaded
server stopped
 starting ssdp...
config saved`

**Comment by mariusmotea** [comment]
Ok, but in this case i believe not the startup method is the issue but the lights_address.json file. Same issue must happen if you execute the script manually  if this file don't exist or is corrupted. If is not working when you execute manually the script then you must start again from scratch. To give you some details about this file that my help you it store the custom data that hue applications must not see, like ip of the light, type, device id, etc. Because is created automatically the owner will be root, not you user (very likely config.json is owned by you).

**Comment by mariusmotea** [comment]
please check config.json if you have this line under config object:
"whitelist": {}

or

"whitelist": {
            "some_big_string": {
                "create date": "2017-06-01T13:07:32",
                "last use date": "2017-06-01T13:07:32",
                "name": "Hue 2#HTC One_M8"
            }
 }

**Comment by pecirep** [comment]
After removing all files and downloading fresh ones  the problem stopped occuring, my phone now reconnects without a problem, my whitelist does list my phone just like in your second example, didn't check if it did before but it's fixed now, thanks!

Still can't get the script to successfully run on boot though.. :(

**Comment by mariusmotea** [comment]
If executed manually works, the issue must be with rc.local file. You can test it by changing directory to any location, for example cd /var. From there execute sudo /etc/rc.local. If this way is working then it means the rc.local file is not executed at boot and you must check if it is still linked to correct system path. If i'm not wrong this is a symbolic link to /etc/rc.d/something... Another trick is to forward the output to a log file, ex:

echo "now the hue emulator will be started" >> /var/log/hue_emulator.log
cd /home/pi
./HueEmulator.py >> /var/log/hue_emulator.log.

If you see any error paste here.

**Comment by pecirep** [comment]
This is the output in the log file:
`now the hue emulator will be started
config loaded
lights address loaded
now the hue emulator will be started
config loaded
lights address loaded
`

**Comment by pecirep** [comment]
I have been looking for the solution to this problem for the past 2 days and I am unable to understand what is causing it. I tried several different methods that run the script as the pi or the root user but nothing works, the log file always just stops at lights address loaded and that is it... starting it with cron also does not work... Running the script through ssh works perfectly fine  though. I am completely out of ideas.

**Comment by mariusmotea** [comment]
I just execute apt update and apt upgrade. After all packages where upgraded i reboot and in 15 seconds i was able to connect and control the lights. I'm using a Pi2 with raspbian jessie lite version. Did you use same installation for other projects, maybe you change something in profile.d or bashrc? If you have a spare sd card i believe is worth to try latest raspbian lite. Is python2 the default for python command? Now i'm writing from my phone, search on google to see how you can output python version from one command and add it to rc.local with output forwarded to a file. Add to rc.local also env >> /var/log/something and compare with the output of same command from your ssh session.

**Comment by pecirep** [comment]
I was using Jessie Pixel up until now. I installed Lite and now it works just fine... Which confuses me even more but I'll take it, at least it works now. Thank you for your help!
