### ISSUE TITLE
status from ESPMilightHub (ESPMH) to diyHue

### ISSUE THREAD

**Issue by kurniawan77** [mariusmotea/diyHue#100]
Hi,

Is it possible to get status updates from the ESPMH? as an example:

It works fine one way: 
 - switch on light with hue app > milights goes on, also in mqtt (espmh supports mqtt)

But the other way it doesnt update the light in hue app:
 - switch off with milight remote or mqtt > milights goes off but in the hue app status it stays on.

**Comment by mariusmotea** [comment]
Hi,

While is possible, i don't have the resources to do this, my MiLight bulbs where converted to wifi and from MiLight Hub i took the Wemos D1 mini board. If you want to try i can help you just with my knowledges.

**Comment by kurniawan77** [comment]
i would be happy to help with resourcing!

**Comment by mariusmotea** [comment]
I'm still looking to find the best approach for this because i still don't want to increase the number of dependencies (mqtt is the issue). So far i'm thinking to create a new script that will post the updates to a websocket.

**Comment by mariusmotea** [comment]
Can you tell me if your MQTT broker is located on same host as HueEmulator, and if is able to publish the updates in more ways than MQTT protocol (socket file, websocket, etc) ?

**Comment by kurniawan77** [comment]
I have my MQTT broker on an other host then HueEmulator. I use Mosquitto as broker. It's possible to use MQTT over websocket but i don't believe that the broker could publish in an other protocol then MQTT. 

But looking at Sidoh's ESPMH, REST endpoints:

10. GET /gateways/:device_id/:device_type/:group_id. Returns a JSON blob describing the state of the provided group.

isn't this what we need?

**Comment by kurniawan77** [comment]
or maybe this:
https://github.com/azhu2/mqtt-hue-client

**Comment by mariusmotea** [comment]
Can you provide me various output examples of this? 

`GET /gateways/:device_id/:device_type/:group_id. Returns a JSON blob describing the state of the provided group`

This can be the best and easy way.

**Comment by kurniawan77** [comment]
easy... no prob

I guess with this way, HueEmulator needs to poll every 30 seconds or so?


`GET /gateways/0x5712/rgbw/3`   returns:
`{"state":"ON","brightness":194,"level":76,"color":{"r":255,"g":255,"b":255}}`

In ESPMH we can choose which state could be published:
![image](https://user-images.githubusercontent.com/3305888/33219991-b0992b12-d145-11e7-8458-d37cfe967175.png)

When all is selected it returns:
`{"state":"ON","status":"ON","brightness":194,"level":76,"bulb_mode":"white","color":{"r":255,"g":255,"b":255}}
`
Nightmode
`{"state":"ON","status":"ON","brightness":163,"level":64,"bulb_mode":"night","color":{"r":255,"g":255,"b":255}}
`
Off
`{"state":"OFF","status":"OFF","brightness":163,"level":64,"bulb_mode":"white","color":{"r":255,"g":255,"b":255}}
`
Red ish
`{"state":"ON","status":"ON","brightness":163,"level":64,"hue":350,"color":{"r":255},"bulb_mode":"color"}
`
Other settings:
![image](https://user-images.githubusercontent.com/3305888/33220122-3e575870-d146-11e7-9f0d-3017dc474d8c.png)

`{"state":"ON","level":64,"color":{"r":0,"g":255,"b":102},"bulb_mode":"color"}
`
![image](https://user-images.githubusercontent.com/3305888/33220207-b3abc138-d146-11e7-98a7-b5b7057ed302.png)

`{"state":"ON","level":64,"hue":344,"bulb_mode":"color","color":{"r":255,"g":0,"b":67}}
`

**Comment by kurniawan77** [comment]
From an other:

`/gateways/0x1081/rgb_cct/4`

`{"state":"ON","level":100,"kelvin":57,"bulb_mode":"white","color":{"r":255,"g":255,"b":255}}`

`{"state":"ON","brightness":255,"color_temp":277,"bulb_mode":"white","color":{"r":255,"g":255,"b":255}}`

**Comment by mariusmotea** [comment]
Hi,

I pull devices status updates only when there is a request to /lights, not at a specific interval of time. I made a new commit in develop branch, but for the moment i add updates just for On/Off, brightness and color temperature. Color will be hard because require conversion from rgb to xy that i don't perform so far, i don't have the formula. From milight hue to philips hue is not a big deal.

**Comment by kurniawan77** [comment]
Hi,

You are fast! 

I am starting off fresh with my raspi2 with a clean raspbian stretch (still running wheezy), so after that i will get the HueEmulator running on it. Will be testing this coming weekend.

**Comment by kurniawan77** [comment]
Goodevening

just did a quick test

brightness works but on/off doesn't. i think this happening because when sending on/off commands with Milight remote or mqtt the brightness doesn't get updated:

Off
`{"state":"OFF","status":"OFF","brightness":163,"level":64,"bulb_mode":"white","color":{"r":255,"g":255,"b":255}}`

**Comment by kurniawan77** [comment]
just reporting some crazy stuff:

because it doesnt turn off in the hue app, i can't turn the lights off in the frontend ui of home-assistant. It toggles back on.... the lights do go off luckily.

**Comment by mariusmotea** [comment]
I fount one mistake

```
                if light_data["state"] == "ON":
                    bridge_config["lights"][light]["state"]["on"] = True
                else:
                    bridge_config["lights"][light]["state"]["on"] = False
```

previews was True instead False. Please correct and test again.

**Comment by kurniawan77** [comment]
Works!

**Comment by kurniawan77** [comment]
Hi,

Sidoh showed this library https://github.com/Q42Philips/hue-color-converter. Maybe it helps?

**Comment by mariusmotea** [comment]
There is a formula on Hue API page:

> Get the RGB values from your color object and convert them to be between 0 and 1. So the RGB color (255, 0, 100) becomes (1.0, 0.0, 0.39)
> Apply a gamma correction to the RGB values, which makes the color more vivid and more the like the color displayed on the screen of your device. This gamma correction is also applied to the screen of your computer or phone, thus we need this to create a similar color on the light as on screen. This is done by the following formulas:
> 
> float red = (red > 0.04045f) ? pow((red + 0.055f) / (1.0f + 0.055f), 2.4f) : (red / 12.92f);
> float green = (green > 0.04045f) ? pow((green + 0.055f) / (1.0f + 0.055f), 2.4f) : (green / 12.92f);
> float blue = (blue > 0.04045f) ? pow((blue + 0.055f) / (1.0f + 0.055f), 2.4f) : (blue / 12.92f); 
> Convert the RGB values to XYZ using the Wide RGB D65 conversion formula The formulas used:
> 
> float X = red * 0.664511f + green * 0.154324f + blue * 0.162028f;
> float Y = red * 0.283881f + green * 0.668433f + blue * 0.047685f;
> float Z = red * 0.000088f + green * 0.072310f + blue * 0.986039f;
> Calculate the xy values from the XYZ values
> 
> float x = X / (X + Y + Z);
> float y = Y / (X + Y + Z);
> Check if the found xy value is within the color gamut of the light, if not continue with step 6, otherwise step 7 When we send a value which the light is not capable of, the resulting color might not be optimal. Therefore we try to only send values which are inside the color gamut of the selected light.
> 
> Calculate the closest point on the color gamut triangle and use that as xy value The closest value is calculated by making a perpendicular line to one of the lines the triangle consists of and when it is then still not inside the triangle, we choose the closest corner point of the triangle.
> 
> Use the Y value of XYZ as brightness The Y value indicates the brightness of the converted color.

i just need some time to implement it.

**Comment by mariusmotea** [comment]
I push one update now in develop branch. This future is untested, if will not work i will need output to see what is the problem. Other changes pushed there are tested (backup config every Sunday, multi-treading  webserver, etc.)

**Comment by kurniawan77** [comment]
Not yet... will give it a try this week
