### ISSUE TITLE
Control of Milights using Milight Bridge

### ISSUE THREAD

**Issue by skyfoxdesign** [mariusmotea/diyHue#103]
Thought I'd create a new question for this:

With regards to the milight integration - how come this requires hacking of the lights, and not just the use of the standard code for changing them via UDP as homebridge-milight and various other systems integrate them?

For instance, I have over 30 bulbs in my home and I don't want to mod them all. With control I use siri and homebridge, but I want some to be controlled through the hue apps, and with my raspberry pi using your diyHue, it seem that this is extremely close but excludes the common way threse bulbs are controlled.

Is there a way to add this functionality in?

**Comment by mariusmotea** [comment]
Hi,

MiLight use proprietary 2.4ghz and cannot be controlled directly from your local network. Hacking the lights is recommended, but not mandatory, you can also build the milight hub device, that is like a bridge between your network and this  2.4ghz proprietary protocol.

Why i convert my bulbs to eps8266:
 - at that time i still use classic switches, and 2 way light synchronisation was useful for me
 - i wanted the option to setup a startup scene when light is powered on
 - transitiontime attribute is required for Go To Sleep and Wake Up functions.

**Comment by skyfoxdesign** [comment]
Having the extra features would be handy, but for basic control, what if you already have a wifi bridge for them? I'm using two milight bridges to control both my sets of lights - This operates on UDP, and I can send commands to it, as I do with my homebridge setup. Is there a way to combine this with your diyHue?

**Comment by mariusmotea** [comment]
Only someone with python skills and that own some milight bulbs paired to milight bridge can help here. I don't have both in this moment and my Milight bulbs are in use and cannot be converted back easy.

**Comment by skyfoxdesign** [comment]
No worries. Hopefully, someone with the necessary skills will spot this!

If it helps, the breakdown of the commands for the wifi bridge is here: http://www.limitlessled.com/dev/

**Comment by richardtrip** [comment]
I own two milight bridges but I'm glad I did build the milight hub device. The combo with this diyhue is perfect.

**Comment by pauleec** [comment]
@marius - I have an 8 zone full color RGB-CCT mixed light type (downlighters, spotlights, bulbs and LED strip controller )environment and would be happy to test anything here that would help improve the support for Full Color Milights operating in 8 zones from a single bridge controller. The lights are also configured to work with the (Mi-Light proprietary 8 zone 2.4Ghz control protocol) B8 remote and 8 zone panel remote as well as the new single zone panel which is 8-zone compatible. Its worth pointing out that the 4 zone remotes (panel and handheld) that are used to control the RGB-CCT lights are not currently compatible with the 8-zone remotes/8 zone bridge configurations. Part of the app setup forces the user to select one remote type. It appears that the older 4-zone protocol built for pre-June 2016 manufactured 4-zone lights (ie some of the RGB-CCT manufactured before June2016 only work in 4 zones and are not 8-zone ready). 4-zone Lights and controllers can cause some interesting random results when used in an 8-zone light configuration. (I have been experimenting with 4-zone remotes working in 8-zone lighting configurations and find some lights in other zones can be switched on or put into a mode for example. The older 4-zone RGB-CCT bulbs are difficult to pair with 8 zone controllers and once paired do not operate as they should).

**Comment by cheesemarathon** [comment]
Closing this issue as you can just use [this](https://github.com/sidoh/esp8266_milight_hub) to control Mi-Lights with no modification

**Comment by oibctl** [comment]
Hey Pauleec,
I am using the milight FUT104 lights in my yards (front and rear).  I have installed them in waterproof housings.  They respond well to the remote control I am using.  i am in the middle of refining the placement and will have approximately 40 of a combination of spot and well lights.  I attempted to use the 2.0 Bridge and ran into some IP address issues and as well, concerned about the security issues of that device.  I have been searching for a solution to include using aduino/rasperry pi etc.  Although I have some electronic background, I am trying to find a relatively easy, less labor intensive/simple way  to control them from my phone as well as have the ability to set timers.  I would also most likely need more than 4 zones.  Based on that, do you have any suggestions  on how I should proceed? Any assistance would be appreciated!  Thanks in advance!

**Comment by mariusmotea** [comment]
@oibctl If you want security one option is to convert the bulbs to wifi like i already did [here](https://github.com/mariusmotea/diyHue/raw/master/Images/MiLight_RGB_CCT_converted_to_ESP-12S.jpg). The firmware that i provide works with this hue emulator but they also have an internal webgui witch allows you to perform some commands.

**Comment by oibctl** [comment]
Thanks for the response. Your solution would entail opening 40 bulbs, installing new chips etc right?  I am trying not to do anything
Like
That. I am thinking it maybe feasible to use the Rf controller board and control it
With Arduino o or raspberry pi. 

Sent from my iPhone

On Nov 1, 2018, at 13:01, Motea Marius <notifications@github.com> wrote:

@oibctl If you want security one option is to convert the bulbs to wifi like i already did here. The firmware that i provide works with this hue emulator but they also have an internal webgui witch allows you to perform some commands.

**Comment by mariusmotea** [comment]
I saw the big number of bulb but that controller speak on a language the is not encrypted. I'm not really sure what is more efficient, writing new firmware for the current installed controller with encryption built in or to replace the chip with one that has firmware already developed. In both cases is not easy.
