### ISSUE TITLE
Apple Homekit 

### ISSUE THREAD

**Issue by diasrobson** [mariusmotea/diyHue#105]
Can I contact this to my apple HomeKit system or can I only use the hue app

**Comment by mariusmotea** [comment]
i'm totally unaware of how Apple HomeKit is working. I also use Android phone.

**Comment by bbgehring** [comment]
So the in app settings the HomeKit & Siri pairing will be nonfunctional? As of now it says its unable to find the hue bridge.

**Comment by mariusmotea** [comment]
Is possible to be a used a different protocol than Philips Hue and i'm not aware how this is working.

**Comment by mariusmotea** [comment]
Can you provide sample output of HueEmulator.py script when you try to pair with HomeKit?

**Comment by Wqrld** [comment]
maybe look into HAP? That allows you to make fake homekit devices which with should be relatively easy to implement into diyhue

**Comment by mariusmotea** [comment]
I believe something is already done. Check this https://github.com/ebaauw/homebridge-hue . I have just a Macbook and i don't believe i can test this. I guess only somebody with iphone can do it.

**Comment by Wqrld** [comment]
/ipad :) i am going to charge my old ipad now and maybe i can get it to connect to the homebridge>fake hue> lights

**Comment by mariusmotea** [comment]
any progress here?

**Comment by Wqrld** [comment]
i've tried getting homebridge-hue to work but it has a weird install loop on dns_sd

**Comment by mariusmotea** [comment]
Erik Baauw is a nice guy, already provided me some help with Deconz and i believe it will provide even better support for his own software.

**Comment by francescofact** [comment]
So, are there any news on how to connect to diyHue with HomeKit?

**Comment by mariusmotea** [comment]
Try homebridge-hue. If is not working maybe you can open issue to have this working.

Marius,

**Comment by francescofact** [comment]
Tried, but i don't understand how to setup a bridge (like diyHue) after i installed both homebridge and the plugin homebridge-hue

**Comment by mariusmotea** [comment]
i don't have an iPhone to help here.

**Comment by maxakuru** [comment]
I can confirm this is working 👍 
- Install Homebridge: https://github.com/nfarina/homebridge
- Install Homebridge-Hue: https://github.com/ebaauw/homebridge-hue
- edit Homebridge config: `sudo nano ~/.homebridge/config.json`
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "Hue",
      "users": {
      },
      "lights": true,
      "host": "192.168.1.99"
    }
  ]
}
```
where `host` is the IP of Pi running diyHue

- run `homebridge`
- pair to Homekit

Done :)

**Comment by cheesemarathon** [comment]
As this has been confirmed working, with detailed setup instructions, I will close this
