### ISSUE TITLE
Not detecting innr smart bulbs

### ISSUE THREAD

**Issue by nmawer** [mariusmotea/diyHue#106]
Hi there,

I'll point out from the very beginning that I'm a complete noob where linux is concerned so apologies if I've missed something.

Firstly, let me congratulate you on a great job!!

I installed Debian 9 and followed the Getting Started instructions to get the HueEmulator service running.
I used a command I saw in another issue to modify the mac address of my ethernet card to reflect the same mac address as a real Philips Hue, but I cannot get the Hue App to detect my innr smartbulbs.  I'm following the Press Search -> Cycle bulb off->on (double blink) but they're never detected.

For some reason the Hue App doesn't automatically detect the Hue Emulator, I can only connect when I manually enter the ip so not sure if that may be part of the issue, or if these bulbs are just not supported.

Its working as status call shows following, 192.168.0.11 is the mobile with the Hue App installed:

nmawer@debian-PC:~/Downloads$ sudo systemctl status hue-emulator.service
● hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2017-11-25 09:42:50 GMT; 2min 22s ago
 Main PID: 4107 (HueEmulator.py)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/hue-emulator.service
           └─4107 /usr/bin/python2.7 /home/nmawer/Downloads/diyHue/BridgeEmulator/HueEmulator.py

Nov 25 09:44:52 debian-PC HueEmulator.py[4107]: 192.168.0.11 - - [25/Nov/2017 09:44:52] "GET /api/a7161538be80d40b3de98dece6e
Nov 25 09:44:52 debian-PC HueEmulator.py[4107]: 192.168.0.11 - - [25/Nov/2017 09:44:52] "GET /api/a7161538be80d40b3de98dece6e
Nov 25 09:44:52 debian-PC HueEmulator.py[4107]: 192.168.0.11 - - [25/Nov/2017 09:44:52] "GET /api/a7161538be80d40b3de98dece6e
Nov 25 09:44:52 debian-PC HueEmulator.py[4107]: 192.168.0.11 - - [25/Nov/2017 09:44:52] "GET /api/a7161538be80d40b3de98dece6e
Nov 25 09:44:52 debian-PC HueEmulator.py[4107]: 192.168.0.11 - - [25/Nov/2017 09:44:52] "GET /api/a7161538be80d40b3de98dece6e
Nov 25 09:44:52 debian-PC HueEmulator.py[4107]: 192.168.0.31 - - [25/Nov/2017 09:44:52] "GET /description.xml HTTP/1.1" 200 -
Nov 25 09:44:53 debian-PC HueEmulator.py[4107]: 192.168.0.31 - - [25/Nov/2017 09:44:52] "GET /description.xml HTTP/1.1" 200 -
Nov 25 09:44:53 debian-PC HueEmulator.py[4107]: 192.168.0.11 - - [25/Nov/2017 09:44:53] "GET /api/a7161538be80d40b3de98dece6e
Nov 25 09:44:54 debian-PC HueEmulator.py[4107]: 192.168.0.11 - - [25/Nov/2017 09:44:54] "GET /api/a7161538be80d40b3de98dece6e
Nov 25 09:44:54 debian-PC HueEmulator.py[4107]: 192.168.0.11 - - [25/Nov/2017 09:44:54] "GET /api/a7161538be80d40b3de98dece6e

Hopefully there's a solution but as I say, I'm a complete linux noob so I'd be really grateful if you'd take that into account when with any instructions.

Many thanks!!!

**Comment by mariusmotea** [comment]
Hi,
I'm not sure why hue app don't detect the emulator automatically, but innr smartbulbs looks to be zigbee lights that cannot be controller directly from LAN network and require extra bridge device. I believe you already have such device in you home, but is not one from supported list (tradri gateway, real hue bridge or raspbee module for raspberry pi).

Marius.

**Comment by nmawer** [comment]
Appreciate the prompt update.  U fortunate but at least I don't have to drive .yself crazy trying to figure it out.
