### ISSUE TITLE
Philips Hue Tap Switch support

### ISSUE THREAD

**Issue by aivs** [mariusmotea/diyHue#109]
Hi, I have a Philips Hue Tap Switch, can I catch clicking in script?
If it possible can you show how I can catch clicking from button #1, button #2, button #3.

I plan to use RaspBee without Philips Hue Hub.

**Comment by mariusmotea** [comment]
Hi,
If deconz don't alter any attributes of the Hue Tap Switch, then you will be able to configure from Philips Hue application like if you are using the original Hue Bridge.
