### ISSUE TITLE
regarding the dimmer switch 

### ISSUE THREAD

**Issue by lennarkivistik** [mariusmotea/diyHue#112]
Hi, awesome work marius,

I seem to be missing something but how does the circuit work at BAV99 the signal diode switch. in Hue_Tap-Dimmer_switch_circuit_prototype.png

i've tried the circuit with a normal diode in this [prototype in falstad](http://www.falstad.com/circuit/circuitjs.html?cct=$+1+0.000005+1.8479586061009856+50+5+50%0AR+720+80+656+80+0+0+40+3.3+0+0+0.5%0Aw+720+80+720+96+0%0Aw+720+96+784+96+0%0Aw+784+96+848+96+0%0Aw+848+96+912+96+0%0As+720+96+720+192+0+1+true%0As+784+96+784+192+0+1+true%0As+848+96+848+192+0+1+true%0As+912+96+912+192+0+1+true%0Aw+1104+160+1104+224+0%0Aw+1104+304+1152+304+0%0Aw+1184+160+1216+160+0%0Aw+1184+304+1312+304+0%0Aw+1312+304+1312+224+0%0At+1216+160+1248+160+0+1+-5.290315230460607+-0.41010453844154265+100%0At+1248+208+1312+208+0+1+-3.180210692019064+0.1197893079809358+100%0Ar+1104+224+1104+304+0+100000%0Ar+1184+304+1184+224+0+100000%0Aw+1184+224+1184+160+0%0AL+1248+144+1392+144+0+1+false+5+0%0Ac+1104+160+1184+160+0+1.0000000000000001e-7+0.58063047159096%0Ag+1152+304+1152+352+0%0Aw+1152+304+1184+304+0%0Aw+1248+176+1248+208+0%0AL+1312+192+1408+192+2+1+false+3.3+0%0AM+720+192+736+192+0+2.5%0AM+784+192+800+192+0+2.5%0AM+848+192+864+192+0+2.5%0AM+912+192+928+192+0+2.5%0Aw+720+192+720+240+0%0Aw+784+192+784+240+0%0Aw+848+192+848+240+0%0Aw+912+192+912+240+0%0Ad+720+240+720+320+1+0.805904783%0Ad+784+240+784+320+1+0.805904783%0Ad+848+240+848+320+1+0.805904783%0Ad+912+240+912+320+1+0.805904783%0Aw+720+320+784+320+0%0Aw+784+320+848+320+0%0Aw+848+320+912+320+0%0Aw+912+320+960+320+0%0Aw+960+320+960+160+0%0Aw+960+160+1104+160+0%0Ax+1423+196+1443+199+4+10+RST%0Ax+1406+147+1442+150+4+10+GPIO16%0Ax+728+213+758+216+4+10+GPIO1%0Ax+792+214+822+217+4+10+GPIO3%0Ax+919+213+949+216+4+10+GPIO4%0Ax+854+214+884+217+4+10+GPIO5%0Ao+24+64+0+4867+3.3+747.1254454825915+0+2+24+3%0Ao+13+64+0+4099+0.0000762939453125+409.6+1+2+13+3%0Ao+11+64+0+4099+5+0.05+2+2+11+3%0A) to simulate, and all seems to be working as indented just that all of the buttons get high if one of them is high as one would presume... As the voltage would still be in the full circuit even if the current is not there, so how do the [BAV99](https://www.vishay.com/docs/85718/bav99.pdf) work in this situation? this has been boggling my mind after looking at your circuit.. 🦊

**Comment by mariusmotea** [comment]
Hi,
Without these diodes once you press one button you will send HIGH signal to all gpio pins, not only to the one that is pointed to that button. I tried to avoid them, but i did not find any solution. The main issue is that a short signal to RST must be applied on every button press to wake up the ESP from deep sleep mode.

**Comment by mariusmotea** [comment]
I add one resistor with value of 1M from one gpio to ground and it did not change anymore to HIGH when i press other buttons. If you face any issues then you can add extra resistors to pull down the gpio pins.

**Comment by lennarkivistik** [comment]
Hah wow, that actually worked great Tried it out on a breadboard and in [falstad](http://www.falstad.com/circuit/circuitjs.html?cct=$+1+0.000005+1.8479586061009856+50+5+50%0AR+720+96+720+64+0+0+40+3.3+0+0+0.5%0Aw+720+96+784+96+0%0Aw+784+96+848+96+0%0Aw+848+96+912+96+0%0As+720+96+720+208+0+1+true%0As+784+96+784+208+0+1+true%0As+848+96+848+208+0+1+true%0As+912+96+912+208+0+1+true%0Aw+1104+160+1104+224+0%0Aw+1104+304+1152+304+0%0Aw+1184+160+1216+160+0%0Aw+1184+304+1312+304+0%0Aw+1312+304+1312+224+0%0At+1216+160+1248+160+0+1+-5.634441008566451+-0.7541182482956148+100%0At+1248+208+1312+208+0+1+-3.0803227602708367+0.11967723972916344+100%0Ar+1104+224+1104+304+0+100000%0Ar+1184+304+1184+224+0+100000%0Aw+1184+224+1184+160+0%0AL+1248+144+1392+144+0+1+false+5+0%0Ac+1104+160+1184+160+0+1.0000000000000001e-7+1.200309719705674%0Ag+1152+304+1152+352+0%0Aw+1152+304+1184+304+0%0Aw+1248+176+1248+208+0%0AL+1312+192+1408+192+0+0+false+3.3+3.2%0AM+720+208+736+208+0+2.5%0AM+784+208+800+208+0+2.5%0AM+848+208+864+208+0+2.5%0AM+912+208+928+208+0+2.5%0Aw+912+288+912+320+0%0Ad+912+208+912+288+1+0.805904783%0Aw+720+320+784+320+0%0Aw+784+320+848+320+0%0Aw+848+320+912+320+0%0Aw+912+320+960+320+0%0Aw+960+320+960+160+0%0Aw+960+160+1104+160+0%0Ax+1423+196+1443+199+4+10+RST%0Ax+1406+147+1442+150+4+10+GPIO16%0Ax+724+194+754+197+4+10+GPIO1%0Ax+790+195+820+198+4+10+GPIO3%0Ax+916+195+946+198+4+10+GPIO4%0Ax+852+194+882+197+4+10+GPIO5%0Ar+832+400+832+336+0+100000%0Ar+768+400+768+336+0+100000%0Ar+704+400+704+336+0+100000%0Aw+848+288+848+320+0%0Aw+784+288+784+320+0%0Aw+720+288+720+320+0%0Ad+848+208+848+288+1+0.805904783%0Ad+784+208+784+288+1+0.805904783%0Ad+720+208+720+288+1+0.805904783%0Ar+896+336+896+400+0+100000%0Aw+720+208+704+208+0%0Aw+784+208+768+208+0%0Aw+848+208+832+208+0%0Aw+912+208+896+208+0%0Aw+768+208+768+336+0%0Aw+832+208+832+336+0%0Aw+896+208+896+336+0%0Aw+704+208+704+336+0%0Aw+704+400+768+400+0%0Aw+768+400+832+400+0%0Aw+832+400+896+400+0%0Aw+976+400+896+400+0%0Aw+976+304+1104+304+0%0Aw+976+400+976+304+0%0Ao+23+64+0+4867+3.3+373.5627227412958+0+2+23+3%0Ao+12+64+0+4099+0.0000762939453125+409.6+1+2+12+3%0Ao+10+64+0+4099+2.5+0.05+2+2+10+3%0Ao+49+64+0+4099+5+0.00009765625+3+2+49+3%0A), used 100K resistors as it was what I had laying around and it worked nicely! Thanks!!
