### ISSUE TITLE
Hue hello app

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#116]
This app for android works with this project. At least the basic controls. I dont have any colored strips mounted at the moment so i cant test the scenes in a meaningful way. It doesnt seem to autodetect the hub, you have to input the ip adress manually.

https://play.google.com/store/apps/details?id=com.prodpeak.huehello

**Comment by mariusmotea** [comment]
This is a nice looking app. For me autodiscover was working, no need to specify the ip manually. I was able to control my colour bulbs.
