### ISSUE TITLE
Unable to add diyhue bridge to smartthings

### ISSUE THREAD

**Issue by subnoize417** [mariusmotea/diyHue#117]
As we were discussing in #95 I'm having trouble getting the smartthings hub to recognize the emulated diyhue bridge. Other apps can discover the bridge and are working correctly. Currently running diyhue on an Ubuntu VM on a ESXi server, with 2 esp8266 sk6812 lights, and the lights from my real hue bridge. Raspberry Pi 3 is also available for testing if it makes a difference

**Comment by mariusmotea** [comment]
Can you confirm that with last commit in develop branch you have identical curl output for both original and emulated bridge on /description.xml?

**Comment by subnoize417** [comment]
Looks like your latest develop commit fixed it! Thank you very much, alexa controlled color settings was the last piece of the puzzle for my project, and now it'll work
