### ISSUE TITLE
Remote DECONZ and ConBee support

### ISSUE THREAD

**Issue by CaCu15** [mariusmotea/diyHue#121]
Greetings Marius,

your project looks really promising. After I had some problems with incompatibilities of various products from Phillips, OSRAM etc. this looks like it will help to get everything connected with one single gateway. 

But before I'll give it a try and invest some money in a RaspBee gateway I've got some questions: 
According to your guide in the wiki the diyHue emulator works with DECONZ and the RaspBee module. I would like to run DECONZ and diyHue in separate virtual machines on a ProxMox virtualization server. Hence I've got the following questions:
1) Is it possible to connect your diyHue emulator to a DECONZ instance running on a remote host? If I understand it correctly you are accessing DECONZ using the REST-API, hence I assume it should feasible. Instead of using LocalHost it would need to direct the REST requests to a remote IP.
2) Because the RaspBee module can't be used in a VM I would like to use the ConBee module offered by Dresden Elektronik. This module is connected as an USB stick and can be passed to a VM. Do you know of any problems with this setup? If you are communicating with ZigBee devices over the DECONZ REST-API only, than it should not matter which type of ZigBee module is used by DECONZ, correct?

Thanks for your help
Carsten

**Comment by mariusmotea** [comment]
Hi,

1. Despite localhost address is hardened in python script, this can be replaced very easy with search and replace on deconz functions. It must work.
2. I believe ConBee module is just one Raspbee module connected to an usb to serial adapter. Here important is the ability of proxmox to passthru the usb device. Given the low transfer speed rate i believe it will work.

Marius.

**Comment by CaCu15** [comment]
Hello Marius,

thx for the quick reply. Just ordered the HW. Hope it'll arive before Christmas. 

Greetings
Carsten
