### ISSUE TITLE
Hue app says update is available again

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#124]
I cant for the life of me remember where i edited the file on the emuator to fool it thinking its latest version again.

**Comment by kurniawan77** [comment]
Config.json file

Change swversion to 1711151408

**Comment by mariusmotea** [comment]
In the future you will not need to do this manually. I create a [file](https://github.com/mariusmotea/diyHue/blob/master/BridgeEmulator/updater) that will patch the configuration automatically when you click "update" button in hue application (first time will say that update has failed, but second time will work). Problem is that i don't have a hue bridge so i need to find out what is the last swversion. Maybe guys with hue bridged devices will create pull requests and edit this file manually for us.

**Comment by erazor666** [comment]
Thanks a lot guys! :)

**Comment by mariusmotea** [comment]
with this [commit](https://github.com/mariusmotea/diyHue/commit/ffeb87ab65de44774ec1addb915ac806abb2d012) you must not have this issue in future, just remember that first time will say that update was failed (not sure what is the output of success update operation), but second time will check again swversion and will say that update was successful.
