### ISSUE TITLE
Sample config File

### ISSUE THREAD

**Issue by viks2015** [mariusmotea/diyHue#126]
Can you please provide a sample config file with relevant data filled

**Comment by mariusmotea** [comment]
What kind of informations are you looking for? Some issues from here have configuration provided in order to debug. config.json file is in 90% of cases populated automatically. You need to edit manually just in case you use alarm future or you have an error that must be manually fixed. Default file is available in repo and contain just the mandatory fields.

**Comment by viks2015** [comment]
what is lights_address for , i did not find it in philips hue api

**Comment by mariusmotea** [comment]
This is custom one to link every light to his address, and here the options are:
 - esp8266 lights = ip address, light id
 - milight_hub = ip of the hub, channel, bulb_type and remote id
 - trandfri gateway = gateway ip, light id, security key
 - Philips Hue Bridge / Deconz = bridge ip, light id, username

mine is looking like this:

```
    "lights_address": {
        "1": {
            "ip": "192.168.10.22",
            "light_nr": 1,
            "protocol": "native"
        },
        "10": {
            "ip": "127.0.0.1:8080",
            "light_id": "4",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        },
        "11": {
            "ip": "127.0.0.1:8080",
            "light_id": "7",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        },
        "12": {
            "ip": "127.0.0.1:8080",
            "light_id": "6",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        },
        "14": {
            "ip": "127.0.0.1:8080",
            "light_id": "8",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        },
        "2": {
            "ip": "192.168.10.30",
            "light_nr": 1,
            "protocol": "native"
        },
        "3": {
            "ip": "192.168.10.30",
            "light_nr": 2,
            "protocol": "native"
        },
        "4": {
            "ip": "192.168.10.30",
            "light_nr": 3,
            "protocol": "native"
        },
        "5": {
            "ip": "192.168.10.32",
            "light_nr": 1,
            "protocol": "native"
        },
        "6": {
            "ip": "127.0.0.1:8080",
            "light_id": "1",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        },
        "7": {
            "ip": "127.0.0.1:8080",
            "light_id": "3",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        },
        "8": {
            "ip": "127.0.0.1:8080",
            "light_id": "2",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        },
        "9": {
            "ip": "127.0.0.1:8080",
            "light_id": "5",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        }
```
Marius.

**Comment by viks2015** [comment]
ok thanks for information. Great Work

**Comment by viks2015** [comment]
If I want to include color change which lights should I use

**Comment by mariusmotea** [comment]
you are using this not in a normal way. These fields must be populated automatically when lights are discovered. To add all informations by hand is painful. 

Here is one of my rgb light:

```
        "5": {
            "modelid": "LCT001",
            "name": "Dormitor Mic",
            "state": {
                "alert": "none",
                "bri": 254,
                "colormode": "ct",
                "ct": 447,
                "effect": "none",
                "hue": 0,
                "on": false,
                "reachable": false,
                "sat": 0,
                "transitiontime": 9,
                "xy": [
                    0.0,
                    0.0
                ]
            },
            "swversion": "66009461",
            "type": "Extended color light",
            "uniqueid": "4a:e0:ad:7f:cf:5c-1"
        },
```
This is under "lights" key in config.json, not under lights_address

**Comment by viks2015** [comment]
I am actually not using actual lights but activating various linux scripts based from commands give to Amazon echo.
Can you change the colour of your hue lights using Amazon echo ?

**Comment by mariusmotea** [comment]
Hmm, this is hard for me to tell, i don't own/use Alexa, all i know is that some futures require remote api using Philips cloud services and this do not work with any emulator. If your light "modelid" is "LCT001", then this is a color light. I will provide my config that has also two ikea tradfri color bulbs, maybe it will work.

https://pastebin.com/cbYP1YBJ

**Comment by haymaan** [comment]
please one more thing how can i add my milight hub to the diyhue  ..?
