### ISSUE TITLE
NOOB needs help

### ISSUE THREAD

**Issue by Elfnoir** [mariusmotea/diyHue#132]
Hi, thanks for your great job !
I have several questions, and sorry if it's too Noob questions...
I followed 2 ways to implement your work but it didn't suceed.
First way is through GitHub : I copy your repository on my Raspberry Pi, and try to launch the Python file 'HueEmulator.py', and I received this log, and don't know which adress do I have to change:
$ sudo ./HueEmulator.py
Config loaded
starting ssdp...
start ssdp broadcast
sync with lights
server stopped [Errno 98] Address already in use
config saved

I have already a Bridge Hue on my network, but unplugged it in case of, with same results...
In the file config.json, I change the gateway adress to my home router gateway, and changed the ipadress to the Raspberry IP adress.

Second one: on this video: https://www.youtube.com/watch?time_continue=1&v=izCzEavYxUY
you asked to tap this line:
 $ sudo cp -r HueBridge/www/. /var/www/html/
cp: cannot stat 'HueBridge/www/.': No such file or directory
Unfortunately, I don't know what do I have to do with this message :-(

Also, when all will be ok, I read that I can transfer the Tap configured in the HueBridge to real Philips Hue Bridge? Because I would like to command my lamps with Google Home !

Many thanks if someone can help me :-D

**Comment by mariusmotea** [comment]
Hi,

Ignore that youtube video, i add in description that is totally outdated. You did a good job on first try, but for some reasons something else is using port 80, that is mandatory for HueEmulator to work. Did you install apache2? If yes then stop it or remove it. To find what is using that port execute `sudo netstat -lntp | grep 80`, stop that service and then execute again `sudo ./HueEmulator.py`

**Comment by Elfnoir** [comment]
Hi,
Thanks for your feedback, it works now: Appache2 was installed! I can follow my implementation.

Regarding the TapSwitch, if I understood well, we can declare it with Hue Bridge on Raspberry, and once created it is possible to transfer/declare it also on official Hue Bridge? Or maybe I'm wrong?
Thanks for support.

**Comment by mariusmotea** [comment]
Emulated bridge can control only the lights on original bridge. If you create the circuit for TapSwitch, it will be created just on emulated bridge, but you can setup to control also the lights from original bridge
