### ISSUE TITLE
Error - Config loaded, server stopped 'bri',config saved

### ISSUE THREAD

**Issue by miranthajayatilake** [mariusmotea/diyHue#134]
Hi,

I had HueEmulator.py running nicely in RPi. I didn't configure it to bootup with the startup. I was running it by calling `sudo python HueEmulator.py`

But I shutdown the RPi while it was running. and Now when I try run it again it gives the error

`Config loaded
server stopped 'bri'
config saved`

Can someone explain why this is and what should be done. Thank you.

**Comment by mariusmotea** [comment]
I guess this is identical with #131 , so just download the last HueEmulator.py from this repo again, it contain a fix.

**Comment by miranthajayatilake** [comment]
Thanks @mariusmotea for the prompt reply. Your project is really cool! Thumbs up!
