### ISSUE TITLE
Generic RGBW esp8266 wiring question

### ISSUE THREAD

**Issue by miranthajayatilake** [mariusmotea/diyHue#135]
I was trying to solder a esp8266 to a Generic RGBW wifi light. The light is shown in the picture below

![img_7510](https://user-images.githubusercontent.com/11708057/34482564-d334cc8c-efde-11e7-8796-ff439b020b6b.JPG)
 
As I understand the RGBW pins have to be soldered to those in the code

```
uint32 io_info[PWM_CHANNELS][3] = {
  // MUX, FUNC, PIN
  {PERIPHS_IO_MUX_MTDI_U,  FUNC_GPIO12, 12},
  {PERIPHS_IO_MUX_MTCK_U,  FUNC_GPIO13, 13},
  {PERIPHS_IO_MUX_MTMS_U,  FUNC_GPIO14, 14},
  {PERIPHS_IO_MUX_GPIO5_U, FUNC_GPIO5 ,  5},
};
```
But how does the on/off work? What GPIO trigger on/off and where should it be connected to?
Thanks.

**Comment by mariusmotea** [comment]
There is no ON/OFF here, PWM is used to control the brightness level, when you turn off the light the PWM level will be set to 0, so the leds will be turned off.

**Comment by mariusmotea** [comment]
Be aware of the power level you have on bulb voltage regulator, esp8266 eat more power than bluetooth or other similar technologies. Put at last one extra 47uF capacitor on power that can avoid esp resets. I used micro buck converters on my converted bulbs to be sure there is no power or heat issue.
