### ISSUE TITLE
schedulerProcessor crashes because of timeout

### ISSUE THREAD

**Issue by stloewen** [mariusmotea/diyHue#136]
Hi @mariusmotea ,
great project. Thanks for your awesome work and for sharing it!

I just tried setting a wake-up routine using the official hue app.
Setting it worked, and it also triggered and the light went on very briefly. But then the `schedulerProcessor` crashes with a timeout and the light is turned off again.

Here is the excerpt from the logs containing the Exception:
```
execute schedule: 2 withe delay 0
127.0.0.1 - - [02/Jan/2018 21:50:00] "PUT /api/a7161538be80d40b3de98dece6e91f904dc96170/sensors/3/state HTTP/1.1" 200 -
in PUT method
/api/a7161538be80d40b3de98dece6e91f904dc96170/sensors/3/state
{"flag": true}
rule 3 is triggered
127.0.0.1 - - [02/Jan/2018 21:50:00] "PUT /api/a7161538be80d40b3de98dece6e91f904dc96170/groups/1/action HTTP/1.1" 200 -
in PUT method
/api/a7161538be80d40b3de98dece6e91f904dc96170/groups/1/action
{"scene": "10"}
scene details:
{"on": true, "bri": 1, "ct": 447}
{"e":"changed","id":"1","r":"lights","state":{"on":true},"t":"event"}
LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/1/state
scene details:
 {"e":"changed","id":"1","r":"lights","state":{"bri":1},"t":"event"}
{"on": true, "bri": 1, "ct": 447}
{"e":"changed","id":"2","r":"lights","state":{"on":true},"t":"event"}
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./HueEmulator.py", line 172, in schedulerProcessor
    sendRequest(bridge_config["schedules"][schedule]["command"]["address"], bridge_config["schedules"][schedule]["command"]["method"], json.dumps(bridge_config["schedules"][schedule]["command"]["body"]), 1, delay)
  File "./HueEmulator.py", line 388, in sendRequest
    response = opener.open(request, timeout=time_out).read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
timeout: timed out

``` 

I'm on commit c4a4571868e73c3ebb7037747e8c7f9975e41614.
I already tried increasing the timeout parameter in [HueEmulator.py:172](https://github.com/mariusmotea/diyHue/blob/master/BridgeEmulator/HueEmulator.py#L172) to `3` but that only makes the thread crash 2 seconds later.
Do you have any idea on where I could look for the cause of this?

EDIT:
The fully resolved statement that is executed in L172 is:
```py
sendRequest(/api/a7161538be80d40b3de98dece6e91f904dc96170/sensors/3/state, PUT, {"flag": true}, 1, 0)
```

**Comment by mariusmotea** [comment]
Hi,

These kind on errors are most harder to debug, basically there is a PUT request to itself that is not handled well by webserver. I will try to reproduce it on my home setup that is currently running a modified version based on python3.

**Comment by oleg2204** [comment]
I got some problems with the routines too. Sometimes they work fine and sometimes not. Really strange. Didnt had time to dig into the problem tho.

**Comment by mariusmotea** [comment]
I believe this problem was solved long time ago
