### ISSUE TITLE
RGB tweaking options in light fw

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#137]
Would be nice to add the option to tweak each RGB channel since especially cheap chinese rgb strips have uneven color reproduction. Ofc its possible now too but its not as straightforward. Maybe a divider for each channel?

**Comment by mariusmotea** [comment]
This is very complicated for me, check the conversion formula from xy to rgb and you will understand why. Every bulb needs his own conversion formula because of uneven color reproduction of the leds, but you need to be expert in mathematics to optimize it.

**Comment by mcer12** [comment]
Its not so big of a deal but especially the blue channel tends to be stronger than others and it's not ideal. Do you know anyone who has better knowledge in this matter and tag him to give some insight?

**Comment by mariusmotea** [comment]
Maybe @shbatm , he already fixed one issue with brightness level here #89

**Comment by mcer12** [comment]
@mariusmotea I was digging around and found out that Fastled library has an option to calibrate colors. This doesn't solve a problem with simple RGB but it might be a solution for addressed strips.

**Comment by mcer12** [comment]
https://github.com/FastLED/FastLED/wiki/FastLED-Color-Correction

**Comment by mariusmotea** [comment]
Did you applied this fix?

> fix for existing users 13.feb.2018
> 
> Pull request https://github.com/mariusmotea/diyHue/pull/173 improve bulbs color. To apply this fix you need to replace in config.json file LCT001 with LCT015 and restart the service. I recommend to upgrade to latest version and upgrade lights firmware.

**Comment by mcer12** [comment]
Yes I did

**Comment by ElliotSmith91** [comment]
Just a quick comment on the FastLED library. 

I have been working on incorporating this library in a new bulb sketch as I purchased a cheap RGB + CW LED bulb which doesn't use basic pwm from pins but an SM16726 LED driver with SPI communication.

If people are interested I can make it public soon. It functions at the moment, but there are definite improvements to be made. It's been a long time since I've done C programming!

**Comment by mcer12** [comment]
Closing since this was resolved in one of the pull requests.
