### ISSUE TITLE
control Neopixel with Raspberry GPIO

### ISSUE THREAD

**Issue by nhmann** [mariusmotea/diyHue#138]
Hello together,
is it possible to use a Neopixel strip like the WS2812b as a Hue lamp when the strip is directly connected to the raspberry pi's GPIO pins?
I used [https://learn.adafruit.com/neopixels-on-raspberry-pi/software](https://learn.adafruit.com/neopixels-on-raspberry-pi/software) to control the strip with the raspberry but I wasn't able to add it as a hue lamp in the hue app.

My other real hue lamps work fine in the hue app with the emulated bridge.

**Comment by mariusmotea** [comment]
Hi,
Yes is possible,  but you will need to implement that library in the example from here #28. If you manage to do it, maybe you will provide the entire code

**Comment by nhmann** [comment]
Hey, sorry for my late answer.
I'm a little bit confused.
I need to install [PiBlaster](https://github.com/sarfata/pi-blaster) right?
And do i need your code frome your Link?
And if yes, where should i place it?

Thanks for your help and sorry for my lack of knowledge.

**Comment by mariusmotea** [comment]
Is not just a copy/ paste but must be very easy to implement. `raw_hue_rgb` value contain the data that must be passed to PiBlaster function. I don't know exactly how PiBlaster works, never used.

```
#convert this from 0 <-> 255 to 0.0 <-> 1.0
pwm_rgb = [raw_hue_rgb[0] / 255.0, raw_hue_rgb[1] / 255.0, raw_hue_rgb[2] / 255.0]
print("red: " + str(pwm_rgb[0]) + ", green: " + str(pwm_rgb[1]) + ", blue: " + str(pwm_rgb[2]))
```

here you need to remove `pwm_rgb = [raw_hue_rgb[0] / 255.0, raw_hue_rgb[1] / 255.0, raw_hue_rgb[2] / 255.0]` and add the PiBlaster sintax to set the color on leds.
