### ISSUE TITLE
ESP8266 problem

### ISSUE THREAD

**Issue by FIFour** [mariusmotea/diyHue#139]
Hi,
I tried to make a Hue Dimmer Switch with a Wemos D1 mini pro. But when the program is uploaded, the LED is flashing all the time and i have this message in the serial monitor.

ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld

The problem is the same even when nothing is connected the the ESP and this ESP works with another program.
Can you help me ?
Thank you.

**Comment by mariusmotea** [comment]
I guess you need to use esp12-e or esp12-s because extra components of d1 mini can cause issues. In my example i use esp12-e board.

**Comment by cad435** [comment]
"rst cause:2" indicates a reset via the reset pin (vor at least the ESP is thinking its the reset pin), so you might want to check on that...

Additionally, check your powersource. ESPs are somewhat sensitive to voltage drop and MIGHT show this behaviour to.

You need about 350-400mA surge current for startup, make sure your Powersupply can handle this...
(If you connect via USB make sure your USB port actually meet the specification of 500mA)
