### ISSUE TITLE
How to choose the MOSFET - RGBW light conversion

### ISSUE THREAD

**Issue by miranthajayatilake** [mariusmotea/diyHue#140]
Hi,

Can I get some support on how to choose a correct MOSFET for the RGBW light conversion using ESP8266. In the ReadMe the IRLB8721 MOSFET is used, but I don't have this with me at the moment. What alternative can be used? What has to be there in the MOSFET specifications to be able to be controlled by 3.3V logic? What specification decides that?

Thank you as always.

**Comment by mariusmotea** [comment]
Check #63

**Comment by cheesemarathon** [comment]
@miranthajayatilake Looks like this can be closed now?
