### ISSUE TITLE
 espcomm_sync failed 

### ISSUE THREAD

**Issue by hason124** [mariusmotea/diyHue#141]
I getting this error when uploading the sketch to the esp. I have googled this issue but I cant seem to find any solution. I am using a nodemcu with built in CP2101 usb to uart. I am on a mac with the drivers directly from the Silicon Labs website. 

This is the console output from the Arduino IDE 1.8.5

In file included from /Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/NeoPixelBus.h:50:0,
                 from /Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino:6:
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:60:21: warning: unused parameter 'height' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:105:21: warning: unused parameter 'width' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:139:21: warning: unused parameter 'width' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:154:21: warning: unused parameter 'height' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:216:21: warning: unused parameter 'height' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:293:21: warning: unused parameter 'width' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:335:21: warning: unused parameter 'width' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:360:21: warning: unused parameter 'height' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
In file included from /Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/NeoPixelBus.h:67:0,
                 from /Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino:6:
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/NeoEsp8266DmaMethod.h:293:58: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     volatile static void ICACHE_RAM_ATTR i2s_slc_isr(void)
                                                          ^
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino: In function 'void convert_hue(uint8_t)':
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino:54:17: warning: right operand of comma operator has no effect [-Wunused-value]
   hh /= 11850, 0;
                 ^
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino: In static member function 'static void std::_Function_handler<void(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes ...) [with _Functor = setup()::__lambda2; _ArgTypes = {}]':
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino:513:37: warning: 'light' may be used uninitialized in this function [-Wmaybe-uninitialized]
     power_status = light_state[light] ? "true" : "false";
                                     ^
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino:508:13: note: 'light' was declared here
     uint8_t light;
             ^
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino: In static member function 'static void std::_Function_handler<void(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes ...) [with _Functor = setup()::__lambda0; _ArgTypes = {}]':
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino:411:14: warning: 'button' may be used uninitialized in this function [-Wmaybe-uninitialized]
       } else if (button == 4000) {
              ^
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino:374:9: note: 'button' was declared here
     int button;
         ^
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino: In function 'void setup()::__lambda1::_ZZ5setupENKUlvE0_clEv$isra$33()':
/Users/raymon/Desktop/DIY Philips Hue/diyHue-master 2/Lights/Arduino/SK6812HueStrip/SK6812HueStrip.ino:493:30: warning: 'light' may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (light_state[light]) {
                              ^
Archiving built core (caching) in: /var/folders/t6/j8qvrz7128sc71bgh4y95xwr0000gn/T/arduino_cache_813749/core/core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,FlashSize_4M1M,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,UploadSpeed_115200_64d0ff5c9e37dc340fe3c167a153feb7.a
Sketch uses 358632 bytes (34%) of program storage space. Maximum is 1044464 bytes.
Global variables use 39604 bytes (48%) of dynamic memory, leaving 42316 bytes for local variables. Maximum is 81920 bytes.
/Users/raymon/Library/Arduino15/packages/esp8266/tools/esptool/0.4.12/esptool -vv -cd nodemcu -cb 115200 -cp /dev/cu.SLAB_USBtoUART -ca 0x00000 -cf /var/folders/t6/j8qvrz7128sc71bgh4y95xwr0000gn/T/arduino_build_63577/SK6812HueStrip.ino.bin 
esptool v0.4.12 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to nodemcu
	setting baudrate from 115200 to 115200
	setting port from  to /dev/cu.SLAB_USBtoUART
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	espcomm_upload_mem
opening port /dev/cu.SLAB_USBtoUART at 115200
	tcgetattr
	tcsetattr
	serial open
opening bootloader
resetting board
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
resetting board
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
resetting board
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	serialport_receive_C0: 00 instead of C0
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

**Comment by mariusmotea** [comment]
I see the issues start with NeoPixelBus_by_Makuna library. Do you receive same errors if you compile any example for this library from here https://github.com/Makuna/NeoPixelBus/tree/master/examples ? Try to downgrade to version 2.2.8, i see now is available 2.2.9 and i did not test it.

**Comment by hason124** [comment]
Downgraded, still the same errors 

Arduino: 1.8.5 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (1M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 115200"

In file included from /Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/NeoPixelBus.h:50:0,
                 from /Users/raymon/Documents/Arduino/sketch_jan05a/sketch_jan05a.ino:8:
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:60:21: warning: unused parameter 'height' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:105:21: warning: unused parameter 'width' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:139:21: warning: unused parameter 'width' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:154:21: warning: unused parameter 'height' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:216:21: warning: unused parameter 'height' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:293:21: warning: unused parameter 'width' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:335:21: warning: unused parameter 'width' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/Layouts.h:360:21: warning: unused parameter 'height' [-Wunused-parameter]
     static uint16_t Map(uint16_t width, uint16_t height, uint16_t x, uint16_t y)
                     ^
In file included from /Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/NeoPixelBus.h:67:0,
                 from /Users/raymon/Documents/Arduino/sketch_jan05a/sketch_jan05a.ino:8:
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/NeoEsp8266DmaMethod.h:293:58: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     volatile static void ICACHE_RAM_ATTR i2s_slc_isr(void)
                                                          ^
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/NeoEsp8266DmaMethod.h: In instantiation of 'NeoEsp8266DmaMethodBase<T_SPEED>::NeoEsp8266DmaMethodBase(uint8_t, uint16_t, size_t) [with T_SPEED = NeoEsp8266DmaSpeed800Kbps; uint8_t = unsigned char; uint16_t = short unsigned int; size_t = unsigned int]':
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/NeoPixelBus.h:105:61:   required from 'NeoPixelBus<T_COLOR_FEATURE, T_METHOD>::NeoPixelBus(uint16_t, uint8_t) [with T_COLOR_FEATURE = NeoGrbFeature; T_METHOD = NeoEsp8266DmaMethodBase<NeoEsp8266DmaSpeed800Kbps>; uint16_t = short unsigned int; uint8_t = unsigned char]'
/Users/raymon/Documents/Arduino/sketch_jan05a/sketch_jan05a.ino:15:72:   required from here
/Users/raymon/Documents/Arduino/libraries/NeoPixelBus_by_Makuna/src/internal/NeoEsp8266DmaMethod.h:126:5: warning: unused parameter 'pin' [-Wunused-parameter]
     NeoEsp8266DmaMethodBase(uint8_t pin, uint16_t pixelCount, size_t elementSize) : NeoEsp8266DmaMethodBase(pixelCount, elementSize)
     ^
Archiving built core (caching) in: /var/folders/t6/j8qvrz7128sc71bgh4y95xwr0000gn/T/arduino_cache_111499/core/core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,FlashSize_4M1M,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,UploadSpeed_115200_64d0ff5c9e37dc340fe3c167a153feb7.a
Sketch uses 252311 bytes (24%) of program storage space. Maximum is 1044464 bytes.
Global variables use 33068 bytes (40%) of dynamic memory, leaving 48852 bytes for local variables. Maximum is 81920 bytes.
/Users/raymon/Library/Arduino15/packages/esp8266/tools/esptool/0.4.12/esptool -vv -cd nodemcu -cb 115200 -cp /dev/cu.SLAB_USBtoUART -ca 0x00000 -cf /var/folders/t6/j8qvrz7128sc71bgh4y95xwr0000gn/T/arduino_build_38571/sketch_jan05a.ino.bin 
esptool v0.4.12 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to nodemcu
	setting baudrate from 115200 to 115200
	setting port from  to /dev/cu.SLAB_USBtoUART
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	espcomm_upload_mem
opening port /dev/cu.SLAB_USBtoUART at 115200
	tcgetattr
	tcsetattr
	serial open
opening bootloader
resetting board
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
resetting board
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
resetting board
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
trying to connect
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

**Comment by mcer12** [comment]
We didn't see your code. Try to upload some neopixel example and if it works, it's problem in your sketch.

**Comment by hason124** [comment]
Still the same issue even with the neopixel examples.

**Comment by mariusmotea** [comment]
In this case is very likely you have a hardware issue or you did not configure Arduino correctly. 
 - Did you add support for esp8266 in Arduino?
 - Did you configure correctly the [board type](http://osoyoo.com/wp-content/uploads/2017/05/board-types.png) 
 - How many esp8266 devices you tried? Are all from from same vendor / same type ?

**Comment by hason124** [comment]
The issue seems to be resolved, for whatever reason having the LEDs hooked up causes that error.

**Comment by hason124** [comment]
Any thoughts on why there is a 2-3s latency of the colors changing after giving input into the hue app?

**Comment by mcer12** [comment]
Probly issue slow wifi, 2-3s is OK imo.

**Comment by mcer12** [comment]
You also might have some packet loss if you have the lights far from the router since the ESP doesnt have a greatest signal gain out there.

**Comment by mariusmotea** [comment]
For sure the cpu performance is not the bottleneck, this is running fine also on Pi Zero. Your issue must be related to poor wifi connection and this can be debugged very easy with ping between your laptop/phone and hue emulator device and from  hue emulator device to esp8266 light. My lights have an 2-3ms average reply time.

**Comment by hason124** [comment]
I am getting initially 50-100ms delay then it suddenly drops to 2-3ms. Is there something going on in the ESP or is it normal. 

ESP Ping 

![screen shot 2018-01-08 at 1 09 17 pm](https://user-images.githubusercontent.com/34976793/34659590-563cbe92-f475-11e7-8b63-6a5bdce5ad3c.png)

iPhone Ping

![screen shot 2018-01-08 at 1 08 03 pm](https://user-images.githubusercontent.com/34976793/34659600-69569e9e-f475-11e7-8866-bde74b48c8f5.png)

**Comment by mcer12** [comment]
You have pretty high ping on both devices. Esp dropping to 3ms is a good
thing not the opposite. Try a better router or some other way to extend
wifi signal. Switch from wifi n to g or even b might also improve things.

Dne 8. 1. 2018 6:11 dop. napsal uživatel "Ray" <notifications@github.com>:

I am getting initially 50-100ms delay then it suddenly drops to 2-3ms. Is
there something going on in the ESP or is it normal.

ESP Ping

[image: screen shot 2018-01-08 at 1 09 17 pm]
<https://user-images.githubusercontent.com/34976793/34659590-563cbe92-f475-11e7-8b63-6a5bdce5ad3c.png>

iPhone Ping

[image: screen shot 2018-01-08 at 1 08 03 pm]
<https://user-images.githubusercontent.com/34976793/34659600-69569e9e-f475-11e7-8866-bde74b48c8f5.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mariusmotea/diyHue/issues/141#issuecomment-355885443>,
or mute the thread

**Comment by hason124** [comment]
How do I go about changing the N, G, B modes.

**Comment by mcer12** [comment]
You change that on in your router settings though I dont think it will have a huge impact. Extending the signal is more important.

**Comment by hason124** [comment]
Thanks, I will have a look into it.
