### ISSUE TITLE
Cannot search for lights

### ISSUE THREAD

**Issue by pecirep** [mariusmotea/diyHue#144]
Edit: Formatting is weird because of the line of dashes...
Every time I search for lights I get following error:

`192.168.0.19 - - [08/Jan/2018 01:44:10] "PUT /api/a7161538be80d40b3de98dece6e91f904dc96170/config HTTP/1.1" 200 -
in PUT method
/api/a7161538be80d40b3de98dece6e91f904dc96170/config
{"touchlink":true}
[
    {
        "success": {
            "/config/touchlink": true
        }
    }
]
192.168.0.19 - - [08/Jan/2018 01:44:12] "POST /api/a7161538be80d40b3de98dece6e91f904dc96170/lights HTTP/1.1" 200 -
in post method
/api/a7161538be80d40b3de98dece6e91f904dc96170/lights
`----------------------------------------

`Exception happened during processing of request from ('192.168.0.19', 59005)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "HueEmulator.py", line 1199, in do_POST
    post_dictionary = json.loads(self.data_string)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by mariusmotea** [comment]
I made improvements on this function. I hope next week to finish the tests and push the changes.

**Comment by oleg2204** [comment]
Same error here. Suddenly all lamps stopped working. I deleted my config.json and now the auto discover functionality doesn't work. No error given.

**Comment by mariusmotea** [comment]
Please provide feedback on the following script https://pastebin.com/f8SsLv5b . Is based on python3

No tested yet:
- milight bulbs join
- hue bridge pair

If you found they are also working, please let me know. All other futures are tested and working.

**Comment by pecirep** [comment]
When I run the script with python3 I get following error. I thougt it was because http.server was merged into util.httpserver but that one didnt work either.

Traceback (most recent call last):
  File "HueEmulator.py", line 2, in <module>
    from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
ImportError: No module named 'BaseHTTPServer'

**Comment by pecirep** [comment]
Searching for lights via the Hue App doesn't throw an Exception but the Lights are still not found. I can access the lights through my browser though.

**Comment by mariusmotea** [comment]
Do you see the lights ip when you execute nmap for port 80? Ex with my raspberry ip, replace with yours

```
pi@raspberrypi:~ $ sudo nmap 192.168.10.200/24 -p80 --open -n | grep report | cut -d ' ' -f5
192.168.10.1
192.168.10.2
192.168.10.3
192.168.10.15
192.168.10.17
192.168.10.22
192.168.10.30
192.168.10.32
192.168.10.200

```

**Comment by mariusmotea** [comment]
BTW, you use recent firmware? At some point i change something in json output of the lights, more exactly i add 'modelid' directly there to know the type of the light that will be emulated.
Ex:
```
pi@raspberrypi:~ $ curl 192.168.10.22/detect
{"hue": "bulb","lights": 1,"modelid": "LCT001","mac": "26:fb:2c:a6:20:a0"}
```

**Comment by pecirep** [comment]
Yes, I did update recently. Running this command gave me an output similar to yours, one of the two lights have now been added. The other one is returning `curl: (7) Failed to connect to 192.168.0.25 port 80: No route to host`

**Comment by mariusmotea** [comment]
looks like network issue,  is mandatory to have communication from emulator host to all lights.
Do you have stable ping with 192.168.0.25?

**Comment by pecirep** [comment]
I do from my PC. It may be due to my weird network setup. Both my Pi and my PC are connected to an old router that is running dd-wrt configured as a Client Bridge. My main router sometimes considers only my PCs IP address for some reason. This does not explain why it works with one light and not the other but I will figure that out.

This is obviously an issue with my network, not your (awesome) software, as both lights are running the exact same hardware, software and are connected the the same access point. Therefore I consider this issue closed.

Side-note: the python3 script has to be run as root and I had to manually install the "request"-package. Again, this could be an issue with my system

**Comment by mariusmotea** [comment]
I need to check if "request" package was installed by me long time ago, or is bundled with python3. Today i made 3 tests with default configuration and android app data erased. Every time all the lights where discovered on first attempt so i believe at detection part the python3 version is quite stable

**Comment by pecirep** [comment]
I just installed python3 on my NAS (instead of my rpi. I'm still trying to solve my weird network behaviour) and request does not come with python3, it has to be installed manually.
