### ISSUE TITLE
Idea - AWS IoT and Alexa Integration 

### ISSUE THREAD

**Issue by miranthajayatilake** [mariusmotea/diyHue#148]
Wonderful project we have here.

I was wondering if we could take this forward by integrating the bridge with a cloud. So the objective are;

- Obtaining a database of connected devices on the cloud IoT platform (Preferably with something like AWS IoT)

- Deploying remote control over internet

- Integration of Alexa to the bridge

Can someone give me an idea for a starting point to handle this? If there are any existing efforts I would like to know.

Thank you.

**Comment by mariusmotea** [comment]
i can provide cloud service with 98% uptime, but i don't know how Alexa works.

Marius.
