### ISSUE TITLE
Help with setup of emulator on Orange Pi Lite

### ISSUE THREAD

**Issue by nikoli280397** [mariusmotea/diyHue#149]
Hi everyone. 

Im kinda stuck. I have installed Armbian on my orange pi lite so i can connect to it via putty. I can do that and i tried following the guide on the wiki page. But nothing comes up when searching for the hub in the app. Can someone help me through the setup, im not so strong in python?

Thanks

**Comment by mariusmotea** [comment]
can you start the script manually and provide the output?
ex: `sudo ./HueEmulator.py`

**Comment by nikoli280397** [comment]
Thank you for your quick answer. The problem is that when i enter the code "sudo ./HueEmulator.py" it says command not found. But all i did was follow your instructions on the wiki.

I plan on adding WS2812 LED strips with a Wifi 01 Mini ESP8266 Dev board.

**Comment by mariusmotea** [comment]
> sudo ./HueEmulator.py" it says command not found.

check #20 there is a small tutorial. You receive that command because you are not in the directory where HueEmulator.py is located.

**Comment by nikoli280397** [comment]
Thanks i got it up and running. But when i close Putty the connection disappears. Can i do something to make it auto run on startup without being connected to a computer?

**Comment by mariusmotea** [comment]
yes, you need to create the systemd service, i provide example in wiki. Be aware that you must correct the paths to HueEmulator.py script. In my example it was located in /home/pi

**Comment by mariusmotea** [comment]
`pwd` command display current location. If you managed to start the HueEmulator.py script by using `sudo ./HueEmulator.py` then it means the script is located in the current location.

**Comment by nikoli280397** [comment]
Great. Can you then help with what i should do if i want to connect 120 LEDs connected on a WS2812 LED strip. I have the Wemos D1 mini pro with ESP8266. What files should i upload to the Wemos? and how is it through Arduino IDE?

**Comment by mariusmotea** [comment]
go to Lights -> Arduino  -> WS2812BHueStrip
open WS2812BHueStrip.ino with Arduino


```
#define lightsCount 3 // put here the number of lights you want to emulate
#define pixelCount 120
```

write the code in Wemod D1 and follow the wiki to connect it to your wifi network. if you have issues with light discovery and you are sure the nmap package is installed, then check #144

**Comment by nikoli280397** [comment]
Great what does Lightscount mean? and what number should i set it to?

**Comment by mariusmotea** [comment]
lightsCount let you setup more lights on one ESP8266 board. For example if you setup lightsCount to 4 then on light discover will be detected 4 new Philips Hue strips, first one will control first 30 leds, second the next 30 leds and so on. I like how default scenes are displayed when you set 3 or more lights per strip.

**Comment by nikoli280397** [comment]
Okay. I have downloaded the board driver to my arduino IDE but it wont let me upload the code. It gives me this error


exit status 1
Error compiling for board WeMos D1 R2 & mini.
jssc.SerialPortException: Port name - COM8; Method name - closePort(); Exception type - Port not opened.
	at jssc.SerialPort.checkPortOpened(SerialPort.java:878)
	at jssc.SerialPort.closePort(SerialPort.java:1088)
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.close(FlasherSerialClient.java:98)
	at cc.arduino.plugins.wifi101.flashers.java.JavaFlasher.testConnection(JavaFlasher.java:56)
	at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:110)
processing.app.SerialException: Error opening serial port 'COM8'.
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.open(FlasherSerialClient.java:86)
	at cc.arduino.plugins.wifi101.flashers.java.JavaFlasher.testConnection(JavaFlasher.java:50)
	at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:110)
Caused by: jssc.SerialPortException: Port name - COM8; Method name - openPort(); Exception type - Port busy.
	at jssc.SerialPort.openPort(SerialPort.java:164)
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.open(FlasherSerialClient.java:54)
	... 2 more
jssc.SerialPortException: Port name - COM8; Method name - closePort(); Exception type - Port not opened.
	at jssc.SerialPort.checkPortOpened(SerialPort.java:878)
	at jssc.SerialPort.closePort(SerialPort.java:1088)
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.close(FlasherSerialClient.java:98)
	at cc.arduino.plugins.wifi101.flashers.java.JavaFlasher.testConnection(JavaFlasher.java:56)
	at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:110)
processing.app.SerialException: Error opening serial port 'COM8'.
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.open(FlasherSerialClient.java:86)
	at cc.arduino.plugins.wifi101.flashers.java.JavaFlasher.testConnection(JavaFlasher.java:50)
	at cc.arduino.plugins.wifi101.UpdaterImpl$2.run(UpdaterImpl.java:110)
Caused by: jssc.SerialPortException: Port name - COM8; Method name - openPort(); Exception type - Port busy.
	at jssc.SerialPort.openPort(SerialPort.java:164)
	at cc.arduino.plugins.wifi101.flashers.java.FlasherSerialClient.open(FlasherSerialClient.java:54)
	... 2 more

**Comment by mariusmotea** [comment]
Don't try to write the firmware with leds connected to board.

**Comment by nikoli280397** [comment]
The LEDs are not connected. Yes i used COM8 with the board. I restarted the computer and got futher but still not uploaded now it says "espcomm_upload_mem failed" so i think i downloaded the wrong library what should i download?

**Comment by mariusmotea** [comment]
"espcomm_upload_mem failed" is a generic error. Based on https://github.com/esp8266/Arduino/issues/2801 the options are " you either have bad wiring, or a bad module, or you're doing something wrong"
Try another computer, different upload speeds.

**Comment by nikoli280397** [comment]
i again found the solution i had set the flash size to  4M (3M SPIFFS) i changed it to 4M (1M SPIFFS) and now it got uploaded.

**Comment by nikoli280397** [comment]
Okay i tried to make the file that would make the orangepi auto start the program. It did not work. Now i cant even start the program via putty. It says its started and sending M-search response to diffrent IP adressess. But after i turned on the power to the LEDs and the ESP8266 my mobile app of Philips Hue wont find the Brigde anymore.

**Comment by nikoli280397** [comment]
Okay now the program let me get into the app. But i cant find any lights? How do i connect to the LEDS

**Comment by nikoli280397** [comment]
Ah okay there is still a problem with the bridge when i close putty then the connection disappears. Im stuck.

**Comment by mariusmotea** [comment]
you need to start the emulator as service, this way it will not be killed once you disconnect your session.

**Comment by nikoli280397** [comment]
How can i do that?

**Comment by mariusmotea** [comment]
follow the wiki

https://github.com/mariusmotea/diyHue/wiki/1.-Getting-started

**Comment by nikoli280397** [comment]
I have followed the wiki, and both made the sudo nano /lib/systemd/system/hue-emulator.service in the first library i come to after login into my orangepi and also here /diyHue/BridgeEmulator. But still does not work when closing putty

**Comment by mariusmotea** [comment]
i believe your service is not working.
execute the following:
`sudo systemctl start hue-emulator.service`
then
`systemctl status hue-emulator.service`

provide me the output.

**Comment by nikoli280397** [comment]
root@orangepilite:~# sudo systemctl start hue-emulator.service
root@orangepilite:~# systemctl status hue-emulator.service
● hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; disabled; vendor pr
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-01-14 17
  Process: 6183 ExecStart=/home/pi/HueEmulator.py (code=exited, status=200/CHDIR
 Main PID: 6183 (code=exited, status=200/CHDIR)

Jan 14 17:35:43 orangepilite systemd[1]: hue-emulator.service: Unit entered fail
Jan 14 17:35:43 orangepilite systemd[1]: hue-emulator.service: Failed with resul

**Comment by mariusmotea** [comment]
ok, you just copy and paste the content of the service from wiki, without to replace the path to python script. In my example it was located in `/home/pi/HueEmulator.py`, in your case must be different. For this reason i provide you pwd command, to see the location of HueEmulator.py file

Look here another way to see the path:

```
pi@raspberrypi:~ $ sudo find / -name HueEmulator.py
/home/pi/HueEmulator.py
```
`/home/pi/HueEmulator.py` is in my case, in your must be different.

**Comment by mariusmotea** [comment]
stop!

i correct here your path. The wiki for you look like this:

```
[Unit]
Description=Hue Emulator Service
After=multi-user.target

[Service]
Type=idle
Restart=always
RestartSec=30
StartLimitInterval=200
StartLimitBurst=5

WorkingDirectory=/root/diyHue/BridgeEmulator
ExecStart=/root/diyHue/BridgeEmulator/HueEmulator.py

[Install]
WantedBy=multi-user.target
```
save and execute the following commands:

```
sudo chmod 644 /lib/systemd/system/hue-emulator.service
sudo systemctl daemon-reload
sudo systemctl enable hue-emulator.service 
sudo systemctl start hue-emulator.service
```

**Comment by nikoli280397** [comment]
Still the same. The instant i close putty the connection dissapears.

**Comment by mariusmotea** [comment]
`systemctl status hue-emulator.service` ?

**Comment by nikoli280397** [comment]
There it is. Thank you for your pattience. I copied the service text twice, sorry.

**Comment by nikoli280397** [comment]
Now i just need to be able to connect to the ESP8266 but it does not appear in the search in the app. And i have done what was on the Wiki. What more does i need to do. The code is uploaded and the LEDs are connected Only 1 LED is on so i know power is flowing.

**Comment by mariusmotea** [comment]
Possible reasons:

1. light is not connected to your wifi network
- did you run wifi wizard to connect the light to your network?
- are you able to control the light from any web browser by accessing its ip?
2. nmap package is not installed on Orange Pi
 - check if nmap package is installed `sudo apt install nmap`

**Comment by nikoli280397** [comment]
The ESP8266 appears as a wifi connection called "New Hue Light" i can connect to it but i then looses connection to the brigde

**Comment by mariusmotea** [comment]
connect to it with your mobile phone, access from browser http://192.168.4.1 then scan for networks and connect to your network.

**Comment by nikoli280397** [comment]
Yep great i got the ESP8266 connected. But then in the moment i connected it the bridge disconnected. And when i log into putty to try manually start the program it says its already in use. But no data. and no way to connect?

**Comment by nikoli280397** [comment]
Okay in a weired way i got connected to the bridge again. The wifi signal of the ESP is gone so i guess its connected to my home network. It still dont show up on light search in the app though. What can cause this?

**Comment by nikoli280397** [comment]
Okay reinstall Nmap seemed to get it to work. Now i test :D Thank you for help

**Comment by mariusmotea** [comment]
Perfect!

**Comment by nikoli280397** [comment]
It works now. But this happens. Do you have an idea of why its happening. I count 40 of the first line then 22 on the next and then a green at the bottom. The green wont turn off. I know i have lots of power since the LED only draw 1A out of 10A. 


![img_20180114_193932](https://user-images.githubusercontent.com/35396940/34919357-cda14312-f962-11e7-8f0b-1be0f5e568b8.jpg)



![img_20180114_193955](https://user-images.githubusercontent.com/35396940/34919358-ce616426-f962-11e7-99e2-44c3117003bb.jpg)

**Comment by mariusmotea** [comment]
When you compile the code, what values you put here?
```
#define lightsCount x
#define pixelCount xxx
```

**Comment by nikoli280397** [comment]
#define lightsCount 3
#define pixelCount 120

there is after counting 118. But does that make a diffrence?

**Comment by mariusmotea** [comment]
here is ok, 120 divide 3 so you must have 3 lights x 40 leds each. Your issue is something that i never faced and is hard for me to tell you what is wrong.

**Comment by nikoli280397** [comment]
What would you suggest me do?

**Comment by mariusmotea** [comment]
i don't have too many details to provide suggestions. Test the light with curl

ex:
```
curl "http://{light ip}/set?light=1&r=0&g=60&b=255"
curl "http://{light ip}/set?light=1&on=false"
curl "http://{light ip}/set?light=1&on=true"
```

this is for first 30 leds, to test other replace `light=1` with `light=2` or `light=3`

Check also if the light can be controlled ok from internal webgui.

**Comment by nikoli280397** [comment]
Im not sure what i should do with the code you sent. I need to change Light IP but to what? Changing it to Light=1 does not do anything.

But so you know i can control "light1" and then part og "light2" but then nothing on the last part. there is just 1 LED that is always on.

**Comment by mariusmotea** [comment]
can you confirm these:
 - you are using strips connected in serial and the total number of leds is 120
 - if from webgui of the light your select `startup` `off`, on power on you see one red pixel moving from binning of the strip up to the last pixel, then after successful connection to wifi the same will happen with a green pixel
- you can control fine light1 and this is changing just the first 40 leds
- you can partially control light2 (how may leds are changing?)
- nothing happen when you play with ligh3

the code i send are commands that you can execute from OrangePi to control the lights directly ( without hue-emulator). replace {light ip} with the ip alocated by your router to esp8266.

**Comment by nikoli280397** [comment]
I found the solution. It was some bad LEDs so i have to resolder some new ones. But now it works like a charm. Thank you for great help :-)

**Comment by nikoli280397** [comment]
Just a last question. When trying to make a Philips Hue account i need to press the bridge but ofcourse i dont have a button to press. Is there a function for this in your firmware?

**Comment by mariusmotea** [comment]
To create a Philips Hue account you will need a real bridge. There is a communication from hue bridge to Philips cloud servers and the api is not public, so it cannot be implemented. Functionality of hue emulators are restricted just to local communication, everything that involve the remote api will not work.

**Comment by nikoli280397** [comment]
Ah okay good to know. Thanks

**Comment by nikoli280397** [comment]
Hi again. Now its a nother problem. I can control the lights but the bridge seems to loose connection to internet avery 2-6 hours so i can set an alarm for sunrise light in the afternoon but no connection to do so in the morning. I can not seem to find out why its happening.

I have tried to add a reboot command so the pi will reboot every 6 hours. But it still brings problems.

**Comment by mariusmotea** [comment]
Is your pi connected using wifi to your network?

**Comment by nikoli280397** [comment]
Yes. And it works but then its like it gets disconneted

**Comment by mariusmotea** [comment]
did you added the cron job from #154 ?

**Comment by nikoli280397** [comment]
Yep. Its also were i added the reboot code.

**Comment by nikoli280397** [comment]
The problem with the cron job code is that i end up having my bridge connected to my 5Ghz network, but my lights are connected to my 2.4 Ghz network so they can not communicate. I can connect to one of the IP's that the ESP makes but it only lets me change light settings not network settings.

**Comment by nikoli280397** [comment]
After a couple of months with 4-6 disconnects every day that required restart i startet from scratch. But this time i can not get futher than this

![image](https://user-images.githubusercontent.com/35396940/36758982-3bf486f0-1c16-11e8-9d30-252be364c71e.png)

**Comment by mariusmotea** [comment]
I suggest to start with automatic script installation, check wiki

**Comment by nikoli280397** [comment]
That I have tried without success

**Comment by mariusmotea** [comment]
Execute manually the script to see the error on exit.

**Comment by nikoli280397** [comment]
It can not find it when I run manually but that is because I don't know how
to navigate the file system it is located when using find

**Comment by nikoli280397** [comment]
Please help me i am doing exactly what you tell me but it just does not work

![image](https://user-images.githubusercontent.com/35396940/36859142-c6d92182-1d7d-11e8-9001-792fd7940987.png)

**Comment by mariusmotea** [comment]
No usefull informations here. You need to start manually the script manually to see the error. Better start from scratch and use automatic install method, it must work.

**Comment by nikoli280397** [comment]
Yes you say that. But if i start from scratch again i get same result. Starting from scratch was the exact thing i did 2 days ago and it ended me here.

**Comment by nikoli280397** [comment]
![image](https://user-images.githubusercontent.com/35396940/36859637-48d3edec-1d7f-11e8-9e2d-aff36ecfa773.png)

**Comment by mariusmotea** [comment]
Is not a completed installation. Execute again the easy_install script from wiki and provide the output.

**Comment by nikoli280397** [comment]
![image](https://user-images.githubusercontent.com/35396940/36859890-1a3bcbc0-1d80-11e8-990e-c8bd9ed9fc54.png)

**Comment by mariusmotea** [comment]
Better paste the text, don't upload pictures.

**Comment by nikoli280397** [comment]
Okay
root@orangepilite:~# sudo /opt/hue-emulator/HueEmulator3.py
sudo: /opt/hue-emulator/HueEmulator3.py: command not found
root@orangepilite:~# curl -s https://raw.githubusercontent.com/mariusmotea/diyHu                      e/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.11.0-3+deb9u2).
nmap is already the newest version (7.40-1).
python3-pip is already the newest version (9.0.1-2).
python3 is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: requests in /usr/lib/python3/dist-packages
Collecting ws4py
  Using cached ws4py-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oct766p6/ws4py/
root@orangepilite:~#

**Comment by mariusmotea** [comment]
Execute again and provide the output. I made some changes for you on installation script

**Comment by nikoli280397** [comment]
It did something, but the hue brigde is still not found in the app
root@orangepilite:~# curl -s https://raw.githubusercontent.com/mariusmotea/diyHue/master/BridgeEmulato           r/easy_install.sh | sudo bash /dev/stdin
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.11.0-3+deb9u2).
nmap is already the newest version (7.40-1).
python3-pip is already the newest version (9.0.1-2).
python3 is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: requests in /usr/lib/python3/dist-packages
Collecting ws4py
  Using cached ws4py-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s1i2dvuv/ws4py/
Cloning into 'diyHue'...
remote: Counting objects: 1988, done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 1988 (delta 46), reused 40 (delta 12), pack-reused 1888
Receiving objects: 100% (1988/1988), 38.36 MiB | 5.95 MiB/s, done.
Resolving deltas: 100% (914/914), done.
 Installation completed. Open Hue app and search for bridges.
root@orangepilite:~#

**Comment by mariusmotea** [comment]
Try a reboot. Is the service running now?

**Comment by nikoli280397** [comment]
Yes now it works i will try the following days and see if it disconnect like last time. Thanks again for great support

**Comment by nikoli280397** [comment]
Sadly after 2 days work without problem it fit not work today so I had to
restart the bridge manually. What can cause this. And how can I fix it

**Comment by nikoli280397** [comment]
Now it does not work at all. It not possible to communicate with at all
even with restarts

**Comment by mariusmotea** [comment]
Replace your board with something that has physical network port. Your issue is hardware related, not software. If you have an usb wifi dongle you can try to use that for wifi connection.
