### ISSUE TITLE
Last Bracket in Line 373 in HueEmulator.py

### ISSUE THREAD

**Issue by pecirep** [mariusmotea/diyHue#15]
The last bracket in [Line 373 of HueEmulator.py](https://github.com/mariusmotea/diyHue/blob/master/BridgeEmulator/HueEmulator.py#L373) is superfluous and the program throws en error when run so it should be removed.

P.S.: I'm fairly new to github, should I open a Pull request next time I find such a case where there is literally one bracket more than it should be?

**Comment by mariusmotea** [comment]
Ooops, somehow i add an extra bracket into the git repo. This is not present on my raspberry pi and for this reason i did not discover so far. You can fork the master, perform the fix and then create PR from your fork into the master, so your contribution to github will be noted.

Thanks.

**Comment by mariusmotea** [comment]
PR merged, thanks!
