### ISSUE TITLE
Support for Hue Entertainment

### ISSUE THREAD

**Issue by mariusmotea** [mariusmotea/diyHue#150]
Hi,

I need some help in order to create the dedicated service for hue entertainment. The requirements are these:

> UDP port 2100 is used for DTLS handshaking and streaming. Only DTLS mode version 1.2 with Pre-Shared Key (PSK) Key exchange method with TLS_PSK_WITH_AES_128_GCM_SHA256 set as Cipher Suite is supported.

the challenge is to have this DTLS protocol implemented for steam decryption.

The api to create the Hue Entertainment area from mobile application seams to work with no changes.

**Comment by francescofact** [comment]
Please figure out how to implement this. I want so bad to use the new Razer Synapse 3 with my MiLights and it require Hue Entertainment

**Comment by mariusmotea** [comment]
i need to find some software that works with hue entertainment protocol in order to progress. I believe pydtls and sslpsk libraries are enough, they only need to be implemented.

**Comment by francescofact** [comment]
try Razer Synapse 3 to try the entertainment protocol

**Comment by francescofact** [comment]
![cattura](https://user-images.githubusercontent.com/28184856/35821938-fb50b500-0aaa-11e8-9df5-6a3dc02ad8b0.PNG)
It says that the bridge must be updated

**Comment by mariusmotea** [comment]
Issue is with secondary listening service that is not implemented. Now if you set apiversion to 1.22 in config.json you will be able to specify the lights and position for light in room, but this is not enough.

Marius.

**Comment by mariusmotea** [comment]
Not sure if available libraries for python can create the dtls server with psk authentication.

**Comment by francescofact** [comment]
I think that this library could help 
https://pypi.python.org/pypi/Dtls/0.1.0

**Comment by mariusmotea** [comment]
i believe this must be used, but all examples i found are based on certificates authentication, not with psk. If you find any examples i will implement-it. Philips provide all the needed details for Entertainment protocol, just the handshake is the main issue.

**Comment by francescofact** [comment]
https://github.com/drbild/sslpsk

With this you can add psk autentication writing sslpsk.wrap_socket instead of ssl.wrap_socket

**Comment by mariusmotea** [comment]
This is for TLS, we need DTLS. Anyway i ask it [here](https://github.com/drbild/sslpsk/issues/6)

**Comment by juanesf** [comment]
Will it work ?:
https://github.com/particle-iot/tinydtls/blob/master/README

**Comment by juanesf** [comment]
Sorry

**Comment by francescofact** [comment]
they found the solution i think
https://github.com/kershner/screenBloom/issues/66

**Comment by avinashraja98** [comment]
Can the dtls server be run using C/C++ and the data then piped into our python script?

**Comment by mariusmotea** [comment]
Yes, but it need to expose a method for sending the data to hue emulator (socket file ?)

**Comment by mariusmotea** [comment]
I believe this is one good option https://github.com/wolfSSL/wolfssl-examples/blob/master/dtls/server-dtls.c

**Comment by cheesemarathon** [comment]
Getting anywhere with this?

**Comment by mariusmotea** [comment]
I don't know c++, cannot start here. Only when sombody will write here that will help us there can be a progress.

**Comment by juanesf** [comment]
Hello, Again.
Searching or searching I found the following:

https://pypi.org/project/Dtls/#description

cipher: 0x00a8

**Comment by juanesf** [comment]
This repo has the installer corrected, you just have to download it and execute: python3 setup.py install

**Comment by mariusmotea** [comment]
check this comment from here,it looks like the required cipher is missing https://github.com/rbit/pydtls/issues/20#issuecomment-375208057

**Comment by juanesf** [comment]
In this post they use the same library but with a different cipher and apparently it works (https://github.com/kershner/screenBloom/issues/66) n°7 PSK-AES128-CBC-SHA

**Comment by juanesf** [comment]
the next library is more updated and has the support of python3 corrected:
https://github.com/inpos/pydtls

**Comment by avinashraja98** [comment]
Hey Guys, I was able to create a server using the mbedtls ssl_server2 program. It supported the required dtls, cipher suites etc. I only had to disable the http response and create a loop to wait for more messages if the first character of the recv buf is 'H' of the huestream entertainment sdk message format. I am able to properly handshake and get the messages in a char buffer in the c program. I tried this with the example dtls_client.txt program provided by the entertainment sdk page. I am sure it should work for the other clients such as Razer Synapse too. I'll try confirming it later today. Now my question is what should I do with the light data? should I process it in the c program and send http msgs to the lights? should I forward it to the Hue-emulator python script using an unsecured udp channel? does the python script have implementation already done for entertainment? Thanks

**Comment by mariusmotea** [comment]
WOW, this is the news we expect to hear in this thread. For the moment we can do this: implementation with no security, meaning one static authentication string that will be provided to all users. Later we may find a way to fetch this via http request from bridge emulator. Light data must be passed mandatory to emulator because hue app configure xy data of the lights in every entertainment area so a believe it must be an http PUT or POST request in 127.0.0.1/entertainment (or any location).

**Comment by avinashraja98** [comment]
I understood the first part, which is getting the static auth string which i have hard coded into the server script for now, multiple username support is causing a slight problem, but I am sure I can figure it out later. I was just wondering if the python script has the implementation for parsing the light data and physically lighting up the bulbs and if yes can you please give me a line number in the file its done in. I am not very good at python sorry.

**Comment by avinashraja98** [comment]
So I just PUT/POST the light data bytes to a url hosted by the python emulator script. If I can see the implementation(if it exists) on the python script side I think I can understand it well.

**Comment by mariusmotea** [comment]
Currently is not implemented, but i believe i can do it fast.

**Comment by avinashraja98** [comment]
Awesome, I'll perfect the server implementation and we'll try testing it out.

**Comment by mariusmotea** [comment]
If is possible to post one json with all lights data will be perfect as is very easy to parse it with python (and all languages in general)

**Comment by avinashraja98** [comment]
Okay so here are my test results with Razer Synapse.
1. Waiting for connection:
![1](https://user-images.githubusercontent.com/22232505/42355353-3c208b2e-80a7-11e8-9167-7d1921084569.PNG)
2. When I toggle the switch near bridge text
![2](https://user-images.githubusercontent.com/22232505/42355367-57a38aae-80a7-11e8-8ae7-59f0488e67be.png)
3. Then after about 2-3 secs, the connection closes and the bridge stream is set to false.
![3](https://user-images.githubusercontent.com/22232505/42355387-78444bb8-80a7-11e8-8ee9-c2065b3286ec.png)

From the get requests, I think the synapse app is checking for changes and since there are no changes( since the implementation is not there), it assumes that the stream is busy and turns itself off. I think once we implement this feature everything should run properly.

**Comment by avinashraja98** [comment]
I'll create the JSON payload asap

**Comment by cheesemarathon** [comment]
Great work so far guys. I'm going to link here from the screen bloom github as they were struggling with the entertainment API in python also.

**Comment by mariusmotea** [comment]
>  I think the synapse app is checking for changes and since there are no changes( since the implementation is not there

I believe the same because is pulling the lights and groups every second so this must be the purpose.

**Comment by mariusmotea** [comment]
@avinashraja98 let's setup here the api we will  use for applications communications. 
I propose this:
http PUT request to http://127.0.0.1/entertainment
post data will be json string with following format:
`{"colorspace": "rgb", "data": {"1": [0x00,0x00,0x00,0x00,0xff,0xff], "5": [0x00,0x00,0xff,0xff,0x00,0x00]}}`

colorspace can be "rgb" or "xy" (0x00 = RGB; 0x01 = XY Brightness)
data is an array that contain the lights ID followed by a list with the data values.

It is ok for you?

I

1 | Protocol name | 9 | Array of 9 characters{‘H’, ‘u’, ‘e’, ‘S’, ‘t’, ‘r’, ‘e’, ‘a’, ‘m’}
-- | -- | -- | --
2 | Version | 2 | Streaming API version 1 byte major version (0x01), 1 byte minor version (0x00)
3 | Sequence ID | 1 | Can be used to indicate the message sequence number. Currently it is ignored by the bridge.
4 | Reserved | 2 | Reserved, all zeros should be sent.
5 | Color space | 1 | 0x00 = RGB; 0x01 = XY Brightness
6 | Reserved | 1 | Reserved, all zeros should be sent.
7-16 | Data [Light slots] | 9 * #lights | Maximum 10 slots of light data, each containing 9 bytes consisting of:
  | Type | 1 | Type of device 0x00 = Light
  | ID | 2 | Unique ID of light
  | Value | 3 * 2 | RGB or XY+Brightness with 16 bit resolution per element

**Comment by avinashraja98** [comment]
Seems fine I'll make the data structure and report asap

**Comment by mariusmotea** [comment]
I implement the api above with one change, the light ID is not string but integer, for me i need string but i believe the formatting is done much easy in python. I perfrorm tests just in rgb mode and seams to work.

**Comment by avinashraja98** [comment]
Okay so here's what happened, the synapse app does recognize that its messages are being sent properly and continues to send messages however, the TCP method is so slow, the server script lags before getting new messages and eventually crashes. I think we need a UDP method so that we can use this entertainment api properly. The api docs say that the light data bytes are sent to the lights and they unbundle the message and act accordingly. We will need a similar solution. I'll try more tests and report.

**Comment by avinashraja98** [comment]
Good work on the http implementation btw

**Comment by mariusmotea** [comment]
Ok, in this case i will create a new UDP server and i believe you will forward entire content unencrypted directly to this. Because the original service use port 2100/udp i will create new service on 2101/udp.

**Comment by mariusmotea** [comment]
i create the service but currently it only prints the messages and don't do anything else. Once i will have some sample output i can go forward with the implementation.

**Comment by avinashraja98** [comment]
Sure, exactly what I was thinking. If you want sample data, you can create a script that sends dummy data to the udp port 2101 at these rates specified by the entertainment api.

* The bridge sends maximum at 25 Hz messages over ZigBee. Thus, the (fastest) effect rate should be 2 - 3 times slower than this 25 Hz, i.e < 12.5 Hz.
* Due to the lossy streaming channel (UDP, and ZigBee) keep the message rate higher than 25 Hz.

It is a little bit confusing but I'm sure you'll figure it out. I'll do the unencrypted data forward asap and report.

**Comment by mariusmotea** [comment]
If you have some sample output of python script with original data please paste it here so i can start the implementation

Thanks.

**Comment by avinashraja98** [comment]
#276

**Comment by mariusmotea** [comment]
Hi,

Just to provide the current status:
 - i implement the udp server and the parse for light data in rgb mode.
 - because of the big number of requests per seconds i will create dedicated udp service in ESP lights firmware, but for other lights i need to perform some advanced filtering (ex: don't send requests to quick or send them only when there is a notable difference in the light color)
 - Hue Sync app for Mac is disconnecting after few seconds. I saw this happens right after a GET request for configuration, so very likely it is inspecting some parameters and because are not the expected ones it stop sending data. In the few working seconds i saw the light data was changing according to the screen brightness .
 - All 4 Hue app is triggering an error when i try the entertainment effects, i believe it work first time, but i'm not sure.

TO DO.
 - extend the udp light service for all color lights (now is just the rgb-cct version)
 - try to understand what values i need to change on the bridge so the Hue Sync will not stop the broadcast anymore.

**Comment by avinashraja98** [comment]
> try to understand what values i need to change on the bridge so the Hue Sync will not stop the broadcast anymore.

This is the problem with Razer Synapse too. I've noticed requests to /api/<username>/groups/<id> when streaming show no changes. Is this the expected behavior? because I am pretty sure this is the issue as synapse requests a GET to this address and then immediately stops broadcast and shows stream busy error.

**Comment by mariusmotea** [comment]
I manage to made Hue Sync to work. Still i need a few changes because in hue application i still see a message that some lights cannot be controlled while hue entertainment is active despite i stop it. Hope today i will push a new release.

**Comment by mariusmotea** [comment]
With the last commit Hue Sync for Mac is working fine. I still have issues with All 4 Hue application for android that is not broadcasting or is broadcasting just one frame. Next step is to simplify the installer by providing precompiled binaries for arm and amd64 platfrorms.

**Comment by avinashraja98** [comment]
Latest commit works beautifully with Razer Synapse and Chroma apps(such as Overwatch).

**Comment by mariusmotea** [comment]
Today i add more improvements and with this i will close this issue. 
@avinashraja98 i added you to contributors list, without you it would not have been possible to solve this issue.

**Comment by avinashraja98** [comment]
Thank You for this wonderful project. Hope everyone has fun with the new features.

**Comment by d8ahazard** [comment]
Hey there! I'm working on a project that aims to send color data directly to my hue system using the entertainment endpoint.

Just curious, did you ever manage to get a working solution for dtls-handshaking? If so, would you care to share the trick? I'm struggling to get the handshake bit to work...

**Comment by mariusmotea** [comment]
I manage to get entertainment working, the source code is present in the repo, but from my understanding you try to create the client, here we made the server.

**Comment by d8ahazard** [comment]
> I manage to get entertainment working, the source code is present in the repo, but from my understanding you try to create the client, here we made the server.

I looked at the repo, but it seems as if you're using a compiled binary to do the transmission? I checked the entertainment.py file, but see nothing there for dtls. Is this implemented somewhere else?

**Comment by mariusmotea** [comment]
The compiled binary is generated from https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/ssl_server2_diyhue.c

**Comment by d8ahazard** [comment]
> The compiled binary is generated from https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/ssl_server2_diyhue.c

Thank you. I'm not too familiar with C (although happy to try and learn).

Is there some way I could chat with you about the issue a bit more? i don't want to keep posting on a closed issue thread. ;)

**Comment by mariusmotea** [comment]
Unfortunately i did not made this, i just ask for help and i receive it.

**Comment by d8ahazard** [comment]
Do you know if I would be able to use the binary to accomplish my goal?

Current handshake request:


    def do_handshake(self):
        print("Handshaking with ", self.bridge_ip)
        ssl_sock = False
        psk = binascii.unhexlify(self.bridge_key)
        print("PSK", psk)
        try:
            do_patch()  # dtls library doing its thing
            print("Patched")
            host = self.bridge_ip
            port = 2100
            print("Wrapping socket")
            tcp_socket = socket(AF_INET, SOCK_DGRAM)
            tcp_socket.connect((host, port))
            ssl_sock = sslpsk.wrap_socket(tcp_socket,
                                          ssl_version=258,
                                          ciphers='PSK-AES128-GCM-SHA256',
                                          psk=psk, hint=self.user)
            print("Socket wrapped")

            msg = "ping"
            ssl_sock.sendall(msg.encode())
            msg = ssl_sock.recv(4).decode()
            print('Client received: %s' % msg)
        except Exception as e:
            print("Socket exception: ", e)
        return ssl_sock


Current "send message" function:


    def send_message(self, states):
        my_socket = self.do_handshake()
        udpmsg = bytearray()
        # Protocol
        udpmsg += bytes("HueStream",'utf-8')
        # Version
        udpmsg += bytes(10)
        # Sequence ID
        udpmsg += bytes(0)
        # Reserved
        udpmsg += bytes(00)
        # ColorSpace (RGB)
        udpmsg += bytes(0)
        # Reserved
        udpmsg += bytes(0)
        # Add individual lights
        for light_data in states:
            print("Sending state for id ", light_data)
            id = light_data[0]
            r = light_data[1]
            g = light_data[2]
            b = light_data[3]
            c = Converter()
            # Add light type
            udpmsg += bytes(0)
            udpmsg += bytes(id)
            udpmsg += bytes(int(r)) + bytes(int(g)) + bytes(int(b))
        print("Trying to send message: ", udpmsg)
        if type(my_socket) is not bool:
            my_socket.sendto(udpmsg, (self.bridge_ip, 2100))
        else:
            print("Invalid socket!")

**Comment by avinashraja98** [comment]
You are on the right track but this binary is the server and is used to receive the message. Something is probably wrong with your message configuration.

**Comment by d8ahazard** [comment]
> You are on the right track but this binary is the server and is used to receive the message. Something is probably wrong with your message configuration.

I never get to the point of trying to send the message, the handshaking fails and I never get the "Socket wrapped" message printed.

**Comment by d8ahazard** [comment]
@avinashraja98 @mariusmotea 

Two final questions:

1. Will the entertain-srv binary work as a relay from my application to send light data to my hue bridge? It looks like I'd just need to open a normal socket to localhost on port 2100 and send light data to that?

2. If so - may I have your permission to use the binary with my project? I will naturally give full credit...

**Comment by mariusmotea** [comment]
@avinashraja98 can you help us with an update to the ciphers? Hue Sync start to use new ciphers since PSK-AES128-CBC-SHA is considered week now.

**Comment by avinashraja98** [comment]
Oh I see. Its been a while since I looked at diyHue, I'll check it out and try getting a solution over the weekend. Lmk if you have any more information thanks.
