### ISSUE TITLE
Any support for Artnet?

### ISSUE THREAD

**Issue by TheFonix** [mariusmotea/diyHue#151]
Hey there, im slightly curious if there is any out of the box compatibility with Art-net to pass through to DMX lights! My aim is to have my current Hue lights connected to my current Hue bridge as well as the 5 DMX lights i have all in my Emulated hue bridge! 

Thanks

**Comment by mariusmotea** [comment]
Hi,

This protocol looks complicated to me, is there any library available that will convert  this protocol to something more simple like rgb data and light id?

**Comment by TheFonix** [comment]
This should make it a little simpler for you, this is an example of what I've been using currently, with adaptations of course and i've matched it with MQTT but im not too fussed about MQTT.

https://github.com/hobbyquaker/artnet

 im just trying to figure out how i can essentially set out different integers to change depending on color (This isn't easy to explain my apologies).

**Comment by mariusmotea** [comment]
> This is a Node.js module that can be used to send ArtDMX packages to an Art-Net node.

We need to receive, not to send forward, so this is not good.

**Comment by TheFonix** [comment]
Sorry, having a brain fart, why would you need data to be put into the Hue emulator, the signal flow should be 
`Hue App -> Bridge Emulator -> Art net Receiver -> DMX `

Thats why i sent that Github Repo as it has functions to send data towards an artnet node

**Comment by hartelt** [comment]
I'm very interested in this, as I also would like the color and brightness of my DMX lights with the Hue system. Has there been any progress?
My first Idea when I saw this project was interfacing a DMX controller through [Open Lighting Architecture](https://www.openlighting.org/ola/), which supports @TheFonix 'es Anyma as well as a number of cheap and simple DMX controllers. OLA runs on a Raspberry Pi and has a Python and a C++ API, but I have no experience with it.

**Comment by TheFonix** [comment]
I've used OLA for a number of years and getting some integration would be amazing, or even if diyHue could talk to a Anyma glad i'm not on my own here @hartelt ! :)

**Comment by mariusmotea** [comment]
For me DMX applications/controllers are unknown territory. If you can provide me an easy api i can implement it.

**Comment by TheFonix** [comment]
There is application frameworks such as:
- https://github.com/cansik/artnet4j
- https://github.com/hobbyquaker/artnet

You mentioned needing to receive data not send it but i dont understand how you can change light colors/brightness if your not sending any data around

**Comment by mariusmotea** [comment]
i need something like this https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf
were all commands are detailed.

**Comment by hartelt** [comment]
The ArtNet Protocol Specs can be found here: http://artisticlicence.com/WebSiteMaster/User%20Guides/art-net.pdf
I guess using an API would be easier though...

**Comment by TheFonix** [comment]
I don't think there is going to be any definitive Art-net API so using something like the OLA API might be a much easier route, there some documentation here:
 https://www.openlighting.org/ola/developer-documentation/python-api/

**Comment by cheesemarathon** [comment]
This looks quite hard to implement as im unable to find a function in OLA API that lists known DMX devices so discovery in the hue app would be impossible. Lights would have to be manually added to the config. Secondly, @mariusmotea and I have no experience with DMX or own any DMX lights to test with so development would be very hard. As such i'm closing this issue for now. It has however been placed in the suggested features project boards so anyone with python and DMX experience can pick it up later if they wish! I hope that's ok guys.
