### ISSUE TITLE
nRF24 - functionality suggestion

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#152]
It would be awesome if there was possibility to attach rf24 directly to the Pi. I currently use one esp8266 with modified light sketch to act as a rf24-wifi bridge and it's not ideal. With nRF24 it would be possible to make lights out of arduinos or even attinys... and in the future maybe even stm8s.

**Comment by mcer12** [comment]
nRF24 library supports mesh networking and even CTP/IP layer

**Comment by mariusmotea** [comment]
I start to study this protocol, there are some benefits for sensors (battery life, instant package delivery), but one major issue... no encryption, basically anybody with a sniffer can play with the devices in your home. Is there any option to add encryption that i miss?

**Comment by mcer12** [comment]
Some simple security like moving each byte value by 1 or something like
that might be sufficient. For someone who doesnt know the algorithm its
difficult to decrypt. They might still be able to send the payload to
different node but thats not much of an issue I think but Im not an expert
on encryption.

Dne 16. 1. 2018 9:13 odp. napsal uživatel "Motea Marius" <
notifications@github.com>:

**Comment by mcer12** [comment]
Take a look here
https://github.com/nRF24/RF24Mesh/issues/88
I like Scubatus' solution
"What I did to make it secure in a very simple way is XOR the payloads with a 16 bits key.
The Raspberry (Master) sends a new key every time it communicates with the Arduino so this makes it very difficult to crack. And even when that particular payload was decoded successfully, it's only valid for that specific payload and cannot be used again."

**Comment by mariusmotea** [comment]
Is complicated for me, but let's keep this opened here, maybe somebody will help.

**Comment by mcer12** [comment]
I came back to check any updates on this. I think even insecure nRF24 should be OK anyway since its just lights changing colors we're talking about :) Of course it's not suitable for opening garage doors etc but thats not really what this app should be used for. Security warning in project wiki should be OK i think.

**Comment by mcer12** [comment]
I'm doing some edits to my wifi-nrf24 bridge. I'll make pull request for the bridge sketch in near future. I also designed some pcbs (for wifi-nrf bridge, wifi sketch and nrf sketch) so if they prove OK I'll add them here together with case designs for 3d print.

**Comment by mariusmotea** [comment]
Any contribution is welcomed. Please ensure the images will be web optimised for small size. Currently the clone process of this repo is taking some time because of the images.

**Comment by cheesemarathon** [comment]
@mcer12 Have you made any progress on this? Shall I close this issue add add it to the suggested features project board?

**Comment by mcer12** [comment]
Indeed I do, I somewhat forgot about this issue. Leave it open I'll add the sketches.

**Comment by cheesemarathon** [comment]
@mcer12 Are you able to add a PR for review with your new sketches?

**Comment by mcer12** [comment]
@cheesemarathon I decided to ditch the esp8266 - rf24 bridge and instead, run the rf24 directly from the Pi. I used the RF24Ethernet library to emulate ethernet, so basically the rf24 sketch should be very similar to original wifi sketch. I can ping the RF24 arduino in terminal and I am able to see the content on arduino's IP address but the Hue app can't find the light.

**Comment by cheesemarathon** [comment]
No problem @mcer12 your heading in the right direction at least it seems!

**Comment by mcer12** [comment]
I managed to run a webserver on arduino+rf24 but there was significant packet loss and high pings so I didn't find it very reliable. To make this worse I wasn't able to find the rf24 light with diyHue so I decided to give up. With current prices of esp8266 I dont longer find any reason for the support anyway.
