### ISSUE TITLE
Orangepi looses connection to internet at night?

### ISSUE THREAD

**Issue by nikoli280397** [mariusmotea/diyHue#154]
Hi i after a struggle to set it up. with a good help. I now could controll my 120 WS2812B LED strip LEDs.

My plan was to use them as a sleep sunrise alarm. But my problem is that now it has happen twice and i haver never got the sunrise to work.  

The problem right now is that the Bridge (orangepi Lite) looses connection to the wifi so its  undiscoverable in the night, so when the sunrise alarm should begin in the morning it cant connect to the bridge. 

What can have caused this and what should i do to fix it. I thought i could be the temperature. But at 25% CPU load the temp is constant 60C which is high but not so high that it should affect the pi.

**Comment by mariusmotea** [comment]
Hi,
For sure this is not related to hue-emulator script wich is not cpu hungry. I believe the wifi chip on your orangepi is not working properly. In case this board has ethernet port i recommend to use it connected with cable, this way you will improve also the response time.

**Comment by nikoli280397** [comment]
It does not have a Ethernet unfortunately. When I tested via the armbian monitor it sit not seem to be the CPU. But I have no idea of what. Because doing the day it works flawlessly with the app. It's wiered that it looses connection at night

**Comment by nikoli280397** [comment]
I know that this it a forum for the firmware. But can someone help me doing this on a orange pi?

http://weworkweplay.com/play/rebooting-the-raspberry-pi-when-it-loses-wireless-connection-wifi/

**Comment by mariusmotea** [comment]
to be more simple do this:

`sudo crontab -e` or if you are root execute directly `crontab -e` 

appen the following line at the end (replace `192.168.1.1` with the ip of your router ...in 80% of the cases is right this) and save:

`*/5 * * * * ping -c4 192.168.1.1 || systemctl restart networking`

**Comment by mariusmotea** [comment]
vim is for advanced users, but you can try.
To write test at cursor position press `i`. Paste the text then pres `Escape` to leave from insert mode. if everything is ok hold `Shift` and press two times `z`
