### ISSUE TITLE
IFTTT support

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#156]
Is it possible to get ifttt support? U need to connect the hue bridge through the Phillips account to ifttt.com ...

**Comment by mariusmotea** [comment]
To create Philips account is required genuine hue bridge, this will not work.

**Comment by ticed35** [comment]
Hello, 
You can use WebHooks action on IFTTT to control your Hue lights. 
You need to expose your Hue bridge through internet (Better to use other port than 80)

First create user to add it to whitelist and get username : 

Method | URI | Body | Result
-- | -- | -- | --
POST | http://LOCAL_IP/api | {"devicetype": "my_hue_app#devapi"} | "success": {"username": "8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxa"}

Then you can discover your lights to find which one to use : 

Method | URI | Result
-- | -- | --
GET | http://LOCAL_IP/api/8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxa/lights | {1: {...},2: {...},3: {...},4: {...},5: {...}}

Take number of light you want to control.
I choose number 5 and to turn on light :

Method | URI | Body 
-- | -- | -- 
PUT | http://LOCAL_API/api/8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxa/lights/5/state | {	"on": true     } 

So you can use this last method to control your light from IFTTT. Don't forget to change LOCAL_API by your external IP or DNS name and to open port.

On Webhooks : 

URL | Method | Content Type | Body
-- | -- | -- | --
http://EXTERNAL_IP/api/8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxa/lights/5/state | PUT | Application/JSON | {	"on": true     }

Exemple to turn blue : 

{
	"hue": 50000,
	"on": true,
	"bri": 100
} 

Official api documentation (Registering required) : https://www.developers.meethue.com/philips-hue-api
Unofficial api documentation : http://www.burgestrand.se/hue-api/

**Comment by mariusmotea** [comment]
anybody who expose the emulator to internet i recommend also to set ["config"]["linkbutton"] to false in config.json in order to deny new user creation. Because the emulator don't have a physical button it will accept by default all new user registration. In case you want to pair a new device then will require to temporary undo this change.

Marius.

**Comment by mariusmotea** [comment]
I consider this issue as solved. Feel free to reopen in case i'm wrong.
