### ISSUE TITLE
Generic_ON_OFF_device.ino not properly responding

### ISSUE THREAD

**Issue by am0815** [mariusmotea/diyHue#157]
This sketch seems not to respond properly, as when browsing to the device's URL and switching the button it doesn't toggle the blue highlighting. I think this is the same problem which causes an issue with Amazon Alexa as when you say "Turn on/off the device" she doesn't respond with "OK" as she normally does. Attached is my current sketch, which only uses one Pin (12) with a relay attached to it. Everything works properly, except the issue stated above.
https://pastebin.com/NT8WRLZn

**Comment by mariusmotea** [comment]
I found at last one issue:

```
    http_content += "<a class=\"pure-button"; if (device_state) http_content += "  pure-button-primary"; http_content += "\" href=\"/?on=true\">ON</a>";
    http_content += "<a class=\"pure-button"; if (!device_state) http_content += "  pure-button-primary"; http_content += "\" href=\"/?on=false\">OFF</a>";
```
device_state here is an array, so i guess a the simplest fix (not the perfect) is to monitor first light, so replace `device_state` with `device_state[0]`

**Comment by am0815** [comment]
Thank you, that solved the issue with toggling. But the Alexa response wasn't affected. I was able to solve this with replacing the type of lamp during detection from `Plug 01` with `LWB010`.

**Comment by mariusmotea** [comment]
You can make a pull request with your finding if you want to be a contributor.
