### ISSUE TITLE
Lights not found

### ISSUE THREAD

**Issue by Haapavuo** [mariusmotea/diyHue#160]
Hi,

I was not able to configure diyHue properly with my Philips Hue Bridge & Lights.

Android Hue app sees the Hue Bridge Emulator running but it won't find any lights. The emulator prints out 

['192.168.1.1', '192.168.1.198', '192.168.1.101', '']
registration fail, is the link button pressed?

I haven't touched the config.json. Should I?

My real Hue Bridge has IP 192.168.1.198 so the emulator seems to find it.
The emulator (Raspberry Pi 3) IP is 192.168.1.101 which also appears on the list above.

I have tried pressing the button on my Hue Bridge but it doesn't seem to help here.

Any hints? Thanks.

**Comment by mariusmotea** [comment]
Did you follow https://github.com/mariusmotea/diyHue/wiki/5.-Hue-Bridge-Lights ?

**Comment by Haapavuo** [comment]
That solved it, thanks! Didn't realize there was a wiki for this. :)
