### ISSUE TITLE
Deletet Hue Clients! No way to add Again ??? (Generic_ON_OFF_device.ino / NodeMCU)

### ISSUE THREAD

**Issue by NedSin** [mariusmotea/diyHue#163]
Hey Guys,
sorry my English skills are very Bad ;) 

I have inadvertently delete the devices from the "Generic On/Off Switch" sketch on "NodeMCU" in the "HUE" App. 

Im not able to add them again and some tricks like change mac adress like this: 

>// Set as SoftAP and client
 > WiFi.mode(WIFI_AP_STA);       
 >// Change MAC 
 >byte *mac = (byte*)malloc(6);
 >WiFi.macAddress(mac);
 >mac[0] = 0xXX;
 >mac[1] = 0xXX;
 >mac[2] = 0xXX;
 >mac[3] = 0xXX;
 >mac[4] = 0xXX;
 >mac[5] = 0xXX;
 >wifi_set_macaddr(STATION_IF, mac);
 >mac[2] = 0xCB;
  >wifi_set_macaddr(SOFTAP_IF, mac);
 >free(mac);

... doesnt Work. 

Hue Bulbs etc. can be reseted, but what to do with ESP8266 ???

Hope i can find help here ...

Best Greeting

Ned ...

**Comment by mariusmotea** [comment]
Hi,
so you tried to replace the mac address to look like is a new device. This might work, but it must not be necessary, once the lights are deleted they can be added back with a new scan, except if:
 - you have one esp8266 board with multiple lights and delete just some lights, not all
 - you broke the light detection (nmap package?)

can you provide config.json file and the mac address of the esp in order to check what can be the problem?

Marius.

**Comment by NedSin** [comment]
Hey Marius,
thank you for your help 

Ive tried to run a rollo up down sketch and edit the generic on/off switch sketch like one item in hue u.s.w 
by this i have deleted all device in the emulated bridge and the original bridge ... Very bad idea ... 

I cant find the config.json (i`m a beginner) in the nmap folders.
Can you tell me where to find it ? 

So long the MAC: 2b:82:43:e8:3a:2c

I know makes no sense without config ... 

Greetings ...

**Comment by mariusmotea** [comment]
I recommend you to start with the default config from here https://github.com/mariusmotea/diyHue/blob/master/BridgeEmulator/config.json

Add the lights and create again the rooms

**Comment by NedSin** [comment]
Hey, 
thank you, i will do so ... 

I think on the Original HUE Bridge ihave to reset too ? 

Thank you for your help ... 

Greetings

**Comment by mariusmotea** [comment]
No, don't reset the original bridge, is not required.

**Comment by NedSin** [comment]
Hey Marius,

i really at the end of my Knowing ... 

i have completed format the sd card of my RasPi3 and installed Raspbian again.
Installed only the diyHUE
 at the first time on hue app one new lamp where found and the app crash, no way to open the app without crashing. 

Reinstalled Raspbian again and installed diyHUE again without any other apps (the needed are installed) 
Reseted the Bridge Complete and Reinstall the HUE app ... 

Found the emulated bridge and add her ...
Search for Lamps ... WLAN has no Internet ??? Really when i searched for lamps my android tells me WLAN has no internet and thats really so till Reboot Android Phone. 

Third time reinstall Raspbian and diyHUE 

Found Emulated bridge, add her and make /hue 

6 of 7 Lamps are found ... 

Search for lamps ... "No HUE connection" and wlan turns off (complete off not no Internet).

Go to Original HUE in the App and add the 7th Lamp ...

Back to Emulated Bridge in HUE app ... 

6 of 7 lights ! the new one not there ... 

Do /hue again and have doubled the 6 of 7 but the 7th is also there ... 

I dont know what do do ... It really komplikated ... and all my fail ;) 

No other (NodeMCU with generic 433MHZ or ON/OFF) Device found with the original bridge :(

Thank you for your Help, but I think for me is no chance to get diyHUE run correct ... why ever !!!
Thats extrem sad ... perhaps someone or you Marius have an idea what i can do ... 

Greetings

Ned

**Comment by mariusmotea** [comment]
Hi,

is not necessary to flash the sd card, in case you want to start from zero just download config.json file again from this repository and replace on sdcard, then restart the hue-emulator service with `sudo systemctl restart hue-emulator`

1. Did you install the hue emulator using the automated installation script?
2. Did you use the official arduino on_off sketch from the repo?
3. In the config you paste i see 8 lights imported from original hue bridge. Can you tell me what is the name that is not displayed in emulated bridge?

**Comment by NedSin** [comment]
Hey Marius thank you for the answer. 

The first thing if tried was to add the zero config.json and restart.
After that i was not able to connect the emulated bridge in HUE App ... 
Than i Formatted the SD and start again ...


I have now a fresh Home-Assistent install with raspian lite. 

I think i try it in the evening / night again ... 

I install it with the automated Installation script, like i have it bevor too ... 

Answers of your Question:

1. Yes i did ...

2. [I uploaded this sketch](https://github.com/mariusmotea/diyHue/tree/master/Lights/Arduino/Generic_ON_OFF_device_433Mhz)

3. The device is the NodeMCU with the sketch that i linked above. It was working. But i was so Stupid to delete the light, because i want to edit the sketch for a Rollo Switch ... 

That Device had the IP 192.168.0.51 ... 
The Device 192.168.0.50 is in the config but was not showing in both HUE Bridges ... 

Hope i made it. 

Will Install ist i the evening again, if you have some tipps for me, would be great ... 

Best greetings Marius ...

**Comment by mariusmotea** [comment]
one tip that can help to debug in case of issues. Start HueEmulator3.py script manually by stopping the service and run `sudo /opt/hue-emulator/HueEmulator3.py` this way you will have the output of every operation. In case you see any error paste here to see what generated the error.

Marius.

**Comment by NedSin** [comment]
Hey Marius, 
Today i have good news and i have Bad News ... 

The Good thing is that the emulated HUE Bridge works fine with the lamps of the original HUE bridge. 

Now the Problem with my two NodeMCU ESP8266: 

The one who was never registered in the Hue/diyHue could be found and add in the emulated bridge.
After this the Devices alway shown ass "Offline". 
I think the WiFiManager library works bad in my Network but i was not able to write the sketch to an normal ESP8266WiFi Library ;) ... i tryed a few times but when connected the webserver dont run. 
Its in my Network with the ip end 50 but really slow connection on Browser and no connection in hue. I Think this is not an issue of diyHUE, rather it be an issue of the NodeMCU or the WiFiManager ... 

Now the NodeMCU wich was the trigger for the complete Problem in this thread ;( : 
I`m not able to add her ... no way, no chance. The WebServer runs at /detect but nothing shown in the emulated hue bridge. 

than i want to make your tip with start HueEmulator3.py script manually and than that:

```
pi@raspberrypi:~ $ sudo /opt/hue-emulator/HueEmulator3.py
CRITICAL! Config file was not loaded

```

I think i try to get another MAC for the NodeMCU, in case of its possible to made it (i`m not sure about this with the WiFI Manager in the Sketch) 

Have you any Idea for me ? 

once again really Sorry for my Bad English and Thank you for your help because this system is a dream. 
Controll the whole Home via Hue at Mobiles, Macs and especially the Harmony One Ultimate. 

Best Greeting 

Ned ...

**Comment by mariusmotea** [comment]
Hi Again,

To debug the lights, try from raspberry pi `curl https://x.x.x.50/detect` repalce x.x.x with your local subnet. What is the output? If there is connectivity from raspberry py to both nodemcu devices, then they must be detected.

```
pi@raspberrypi:~ $ sudo /opt/hue-emulator/HueEmulator3.py
CRITICAL! Config file was not loaded
```
my bad, you  must go in /opt/hue-emulator/ directory first

```
cd  /opt/hue-emulator/
sudo ./HueEmulator3.py
```

Search for lights, see if the ip of both nodemcu boards apear in the list during scanning.

PS. backup config.json to be sure you cannot broke anything. This is automatically saved every hour (minute 00), or by accessing https://{raspberry ip}/save

Marius.

**Comment by NedSin** [comment]
Hey,
both Nodemcu are connected to my WiFi Router, the Raspi is connected via cat5 LAN ... 

the Output of /detect is:

`{"hue": "bulb","lights": 1,"modelid": "Relay","mac": "2b:82:43:e8:3a:2c"}
`

Everthings fine but HUE emulated bridge dont find. 

I have now the log, not the complete but the part i have start search. 
The IP`s thats shown are Mac`s, Routers, etc. but searched not by end ip 50 or 51 or so ...

> start ssdp broadcast
> sync with lights
> Starting httpd...
> Sending M-Search response to 192.168.0.111
> 192.168.0.111 - - [04/Feb/2018 17:06:29] "GET /description.xml HTTP/1.1" 200 -
> Sending M-Search response to 192.168.0.111
> Sending M-Search response to 192.168.0.111
> Sending M-Search response to 192.168.0.97
> Sending M-Search response to 192.168.0.97
> Sending M-Search response to 192.168.0.111
> Sending M-Search response to 192.168.0.111
> Sending M-Search response to 192.168.0.111
> Sending M-Search response to 192.168.0.180
> Sending M-Search response to 192.168.0.180
> 192.168.0.170 - - [04/Feb/2018 17:07:22] "GET /description.xml HTTP/1.1" 200 -
> Sending M-Search response to 192.168.0.180
> Sending M-Search response to 192.168.0.180
> Sending M-Search response to 192.168.0.111
> 


i have no idea what to do ...

**Comment by mariusmotea** [comment]
One issue that i believe is the root one:

`"modelid": "Relay"` must be `"modelid": "Plug 01"` 
Please use the original sketch and apply changes just in header of the files where you specify the number of lights and the gpio pins.

Marius.

**Comment by NedSin** [comment]
THATS IT ... Yeah ... Thats the little thing what goes Wrong. 

Sorry i thought that there can Add a Name that shows in the HUE app, never have think thats this is an big big fail.

I edited the sketch for Different jobs, the one above open the window shutter 30 sec. long when light in hue app is on. If light off the sketch close the window shutter 30. sec long. 

This with NodeMCU and 2 Relays simple but Effektiv. 

Is there a Place where i can upload this sketch for other who want make this ? 
It works now perfekt ... 

Big Big Thank to you.

**Comment by mariusmotea** [comment]
Yes, for example Generic_ON_OFF_device_433Mhz was uploaded by the user Mevel. You need to fork this repo, upload you sketh with a new folder inside Lights directory and then create Pull Request. I will merge. If you never worked with git before read [this](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by NedSin** [comment]
Okay thats great.

When I complete Finish the sketch i will do upload it like you say and read the link you gave me. 

Close this Issue and will go on with my SmartHUEome projekt ... 
I will test your qtHue and are very excited for it. 
Hope there is the function for own Design and Colors, that would be great ... 

Thank you Marius ...
