### ISSUE TITLE
Kodi Philips hue

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#165]
I tried a Kodi Hue Plugin in the last days and notice that the colors are a bit wrong. Does someone have the Plugin working and can give me a hint for the right Plugin (i found a few on github) and the right settings?

**Comment by mariusmotea** [comment]
I use it. can you provide more details, maybe i did not notice the problem. After some time i switch to cinema mode (lights are dimmed when movie starts and automatically resume then i put pause or stop).

**Comment by oleg2204** [comment]
I use the ambilight mode. I assume my problem is rather related to the kodi plugin and i think it some kind of setting fail in the plugin. For example: If i have a red scene in the video the lights get a purplish color. 
There are some settings like saturation and other think that i dont rly know what they do :/ . So i hoped someone is using the kodi plugin and can post his settings here. Or maybe there is some better plugin out there.

**Comment by cheesemarathon** [comment]
@oleg2204 Have you managed to improve the performance or do you need more help?

**Comment by cheesemarathon** [comment]
@oleg2204 I'm going to close this issue due to lack of communication. If you still want support, please re-open this issue.
