### ISSUE TITLE
Scheduling timezone issue

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#167]
I found out the scheduler in my location (central europe timezone) is launching one hour later than it's supposed to. I found an option to change timezone in Hue app settings and it's set to Bucharest by default. If I try to change it, it returns an error Couldnt load timezones.

**Comment by mariusmotea** [comment]
Need help from somebody with real hue brigde. On internet timezones list is truncated because is too big. I only need to add more timezones in capabilities and the problem will be solved.

**Comment by mariusmotea** [comment]
As workaround you can manually replace in config.json the timezone. You must figure what zone/city is good for you. Don't forget to restart the service.

**Comment by mcer12** [comment]
I did this and the time was still off. I had to change the timezone on my orange pi too and it seems to work now. Thanks!
