### ISSUE TITLE
Hue emulator service inactive (dead) 

### ISSUE THREAD

**Issue by rbonvino** [mariusmotea/diyHue#168]
Hi, I just installed the hue emulator service in a fresh Jessie on a Raspberry Pi2, but when i launch the service and check the status I get that is inactive (dead). I got no errors from automatic installation and have no errors in the service start. What's the problem? Thanks to all.

**Comment by mariusmotea** [comment]
Can you manually execute cd script? 
```
cd /opt/hue-emulator
sudo ./HueEmulator3.py
```

**Comment by rbonvino** [comment]
Hi, I get the following error:
![image](https://user-images.githubusercontent.com/7695809/35906256-24e2a55a-0bea-11e8-97e3-7171dc43fd24.png)

**Comment by mariusmotea** [comment]
you have some services that already run on ports used by hue-emulator. Maybe service is still running and when you execute manually the conflict was created.

try first:

`sudo systemctl stop hue-emulator`

then execute:

```
cd /opt/hue-emulator
sudo ./HueEmulator3.py
```

**Comment by rbonvino** [comment]
Hi, I have the same error. Maybe it's because I have a openhab2 instance open on the port 8080?

**Comment by mariusmotea** [comment]
Port 8080 is not used. Show me the error and i will tell you what is the issue.

Marius.

**Comment by rbonvino** [comment]
Hi, this is the error.
![image](https://user-images.githubusercontent.com/7695809/35908757-d95dc530-0bf1-11e8-9701-4ededf0dae3c.png)

**Comment by mariusmotea** [comment]
you have secondary ssdp service, maybe is openhab2.

You can check with `sudo netstat -lnup`
check the process that is currently listening on port 1900
if you see just the pid id, then try `ps aux | grep {founded pid}`

Optionally you can disable ssdp service, but most hue apps will not be able to automatically detect the hue-emulator on the network, so you will need to manually specify the ip address.

Marius.

**Comment by rbonvino** [comment]
Yes, the port is owned by openhab2. Can you tell me how to disable ssdp service? I just want to control two Tradfri bulbs through raspbee. Thanks.

**Comment by mariusmotea** [comment]
At the bottom of the HueEmulator3.py script you have this:

```
if __name__ == "__main__":
    if bridge_config["deconz"]["enabled"]:
        scanDeconz()
    try:
        if update_lights_on_startup:
            updateAllLights()
        Thread(target=ssdpSearch).start()
        Thread(target=ssdpBroadcast).start()
        Thread(target=schedulerProcessor).start()
        Thread(target=syncWithLights).start()
        run()
```
just comment the line `Thread(target=ssdpSearch).start()`
ex: `#Thread(target=ssdpSearch).start()`

**Comment by rbonvino** [comment]
No, way. I checked the service status and is always inactive (dead).

**Comment by rbonvino** [comment]
![image](https://user-images.githubusercontent.com/7695809/35910214-28e5f45c-0bf6-11e8-99a3-ba1169f5a53f.png)

**Comment by mariusmotea** [comment]
maybe you have something also on port 80?
check with `sudo netstat lntp `

**Comment by rbonvino** [comment]
I have an apache server using the 80 port.
![image](https://user-images.githubusercontent.com/7695809/35912877-242f1a76-0bfe-11e8-92e1-cb938b58a52e.png)

**Comment by mariusmotea** [comment]
Port 80 is mandatory for hue-emulator. You need to move apache to other port.

**Comment by rbonvino** [comment]
That did the trick. Thanks.

**Comment by rbonvino** [comment]
Hi, I spoken too early. It works only if I start it manually and not as a service. Do you have ideas about this?

**Comment by rbonvino** [comment]
Maybe some permission issue?

**Comment by mariusmotea** [comment]
must work also as service. 

`sudo systemctl status hue-emulator -l`

what is the output?

**Comment by rbonvino** [comment]
![image](https://user-images.githubusercontent.com/7695809/35918521-62c9bb4c-0c12-11e8-92ab-0011027b63de.png)

**Comment by mariusmotea** [comment]
Hmm, wired.

You did not made any other changes except to comment that ssdp line?

i was expected systemd to show the error. In syslog can you see something interesting when you execute `sudo systemctl start hue-emulator` ?

**Comment by rbonvino** [comment]
I just commented that line. In syslog there's nothing about hue-emulator when i start It.

**Comment by mariusmotea** [comment]
I don't have any idea to debug this issue with not logs. If from manual execution it is working fine, it must work also from service. Did you try to reboot to see if it will start automatically?

**Comment by rbonvino** [comment]
Yes, i tried with no luck...

**Comment by rbonvino** [comment]
Maybe any error related to the service script?

**Comment by mariusmotea** [comment]
this is mine, check if your is (almost) identical:

```
pi@raspberrypi:~ $ cat /lib/systemd/system/hue-emulator.service
[Unit]
Description=Hue Emulator Service

[Service]

ExecStartPre=/bin/sleep 20
Restart=always
RestartSec=30
StartLimitInterval=200
StartLimitBurst=5
WorkingDirectory=/home/pi
ExecStart=/home/pi/HueEmulator3.py


[Install]
WantedBy=multi-user.target
```

i keep the script in `/home/pi` instead of `/opt/hue-emulator` and i use a delay of 20 seconds on start (`ExecStartPre=/bin/sleep 20`)

service status is this:

```
pi@raspberrypi:~ $ systemctl status hue-emulator -l
● hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-02-04 00:21:13 EET; 3 days ago
  Process: 357 ExecStartPre=/bin/sleep 20 (code=exited, status=0/SUCCESS)
 Main PID: 564 (HueEmulator3.py)
   CGroup: /system.slice/hue-emulator.service
           └─564 /usr/bin/python3 /home/pi/HueEmulator3.py

Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: {"config":{"alert":"none","battery":87,"duration":60,"group":"11930","on":true,"r
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: {"config":{"alert":"none","battery":60,"group":"51837","on":true,"reachable":true
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: {"e":"changed","id":"5","r":"lights","state":{"ct":250},"t":"event"}
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: Sending M-Search response to 192.168.10.13
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: {"e":"changed","id":"8","r":"sensors","state":{"dark":false,"lastupdated":"2018-0
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: set triggered flag
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: ddx rule 77 canceled after 159 seconds
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: {"e":"changed","id":"8","r":"sensors","state":{"dark":false,"lastupdated":"2018-0
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: Sending M-Search response to 192.168.10.12
Feb 07 17:02:02 raspberrypi HueEmulator3.py[564]: Sending M-Search response to 192.168.10.12
```

**Comment by rbonvino** [comment]
I was using the default script made by the auto_install. I reproduced yours one and now everything works as expected. Thanks
![image](https://user-images.githubusercontent.com/7695809/35926196-e40cc39c-0c27-11e8-80c7-01b7091fa121.png)

**Comment by rbonvino** [comment]
I would to ask if it is possible to emulate a tradfri bridge and communicate with the ikea bulbs with raspbee and if it possible to communicate with it as it is a hue bridge. Thanks.

**Comment by mariusmotea** [comment]
Why do you want to emulate tradfri bridge? There is no benefit, just a big lack of options and applications..

**Comment by rbonvino** [comment]
Because i want to control it using openhab2. As far as i know it is not possible to openhab to control a tradfri bridge.

**Comment by mariusmotea** [comment]
but if you use raspbee module you will communicate directly with tradfri devices, without tradfri gateway. I use tradfri gateway just to upgrade the firmware of my devices. Basicaly will be like you have an original Hue Bridge that is connected to some tradfri bulbs and sensors. Hue application know to configure just hue devices, for this reason there is dedicated webpage in hue-emulator to configure trafri devices (basically to add the rules).

**Comment by rbonvino** [comment]
So the idea would be to discover the bulbs directly from hue-emulator and to make openhab2 communicate with it as it is a hue bridge? What about the fact tha i can't use the sdp now? Thanks.

**Comment by mariusmotea** [comment]
you will discover the bulbs from deconz, the raspbee driver. Openhab works with hue-emualator, is possible to work directly with deconz. For ssdp issue, try to start first the hue-emulator, then openhab2, maybe openhab will not use ssdp once the port is already in use. Search openhab issues page, maybe there is a workaround to stop internal ssdp service.

**Comment by rbonvino** [comment]
Do you Think it is useful ssdp with the above configuration?

**Comment by mariusmotea** [comment]
Not really, after you pair the application the future connections will be made based on recorded mac address. There will be an issue if you like some hue applications that perform always ssdp discover, but i believe are just a few. Note that will be possible to stop openhab and start hue-emulator with ssdp service enabled in case some application  require ssdp during bridge joining only.

**Comment by rbonvino** [comment]
I want just to pair two bulbs and use openhab with its app instead of the hue original one. Do you think it's possible without ssdp?

**Comment by mariusmotea** [comment]
cannot confirm, i'm not an openhab user, other users confirm openhab is working with this emulator, not sure if ssdp is vital. I believe it will work.

**Comment by rbonvino** [comment]
I will give it a try when arrives the Raspbee and let you know. Thanks.

**Comment by rbonvino** [comment]
Hi, do you think there could be problems if i set the deconz port to 8090? My 8080 port is busy with openhab. I'm running deconz and openhab on the same raspberrypi.

**Comment by mariusmotea** [comment]
in config.json you have the deconz port specified (deconz => port ). Restart the service

**Comment by rbonvino** [comment]
Thanks

**Comment by rbonvino** [comment]
I'm having some problems compiling the deconz-rest-plugin . Is necessary for hue-emulator to work?

**Comment by mariusmotea** [comment]
the plugin is also bundled in deb files, is required to compile just in case you want to add changes, otherwise install just the deconz deb file (without -dev).

**Comment by rbonvino** [comment]
The setup is working like a charme... Thankyou for all!
