### ISSUE TITLE
WiFi disconnects when changing scenes and strip turns red

### ISSUE THREAD

**Issue by EgeSS** [mariusmotea/diyHue#169]
After a lot of tries,I've managed to set up the WS2812B strip but,not in the hue application.When i try to change the scene to Concentrate or most of the scenes that contain white it crashes and the WiFi disconnects.Also,i still couldn't add the light to the hue bridge.Can someone pls help?

**Comment by mariusmotea** [comment]
What is the number of leds and lights you set in arduino sketch? Any other changes outside the "user area"?

**Comment by EgeSS** [comment]
6 lights,30 leds.I've tried several times on the hue app.I even tried the gen1 hue app.But still,i can't connect.

**Comment by mariusmotea** [comment]
ok, debug with the following commands:

on host where hue-emulator is running:

`nmap 192.168.1.0/24  -p80 --open -n | grep report | cut -d ' ' -f5`

replace the ip with the one used on your network. Is the ip of the esp8266 listed?

`curl http://{light ip}/detect`  provide any output?

Provide the output of hue emulator during light scanning by running the script manually:
```
sudo systemctl stop hue-emulator
cd /opt/hue-emulator
sudo ./HueEmulator3.py
```

**Comment by mcer12** [comment]
Issue with white causing restarts could mean you have insufficient power supply.
