### ISSUE TITLE
Group "0" Not Properly Reported When Queried

### ISSUE THREAD

**Issue by shbatm** [mariusmotea/diyHue#172]
Group "0" is a special group which contains all of the Hue lights attached to a particular bridge.  It does not show up when you query `/api/username/groups` but does report out if you query `/api/username/groups/0`:

```shell
{"name":"Group 0","lights":["1","2","3","4"],"type":"LightGroup","state":{"all_on":false,"any_on":false},"recycle":false,"action":{"on":false,"bri":254,"hue":47258,"sat":253,"effect":"none","xy":[0.1424,0.0824],"ct":153,"alert":"none","colormode":"xy"}}
```

This is not yet implemented in your code, and causes an error when other software attempts to query the groups by calling `groups` and then `groups/0`. 

This may also be related to #76, if the Echo is querying the groups and not getting a response back for "0" (All Hue Lights) it will not add the scenes.

**Comment by shbatm** [comment]
More explanation from the [API on Groups](https://www.developers.meethue.com/documentation/groups-api):

Group "0" is "A special group containing all lights in the system, and is not returned by the ‘get all groups’ command. This group is not visible, and cannot be created, modified or deleted using the API."

**Comment by mariusmotea** [comment]
Hi,

Never saw any example so far with output from group 0, i was believed this is used just to set some values to all lights. Can you confirm the output you provided is correct ?
Marius.

**Comment by shbatm** [comment]
Yes, the above JSON was a dump from my actual bridge `/api/username/groups/0` call will no lights on.

Here is all lights on, different colors:
```
{"name":"Group 0","lights":["1","2","3","4"],"type":"LightGroup","state":{"all_on":true,"any_on":true},"recycle":false,"action":{"on":true,"bri":254,"hue":47258,"sat":253,"effect":"none","xy":[0.1424,0.0824],"ct":153,"alert":"none","colormode":"xy"}}
```
And here is just some lights on:
```
{"name":"Group 0","lights":["1","2","3","4"],"type":"LightGroup","state":{"all_on":false,"any_on":true},"recycle":false,"action":{"on":true,"bri":254,"hue":47258,"sat":253,"effect":"none","xy":[0.1424,0.0824],"ct":153,"alert":"none","colormode":"xy"}}
```

**Comment by mariusmotea** [comment]
ok, i will implement.

**Comment by mariusmotea** [comment]
I made a simple implementation, but still i'm not sure how the values from the state are generated on real bridge. I guess they may be the last values applied directly to this group, but so far i never saw any application that apply xt, ct or bri to all lights.

**Comment by shbatm** [comment]
Thank you for the quick turnaround. I doubt there's much use for the state values being reported specifically, but the report out of the group in general allows discovery of the "All Hue Lights" group in my case.  There is definitely use for the All Lights use when turning everything off, but it looks like this is handled already elsewhere in the code. If I find something that requires a more specific use for the state being reported through the `/api/username/groups/0` call, I will re-open.

For your reference, my use is based on the https://github.com/studioimaginaire/phue repo, specifically studioimaginaire/phue#100 which is used in the https://github.com/exking/udi-hue-poly repo.
