### ISSUE TITLE
easy install not possible

### ISSUE THREAD

**Issue by dr-hackepetzi** [mariusmotea/diyHue#174]
Hy,
i get following error message:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f6b6g8d8/ws4py/

It worked on my old raspberry pi 3 with the manual install.
But on my new raspberry pi 3 it don't want to install with the "easy_install.sh".

Can you help me with this? Everything i found on google is not usefull and it doesn't fix my issue.

Greetings

**Comment by mariusmotea** [comment]
Hi,

For some reasons pip fail to install ws4py package. This is used just in case you use Raspbee module. If you don't use it, then skip this one and execute manually the rest.

[Here](https://raw.githubusercontent.com/mariusmotea/diyHue/master/BridgeEmulator/easy_install.sh) are the commands executed.

Marius.

**Comment by mariusmotea** [comment]
Fixed
