### ISSUE TITLE
ESP8266 GU10 Bulb

### ISSUE THREAD

**Issue by UnReal933** [mariusmotea/diyHue#175]
Hello and thanks for this awesome work.

Does someone have already found GU-10 bulbs directly built-in with esp 8266 ?

All the GU10 bulbs available are working with MiLight and need MiLight Hub to work .. 

[See here](https://fr.aliexpress.com/item/100-Original-Mi-Light-2-4G-WiFi-Control-RGBW-RGB-WW-LED-lamp-4W-5W-6W/32789195460.html?spm=a2g0w.search0104.3.92.e2c92c13Y5pPRg&ws_ab_test=searchweb0_0,searchweb201602_5_10152_10151_10065_10344_10068_10342_10343_10340_10341_10084_10083_10618_10305_10304_10307_10306_10302_5711211_5722315_10313_10059_10184_10534_100031_10629_10103_10626_10625_10624_10623_10622_10621_10620_10142,searchweb201603_25,ppcSwitch_5&algo_expid=006c4610-1bb8-4706-baf7-cd66d7e5ec00-13&algo_pvid=006c4610-1bb8-4706-baf7-cd66d7e5ec00&priceBeautifyAB=0)

**Comment by mariusmotea** [comment]
Hi,

I tried to search for some pictures to see how much free space is inside this bulbs. AlI i find is [this](https://stair-lighting.com/images/MI-LIGHT/FUT018/FUT018-5.jpg) i believe is possible to fit one small esp board inside, but you need skills .

Marius.

**Comment by UnReal933** [comment]
Hi,

What do you think about these one: [Here](https://www.hama.com/00176532/hama-wifi-led-light-gu10-45w-rgb-can-be-dimmed#technical-details)

I just doesn't find where to buy them.

**Comment by mariusmotea** [comment]
It may work if is based on esp8266 with pwm, but you cannot be sure about this until you buy and open one.

**Comment by cheesemarathon** [comment]
Hi @UnReal933
Can you close this for now? Feel free to discuss hardware further in our slack chat (link to join in readme)
Thanks

**Comment by danj1980** [comment]
@UnReal933 This is my first comment on Github so I apologise if it is not etiquette to comment on closed posts. Just found a load of Youtube videos talking about the ability to flash new firmware onto smart devices which has opened up a whole new world for me. This thread came up when I saw searching so thought I'd reply. Hope it helps! Just opened up the front of a Lohas GU10 smart bulb and found they have ESP8266 onboard. Not tried doing anything with it yet though. Baby steps.
Hope that helps.
![IMG_20190311_200827](https://user-images.githubusercontent.com/12071228/54154745-87e16b80-443a-11e9-8395-793e02f7b3f0.jpg)
![IMG_20190311_122150](https://user-images.githubusercontent.com/12071228/54154751-8a43c580-443a-11e9-8f7b-5c68b1ff83d6.jpg)

**Comment by UnReal933** [comment]
@danj1980 

Many thank for your work. I have to admit that one year ago I did not found ESP8266 based bulb and choose to use Mi-Light Bulb with a Milight Hub on an ESP8266.

I'm very happy to see someone who found an ESP8266 based bulb. I just took a look, and the price seems correct. 

I would be highly interrested if you manage to flash it with DIYHue firmware and add it to hue 🥇

**Comment by mariusmotea** [comment]
@danj1980 unfortunately this bulb use the  NY92XX pwm chip. There is an implementation on this repo but some users report to not work. As i don't have this bulb i cannot test it. As a good practice if you want to give it a try just desolder the SPI fash chip that contain the current firmware and use another one from any ESP8266 boards.
