### ISSUE TITLE
OpenWrt support?

### ISSUE THREAD

**Issue by juanesf** [mariusmotea/diyHue#178]
hello, I'm trying to run the emulator in OpenWrt 15.05 under python2 and python3. is python3 I have problem with python3-pip is not found in the repos so the code fails and when importing asks for pip.
in python2 I have problem executing the code, the action def getIpAddress (): s = socket.socket (socket.AF_INET, socket.SOCK_DGRAM) s.connect (("8.8.8.8", 80)) return s.getsockname () [0] change the main address of my router to the WAN (external ip). How do I leave the local address of my fixed router?

**Comment by mariusmotea** [comment]
I don't know how you can retrieve the LAN ip interface in OpenWRT. Better set the ip static, maybe there are also other issues.
Try this, and replace the ip with the router one:
```
def getIpAddress():
    return "192.168.1.1"
```

**Comment by juanesf** [comment]
root@GL-MT300A:/overlay/upper/opt/hue-emulator# python2 HueEmulator.py
Config loaded
server stopped [Errno 125] Address already in use
start ssdp broadcast
sync with lights
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "HueEmulator.py", line 139, in ssdpBroadcast
    sent = sock.sendto(message + "NT: " + custom_message[x]["nt"] + "\r\nUSN: " + custom_message[x]["usn"] + "\r\n\r\n",multicast_group_s)
error: [Errno 128] Network is unreachable

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "HueEmulator.py", line 111, in ssdpSearch
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 19] No such device

config saved

**Comment by mariusmotea** [comment]
I believe OpenWrt is using port 80 and this is mandatory for hue-emulator.

**Comment by juanesf** [comment]
hello, changed port 80 occupied by luci (lighttpd) to 82, and the line:
def getIpAddress ():
return "192.168.1.1"
with that I could run the version HueEmulator.py on GL-MT300A with Openwrt Chaos Calmer 15.05, running python2 in 2Gb partition on microSD as overlayroot. Thanks

**Comment by juanesf** [comment]
Thanks you very much...
