### ISSUE TITLE
Can't use RGB on RGB+CCT Milight bulbs.

### ISSUE THREAD

**Issue by tbrasser** [mariusmotea/diyHue#18]
I finally got everything set-up, with a neopixel ledstrip and a couple of RGB+CCT Milights. I added the milights as RGB+CCT lamps (which they are, and they function normally outside of the HueEmulator). But when I try to set them to a color, they don't respond. (they seem to be stuck in CCT mode, because that functionallity works well). It's the same in both manual control as when trying scenes.

**Comment by mariusmotea** [comment]
Hi,

I double check now milight hub api and i saw that rgb data was sent without the key "color". I fix this in last commit from develop branch. Please check and confirm.

Marius.

**Comment by tbrasser** [comment]
You fixed it! Thanks :D

**Comment by mariusmotea** [comment]
Good!
P.S. you can convert Milight bulbs to ESP8266 to have a better support.

**Comment by tbrasser** [comment]
Yeah I know, but I have 50+ of them 😅
