### ISSUE TITLE
Device ID in milight configuration

### ISSUE THREAD

**Issue by francescofact** [mariusmotea/diyHue#180]
Where can i find the Device id of my bulbs?
I have successfully paired them to my MiLight Hub

**Comment by mariusmotea** [comment]
Device id is remote id. With milight hub you can emulate any remote id. To pair the bulb you need to put there a remote id (any), the add that id in hue-emulator

**Comment by francescofact** [comment]
Ok, i paired the bulb with the MiLight bridge v6 pressing link in the app when the bulb turned on. Now i can control it with my MiLight app.
to make it appear in the Philips Hue app i went to http://{my_rasp_IP}/milight
I wrote my milight hub ip in the first input, than i wrote 0x1234 (used the tip), selected the RGB+CCT, but in the app the bulb is not online.

**Comment by mariusmotea** [comment]
Milight hub is not reachable from hue emulator,or ip was typed wrong. Try to ping or check the output of the hue emulator script.

**Comment by francescofact** [comment]
I can ping it from my raspberry and the ip is correct. Are you sure that your software support the v6 protocol?

**Comment by mariusmotea** [comment]
But are you using the milight hub? I believe you are using the official gateway. That is not supported. This is the reason why device id is unknown. If you will use the milight hub for sure you will know it.

**Comment by francescofact** [comment]
Can you link me the official gateway? I don’t know what are you talking about

Francesco Fattori

**Comment by mariusmotea** [comment]
This is the supported device
https://github.com/sidoh/esp8266_milight_hub

Did you build it?

**Comment by francescofact** [comment]
oh thanks, i will try to build it.
Why you don't support the native udp protocol? it would be a lot easier
Il 22/02/2018 19:48:21, Motea Marius <notifications@github.com> ha scritto:
This is the supported device
https://github.com/sidoh/esp8266_milight_hub [https://github.com/sidoh/esp8266_milight_hub]
Did you build it?

**Comment by mariusmotea** [comment]
Usually to add support for a device i need to have it. For me is not worth to buy any new hardware as i already have smart lights in my entire house. Is not too easy to play with udp protocol also.

**Comment by francescofact** [comment]
So are these product ok for the built?
http://amzn.to/2CeFGqq
http://amzn.to/2oqvIc0

**Comment by mariusmotea** [comment]
Hi,

Must work. Any NRF24L01+ is good. Be aware that these are very cheep and low quality, i spent a few hours to debug the circuit, in the end i found the antenna (removable) worked only when was pressed a little bit. 

Marius.

**Comment by spidLL** [comment]
Just to clarify: the only supported way for the BridgeEmulator to communicate with miLights is to build that circuit, right?
If I use a milight official wifi hub (i.e. iBox2) it won't work, correct?

**Comment by mariusmotea** [comment]
True, you need to build that circuit.
