### ISSUE TITLE
Basic domoticz support (for eg z-wave lights)

### ISSUE THREAD

**Issue by mreijnde** [mariusmotea/diyHue#181]
Hi all,

I was looking for some hue emulation and stumbled on your nice project. I want to control both my z-wave lights and my new philips hue lamps with the same standard hue app. 

My z-wave lights are controlled by Domoticz (running on a rpi2) with a z-wave dongle. I can also add the hue lights to domoticz, but that does not give me the possiblity to control everything from the original hue app. Unfortunatly, I didn't see any support for Domoticz in the diyHue code yet. 

Last evening I looked at the code and spend some time on adding the basic domiticz support myself that I needed.  I am happy, I can now control all my lights from the hue app. I share here what I have done, maybe this is interesting for more people, or maybe domoticz  support can even be added in an official future version.

All lights controlled by domoticz can be operated through a simple api described in https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s .  To support this protocol  I added some small section to `sendLightRequest(..)' and 'syncWithLights()', see https://github.com/mreijnde/diyHue/commit/c462100aac6f9a968ade15c4a8076b54b858b932

The lights can be manual added to the config.json file. In the address section the ip and port of domoticz should be used, the light_id is the device idx from domoticz. An overview list can be easily obtained by: http://[domoticz ip]:[domoticz port]/json.htm?type=command&param=getlightswitches
```    
    "lights_address": {
        "7": {
            "ip": "192.168.1.100:8080",
            "light_id": "281",
            "protocol": "domoticz"
        },
       "8": {
            "ip": "192.168.1.100:8080",
            "light_id": "318",
            "protocol": "domoticz"
        },
    },`

```
and the lamp properties in the light section. 

```
  "lights": {
        "7": {
            "manufacturername": "domoticz",
            "name": "Eettafel",
            "state": {
                "alert": "none",
                "on": true,
                "reachable": true
            },
            "swversion": "V1.04.12",
            "type": "On/Off plug-in unit",
            "uniqueid": "xx:xx:xx:xx:xx:xx:xx:xx-xx"
        },
        "8": {
            "manufacturername": "domoticz",
            "name": "Speelhoek",
            "state": {
                "alert": "none",
                "bri": 249,
                "on": true,
                "reachable": true
            },
            "type": "Dimmer",
            "uniqueid": "xx:xx:xx:xx:xx:xx:xx:xx-xx"
        },
 ```

The on/off light (eg nr 7) still shows as a dimmer in the hue app. Does the hue app support on/off devices without showing dimmer bar? If so, what should I change in my parameters to get it fixed?

Remarks:
- no support for color lights from domoticz, but relative simple to add, parameters are available.
- automatic adding of lights should be possible based on the list created by 'json.htm?type=command&param=getlightswitches'. But it was not clear for me where to add that in the code.

Regards Merijn

**Comment by mariusmotea** [comment]
Thanks,

I will create a PR from your repo when i will arrive home. Seams easy to extend the support for colors, i believe i will do it.

Marius.

**Comment by mrrioes** [comment]
Hi,

I have problems to get it working.
In hue app lights are found but I´m not able to add them to a room. So it´s not possible to control them.
Any advice?

Thanks.

**Comment by mariusmotea** [comment]
I'm in a business trip this week, but maybe if you start the HueEmulator3.py script manually and provide the output i will be able to see the issue.

**Comment by cheesemarathon** [comment]
@mariusmotea Does this issue still exist?

**Comment by cheesemarathon** [comment]
I'm going to close this as support for Domoticz now exists. @mrrioes if your still having trouble getting Domoticz to work, then please open a new issue.
