### ISSUE TITLE
Lights won't turn off when applying a scene

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#182]
Hi, I've set a scene with some lights turned off completely but they don't turn off if they were turned on before the scene change. Simple ON/OFF sketch works OK but other sketches that support dimming or RGB don't.

**Comment by mariusmotea** [comment]
Hi, default behavior is to turn on the light on any attribute change. Few months ago i start to believe this is not correct, but i don't perform any fix.

Try this:

```
  server.on("/set", []() {
    light_state = true;
```

just remove `light_state = true;` line from here.

Marius.

**Comment by mcer12** [comment]
This doesn't seem to be the case. At least in generic dimmable light sketch, there is no such line.

**Comment by mariusmotea** [comment]
There is a little bit different:

```
else if (server.argName(i) == "bri") {
    light_state[light] = true;
```

remove ` light_state[light] = true;` from here (line 276).

Marius

**Comment by mcer12** [comment]
Works thanks!
