### ISSUE TITLE
Custom lamp name

### ISSUE THREAD

**Issue by freddebo** [mariusmotea/diyHue#184]
I’m looking for a feature to name the different lights for the SK6812 version. I would like to have 6+ units and would like to name this in the Arduino sketch for different lamps. Is it possible to add directly in the scetch or do I have to change all in the config file after they are added?

**Comment by mariusmotea** [comment]
You can rename the lights from hue application, is not necessary to perform changes in config.json.

**Comment by freddebo** [comment]
Yes, that is much easier! Thank you!
