### ISSUE TITLE
Generic RGB light won't get discovered

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#185]
Hi @mariusmotea I would like to point out that this commit is uncomplete:
https://github.com/mariusmotea/diyHue/pull/173
Only the HueEmulator3.py is updated but HueEmulator.py is not. Therefore LCT015 lights won't be discovered by the hue app... Found that out the hard way today when updating firmwares :)

**Comment by mariusmotea** [comment]
I know, but any change need also to be tested and time is a problem for me. I want to remove in time HueEmulator.py and go forward with HueEmulator3.py. If i'm not wrong python2 support ends in 2020, so from now i expect general attention to be on python3.

**Comment by mcer12** [comment]
I made a transition to HueEmulator3, thanks. Maybe add a note in wiki that the support is being dropped for the old one.
