### ISSUE TITLE
Whats wrong on start?

### ISSUE THREAD

**Issue by thecompix** [mariusmotea/diyHue#186]
Hey Guys,
I started the easy_install.sh and the progress was successful.
Then I edited and saved the config.json.
Now the question is. Is the message with: server stopped normally?
If not, what is the error?

```

root@raspberrypi:/opt/hue-emulator# service hue-emulator status
● hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; enabled)
   Active: active (running) since Thu 2018-03-01 10:37:55 CET; 10min ago
 Main PID: 14401 (HueEmulator3.py)
   CGroup: /system.slice/hue-emulator.service
           └─14401 /usr/bin/python3 /opt/hue-emulator/HueEmulator3.py


Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: E-mail account configured
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: Send test email
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: successfully sent the mail
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: Mail succesfully sent
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: Create alarm virtual light
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: starting ssdp...
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: start ssdp broadcast
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: sync with lights
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: server stopped [Errno 98] Address already in use
Mar 01 11:26:38 raspberrypi HueEmulator3.py[1681]: config saved


```

**Comment by mariusmotea** [comment]
`server stopped [Errno 98] Address already in use`

something is using the port 80, very likely a background process of hue-emulator.

try:

`sudo netstat -lntp | grep 80`

here you will see the pid of the process that use this port

`sudo kill {pid id}`

If is too complicated, then simply reboot and problem will be fixed.

Marius.

**Comment by thecompix** [comment]
Ahhyeaah. Apache2 was the prob.
is it possible to set the hue-emulator on another port?
But the httpd server starts.
Now i open the hue app on my iphone. does the hue emulator make a simulated hue bridge?
Because i dont see anyone in my app.

Sorry. iam a newby.

**Comment by mariusmotea** [comment]
You can set hue-emulator on different port, but no hue application will detect it because they expect port 80 to be used (remember that Hue Bridge is a dedicated device that has port 80 just for this service). Maybe you can set some virtual hosts in you apache and forward all the request that come with no host header to hue-emulator on different port, or forward only request with /api/ . This way you can use apache on port 80.
To change the hue-emulator port you must edit the script and replace in the bottom where the service start 80 with different one.

**Comment by thecompix** [comment]
okay, when i set the port basicly on 80, should i see the pi als bridge in my hue app?

**Comment by mariusmotea** [comment]
Yes, you will find a new new bridge with the name "Philips hue".

**Comment by thecompix** [comment]
thaaaanks
