### ISSUE TITLE
Tradfri Remote not working

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#187]
My Tradfri remote is not working :(

Im using the raspbee module

I have done the following steps:
- I connected the Tradfri remote with deconz and it shows up there
- I unlocked the gateway and opened "http:/raspberry/deconz" and the remote appeared
- I configured it as Hue Dimmer Scene Switch
- Hue Dimmer appeared in the official Hue App
- I configured the Hue Dimmer in the official Hue App

When I press any button on the Tradfri remote nothing happens...

Im completely clueless. Can Someone help?

**Comment by oleg2204** [comment]
Update:
I removed and readded the remote in deconz and in the hue bridge emulator. Now the tradfri remote events are shown correctly in the hue app (On button pressed, off button pressed and so on).
I also reconfigured the room and the lights. Still no reaction by the lights to any key pressed on the remote. I don't have much time now and will dig into the network stuff some other day. Hope meanwhile someone can reproduce this ....

**Comment by mariusmotea** [comment]
I can help if you start manually hue emulator script and provide the output, maybe there is an error there. I have 10 Tradfri remotes, but i configure them in other modes.

**Comment by oleg2204** [comment]
Here is the output right after i press the "on" button (big middle):

{"e":"changed","id":"2","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2018-03-02T20:54:22"},"t":"event"}
rule 13 is triggered
rule 1 is triggered
rule 17 is triggered
unable to process the request'buttonevent'

**Comment by mariusmotea** [comment]
Are you using latest version?

**Comment by oleg2204** [comment]
No i dont think so. Im gonna now reinstall the whole thing completly and will report back

**Comment by oleg2204** [comment]
Okay have reinstalled completly new and fresh. Now hue app is telling me that my bridge needs an update and that it cant be updated :/

**Comment by oleg2204** [comment]
Okay got the Updatething working. Needed just a restart :)

**Comment by mariusmotea** [comment]
Try now again to update (first time will fail). On feb 5 was released a new update and i add this version to updater. Is wired that now is asking to update the bridge.

**Comment by mariusmotea** [comment]
I guess my commit fixed this, soon everybody will require to perform this update operation.

**Comment by oleg2204** [comment]
Okay issue is fixed. All Light my Sk6812 Lights are working. All Ikea Lights (raspbee) are working and Tradfri remote is working too.
