### ISSUE TITLE
Could notstart emulator with newest version

### ISSUE THREAD

**Issue by cad435** [mariusmotea/diyHue#188]
Hey!

I just installed the neweset version.
I tried running "./HueEmulator.py" but it gives me just a "Could not load Config"
when I try running "./HueEmulator3.py" it also gives me the same error

I also try to load the stock config you provided with this version (eg. the config wich has no lights in it)

any suggestions?

cad435

**Comment by mariusmotea** [comment]
Hi,

the config.json file location is hardcoded now, it must be located in /opt/hue-emulator/

Marius.

**Comment by cad435** [comment]
Ah, that fixed it...
