### ISSUE TITLE
LPD8066 LED Stripe

### ISSUE THREAD

**Issue by foonky** [mariusmotea/diyHue#190]
Hello,

first of all thank you for your awesome work. My Question is, if it is possible to control LPD8066 Stripes.
I have 5 meters in spare. I found a library to control the LPD8066 with the esp8266
https://github.com/adafruit/LPD8806
and 
https://github.com/dmcinnes/Lua-LPD8806

But i have no clue how to implement it.

Thank you in advance

**Comment by foonky** [comment]
Nevermind. i see that LUA Problem

**Comment by mariusmotea** [comment]
After i read some info about LPD8806, they seams to be complicated to use, with poor documentation.
