### ISSUE TITLE
Yeelight Support?

### ISSUE THREAD

**Issue by dreamonn** [mariusmotea/diyHue#191]
Is it possible to use diyHue to allow an Ambilight TV to control Yeelight RGB bulbs & /or LED strips? 

If so, could someone outline how to do this?

Thanks

**Comment by mariusmotea** [comment]
Support for Yeelight is pending, @mcer12 ordered one bulb for me, but it is still on the way. Check https://github.com/mariusmotea/diyHue/issues/86

**Comment by mcer12** [comment]
Yes it sould arrive in 1 or 2 weeks.

**Comment by mcer12** [comment]
Update: I had to order from different seller, should arrive by the end of the month hopefully.

**Comment by dreamonn** [comment]
Has the bulb arrived yet?

**Comment by mariusmotea** [comment]
Not yet, but is close. Has entered in my country.

**Comment by J3n50m4t** [comment]
@mcer12 I've had one laying around #236 feel free to test 
make sure Yeelight is in LAN mode (last entry in yeelight menu)

**Comment by mcer12** [comment]
@J3n50m4t Great I'll test it as soon as I get home. Marius' bulb is still in transit...
:postal_horn:

**Comment by mariusmotea** [comment]
Hi,

I merge the pull request without to test as the code look to be worked fine. I hope the bulb will arrive this week. I believe i only need to add color support now.

**Comment by J3n50m4t** [comment]
Found one strange behaviour:
Can't find the yeelight with Alexa. Is there something more to do? Didn't saw anything related to alexa. or is it maybe the "ü" in it's name.

**Comment by mariusmotea** [comment]
Start HueEmulator3.py manually with sudo and check if ssdp search requests are coming from Alexa.

**Comment by J3n50m4t** [comment]
I told my alexa to forgett all devices. Rescanned, all there except for yeelight. 

logs are like this. Not sure where to start with Alexa right now tbh 

`Sending M-Search response to 192.168.1.131
192.168.1.131 - - [23/May/2018 14:06:42] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.131 - - [23/May/2018 14:06:42] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.131 - - [23/May/2018 14:06:44] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.131 - - [23/May/2018 14:06:44] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
Sending M-Search response to 192.168.1.151
192.168.1.151 - - [23/May/2018 14:06:44] "GET /description.xml HTTP/1.1" 200 -
192.168.1.151 - - [23/May/2018 14:06:45] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights HTTP/1.1" 200 -
192.168.1.131 - - [23/May/2018 14:06:45] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.131 - - [23/May/2018 14:06:46] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.131 - - [23/May/2018 14:06:46] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.131 - - [23/May/2018 14:06:46] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
`

**Comment by mariusmotea** [comment]
I see the requests there. Login on webgui and press the link button:

> Go to http://{IP_ADRESS}/hue/linkbutton when you want to allow new device on hue emulator. Default username: Hue password: Hue

I propose to start a new thread for this issue if is not solved.

**Comment by J3n50m4t** [comment]
@mariusmotea Did you enable LAN mode? 
You can activate it in the Yeelight App -> Bulp -> The Icon in the right corner looking like eject
Without this activated the Bulp refuses connections

Yeelight is also working great here.

**Comment by mariusmotea** [comment]
Thanks, is working as expected. I will work on a few optimizations, but the hard work was already done by you.

**Comment by mariusmotea** [comment]
With the last commit i add the following improvements and fixes:
- Yeelight bulbs are automatically detected in light search from application (was possible because of unique tcp port 55443)
- support for transitiontime parameter
- fix brightness to fit value 1 - 100 when min/max
- light is added as LCT015 for better colors
- other minor improvements

**Comment by mariusmotea** [comment]
I made a new [commit](https://github.com/mariusmotea/diyHue/commit/7b41c403bf94401b6d423163b8486f8c32f43ed8) that improve the syncronization with yeelight, now the values are pulled based on current color mode and converted correctly to hue api values.

Marius.

**Comment by mariusmotea** [comment]
I believe full integration of YeeLight was done. I replace nmap auto discovery with ssdp as this is faster and provide more details about the light including the unique id that can be used to identify the light and  the ip's in new search.
Other changes:

- now discovered lights are emulated in correct Philips bulbs based on detected properties (color, ct or just dimmer)
- light will flash on alert but this is working just with light turned on
- ip's of yeelight will be updated on every light search based on unique id of the light and current ip on network.
