### ISSUE TITLE
Trouble Flashing RGBW Firmware to Bulb

### ISSUE THREAD

**Issue by jlubins** [mariusmotea/diyHue#192]
Hey,

Trying to use generic RGBW Bulbs with ESP8266 chips in them that I got from Amazon. I think I have everything soldered and wired correctly because I was able to use esptool.py to delete the current firmware on the bulb. However, when I try to upload the code in Arduino IDE, I get this error message:

```
Arduino: 1.8.4 (Mac OS X), Board: "Generic ESP8266 Module, 80 MHz, ck, 26 MHz, 40MHz, QIO, 1M (128K SPIFFS), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Archiving built core (caching) in: /var/folders/yf/v0mm1gt17d75p1rdyd5vjlkw0000gn/T/arduino_cache_140262/core/core_esp8266_esp8266_generic_CpuFrequency_80,ResetMethod_ck,CrystalFreq_26,FlashFreq_40,FlashMode_qio,FlashSize_1M128,led_2,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_115200_7f04165fe51592c926f91225eac66eae.a
sketch/Generic_RGBW_Light.ino.cpp.o: In function `pwm_start':
sketch/pwm.c:356: multiple definition of `pwm_start'
sketch/pwm.c.o:sketch/pwm.c:356: first defined here
sketch/Generic_RGBW_Light.ino.cpp.o: In function `_Function_base':
sketch/pwm.c:403: multiple definition of `pwm_set_duty'
sketch/pwm.c.o:sketch/pwm.c:403: first defined here
sketch/Generic_RGBW_Light.ino.cpp.o: In function `pwm_init':
sketch/pwm.c:415: multiple definition of `pwm_get_duty'
sketch/pwm.c.o:sketch/pwm.c:415: first defined here
sketch/Generic_RGBW_Light.ino.cpp.o: In function `pwm_init':
sketch/pwm.c:426: multiple definition of `pwm_set_period'
sketch/pwm.c.o:sketch/pwm.c:426: first defined here
sketch/Generic_RGBW_Light.ino.cpp.o: In function `String::operator==(char const*) const':
sketch/pwm.c:161: multiple definition of `pwm_init'
sketch/pwm.c.o:sketch/pwm.c:161: first defined here
sketch/Generic_RGBW_Light.ino.cpp.o: In function `operator()':
sketch/pwm.c:436: multiple definition of `pwm_get_period'
sketch/pwm.c.o:sketch/pwm.c:436: first defined here
sketch/Generic_RGBW_Light.ino.cpp.o: In function `operator()':
sketch/pwm.c:442: multiple definition of `get_pwm_version'
sketch/pwm.c.o:sketch/pwm.c:442: first defined here
sketch/Generic_RGBW_Light.ino.cpp.o: In function `operator()':
sketch/pwm.c:446: multiple definition of `set_pwm_debug_en'
sketch/pwm.c.o:sketch/pwm.c:446: first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Generic ESP8266 Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

I have coding experience, but not in C so this firmware (and the compile error) looks almost unintelligible to me, but I'm very excited to get it working. Any help would be appreciated and thanks for these awesome tools!

**Comment by mariusmotea** [comment]
Hi,

Looks like the issues is generated when pwm library is compiled. I'm not a maintainer  of that library, but i guess you can receive help [here](https://github.com/StefanBruens/ESP8266_new_pwm)

**Comment by ticed35** [comment]
Hi @jlubins , 
I had the same issue, if i remember well i renamed the pwm.c file to pwm.h and changed his declaration in .ino file. 
Cédric

**Comment by jlubins** [comment]
I ended up fixing it by adding the header file from the ESP8266 SDK and just changing the data types in it to reflect those of pwm.c. Everything compiled and flashed okay, and the WiFiManager on the bulb works (I could set it up on my network and access the web GUI), but my lights will not light up, so something is still off.

So I'll try what you did next. Thank you, Cédric.

**Comment by mariusmotea** [comment]
What model is your bulb? Are you sure the pins are the correct ones?

**Comment by jlubins** [comment]
It exactly resembles the one in this article:
http://tinkerman.cat/ailight-hackable-rgbw-light-bulb/

Everything is pretty clearly marked on the bulb and I followed the wiring exactly. I probably screwed something up when modifying the SDK header. Cédric's solution to change the .c file to a .h compiles. Going to check soon to see if that makes the bulb work.

**Comment by mariusmotea** [comment]
There is an issue with that bulb. Is not using the pwm from esp chip but a second chip named MY9291QD. I tried to made a [sketch](https://github.com/mariusmotea/diyHue/tree/master/Lights/Arduino/MY92XX_RGBW_Light) also for this chip without the bulb and so far i get feedback that is not working. If you have skills maybe you can see why is not working.

Marius.
