### ISSUE TITLE
Is there a chance this ccan be made to work with matrix creator boars?

### ISSUE THREAD

**Issue by vizonyc** [mariusmotea/diyHue#196]
As it has both zigbee and zwave radios I am wondering what would be need to get it work. https://www.matrix.one/products/creator

**Comment by mariusmotea** [comment]
browsing the website and git repos i did not find some api documentation. I need api to fetch and control the lights connected to this board and also a way to receive sensors events.

Marius.

**Comment by vizonyc** [comment]
Ok will track down for you

**Comment by vizonyc** [comment]
ok this is what was posted back tho I am not sure if this is helpful
I also found this https://github.com/matrix-io/matrix-malos-zigbee
yoelrc88
1h

Would be glad to help him.

Indeed, he can use MALOS layer to do it. MALOS is an abstraction layer that exposes, in this case, the LEDs functions using Protocol Buffers through a ZMQ connection:

    MALOS repo : https://github.com/matrix-io/matrix-creator-malos/
    Pyhton examples: https://github.com/matrix-io/matrix-creator-malos/blob/master/src/python_test/test_everloop.py

This communication here would be :
Your Python App -> Protobuf messages over ZMQ -> MALOS -> HAL (C++ layer) -> MATRIX Creator

Another option would be to access directly from python without using MALOS. We know about this
Python driver for Matrix Creator / Voice from cmetz. Note that this repo is not officially supported by us. But we see it as a good option too.

Let us know how it goes and if you have any more questions

**Comment by mariusmotea** [comment]
Hi,

MALOS looks good, it provide a way to receive sensors events, however this cannot be implemented blindly and i'm not gonna invest any money for this, while my Raspbee module is working fine for my house. I can provide support for anybody that want to try this.

Marius.

**Comment by vizonyc** [comment]
I would be willing to send you mine if you are willing get this working.

**Comment by mariusmotea** [comment]
ssh sessions are good for a quick debugging, not for development. Currently i'm very busy, i work for this project ~30 minutes per day and if you send me your board i will feel pressed to implement it faster and for sure will require to postpone personal activities, that i don't want. I already accept to work for yeelight implementation when the bulb will arrive...

**Comment by cheesemarathon** [comment]
@mariusmotea close this for now?
