### ISSUE TITLE
CRITICAL! Config file was not loaded

### ISSUE THREAD

**Issue by DylanHedger** [mariusmotea/diyHue#197]
I followed all the steps of Issue #20 after looking up how to setup diyHue and when I get to the step
`sudo ./HueEmulator.py`
It will just reply with 
`CRITICAL! Config file was not loaded`

**Comment by Wqrld** [comment]
try running without sudo, that might keep it from finding the config file, can you also run a ls to see if a config file is there

**Comment by mariusmotea** [comment]
There are two options:
Your config.json is not located in /opt/hue-emulator/ or your config.json file is corrupted.
Deploy with automatic installation script and it must work.

**Comment by DylanHedger** [comment]
okay i did the installation script and now it prints

`Config loaded
start ssdp broadcast
server stopped [Errno 98] Address already in use
sync with lights
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./HueEmulator.py", line 109, in ssdpSearch
    sock.bind(server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

config saved`

but when i use the app it discovers it, then i try to find my light but it cannot find it and yes its a philips hue and on it, it states that it works with the bridge.

**Comment by Wqrld** [comment]
with a brower go to your raspberrys ip adress and look if you have anything important running there, if not
netstat -lvnp | grep 80         and look for (number)/(text) (should be on the right side

if you are sure it is nothing important is running on port 80 type `kill -9 (numberfromnetstat)`

and then try to relaunch diyhue

**Comment by DylanHedger** [comment]
no nothing only local 0.0.0.0:80 tcp its a fresh install of rasbian

**Comment by mariusmotea** [comment]
Netstat -lnup i believe ssdp port is the one already in use

**Comment by DylanHedger** [comment]
???

**Comment by mariusmotea** [comment]
Check if port 1900/udp is already used by other process

**Comment by DylanHedger** [comment]
yeah it is

**Comment by DylanHedger** [comment]
okay i stopped that port and now it seems to run without errors but i still cant connect it to my lights. Is it supposed to let me through the app because the app recognises it as a bridge but its kinda not working like one, it wont let me connect the lights

**Comment by mariusmotea** [comment]
what lights do you have? If you have original zigbee bulbs it will not work directly. You need Raspbee module.

**Comment by DylanHedger** [comment]
I have the dimmable ones or something the ones that look like a bulb sorry for replying late

**Comment by mariusmotea** [comment]
Are you able to connect to light internal gui and control the light? If yes it must be detected.

Marius.

**Comment by DylanHedger** [comment]
light internal gui???
are you talking about the app i dont have a bridge so i cant connect to it and the emulated bridge cant discover it.

**Comment by mariusmotea** [comment]
Please read wiki to know better how this is working.

> I have the dimmable ones or something the ones that look like a bulb sorry for replying late

dimmable lights with firmware provided by me?
zigbee lights?

**Comment by mariusmotea** [comment]
You cannot control ZigBee devices without zigbee communication module. You will need the Raspbee module for raspberry pi or the original Hue Bridge.
