### ISSUE TITLE
led matrix support / how to add support for other lights

### ISSUE THREAD

**Issue by Wqrld** [mariusmotea/diyHue#198]
what would be needed to add a new device?
i have a way to interface led matrixes in python but is it possible to control them using diyhue?
What files would need to be changed?

edit: this might require some external files so is it also possible to add those as "non-required"?

**Comment by mariusmotea** [comment]
We need a way to interface with led matrix api. I understand there is no http protocol support, so a new protocol need to be implemented. Then converting formula from hue api to led matrix api.

Marius.

**Comment by Wqrld** [comment]
interfacing with the matrix api can be done in python with https://github.com/hzeller/rpi-rgb-led-matrix
ill take a look at how the converting would work. Respond if you know anything that would help

**Comment by Wqrld** [comment]
is there any documentation on what diyhue is sending to eg [this](https://github.com/mariusmotea/diyHue/blob/master/Lights/Arduino/Generic_RGB_Light/Generic_RGB_Light.ino)

**Comment by mariusmotea** [comment]
By starting the HueEmulator3.pyt script manually you will be able to see the url with parameters that is sent to the lights. Also in wiki you have the arguments (basically are the ones from hue api). I will try now to migrate the lights to pute json post like with hue api

**Comment by mariusmotea** [comment]
How do you want to control the led matrix, all leds to display one color, or you want to simulate multiple lights by splitting the matrix?

**Comment by Wqrld** [comment]
My idea was to display one color as a matrix is basicly 1 part

**Comment by mariusmotea** [comment]
provide me one example how you do this manually and i will help with conversion formula, etc

**Comment by cheesemarathon** [comment]
I have asked @mariusmotea to try create a base python script for others to adapt to add support for lights attached to a pi, either remote or local to the diyHue bridge, in issue #340

**Comment by Wqrld** [comment]
Please don't delete this yet, #340 als hasn't had much activity

**Comment by Wqrld** [comment]
Nope, still not.
