### ISSUE TITLE
Discovering other types of bulbs

### ISSUE THREAD

**Issue by WoodsterDK** [mariusmotea/diyHue#2]
Hi there, does it also support discover of different types of bulbs other than the ESP8266 ones e.g. real HUE bulbs.?

Will it be possible to make a wrapper for interfacing with other kinds - e.g. milight bulbs, IKEA trådfri...?

**Comment by mariusmotea** [comment]
Hi,
The bulbs you are talking about use ZigBee protocol, so to have support for these some code lines must be added on bridge, this will be easy... but adding ZigBee feature to RaspberryPi/OrangePi require extra hardware that i currently not have. Maybe this will be implemented in the future, depending on number of requests.
Marius.

**Comment by WoodsterDK** [comment]
I was thinking of the concept with some middleware that e.g. talked to the IKEA gateway, and then interfaced somehow with your bridge emulator.... then an IKEA bulb would be seen as a Philips hue bulb.

So only software, and some middleware up against the corresponding hardware/gateway ....

**Comment by WoodsterDK** [comment]
Milight bulbs use a different protocol and media, but could be emulated with some middleware.

**Comment by mariusmotea** [comment]
If IKEA gateway accept http requests and we can find the api somewhere i guess in 1-2 days i will be able to add support for them. Regarding Milight bulbs, these can be easy converted to ESP8266, a tutorial is right here: http://itay.mobi/blog/?p=24.

**Comment by WoodsterDK** [comment]
Some info.....
https://github.com/hardillb/TRADFRI2MQTT
https://github.com/hvanderlaan/ikea-smartlight
https://github.com/stenehall/homebridge-ikea

Furthermore it would be nice to keep the milight bulbs stock - and there is this great project for a replacement hub:
https://github.com/sidoh/esp8266_milight_hub

**Comment by mariusmotea** [comment]
I like the idea to support IKEA products, i believe i will buy the gateway with some bulbs and provide support for them.

**Comment by WoodsterDK** [comment]
May I ask why you have choosen php for the project. It is a bit out of my comfort zone, so I dont know if there are any advantages....

**Comment by mariusmotea** [comment]
i choose php because from the languages i know (php, python, perl) was most suitable for fast development, hue api is http based, is very easy to manage json arrays with json_decode and json_encode functions and all action are based on web requests so no need to have a running loop process. Only problem was to store json data in mysql in order to perform fast queries, but in the end i solve this.

**Comment by WoodsterDK** [comment]
OK - I'm a C, C# guy myself, so this is quite different.... any chance of converting it :)

**Comment by mariusmotea** [comment]
Yes, yesterday i analyse the advantages to convert it to python and i believe i will give it a try.

**Comment by WoodsterDK** [comment]
Interesting - C# is still my thing, but it might be possible for me to convert the python version.
Impressive project you have running !!!

**Comment by WoodsterDK** [comment]
For milight, using this as a hub will give unlimited bulbs, and a easy interface.
https://github.com/sidoh/esp8266_milight_hub.

**Comment by mariusmotea** [comment]
This is half done, support for milight bulbs was added, i tested just with cct bulbs, but looking to logs i believe will work fine also with color bulbs. rgbw milight bulbs are on the way so for the moment i will focus on IKEA bulbs.

**Comment by mariusmotea** [comment]
Done also with support for IKEA Tradfri.

Marius.
