### ISSUE TITLE
configuration Emulator with ESP8266 

### ISSUE THREAD

**Issue by elmo25674** [mariusmotea/diyHue#203]
Hello,
i changed the Rpi and installed everything new. Now i can not find the Lights in the app.
I installed nmap (NetworkMapper) on my Phone, but i cannot find the Lights in the app.
Connection to the Emu_Bridge is ok.
i´m Sure i do something wronge with nmap.
i have the same problem here :
https://github.com/mariusmotea/diyHue/issues/29
at this time i fixed it with install of nmap.But now???
Please help.

Christian

**Comment by mariusmotea** [comment]
nmap package must be installed on raspberry, not on your phone. If you used the automatic installation script it must be installed. If not `sudo apt install nmap.`

Marius.

**Comment by elmo25674** [comment]
hey Marius,
i installed it with automatic installation. so it is installed on raspberry.
Shoudi have to do something on raspberry before i start searching the light in the app

christian

**Comment by mariusmotea** [comment]
No, just ensure you connected the lights to your wifi network and perform light search from hue application.

**Comment by elmo25674** [comment]
Good morning, 
The light are connected to my network, i can switch it on and off by the web interface.
But in the hue app i can't find the light. 
On the esp is allready the sketch from September 2017,installed.
Is it necesserycs to update the esp to the actual sketch?

Christian

**Comment by elmo25674** [comment]
OK thank you. I will try it. But I will do it on Friday or Saturday, because I'm not at home.
I informe you as soon as possible what's happen with the new sketch. 
Thanks
Christian

**Comment by recepg89** [comment]
After updating the hue app on May 31 the lights now disappeared and i cannot discover them anymore.

The hue app connects to the RaspberryPi Huebridge and the ESP8266 's are connected to the same network. I can use my browser to change the lights.

**Comment by mariusmotea** [comment]
start HueEmulator3.py manually and provide the output to see what is the difference between the app and browser requests.

**Comment by recepg89** [comment]
i think there is something wrong with the configuration. Sorry i am not very versed in programming. Is this correct:

first i killed the HueEmulator3.py
Then i started HueEmulator3.py located in
diyHue/BridgeEmulator/
with this command ./HueEmulator3.py

Then it look like a loop with this
 91f90/sensors/new HTTP/1.1" 200 -
192.168.178.117 - - [31/May/2018 18:22:21] "GET /api/a7161538be80d40b3de98dece6e                                      91f90/lights HTTP/1.1" 200 -
192.168.178.117 - - [31/May/2018 18:22:21] "GET /api/a7161538be80d40b3de98dece6e                                      91f90/groups HTTP/1.1" 200 -


.117 is my phone using the hue app.

am i doing this wrong

**Comment by recepg89** [comment]
is there a way to reset the config file without breaking the whole system?

**Comment by recepg89** [comment]
i used your automatic installtion curl, now it works fine
