### ISSUE TITLE
Not an issue, Can we have more than 1 relay/lamp on one Wemos D1 Mini

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [mariusmotea/diyHue#205]
Hi here , i want to now if i can have more than 1  relay/lamp on one Wemos D1 Mini

Thanks for replying

**Comment by mariusmotea** [comment]
Yes, but only for on/off and dimmable lights. The color ones use at last 3 channels per light and i don t implement this future. As workaround for color lights you can use neopixel leds and use just the output to control more powerful led drivers

**Comment by TomAvecLeVdsl** [comment]
okey and about google home intregration and hue app ? What about this

**Comment by mariusmotea** [comment]
Google switched to remote api, so is not working anymore.

**Comment by TomAvecLeVdsl** [comment]
Okey thanks for replying
