### ISSUE TITLE
Plans to switch to esp32

### ISSUE THREAD

**Issue by betonishard** [mariusmotea/diyHue#209]
Hello again,

Do you have plans to make it also compatible with esp32?

Thank you in advance.

Keep up the great work!

**Comment by mariusmotea** [comment]
Hi, 

Is not up to me, my code is not directly related to hardware. If the guys will add support in arduino for esp32 and the libraries will work, then my sketch will work also. I never tested this so far.

Marius.

**Comment by pecirep** [comment]
I will buy an ESP32 and test this. It should work in theory, the ESP32 actually has better arduino IDE support than the ESP8266. I will report back when I have results.

**Comment by mariusmotea** [comment]
I also have one on the way. I saw there is one issue with the [pwm library](https://github.com/StefanBruens/ESP8266_new_pwm) if esp library v2.4 is used. There are some compilation errors with duplicate definition of some functions. If they perform good improvements with pwm on v2.4 i will switch to build in pwm library.

**Comment by betonishard** [comment]
Re-open? It would be great to have the ws2812 ledstrip working..

**Comment by mcer12** [comment]
@betonishard just update the neopixelbus library, esp32 is supported now.

**Comment by betonishard** [comment]
@mcer12 @cheesemarathon 
Haven't been able to test yet, I have the diyHue code integrated in another piece of code so that  I only needed one esp (behind the tv along with the rgb ledstrip) with lots of sensors that provide lux/temp/hum/pir/infrared receiving all in one via mqtt. In about two weeks I will go with the ESP32 testing ( so I can  add bluetooth as well) to detect BLE.

So thank you for the update!!

**Comment by mcer12** [comment]
@betonishard this is not really a diyHue issue, you can use existing sketches with esp32 with minimal changes. If you have any problems regarding esp32, or some library or features not working, please refer to their respective github pages for bugfix :)

**Comment by cheesemarathon** [comment]
@mcer12 I agree. @betonishard I suggest that if you want to chat about the changes required to support ESP32 then do so on our Slack chat. I'll close this again, and If and when you create new versions to support ESP32 you can create a PR to merge them. Thanks for your work @betonishard 

[![JoinSlack](https://img.shields.io/badge/Join%20us-on%20Slack-green.svg)](https://slackinvite.squishedmooo.com/)

**Comment by pecirep** [comment]
I'm having trouble setting up the esp32. What are these minimal changes you are speaking of @mcer12 ?

**Comment by cheesemarathon** [comment]
@pecirep I don't believe @mcer12 had any specific suggestions. He was just aware that there are versions of most required libraries and prehaps a few esp32 specific requirements. In theory, if you can do it one an 8266 you can do it on a 32. Can I suggest that you [join us on slack](https://slackinvite.squishedmooo.com/) and we will help debug this further there. If your sketch won't compile, post the output error when you try to compile on slack.
