### ISSUE TITLE
New HUE app and functions 2018

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#212]
https://www.google.no/amp/s/www.theverge.com/platform/amp/ces/2018/1/10/16872378/philips-hue-sync-app-outdoor-lighting-ces-2018

Anybody beta testing this now? Will diy try to implement support for any of the new functions?

**Comment by mariusmotea** [comment]
If this new app will use the hue entertainment, then is a big problem with dtls support in python. I believe the udp service must be buit in different language and implement a socket file for communication between the processes.
