### ISSUE TITLE
Extremly slow on Raspberry with ESP8266 and WS2812b

### ISSUE THREAD

**Issue by nhmann** [mariusmotea/diyHue#214]
Hello,
I am using diyHue on my Raspberry 3. Everything is installed and running.
My only problem is the extrem lag between the change in the hue app and the real change on the strips. Often it does nothing and when it does something, it happend 10 seconds later.

Has anybody an idea why it is so buggy?

**Comment by mariusmotea** [comment]
Very likely because of poor wifi connectivity in your home. Try to ping the lights from your raspberry py. What is the average time reply? Is the raspberry wired or wifi connected?

**Comment by nhmann** [comment]
Further Informations: i get 30mbps download with my Raspberry Pi. controlling real Hue Lights is super fast and no problem at all

**Comment by mariusmotea** [comment]
Try to start HueEmulator3.py script manually and check the output. You will see when light request is received/forwarded and when the light state is changing. My raspberry pi is connected on wifi to my router (5Ghz frequency) and the lights are in different rooms . All are responding instant.  How many lights are you emulating per ESP8266  device?

**Comment by mariusmotea** [comment]
3 lights is not a problem, mines have 3 and 4

**Comment by nhmann** [comment]
Config loaded
LightRequest: http://192.168.0.213/set?light=2&on=False
update status for light 2
request error
update status for light 9
LightRequest: http://192.168.0.213/set?light=1&on=True&bri=200
update status for light 1
LightRequest: http://192.168.0.213/set?light=3&on=False
update status for light 3
request error
update status for light 6
request error
update status for light 5
request error
update status for light 4
start ssdp broadcast
sync with lights
server stopped [Errno 98] Address already in use
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "HueEmulator3.py", line 111, in ssdpSearch
    sock.bind(server_address)
OSError: [Errno 98] Address already in use

**Comment by nhmann** [comment]
I think I have to kill the autostarted HueEmulator3.py. How can I do it?

**Comment by mariusmotea** [comment]
`sudo systemctl stop hue-emulator`, but i don't believe is necessary, as you can see `request error` means the pi was unable to reach esp8266 webserver.

**Comment by nhmann** [comment]
okay, i connected my pi to the router per lan. and look, its working fine. I didn't thought that the raspberry pi 3's wifi-module is so weak. the distance wasn't more than 3 meters, without any objects between them.

**Comment by mariusmotea** [comment]
My Rpi3+ has also 5Ghz ac and is very stable with my router (Mikrotik).
