### ISSUE TITLE
Wifi issue with new cheap NodeMCU

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#215]
Hi this is more related to NodeMCU itself than diyHue but I wonder if anyone else experienced this problem. I bought some supercheap NodeMCU with bare ESP chip soldered to the board. Board looks like this
http://robotstore.cz/wp-content/uploads/2017/01/nodemcu-v3-lua-cp2102-wifi-vyvojova-deska-esp8266-8mb-arduino-1.jpg
but it has very poor signal. Has anyone found a way to make it better? It works most of the time but sometimes lights change state to "unavailable". Also the light changes take longer to take effect. Maybe it's just a design flaw so take this as a warning not to buy these. Other NodeMCUs and D1 minis (with ESP-12 module) work great.

**Comment by mcer12** [comment]
Yes I thought of this but I have one of the lights literally few centimeters from wifi AP and second one across the room with little to no difference, so I doubt it's antenna related. I dont own an oscilloscope but I think this might be due to insuficient ripple filtering. I'm trying it with powerbank and so far no lights went "unavailable".

**Comment by mariusmotea** [comment]
Place a capacitor near the esp on power circuit. Very likely the current ones are not that good.

**Comment by betonishard** [comment]
I have soldered two capacitors, one capacitor (beefy) and a small cap soldered and this makes a big difference!! Definitely worth a try, I solder caps things standard to all my esp's...

**Comment by mcer12** [comment]
Thanks for replies guys. The arduino is powered by mini360 buck converter to drop 12v to 5v which is directly connected to VIN. I have a 22uF electrolytic cap on the output of the buck converter.
@betonishard Do you have this particular board I posted or different? Can you post your values of capacitors you use?

**Comment by betonishard** [comment]
@mcer12,
I got a 1000uF 25v electrolytic cap in parallel with a 104 ceramic cap

Here is the link of the big one.
https://nl.aliexpress.com/item/10PCS-Aluminum-electrolytic-capacitor-25V-1000UF-1000-uf-25v-size-10-17mm-25-V-1000-UF/32725883192.html?spm=a2g0s.9042311.0.0.SjTDjJ

ceramic cap, i soldered it just like this, as close as possible to the 3v3 and ground.
http://tinypic.com/view.php?pic=2dqlqah&s=8#.WvCemy-B3OQ


Good luck...!

**Comment by mcer12** [comment]
@betonishard Thanks but this is not really relevant since its interirely different board.. I will try the ceramic cap though and tinker with it little little more.

**Comment by mariusmotea** [comment]
BTW one instable esp powered by a bad PS in my home cause connectivity issues with other esp's from proximity. Ceramic caps are a better solution, i saw all cpu's have ceramic caps near them for filtering.

**Comment by mcer12** [comment]
@mariusmotea Hmm good thought but wouldnt that affect the other ESPs too? I have one d1 mini right between these two nodeMCUs and it's working flawlessly.

**Comment by mariusmotea** [comment]
For sure they can create unwanted noise in 2.4 spectrum. I had hard time to fix my ceiling light in the bedroom. In the end i find out that other esp in the room was the problem. It still cause me issues once 2-3 months, but now i know what to reset when ceiling light stop responding

**Comment by mcer12** [comment]
I'm closing this, these boards are just shitty. I urge everyone not to use those.
