### ISSUE TITLE
First LED of WS2812B turns blue

### ISSUE THREAD

**Issue by JakobGrine** [mariusmotea/diyHue#216]
Hi,
when I flash the WS2812B-sketch to my NodeMCU 1.0, the first NeoPixel LED always turns blue after some time. Even if I set a new color in the Hue-App, it returns to blue.

I would appreciate some help.
Thanks.

**Comment by mariusmotea** [comment]
After how much time it return to blue? I guess you can switch from hardware support to software support any use any other gpio pin. The hardware pin is the rx and serial adapter may cause issues

**Comment by shbatm** [comment]
Recommend you take a look at this guide from Adafruit.com -- WS2812B First Pixels can be damaged due to spikes in voltage or poor signal.  They repeat the signal down the chain, so it usually only affects the first pixel

https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices

**Comment by JakobGrine** [comment]
Thank you for your answers. That solved the issue.
