### ISSUE TITLE
Error in ssdp Broadcast

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#217]
Im getting some strange error. I tried to search for a new Light and couldn't find it. So I started the Service up manually and took a look at the output...
Maybe someone can help find the issue?

Config loaded
Starting deconz websocket
LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/3/state
update status for light 2
LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/2/state
update status for light 1
LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/1/state
update status for light 3
start ssdp broadcast
sync with lights
Starting httpd...
192.168.0.38 - - [07/May/2018 11:34:18] "GET /api/config HTTP/1.1" 200 -
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "HueEmulator3.py", line 111, in ssdpSearch
    sock.bind(server_address)
OSError: [Errno 98] Address already in use

**Comment by mariusmotea** [comment]
sudo netstat -lnup 
See what service is using the port 1900

Marius.

**Comment by oleg2204** [comment]
ctive Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           20402/deCONZ        
udp        0      0 0.0.0.0:42410           0.0.0.0:*                           316/avahi-daemon: r 
udp        0      0 0.0.0.0:68              0.0.0.0:*                           513/dhcpcd          
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           316/avahi-daemon: r 
udp6       0      0 :::57338                :::*                                20402/deCONZ        
udp6       0      0 :::546                  :::*                                513/dhcpcd          
udp6       0      0 :::58953                :::*                                316/avahi-daemon: r 
udp6       0      0 :::5353                 :::*                                316/avahi-daemon: r 


deCONZ :/

**Comment by oleg2204** [comment]
Okay got it.  I forgot to add    --upnp=0

Error is gone now. Can be close

**Comment by oleg2204** [comment]
Hmm.... The Error is gone, but I can't detect any Lights. I build 2 new Lights with NodeMCU and SK6812 and they don't get detected

**Comment by mariusmotea** [comment]
Start the script manually and provide output during the lights scanning task.

**Comment by mariusmotea** [comment]
Perfect.
