### ISSUE TITLE
Not working on ESP8266-01

### ISSUE THREAD

**Issue by harrylisby** [mariusmotea/diyHue#218]
I'm uploading the code for Generic_CCT_Light to an ESP8266-01 with a few modifications made by myself. For some unknown reason the code wont run, seems like it is crashing and sends this message or variations of it:

```
 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld
```

And after a while...

```
Fatal exception (0): 
epc1=0x400ef424, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
```

I tried flashing the same exact code to an NodeMCU 1.0 and it runs as it should.
Also, a few days ago I uploaded that code to an ESP8266-01 board and it's been working fine, but right now I've tried in other 6 boards and non of them work. But if I upload some other basic test sketch it runs fine in them.

**Comment by mariusmotea** [comment]
Ehat is the size of flash on ESP8266-01? Maybe the firmware need more space than available. Try to remove arduino ota, or the internal static html content

**Comment by mcer12** [comment]
I think there is no version with less than 512kb. Even the smallest should work, but without OTA. Maybe you have your memory size set wrong or something like that. ESP01 is sold with 512kb and 1mb versions so try both.

**Comment by harrylisby** [comment]
It is 1Mb, should work as the previous ESP-01 I flashed were also 1Mb. Used checkFlashConfig sketch and everything seems fine in my flash configuration. Will try removing OTA just to be sure.

**Comment by mcer12** [comment]
Is it working without your changes?

**Comment by harrylisby** [comment]
No luck! I'm starting to think that there's something wrong with that batch of boards, the other ESP8266-01 I've got flash and run properly!

**Comment by mcer12** [comment]
Try To set different (smaller) memory size in the IDE and remove the ota
from sketch. That might be the problem. If simple sketch works then i doubt
its a bad batch.

Dne st 9. 5. 2018 0:13 uživatel harrylisby <notifications@github.com>
napsal:

**Comment by harrylisby** [comment]
It won't run after many attempts with different configurations and code moddifications.

I've also got some 12E modules, so will try with them as it runs fine in nodeMCU which is based on that same board

**Comment by mariusmotea** [comment]
Teoretically is the same esp chip with spi storage. The hardware design is much better optimised but i still cannot understand why on 01 will not work and on e12 will work.

**Comment by mcer12** [comment]
Do the not working modules have all the same flash chip? And is the chip
different from the working esp01?

Dne st 9. 5. 2018 4:36 uživatel harrylisby <notifications@github.com>
napsal:

**Comment by harrylisby** [comment]
Tried multiple stuff on the esp01, made the code run as intended but after a while it started crashing continously. So I gave a try to esp12E and it worked perfectly with no issues to the date.
I guess there's something wrong with those esp01 boards!

**Comment by betonishard** [comment]
Strange, I have 5 esp-01's working with ws2812... They all work solid..

**Comment by harrylisby** [comment]
Makes me think the specific batch I've got is deffective. I have two esp01s that work as intended, but I bought them long before the ones I'm trying with. But I using esp12e works for me. :)

**Comment by mariusmotea** [comment]
never buy the most cheapest esp boards. Wemos are a little bit expensive, but none failed so far in my home.

**Comment by mcer12** [comment]
Well if it has ESP-12 or any other shielded ESP on it, it should be OK. If it's just a bare esp chip without shield, it can always be counterfeit or have very shitty memory module. There are some nice deals on esp8285 on aliexpress and since they have memory embedded inside the chip, there is much less of a chance for it to fail.
