### ISSUE TITLE
Osram Smart+ crashes the Hue app

### ISSUE THREAD

**Issue by FezVrasta** [mariusmotea/diyHue#220]
Hi, I have a RaspBee + DeCONZ setup, I just installed diyHue and tried to open the Hue app and discover the new bridge.
My deCONZ app controls 3 Tradfri remotes and 1 Osram Smart+

The problem is that as soon the bridge is discovered the app crashes.

I think the problem is my Osram Smart+ (Smart Power Outlet), I see the same behavior if I try to connect to the DeCONZ bridge directly since I added this new device to the list.

The problem must be that the power outlet is listed as bulb in DeCONZ and the Hue app attempts to call some API on it that crashes the app.

Would it be possible to exclude this kind of device from the ones exposed by diyHue so that the app works properly?

Since the power outlet is the only device listed as light in my DeCONZ bridge (the others are switches), I tried to remove the only `light` entry in the `config.json`, but the Hue app still crashes when I try to pair the bridge, if I reopen the config I see that the light is added again automatically to the config. Ideas?

**Comment by mariusmotea** [comment]
You can made them to work. Stop hue-emulator service, locate the Osram Smart+ "light" in config.json and replace the light type and modelid with the default ones used in my sketches

`"Plug 01": {"state": {"on": False, "alert": "none", "reachable": True}, "type": "On/Off plug-in unit", "swversion": "V1.04.12"}`

Plug 01 is the modeid

You can put there any light type, all must work, only that if you put color bulbs you will see the menu to change the light color. After this change the link of the light remain the same with deconz and you will be able to change the "on" state on Deconz for Osram device.

Marius.

**Comment by FezVrasta** [comment]
Thanks, should I change this so?

```
  "lights": {
        "1": {
            "etag": "17e7858d8a5f160e6394c506d87e3233",
            "hascolor": false,
            "manufacturername": "OSRAM",
            "modelid": "Plug 01",
            "name": "Smart Plug",
            "state": {
                "alert": "none",
                "on": false,
                "reachable": true
            },
            "swversion": "V1.04.12",
            "type": "On/Off plug-in unit",
            "uniqueid": "7c:b0:3e:aa:00:a7:3c:4e-03"
        }
    },
```

**Comment by mariusmotea** [comment]
Try now, if you still have issues i recommend to delete "hascolor" and "etag" keys. These are imported from deconz.

**Comment by mariusmotea** [comment]
You may also delete the light "1" to be sure this one cause issues (backup config.json first).

**Comment by FezVrasta** [comment]
The one I pasted is the config that has been automatically generated actually. I tried to delete the two properties but it didn't help.

If I delete the entire item and leave `"lights": {}` diyHue doesn't start at all.

**Comment by mariusmotea** [comment]
Once lights and sensors are imported, they are created in "sensors" and "lights" root keys, but are added also in "deconz" key. If they remain stored in deconz key but are deleted from "lights" or "sensors" then they will not be imported back from deconz on startup. But is very easy to trick hue applications that you are using genuine Philips bulbs, while in backend you can have any other type of devices.

**Comment by FezVrasta** [comment]
This is my config, it results as valid JSON if I run it trough a validator.

https://gist.github.com/FezVrasta/5c9f4c34668adbd43348fe752bbb23bf

**Comment by mariusmotea** [comment]
can you start HueEmulator3.py manually with sudo to see if you receive any errors?

**Comment by FezVrasta** [comment]
```
pi@raspberrypi:/opt/hue-emulator $ sudo ./HueEmulator3.py
Config loaded
server stopped '1'
config saved
```

**Comment by mariusmotea** [comment]
i believe i understand now. Is trying to send the last know state to the lights and fail. Try to delete key "1" also from here:

```
    "lights_address": {
        "1": {
            "ip": "127.0.0.1:8080",
            "light_id": "2",
            "protocol": "deconz",
            "username": "283145a4e198cc6535"
        }
```

**Comment by FezVrasta** [comment]
Yes it was it, now it starts but the Hue app still crashes :-(

**Comment by mariusmotea** [comment]
I will test you config when i arrive home. You are using android or iphone application?

**Comment by FezVrasta** [comment]
iPhone, thanks for the help!

**Comment by mariusmotea** [comment]
If you delete the switches, the app is still crashing?

**Comment by mariusmotea** [comment]
And add back the plug unit, i don't believe it is quilty.

**Comment by FezVrasta** [comment]
I deleted all the sensors and now the app works properly. I'll try to add back them one by one

**Comment by FezVrasta** [comment]
Ok so, the problem seems to be the Osram sensor (the one that reports the consumed wats)

**Comment by FezVrasta** [comment]
Maybe you could add a way to specify which devices the user wants to import when DeCONZ is setup? This way people can easily add just the lights and switches and exclude the rest

**Comment by mariusmotea** [comment]
Is first time when i hear about such issue. Still there are workarounds to remove unwanted devices. Regarding your Osram sensor, it is possible to truncate all keys until hue applicatio will accept it.

**Comment by FezVrasta** [comment]
Thanks for the info, I don't actually care to have it show up in the Hue app since it wouldn't be useful anyway. Thanks for the help!
