### ISSUE TITLE
Lights turn on when service starts after reboot?

### ISSUE THREAD

**Issue by FezVrasta** [mariusmotea/diyHue#221]
Hi, I'm not really sure what's happening, but whenever I restart my RPi3, some of my lights turn themselves on automatically.

```
❯ cat /lib/systemd/system/hue-emulator.service                                                                                                                    pi@raspberrypi
[Unit]
Description=Hue Emulator Service
After=multi-user.target

[Service]
Type=idle
Restart=always
RestartSec=30
StartLimitInterval=200
StartLimitBurst=5

WorkingDirectory=/opt/hue-emulator
ExecStart=/opt/hue-emulator/HueEmulator3.py

[Install]
WantedBy=multi-user.target
```

I tried to `systemctl disable hue-emulator` and the lights don't turn on automatically when I restart the Pi.

If I do `systemctl restart hue-emulator` they don't turn on automatically neither.

And neither if I run HueEmulator3.py manually.

Ideas?

**Comment by mariusmotea** [comment]
Hi,

Check in the header of HueEmulator3.py script. There is the option to apply last lights state on startup and default is `True`. Switch this to `False`. Normally this is a useful future, since zigbee or milight lights turn on when is a power outage and this turn them back off if last know state was off.

**Comment by FezVrasta** [comment]
Thanks I'll try, but my lights aren't turned on when I restart my Pi. (I have a overnight schedule to restart the Pi to keep it fresh)

**Comment by FezVrasta** [comment]
Ok I can confirm that with that setting turned off everything works nicely, but honestly I'd like to keep it on because it's indeed useful.

**Comment by mariusmotea** [comment]
The script save the config.json file every hour when minute and the second is 00. Normally the automatically lights fetch help to have the last state saved on the bridge. Try to set the reboot cron to minute 01 of that hour to reboot it right after the config was saved.

**Comment by FezVrasta** [comment]
I guess I could also call the save script via curl to force the save?

**Comment by mariusmotea** [comment]
Yes `http://{RPi_ip}/save` if i'm not wrong.

**Comment by FezVrasta** [comment]
Ok, so I did this:

```
sudo su root
echo 'curl 127.0.0.1/save' > /etc/rc6.d/K99_save_hue_emulator_state
chmod +x /etc/rc6.d/K99_save_hue_emulator_state
```

this should trigger the Hue Emulator save every time the Pi is restarted.

**Comment by FezVrasta** [comment]
Second attempt, add `ExecStop=/opt/hue-emulator/save.sh` to the systemd script, then in `save.sh` write:

```
#!/bin/sh
curl 127.0.0.1/save
sleep 1
```

(run `systemctl daemon-reload && systemctl restart hue-emulator` and then attempt a `reboot now`)

This one seems to work, and it's actually cleaner. It may be added to diyHue as a default setting, I guess it'll be useful to others.

Ideally we should have a way to call `save` using python to make it cleaner.

**Comment by FezVrasta** [comment]
Second attempt, add `ExecStop=/opt/hue-emulator/save.sh` to the systemd script, then in save.sh write:

#!/bin/sh
curl 127.0.0.1/save
sleep 1
(run systemctl daemon-reload && systemctl restart hue-emulator and then attempt a reboot now)

This one seems to work, and it's actually cleaner. It may be added to diyHue as a default setting, I guess it'll be useful to others.

Ideally we should have a way to call save using python to make it cleaner.

**Comment by mariusmotea** [comment]
I spend some time here, but in python to get the kill signal you need to import more modules, is not that easy. I test even the systemd method, but without sleep 1 and it fail. Here i will say sleep 3 is better, my config is very big and it take more than 1 seconds to have it saved on sd card.

**Comment by mariusmotea** [comment]
Ok, with last commit i fix also this problem
