### ISSUE TITLE
Homeassistant recognise diyHue

### ISSUE THREAD

**Issue by betonishard** [mariusmotea/diyHue#225]
Hi all,

Not per se related to here but maybe someone uses diyhue in conjunction with homeassistant,

When I add the diyHue as hue device to homeassistant, I only see the rooms being recognised and not the individual bulbs (which are esp01's with ws2812 strip).

I added the following to the configuration.yml file (and running on homeassistant 0.69):

hue:
  bridges:
    - host: DEVICE_IP_ADDRESS

Would appreciate it if someone has the solution.
Regards,

**Comment by J3n50m4t** [comment]
I'm running HomeAssistant and this is my very minimal config 
```
hue:
  bridges:
    - host: 192.168.1.XXX
```
I see Rooms and there Lights. So your problem is not related to this project.
![image](https://user-images.githubusercontent.com/13681191/40455062-8c6ac21c-5eeb-11e8-9e64-c541a667929a.png)

**Comment by J3n50m4t** [comment]
I have a diyHue Bridge with a few tradfri and yeelight Bulps. I've linked my full config below. 
Before i removed tradfri etc I created with nearly nothing but hue in it. 
The Screenshot is from this version. 
Maybe you want to try out my full config to test. Groups are not updated and you could also outcomment them. 
https://github.com/J3n50m4t/HomeAssistantConfiguration/blob/3d8320cba45d5ae855d1eba87c8de442c8606c58/configuration.yaml#L35

**Comment by betonishard** [comment]
Ok so I finally found the issue. The problem is that when you add the bulbs to diyHue manufacturername is not added in the config.json. This is something that home assistant does not like.

I manually added the manufacturername to config.json with the value "Philips" and it works.. 

@J3n50m4t thanks for your input.

**Comment by J3n50m4t** [comment]
Would you be so kind to paste the specific part of your config?  So it can be fixed for further users

I don't see anything related to manufacturer name in my conf.

**Comment by betonishard** [comment]
Changed this:
`    "lights": {
        "1": {
            "modelid": "LST001",
            "name": "TV woonkamer",
            "state": {
                "alert": "none",
                "bri": 81,
                "colormode": "xy",
                "ct": 447,
                "effect": "none",
                "hue": 0,
                "on": true,
                "reachable": true,
                "sat": 0,
                "transitiontime": 20,
                "xy": [
                    0.58,
                    0.39
                ]
            },
            "swversion": "66010400",
            "type": "Color light",
            "uniqueid": "f9:2d:3e:7f:cf:5c-1"
        },`

To this:

`    "lights": {
        "1": {
            "manufacturername": "Philips",
            "modelid": "LST001",
            "name": "TV woonkamer",
            "state": {
                "alert": "none",
                "bri": 81,
                "colormode": "xy",
                "ct": 447,
                "effect": "none",
                "hue": 0,
                "on": true,
                "reachable": true,
                "sat": 0,
                "transitiontime": 20,
                "xy": [
                    0.58,
                    0.39
                ]
            },
            "swversion": "66010400",
            "type": "Color light",
            "uniqueid": "f9:2d:3e:7f:cf:5c-1"
        },`

**Comment by betonishard** [comment]
@J3n50m4t I guess you're right.. It works now nevertheless and users with the same issue can find it.

**Comment by cheesemarathon** [comment]
I have had the exact same issue. Adding in "manufacturername": "Philips"  to the config for each light worked for me also. Can there be an update created so that this happens by default?

**Comment by mariusmotea** [comment]
I made a new commit in order to add this parameter on all new lights that are detected.

https://github.com/mariusmotea/diyHue/commit/dac16a771a7904d5269bf02c833283f8ae21e743
