### ISSUE TITLE
responsive webgui for lights control

### ISSUE THREAD

**Issue by mariusmotea** [mariusmotea/diyHue#226]
Hi,

I want to create an http webgui that will be added to hue-emulator and will allow to turn on/off the lights and to change the brightness. Will be nice to have also a color picker for color lights, but this is just an extra. I'm not that good with css desing and i will require some help

From my researches we can use http://www.bootstraptoggle.com/ for the on/off button and http://seiyria.com/bootstrap-slider/ for brightness slider.

Thanks,
Marius.

**Comment by FezVrasta** [comment]
Would something like this work?

https://codesandbox.io/s/kw2pxoq77r

**Comment by mariusmotea** [comment]
I cannot view that page, i receive:

> ModuleNotFoundError
> Could not find module in path: './Hello'

What you said is much more than i was hopping. for me just the static ui is enough, i will take care to made it dynamic.

**Comment by FezVrasta** [comment]
try now please, there was a problem with the link

**Comment by FezVrasta** [comment]
If you'd like to give me a mock of a API response I can already make this part of the work.

**Comment by FezVrasta** [comment]
To be more specific, I can make the App component take a `data` property (the lights data structure) and a `onLightChange` property (which will be called when the user requires a light to change its state).

Doing so you can then hook into it easily.

**Comment by mariusmotea** [comment]
This is how i wanted to implement the webgui. On a successful login will be provided an username to access the api. This can be done by dinamically place a variable in javascript code with the username or by a json call. After the this username key is provided is simple to get entire date by using hue api witch is json based.

To get all the groups + data of them:
http GET /api/{provided username key}/groups

the reply will be something like:
```
{
        "1": {
            "action": {
                "alert": "select",
                "bri": 57,
                "colormode": "ct",
                "ct": 447,
                "effect": "none",
                "hue": 0,
                "on": true,
                "sat": 0,
                "scene": "10",
                "scene_inc": 1,
                "transitiontime": 9,
                "xy": [
                    0.0,
                    0.0
                ]
            },
            "class": "Bedroom",
            "lights": [
                "1"
            ],
            "name": "Bedroom",
            "state": {
                "all_on": true,
                "any_on": true
            },
            "type": "Room"
        },
......
````
from here we get for every group the name, on status (state => any_on), the brightness (state =>bri), the current color mode (state=>colormode, can be ct. xy or hs) and the color (state=> ct, state=>xt... depending on the mode selected)

to change something here you need to perform PUT http request with the parameters you want to change (colormode will be automatically switched to xy, ct, or hs if you provide one specific value)
to turn on the lights in group 1 the request will be 
PUT /api/{username key}/groups/1/action
content `{"on": true}`
or `{"bri": 254}` for brightness. 

I know this is hard, but i will be able to do this by myself if you can provide me a static template.

**Comment by mariusmotea** [comment]
Hue app is working this way:
Is getting the groups, then every 1 second is fetching the lights. Is doing this because in hue app is drawing an gradient with the color of all lights, and the only wait to get the color or the lights is by fetching also the lights

**Comment by FezVrasta** [comment]
Thanks, so the above json is an example of a light of a room? I think I just need an example with few lights and rooms, in different states, so that I can then build the UI around them.

**Comment by mariusmotea** [comment]
The above example is for a group, in the goup is just one line (light "1").

Here is an example of one light:
```
"12": {
            "etag": "22064e20026e091be82d443a4ae306eb",
            "hascolor": false,
            "manufacturername": "IKEA of Sweden",
            "modelid": "TRADFRI bulb E27 opal 1000lm",
            "name": "Baie",
            "state": {
                "alert": "select",
                "bri": 234,
                "on": false,
                "reachable": true
            },
            "swversion": "1.2.214",
            "type": "Dimmable light",
            "uniqueid": "00:0b:57:ff:fe:12:72:c2-01"
        },
```
And for color bulbs:
```
        "15": {
            "modelid": "LST001",
            "name": "Hue strip LST001 1",
            "state": {
                "alert": "select",
                "bri": 217,
                "colormode": "xy",
                "ct": 367,
                "effect": "none",
                "hue": 0,
                "on": true,
                "reachable": true,
                "sat": 0,
                "transitiontime": 9,
                "xy": [
                    0.39,
                    0.3
                ]
            },
            "swversion": "66010400",
            "type": "Color light",
            "uniqueid": "c4:84:2c:a6:20:a0-1"
        },
```
Important keys are "name" and "state", here are the details of the values inside state:

on | bool | On/Off state of the light. On=true, Off=false
-- | -- | --
bri | uint8 | Brightness of the light. This is a scale from the minimum brightness the light is capable of, 1, to the maximum capable brightness, 254.
hue | uint16 | Hue of the light. This is a wrapping value between 0 and 65535. Note, that hue/sat values are hardware dependent which means that programming two devices with the same value does not garantuee that they will be the same color. Programming 0 and 65535 would mean that the light will resemble the color red, 21845 for green and 43690 for blue.
sat | uint8 | Saturation of the light. 254 is the most saturated (colored) and 0 is the least saturated (white).
xy | list 2..2 of float 4 | The x and y coordinates of a color in CIE color space.The first entry is the x coordinate and the second entry is the y coordinate. Both x and y are between 0 and 1. Using CIE xy, the colors can be the same on all lamps if the coordinates are within every lamps gamuts (example: "xy":[0.409,0.5179] is the same color on all lamps). If not, the lamp will calculate it's closest color and use that. The CIE xy color is absolute, independent from the hardware.
ct | uint16 | The Mired Color temperature of the light. 2012 connected lights are capable of 153 (6500K) to 500 (2000K).
alert | string | The alert effect, which is a temporary change to the bulb’s state. This can take one of the following values:“none” – The light is not performing an alert effect.“select” – The light is performing one breathe cycle.“lselect” – The light is performing breathe cycles for 15 seconds or until an "alert": "none" command is received.Note that this contains the last alert sent to the light and not its current state. i.e. After the breathe cycle has finished the bridge does not reset the alert to "none".
effect | string | The dynamic effect of the light, can either be “none” or “colorloop”.If set to colorloop, the light will cycle through all hues using the current brightness and saturation settings.
colormode | string 2, 2 | Indicates the color mode in which the light is working, this is the last command type it received. Values are “hs” for Hue and Saturation, “xy” for XY and “ct” for Color Temperature. This parameter is only present when the light supports at least one of the values.
reachable | bool | Indicates if a light can be reached by the bridge.

**Comment by mariusmotea** [comment]
one difference between groups and lights, when you want to apply changes to groups the url is
```
/api/{user key}/groups/{group id}/actions
```
with the lights the url is:
```
/api/{user key}/lights/{light id}/state
```

**Comment by FezVrasta** [comment]
Cool thanks! I'll try to work on it in my spare time.

**Comment by mariusmotea** [comment]
BTW your config.json file contain nativ hue api data. You can play with curl command to PUT json data, the usename key is located in config=> whitelist. Pick any key hash key available, all will work. Also if you start HueEmulator script manually the requests and json's will be displayed.

**Comment by mariusmotea** [comment]
I forget one important thing. The qtHue project made by me is based on javascript requests. Some functions from there can be used also here.

**Comment by FezVrasta** [comment]
Do you have any algorithm to convert the `ct` into a RGB or HEX color value?

**Comment by mariusmotea** [comment]
Yes, also for xy (cie)

```
function cieToRGB(x, y, brightness)
{
    //Set to maximum brightness if no custom value was given (Not the slick ECMAScript 6 way for compatibility reasons)
    if (brightness === undefined) {
        brightness = 254;
    }

    var z = 1.0 - x - y;
    var Y = (brightness / 254).toFixed(2);
    var X = (Y / y) * x;
    var Z = (Y / y) * z;

    //Convert to RGB using Wide RGB D65 conversion
    var red 	=  X * 1.656492 - Y * 0.354851 - Z * 0.255038;
    var green 	= -X * 0.707196 + Y * 1.655397 + Z * 0.036152;
    var blue 	=  X * 0.051713 - Y * 0.121364 + Z * 1.011530;

    //If red, green or blue is larger than 1.0 set it back to the maximum of 1.0
    if (red > blue && red > green && red > 1.0) {

        green = green / red;
        blue = blue / red;
        red = 1.0;
    }
    else if (green > blue && green > red && green > 1.0) {

        red = red / green;
        blue = blue / green;
        green = 1.0;
    }
    else if (blue > red && blue > green && blue > 1.0) {

        red = red / blue;
        green = green / blue;
        blue = 1.0;
    }

    //Reverse gamma correction
    red 	= red <= 0.0031308 ? 12.92 * red : (1.0 + 0.055) * Math.pow(red, (1.0 / 2.4)) - 0.055;
    green 	= green <= 0.0031308 ? 12.92 * green : (1.0 + 0.055) * Math.pow(green, (1.0 / 2.4)) - 0.055;
    blue 	= blue <= 0.0031308 ? 12.92 * blue : (1.0 + 0.055) * Math.pow(blue, (1.0 / 2.4)) - 0.055;


    //Convert normalized decimal to decimal
    red 	= Math.round(red * 255);
    green 	= Math.round(green * 255);
    blue 	= Math.round(blue * 255);

    if (isNaN(red))
        red = 0;

    if (isNaN(green))
        green = 0;

    if (isNaN(blue))
        blue = 0;

    var decColor =0x1000000+ blue + 0x100 * green + 0x10000 *red ;
    return '#'+decColor.toString(16).substr(1);
}



function colorTemperatureToRGB(mireds){

    var hectemp = 20000.0 / mireds;

    var red, green, blue;

    if( hectemp <= 66 ){

        red = 255;
        green = 99.4708025861 * Math.log(hectemp) - 161.1195681661;
        blue = hectemp <= 19 ? 0 : (138.5177312231 * Math.log(hectemp - 10) - 305.0447927307);


    } else {

        red = 329.698727446 * Math.pow(hectemp - 60, -0.1332047592);
        green = 288.1221695283 * Math.pow(hectemp - 60, -0.0755148492);
        blue = 255;

    }

    red = red > 255 ? 255 : red;
    green = green > 255 ? 255 : green;
    blue = blue > 255 ? 255 : blue;


    var decColor =0x1000000+ parseInt(blue, 10) + 0x100 * parseInt(green, 10) + 0x10000 * parseInt(red, 10) ;
    return '#'+decColor.toString(16).substr(1);


}

function rgb_to_cie(red, green, blue)
{
    //Apply a gamma correction to the RGB values, which makes the color more vivid and more the like the color displayed on the screen of your device
    var red 	= (red > 0.04045) ? Math.pow((red + 0.055) / (1.0 + 0.055), 2.4) : (red / 12.92);
    var green 	= (green > 0.04045) ? Math.pow((green + 0.055) / (1.0 + 0.055), 2.4) : (green / 12.92);
    var blue 	= (blue > 0.04045) ? Math.pow((blue + 0.055) / (1.0 + 0.055), 2.4) : (blue / 12.92);

    //RGB values to XYZ using the Wide RGB D65 conversion formula
    var X 		= red * 0.664511 + green * 0.154324 + blue * 0.162028;
    var Y 		= red * 0.283881 + green * 0.668433 + blue * 0.047685;
    var Z 		= red * 0.000088 + green * 0.072310 + blue * 0.986039;

    //Calculate the xy values from the XYZ values
    var x 		= (X / (X + Y + Z)).toFixed(4);
    var y 		= (Y / (X + Y + Z)).toFixed(4);

    if (isNaN(x))
        x = 0;

    if (isNaN(y))
        y = 0;


    return [parseFloat(x), parseFloat(y)];
}
```

**Comment by FezVrasta** [comment]
LOL that's huge, thanks

**Comment by FezVrasta** [comment]
Here the first sketch for the bulb settings:

![image](https://user-images.githubusercontent.com/5382443/40042574-35ef211e-5822-11e8-91e8-fe8f77a61ebb.png)

**Comment by FezVrasta** [comment]
Why do I get `hasColor` `true` on color temperature lights?

**Comment by mariusmotea** [comment]
Ignore that, is not a valid hue api value, it is added by deconz and will be present just on deconz lights.

**Comment by FezVrasta** [comment]
How can I know if a light supports colors or not then? I need to conditionally show the color picker.

Also, what's the min and max kelvin value?

**Comment by FezVrasta** [comment]
Also, on my IKEA lights I get:

```
    "state": {
      "reachable": true,
      "alert": "none",
      "ct": 485,
      "on": false,
      "bri": 254,
      "colormode": "ct"
    },
    "ctmin": 250,
    "ctmax": 454,
```

why the `ctmax` is lower than the current `ct` state?

**Comment by FezVrasta** [comment]
Ah and last question, may you give me the formula to convert `xy` to `rgb` please?

**Comment by mariusmotea** [comment]
ctmax and ct min is also not philips hue api value. It just show the minimum and maximum mireds value that can be reproduced by that bulb.

Check below function, from xy to rgb is using `function cieToRGB(x, y, brightness)`

**Comment by FezVrasta** [comment]
So why do my bulbs have a current temp value higher than the maximum?

**Comment by mariusmotea** [comment]
> So why do my bulbs have a current temp value higher than the maximum?

Because hue app don't read that value and it work by default in 153 - 500 mireds range.

I provide you 3 functions in previews comment. One to convert from rgb to xy that is useful as color picker provide rgb values that are not accepted by hue bridge. xy to rgb to show the current color of the bulb, and color temp to rgb in order to display the current color temperature level.

**Comment by mariusmotea** [comment]
for your color temp slider, made it to send 153 when is minimum and 500 when is maximum.

**Comment by mariusmotea** [comment]
i miss one question from you:

> How can I know if a light supports colors or not then? I need to conditionally show the color picker.

- if the light has xy or hue/sat values in state, then is a color bulb
- if the light has ct value, then it support color temperature
- if the light has bri value, then it support dimming

**Comment by mariusmotea** [comment]
What you have done is awesome. If you can upload the files in a new folder in BridgeEmulator will be good, i'm not familiar with this codesandbox.

Thanks you very much. I will add you to contributors list.

**Comment by FezVrasta** [comment]
Sure thing, I'll set up everything needed to build it also.

**Comment by FezVrasta** [comment]
If you need help with anything just leave a comment here or contact me on [Twitter](https://twitter.com/FezVrasta) or [Spectrum](https://spectrum.chat/users/fezvrasta)

**Comment by mariusmotea** [comment]
Thanks,
For now i will start to work with what you already provide me. I know some javascript so i believe i will be able to understand who this is working and go forward.

**Comment by FezVrasta** [comment]
cool, I'll need to make some adjustments to make sure the sliders get the updated values after the API call succeeded, so for now don't worry if the sliders act funny

**Comment by FezVrasta** [comment]
@mariusmotea I'm trying to integrate part of the API requests inside the web app.

I can get the gateway from `config.gateway`, but what about the API key?

**Comment by mariusmotea** [comment]
api key need to be a constant variable in code ex: `xxxxxxxxxxxxxxxx`. I will made the internal webserver to replace the content of `xxxxxxxxxxxxxxxx` with first user key from config => whitelist when this file will be served. If you want to perform tests with your hue-emulator, open config.json and copy one user key from config => whitelist.

**Comment by FezVrasta** [comment]
What if the user doesn't have any client whitelisted? Shouldn't we create an entry automatically just for the web ui?

**Comment by mariusmotea** [comment]
good question. i can take care of this, if no user key is available then i will generate one random to have something to provide. If we will use one statically it will be a security issue, some users allow access from internet to their emulated bridges.

**Comment by mariusmotea** [comment]
Hi,

I'm having some hard time trying to build this project. I was expected there is an easy way to export it to html + js files but i did not manage to do it. Running `npm build` download lot of folders in node_modules, but no other progress.

**Comment by FezVrasta** [comment]
First you have to install the dependencies with `npm install`, then you can run `npm build` to build the project in the `/build` folder

**Comment by FezVrasta** [comment]
No there are several dependencies, just run `npm install` and they will get installed automatically.

```
cd BridgeEmulator/web-ui
npm install
npm run build
```

**Comment by mariusmotea** [comment]
i will start from scratch with a new Ubuntu VM. Maybe i broke my installation trying all the solution from google.

```
root@ubuntu:/home/marius/diyHue-master/BridgeEmulator/web-ui# npm run build

> hue-emulator-ui@1.0.0 build /home/marius/diyHue-master/BridgeEmulator/web-ui
> react-scripts build

/home/marius/diyHue-master/BridgeEmulator/web-ui/node_modules/react-scripts/scripts/build.js:64
    ({ stats, previousFileSizes, warnings }) => {
     ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-104-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! hue-emulator-ui@1.0.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hue-emulator-ui@1.0.0 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hue-emulator-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hue-emulator-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hue-emulator-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/marius/diyHue-master/BridgeEmulator/web-ui/npm-debug.log
root@ubuntu:/home/marius/diyHue-master/BridgeEmulator/web-ui# 
```

**Comment by mariusmotea** [comment]
I feel embarrassed, it was straightforward. Is working, thanks.

**Comment by mariusmotea** [comment]
Hi, 

with the commit https://github.com/mariusmotea/diyHue/commit/e4078fcf9a122075839b4bb021211ffdcc902cf8 i add support for web-ui. I see the request on groups and lights with the correct user key, but in chrome console i receive:

```
TypeError: Cannot read property 'on' of undefined
    at Room.js:93
    at Array.map (<anonymous>)
    at re (Room.js:84)
    at beginWork (react-dom.production.min.js:137)
    at a (react-dom.production.min.js:176)
    at i (react-dom.production.min.js:176)
    at x (react-dom.production.min.js:182)
    at m (react-dom.production.min.js:181)
    at y (react-dom.production.min.js:181)
    at h (react-dom.production.min.js:180)
```

I believe must be a problem with the way the lights are processed from hue-emulator output, because from static json files everything was fine.

**Comment by FezVrasta** [comment]
It looks like one of your lights doesn't provide a `state` property?

https://github.com/mariusmotea/diyHue/blob/master/BridgeEmulator/web-ui/src/Room.js#L93

**Comment by mariusmotea** [comment]
Sure, this is the output:

```
pi@raspberrypi:~ $ curl 127.0.0.1/api/18d5e553f02c644ec7ca8c89c631f0ca/groups
{"1": {"name": "Bedroom", "class": "Bedroom", "lights": [1], "type": "Room", "action": {"transitiontime": 9, "colormode": "ct", "alert": "select", "xy": [0.531861, 0.322905], "effect": "none", "ct": 458, "sat": 254, "hue": 47330, "on": false, "bri": 20}, "state": {"any_on": false, "all_on": false}}, "2": {"name": "Dressing", "class": "Office", "lights": [], "type": "Room", "action": {"colormode": "ct", "alert": "none", "xy": [0.459796, 0.411618], "effect": "none", "on": false, "sat": 0, "hue": 0, "transitiontime": 9, "bri": 225}, "state": {"any_on": false, "all_on": false}}}pi@raspberrypi:~ $
pi@raspberrypi:~ $
pi@raspberrypi:~ $ curl 127.0.0.1/api/18d5e553f02c644ec7ca8c89c631f0ca/lights
{"1": {"ctmax": 454, "name": "Table 3", "hascolor": true, "ctmin": 250, "modelid": "TRADFRI bulb GU10 WS 400lm", "etag": "27c29fc43dea85f652d804c002b2a23f", "type": "Color temperature light", "swversion": "1.2.217", "uniqueid": "90:fd:9f:ff:fe:79:2f:0f-01", "manufacturername": "IKEA of Sweden", "state": {"colormode": "ct", "alert": "none", "ct": 238, "on": true, "reachable": true, "bri": 254}}}pi@raspberrypi:~ $
```

what is the name of this programming language as it it not pure javascript?

**Comment by FezVrasta** [comment]
It's JSX.

On index.js on line 51, add a `console.log(json)` and see if it logs the correct payload.

I tried your payloads using codesandbox and the UI loads fine.

**Comment by FezVrasta** [comment]
Oh nevermind I can reproduce locally, I'm on it.

**Comment by FezVrasta** [comment]
fixed https://github.com/mariusmotea/diyHue/pull/231

**Comment by mariusmotea** [comment]
Thanks, is working fine now.

**Comment by mariusmotea** [comment]
Hi again,

I need again some help. I implement http request and now i can control the lights, but the slide bars trigger the http put request too fast and i instant overload the webserver in python script. Is there a parameter that can be attached to these so the "trigger" speed to be lower (1 trigger every second for example?). Now is working perfect if i click to the desired place without to swipe.

**Comment by FezVrasta** [comment]
Sure! I'll add a throttle to the sliders so that we trigger only one action each N milliseconds.

I'll add it tomorrow morning

**Comment by mariusmotea** [comment]
Hi again,

I fix most of the problems in last commits, i can control all the lights parameters, but the changes are visible just to the lights, not also to the interface. I need to refresh the page to have the changes visible also to interface.  First time when you provided the page https://pwn1vjon0m.codesandbox.io/ some buttons were working and i tried to take the example from there, but it was updated and the switch buttons are all statical. Also i want to know how to call the functions from color.js, now i duplicate the one used for xy conversion.

**Comment by FezVrasta** [comment]
We'll have to poll the API endpoints to fetch the updated data each X seconds. I can do that for you.

To import the functions from color.js you can do `import { nameOfTheFunction } from './color'`

**Comment by mariusmotea** [comment]
I just find a scaling bug for phones displays. [Screenshot](https://drive.google.com/file/d/15BfbrBTgHBhbJ0m-yV26Xz8M1I3zuT-R/view?usp=sharing).

**Comment by FezVrasta** [comment]
Yes I'm aware of it, tomorrow I'll fix it

**Comment by mariusmotea** [comment]
Thank you for all this effort

**Comment by FezVrasta** [comment]
Hey @mariusmotea what's the status on this issue? Once this part is released I'm going to add more pages to control all the other APIs (like hue touchlink, deconz etc) but first I'd like to have this released :-)

**Comment by mariusmotea** [comment]
Hi,

Only issue remain with hue control, despite it is working, it is going to initial value right away. I made a change to last commit from you, `defaultColor` did not work, i replace with `color` and i added the conversion formula from xy to rgb. Now when you access the light property the slider color is positioned to exactly the color of the bulb. Sliding this to different color will apply the change to the light, but the slider position will go back to previews position. If i refresh the page it will be on correct place.

**Comment by mariusmotea** [comment]
Hi,

I made the first release with current progress. I rename `web-ui` folder into `web-ui-src` and the uploaded `web-ui` contain the compiled code.

**Comment by FezVrasta** [comment]
@cheesemarathon I think this should be "in progress" or maybe directly "done", and then we can create new issues for the additional functionalities we want to add to the web UI.

**Comment by cheesemarathon** [comment]
Closing this issue, please create new issues for each feature you would like added to the UI.
