### ISSUE TITLE
Hue URL commands via raspbee

### ISSUE THREAD

**Issue by moveslikeyoda** [mariusmotea/diyHue#227]
Is it possible to control Raspbee connected lights with a get request via URL similar to the Wifi lights in the Lights API section?  I know how to do this through the normal Hue API on the Phillips bridge, but the environment is not available through your emulator.  I want to issue a command from outside the Hue app or Webapp.

**Comment by mariusmotea** [comment]
Hi,

Is the same as with hue bridge, to get the user key hash for requests just open /opt/hue-emulator/config.json and look in config => whitelist. Pick any user hash from there. 
to send the request with curl use something like this:
`curl -X PUT -d '{"on": true}' http://{emulator_Ip}/api/{user_key}/lights/{light id}/state`

or for groups:

`curl -X PUT -d '{"on": true}' http://{emulator_Ip}/api/{user_key}/groups/{group id}/action`

**Comment by moveslikeyoda** [comment]
Works great, thank you for the quick reply.
