### ISSUE TITLE
Deep Sleep Switch

### ISSUE THREAD

**Issue by Purzel84** [mariusmotea/diyHue#229]
Hi, is there a way to run the tap switch with a battery and send the esp to the deepsleep until you press it the next time?

**Comment by mariusmotea** [comment]
This is exactly the current behaviour.

**Comment by Purzel84** [comment]
Okay I found that but what do I have to enter to fall into the deepsleep and wake up when I press the switch? Unfortunately, I am dependent to Operator  your tap control with a lipo battery.

**Comment by Purzel84** [comment]
So far he has pulled the battery empty in two days: - /

**Comment by mariusmotea** [comment]
Once in deepsleep the circuit will send a short pulse to rst pin via that capacitor that will wake up the esp. After this it will send the http request for the pressed button amd enter back in deepsleep. If the circuit is not working properly it can have unexpected behaviour.
