### ISSUE TITLE
Scene update delay

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#232]
Hi @mariusmotea I notice there is a huge lag when one of the lights in the room is offline until the remaining lights change. I suppose it sends a command to each of them one by one and waits for ack before it continues to next one. Is there a way to do this asynchronously so that it doesnt wait for each light to respond? It would speed up the scene change alot.

**Comment by mariusmotea** [comment]
Yes, but you need to be carefully as in case you have one device that control multiple lights it can be overloaded by receiving too many concomitant http requests. The workaround was explained here: https://github.com/mariusmotea/diyHue/issues/224#issuecomment-388809871

**Comment by mariusmotea** [comment]
I'm thinking to add a new variable that will store the ip of last light and if is not identical,then execute the request in new thread. 

> Will it help if i switch it to 160mhz?

I believe will help only if you have good wifi connection (router with good rx sensitivity + good ESP's)

**Comment by mariusmotea** [comment]
With the new updates the requests for groups and scenes will be instant send to first lights with different ip's, then will continue in non threaded mode. This is the best i can do.
