### ISSUE TITLE
Yeelight not found by Alexa

### ISSUE THREAD

**Issue by J3n50m4t** [mariusmotea/diyHue#237]
### Yeelight not found by Alexa
Alexa search Device doesn't add the yeelight.

All features from the Hue app are working with the bulp, but alexa doesn't want the yeelight yet.

1. I startet the HueEmulator
2. opened the Linkbutton page
3. pressed activate 
4. searched with alexa

```pi@raspberrypi:~ $ sudo /opt/hue-emulator/HueEmulator3.py
Config loaded
start ssdp broadcast
starting ssdp...
sync with lights
Starting httpd...
192.168.1.132 - - [23/May/2018 15:55:36] "GET /hue/linkbutton HTTP/1.1" 200 -
192.168.1.132 - - [23/May/2018 15:55:41] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
Sending M-Search response to 192.168.1.152
Sending M-Search response to 192.168.1.152
192.168.1.152 - - [23/May/2018 15:55:57] "GET /description.xml HTTP/1.1" 200 -
192.168.1.152 - - [23/May/2018 15:55:57] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights HTTP/1.1" 200 -
Sending M-Search response to 192.168.1.152
192.168.1.152 - - [23/May/2018 15:55:58] "GET /description.xml HTTP/1.1" 200 -
192.168.1.152 - - [23/May/2018 15:55:58] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights HTTP/1.1" 200 -
sync with lights
Sending M-Search response to 192.168.1.152
192.168.1.152 - - [23/May/2018 15:55:59] "GET /description.xml HTTP/1.1" 200 -
192.168.1.152 - - [23/May/2018 15:55:59] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights HTTP/1.1" 200 -
Sending M-Search response to 192.168.1.1
Sending M-Search response to 192.168.1.1
Sending M-Search response to 192.168.1.1
Sending M-Search response to 192.168.1.1
Sending M-Search response to 192.168.1.1
Sending M-Search response to 192.168.1.1
```

**Comment by J3n50m4t** [comment]
Alexa finds Tradri bulbs with the same steps

**Comment by mariusmotea** [comment]
i believe i know what is the issue. Alexa display just the "certified" lights. You need to change in config.json the `modelid `and maybe the `manufacture ` to reflect a certified light. Remember to stop the hue-emulator service before you edit, to not override your changes.

**Comment by mariusmotea** [comment]
for a test you can replicate with the values from tradfri bulbs, even if they differ in properties.

**Comment by mariusmotea** [comment]
`"type": "Yeelight Color"`

I don't have Alexa. but i believe this can be the issue.

**Comment by J3n50m4t** [comment]
> "type": "Yeelight Color"

changed it to `Extended color light` and Alexa found it.
Shall I create a new PR or are you fixing this one line? 
https://github.com/mariusmotea/diyHue/blob/d5cf873df6e95ca51f4de6800b2700de2a9870ad/BridgeEmulator/HueEmulator3.py#L1335

**Comment by mariusmotea** [comment]
I fix it.
