### ISSUE TITLE
Using umlauts in room names can crash the app

### ISSUE THREAD

**Issue by Cludch** [mariusmotea/diyHue#238]
Hey,

first of all: I really love diyHue!
I had an issue earlier that my room names were called "K\u00fcche" (German for kitchen). When I clicked the room name in the main menu, the app crashed. A simple workaround is just change the name in the config file, but I feel like there will be further issues within the app as there are more umlauts being generated automatically.
I can't really tell why this is an issue because diyHue escapes the names (correctly I think) and the native bridge does support umlauts.

**Comment by mariusmotea** [comment]
Hi,

Do you know how the real bridge escape the special characters? I believe at some point an user from Germany provide me the config of his real bridge via email. I will try to find and check if in rooms names he has this character.

**Comment by Cludch** [comment]
Sadly not. But I am about to set up my real bridge this weekend. Then I could test it for you.

**Comment by mariusmotea** [comment]
Hi,

I found the real bridge config sample and i saw one scene name is "Tropendämmerung". Maybe the issue is exactly the automatic escape done by the emulator?

**Comment by J3n50m4t** [comment]
I'm also from germany and I can't see app crashings with my emulated hue. 
But we should search for an fix, because a lot of scenes are named with äüö.
Tropendämmerung, Frühlingsblüten.
May we could add utf8 encoding when writing to the conf. I will try it the next few days.

**Comment by Cludch** [comment]
@J3n50m4t do you have room with umlauts?
Yeah, I figured that scenes could cause trouble.
I just got my hue lamp and will check later how the real one does the encoding.
But UTF-8 sounds like a solid approach.

**Comment by J3n50m4t** [comment]
@Cludch Yes. Büro and Küche. But I had no crash yet in around 2 weeks using.  
None of my lights contains a umlaut tho.

**Comment by mariusmotea** [comment]
Android and iPhone applications are different, maybe the issue is just with one of them. I also have tradfri bulbs with swedish specific characters and no errors.

**Comment by mcer12** [comment]
I had issues with this also. It didnt crash the app but the extended latin characters appeared broken. The issue may be still open since few months ago. I settled with using basic latin for the time being.

**Comment by mcer12** [comment]
The escaping issue is with all extended latin characters.

**Comment by cheesemarathon** [comment]
Has anyone been able to show how the genuine hue bridge escapes extended latin characters so that this can be implemented?

**Comment by Brainstorm100** [comment]
Hello
I did everything as stated in the instructions. Installed on a PI 3. And also the association with the divice goes well. Only when I type a lamp number one. Raid the app.
I have now reinstalled it 17 times and it is always the same mistake.
Where could be the problem ?

**Comment by dfloer** [comment]
@cheesemarathon I just checked, and the official bridge (model: BSB002, vers: 1806051111) and app (Android 3.4.0) does accept Unicode in room names. Here's the room in JSON from an API call.

```json
{
"name": "Störâge Room ツ",
"lights": [
  "4"
],
"type": "Room",
"state": {
"all_on": false,
"any_on": false
},
"recycle": false,
"class": "Living room",
"action": {
"on": false,
"bri": 254,
"ct": 366,
"alert": "none",
"colormode": "ct"
}
```

**Comment by Brainstorm100** [comment]
Hat niemanden sonst das broblem das die App nach dem hinzufügen einer Lampennummer abstürzt??

**Comment by mariusmotea** [comment]
I need clear example of characters that need to be escaped in order to debug.

**Comment by dfloer** [comment]
@mariusmotea Haven't looked into the code yet to see why it's doing this, but the issue seems to be that the characters are being improperly escaped.

I renamed a room to add two unicode characters through the app, and it immediately returned the � (replacement character) in the app, rather than crashing.

A real bridge  sends back the proper unicode characters, the emulated bridge responds with escaped characters. This seems to be what's confusing the app.
`"name":"Kitchen \u00f6 \u30c4"` rather than the expected json of `"name":"Kitchen \u00f6 \u30c4"`.

**Comment by Brainstorm100** [comment]
@cheesemarathon
I have only entered the serial number of the lamp in the APP. Then when I click search the app throws off.

**Comment by cheesemarathon** [comment]
@Brainstorm100 So the app crashes when you click search to add a light?

**Comment by Brainstorm100** [comment]
Yes, !!!

**Comment by mariusmotea** [comment]
@Brainstorm100 what lights did you have in the network and did you replace the light_name variable in lights sketch header with something that contain umlauts?

**Comment by Brainstorm100** [comment]
I have no lights in the network. I have two original hue lamps and when I enter the serial number in the app and then search on the app crashes.

**Comment by mariusmotea** [comment]
This solution can control original hue lamps only using the original hue bridge as proxy or using Raspbee module (Deconz).

**Comment by cheesemarathon** [comment]
@Brainstorm100 If you are having issues with setup, i suggest you [join us on slack](https://slackinvite.squishedmooo.com/) and we can help you there. Your problems don't seem to be related to this issue.

**Comment by cheesemarathon** [comment]
> 
> 
> @mariusmotea Haven't looked into the code yet to see why it's doing this, but the issue seems to be that the characters are being improperly escaped.
> 
> I renamed a room to add two unicode characters through the app, and it immediately returned the � (replacement character) in the app, rather than crashing.
> 
> A real bridge sends back the proper unicode characters, the emulated bridge responds with escaped characters. This seems to be what's confusing the app. The config.json also shows the escaped characters.
> `"name":"Kitchen \u00f6 \u30c4"` rather than the expected json of `"name":"Kitchen \u00f6 \u30c4"`.

@dfloer I think you have a typo in your comment. Your two json quotes look the same to me. This `"name":"Kitchen \u00f6 \u30c4"` and this `"name":"Kitchen \u00f6 \u30c4"`

**Comment by dfloer** [comment]
It was right when I wrote it, but is appears something involving my broswer or github changed it. I've edited the comment, and when I wrote this, it's accurate.

**Comment by mariusmotea** [comment]
This may be the solution:
https://stackoverflow.com/questions/11977935/how-to-convert-a-string-with-umlauts-back-to-json

Changing the encoding to 'cp1250'. I will try to test it.

**Comment by cheesemarathon** [comment]
> This may be the solution:
> https://stackoverflow.com/questions/11977935/how-to-convert-a-string-with-umlauts-back-to-json
> 
> Changing the encoding to 'cp1250'. I will try to test it.

Any progress on this @mariusmotea?

**Comment by gensmann** [comment]
In a similar situation, using lamp names with danish æ, ø or å in the . hue bridge at importing those lamps from the hue-bridge creates a lamp with no name (blank), but fully functional in the hue app.

trying to name a lamp with an æ, ø or å through the app on the DIYhue bridge simply creates a blank name as well.

Might be related?

**Comment by LordVoodoo** [comment]
The Osram Lightify Surface W28 is created with an unreadable character as well. Unfortunately, even editing the SQL-Lite file didn't help.

**Comment by cheesemarathon** [comment]
For anyone that is still watching this. The issue is now fixed thanks to @n3PH1lim over at [diyhue/diyHue](https://github.com/diyhue/diyHue/pull/94)
