### ISSUE TITLE
New HUE app 3.0.0

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#239]
What functions are planed for support? For instance, under advanced in settings there is a sunset/sunrise function. App crashes when i click it (probably the emulator has no idea what to do with it). 

Entertainment areas showed up in the app, guessing i cant do much with em yet.

Also a new scenes button showed up. Will these function now?

**Comment by mariusmotea** [comment]
Hi,

- Need some help for somebody with real hue bridge to provide new output, i believe sunset/sunrise is just one logical light level sensor.
- HueEntertainment - probably i need help from a good C/C++ coder that is able to create the UDP service, as python has low support for DTLS.
- All other functions are working like with previews application. One future problem is that Hue protocol is changing from http to https and i need to create this additional service, not sure if certificate is hardcoded in the app.

**Comment by erazor666** [comment]
I was kinda guessing the sunset sensor uses your lat-/longitude like home assistant for instance to calculate when the sun rises at your location. Sunset data is quite nice as a parameter for turning on or off lights, as well as fading out lights according to the sun.

**Comment by juanesf** [comment]
My router with VPN connection and diyHue running without problems has default dtls connection:
https://github.com/cernekee/openconnect/blob/master/dtls.c

**Comment by mariusmotea** [comment]
Don't help, we need a special dtls key exchange https://github.com/mariusmotea/diyHue/issues/150, so far i found support just in C# libraries

**Comment by mariusmotea** [comment]
New Hue required changes were done, so i will close this issue.
