### ISSUE TITLE
Can this be made to work with smartthings?

### ISSUE THREAD

**Issue by clmcgrath** [mariusmotea/diyHue#24]
Is it possible to make this work with smart things ,  would like to port my phillips switches over to smart things  and this seems like it could be a good option 

basically what i want to do is force  hue to push an update on button change events

**Comment by mariusmotea** [comment]
Currently there is no hardware support for zigbee communication. It is possible to import all switches and sensors from original Hue Bridge and fetch them every second to detect if a button was pressed or motion sensor triggered, but i'm not sure this is what you want.

**Comment by clmcgrath** [comment]
Looking more for something along the lines of the emulated hue bridge type functionality that exists in homeassistant just don't want the hassle of running a full I stance of ha for it
Now that I think of it not so sure I can do what I want 
But the polling is an interesting thought I have had slow response time doing this from ST

**Comment by clmcgrath** [comment]
Min poll time is 1 min minimum

**Comment by mariusmotea** [comment]
"Min poll time is 1 min minimum" what do you mean? I guess the original Hue Bridge will not be overloaded if receive a GET request on every second.

**Comment by mariusmotea** [comment]
Closed as there is no feedback
