### ISSUE TITLE
Razer Synapse support?

### ISSUE THREAD

**Issue by Dukadyr** [mariusmotea/diyHue#240]
Hello folks!
Is there at the moment any posibility to link the Razer Synapse Hue function with the diyHue Bridge?
Right now it tells me that the bridge is outdated.

btw: nice work guys!

**Comment by mariusmotea** [comment]
Hi,

The only issue is that i cannot create the hue entertainment service because of low support for dtls in python. I request for help maybe somebody with C/C++ skills can create this service.

**Comment by UniCizin** [comment]
hey
now, as the entertainment service is up and running,
can you have a deeper look into the Synapse integration?

**Comment by mariusmotea** [comment]
Synapse is now working so i will close this.
