### ISSUE TITLE
Autoduscover in new app

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#241]
New app gets stuck on searching for new lights. Keeps searching forever.

**Comment by mariusmotea** [comment]
True, i found the POST request is different with new app. I made a quick fix (last line), but i believe i can provide a more elegant solution soon.
```
        print ("in post method")
        print(self.path)
        self.data_string = "{}".encode() if self.headers['Content-Length'] is None else self.rfile.read(int(self.headers['Content-Length']))
```

**Comment by mcer12** [comment]
Thanks, feel free to close it when you push the final solution.

**Comment by mariusmotea** [comment]
Fixed in last commit.
