### ISSUE TITLE
Hue Sync support?

### ISSUE THREAD

**Issue by FezVrasta** [mariusmotea/diyHue#244]
The Hue Sync app is out, but it won't connect to the bridge saying that it's outdated

**Comment by mariusmotea** [comment]
I made some debugging, after i update the api version and the bridge is up to date, it ask for creating the hue entertainment areas, so no luck.

**Comment by J3n50m4t** [comment]
As an alternative i can suggest you http://www.screenbloom.com
not exactly the same but it does its job fine over here. And is compatible

**Comment by mcer12** [comment]
@J3n50m4t If I'm not mistaken this only controls one light right?

**Comment by J3n50m4t** [comment]
@mcer12 I don't have 2 color bulps in one room and was to lazy to go through the rooms. 
But in the Interface I can add as many as I want. So i assume you can use more than one.

**Comment by mariusmotea** [comment]
Hue Sync support is now in place.
