### ISSUE TITLE
meethue and ifttt

### ISSUE THREAD

**Issue by aldoushx** [mariusmotea/diyHue#248]
Hi,
The bridge is not found when creating a meethue account to use it with ifttt. 
Did anyone manage to make it work ?
Or is there another way to pair the bridge with ifttt ?

**Comment by mariusmotea** [comment]
There are not good news with meethue services, i buy and root one hue bridge to check the communication with cloud services, but it seams every device is provisioned with a key and there is a single sign on hash in every http requests that i don't know how to generate.

**Comment by cheesemarathon** [comment]
Closing this for now as support is currently impossible with what we know.
