### ISSUE TITLE
Schematic Diagram Missing for Switch

### ISSUE THREAD

**Issue by cheesemarathon** [mariusmotea/diyHue#249]
The image for the schematic for the [switch](https://github.com/mariusmotea/diyHue/wiki/9.-Sensors) circuit is missing. Can this be fixed?

**Comment by mariusmotea** [comment]
Is still present here: Images/Hue_Tap-Dimmer_switch_circuit_prototype.png
Be aware that playing with esp deep sleep mode can be very tricky. If everything is not perfect it can consume the battery very fast.

**Comment by cheesemarathon** [comment]
Ah, I hadn't found that. In that case, it's just missing from the wiki page I linked in my first post. That's easy to fix and then this can be closed.

**Comment by mariusmotea** [comment]
Fixed.
