### ISSUE TITLE
i cant seem to install the latest version

### ISSUE THREAD

**Issue by spuddud** [mariusmotea/diyHue#25]
i was following your video and i got stuch with cp huebridge/www/. i dunno how i can install this

**Comment by mariusmotea** [comment]
That was the first release of Bridge Emulator based on PHP/MySQL. Now there is a newer release based on python, so you will need only to execute a python script (and to install nmap package for lights auto discover). Please read issue #20 where i explain the setup process. There i miss the nmap package installation, so just execute ```apt install nmap```

**Comment by spuddud** [comment]
i read through that and it seams i have  all ready instaled apt install nmap here is a log
pi@raspberrypi:~/diyHue/BridgeEmulator $ sudo apt install nmap                  Reading package lists... Done
Building dependency tree
Reading state information... Done
nmap is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.
pi@raspberrypi:~/diyHue/BridgeEmulator $ sudo ./HueEmulator.py
config loaded
lights address loaded
starting ssdp...
server stopped
config saved
pi@raspberrypi:~/diyHue/BridgeEmulator $


hope this helps

**Comment by spuddud** [comment]
not too sure why it crossed out most of it though

**Comment by mariusmotea** [comment]
Remove the two .json configuration files and download again config.json from this repository (is mandatory to have some default informations and structure). lights_address.json will be automatically created when you will add new lights.

**Comment by spuddud** [comment]
but i dont have two of them
pi@raspberrypi:~/diyHue/BridgeEmulator $ ls
coap-client-linux  config.json  HueEmulator.py  lights_address.json
pi@raspberrypi:~/diyHue/BridgeEmulator $

**Comment by mariusmotea** [comment]
sudo rm config.json lights_address.json
then download again config.json file from this repo because this file is mandatory. You receive "server stopped" because something is wrong with one of these two files. Hope you don't have apache installed because will conflict when bindin on port 80. sudo apt remove apach2

**Comment by spuddud** [comment]
did sudo apt-get remove apache2 php5-mysql php5-curl nmap
 still got the problem an i also did sudo ./HueEmulator.py
but now it says
config loaded
lights address loaded
starting ssdp...
Starting httpd...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./HueEmulator.py", line 90, in scheduler_processor
    for schedule in bridge_config["schedules"].iterkeys():
KeyError: 'schedules'

^X^Cserver stopped
config saved

**Comment by mariusmotea** [comment]
you have an error in config.json, the key schedules is missing. Just delete diyHue folder and download again, then execute ```sudo ./HueEmulator.py``` and it will work. BTW you removed also nmap package that is needed.

**Comment by spuddud** [comment]
Hay it works! thanks so much btw
