### ISSUE TITLE
Motion Sensor

### ISSUE THREAD

**Issue by Purzel84** [mariusmotea/diyHue#250]
Hi, does anyone have the motion sensor in operation? I rebuilt the circuit on a breadboard. When moving the esp goes into the reboot. The HueApp does not find the motion sensor, the app all4hue already. However, "no movement" is always displayed. No matter how I dance in front of the device. The circuit reacts to the movements. I just despair a little bit about it :(

**Comment by mariusmotea** [comment]
Hi,
Start the HueEMulator3.py script with sudo and display the http request that come from the sensor. I switch to tradfri and xiaomi motions sensors long time ago and i don't use this anymore. Maybe one of my changes introduce an error here,

**Comment by Purzel84** [comment]
I just tried it and got it out of here. I have to say that I have no idea of ​​python



pi@raspberrypi:/opt/hue-emulator $ sudo python HueEmulator3.py
Traceback (most recent call last):
  File "HueEmulator3.py", line 2, in <module>
    from http.server import BaseHTTPRequestHandler, HTTPServer
ImportError: No module named http.server
pi@raspberrypi:/opt/hue-emulator $

**Comment by mariusmotea** [comment]
Run it with python3, not python2

**Comment by Purzel84** [comment]
so i only have to update python to version 3? O.O

**Comment by mariusmotea** [comment]
Stop the  hue-emulator service first to avoid network ports conflict

**Comment by Purzel84** [comment]
ok, it's getting slow thank you for your patience.

I've tried it and you first copied the section with the ip of the sensor.
after 3 minutes that is unfortunately the only status that comes from him. So it seems that he just posted the light values ​​and not the activation

`192.168.178.190 - - [02/Jun/2018 17:37:18] "GET /switch?mac=2c:3a:e8:6:8f:8&lightlevel=30720&dark=false&daylight=tr                                                  ue HTTP/1.1" 200 -
{'dark': ['false'],
 'daylight': ['true'],
 'lightlevel': ['30720'],
 'mac': ['2c:3a:e8:6:8f:8']}
`

**Comment by Purzel84** [comment]
I now taped the photosensor, that does not change anything.

**Comment by Purzel84** [comment]
`192.168.178.190 - - [02/Jun/2018 18:32:32] "GET /switch?mac=2c:3a:e8:6:8f:8&presence=false HTTP/1.1" 200 -
{'mac': ['2c:3a:e8:6:8f:8'], 'presence': ['false']}
`

`
192.168.178.190 - - [02/Jun/2018 18:29:45] "GET /switch?mac=2c:3a:e8:6:8f:8&lightlevel=20730&dark=false&daylight=false HTTP/1.1" 200 -
{'dark': ['false'],
 'daylight': ['false'],
 'lightlevel': ['20730'],
 'mac': ['2c:3a:e8:6:8f:8']}
`

**Comment by mariusmotea** [comment]
At this moment i can provide only debugging advises. First i recommend to use an older esp8266 library for arduino, maybe the new ones come with changes that made this sketch to not work.
### How is working:
 Wifi interferences trigger the PIR even if is no motion, for this reason the complexity of the sketch is high. To avoid interference the ESP will wake up from deep sleep with rf disabled, check the status of GPIO 5 pin and based on previews stored values in RTC memory it will restart again in rf mode and send what it has to report to bridge.

If you have Arduino knowledge i propose you to made this much simple by sending the light level + motion only when motion was detected. This means when ESP will wake up from deep sleep it need to mesure the light data and send it to bridge. I will create a new function to monitor the present attribute of the motion sensors and change it to false if after more than 1 minute there is no update request.

**Comment by mariusmotea** [comment]
BTW if you configured the motion sensor from hue application, to trigger the light the parameter "dark" and motion must be true. In your case i see is sending 'dark': ['false'] so in this case the light will not be turned on. 

You can debug with curl, ex:

```
curl {bridge emulator ip}/switch?mac=2c:3a:e8:6:8f:8&lightlevel=20730&dark=true&daylight=false
curl {bridge emulator ip}/switch?mac=2c:3a:e8:6:8f:8&presence=true
```

at this moment the lights will turn be turned on if previews presence flag was false

`curl {bridge emulator ip}/switch?mac=2c:3a:e8:6:8f:8&presence=false`

depending on the duration configured in hue application, the light will dim to half, and in another 30 seconds will turn off

**Comment by cheesemarathon** [comment]
Hi @Purzel84 
Did you get the motion sensor working? If so can you close this? Or let us know if you need more help!

**Comment by cheesemarathon** [comment]
I'm closing this for now. If you still need support please re-open this issue.
