### ISSUE TITLE
LED Strip Controller ESP8266 - LD382A

### ISSUE THREAD

**Issue by MarkusH1975** [mariusmotea/diyHue#252]
Hi,
this is not an issue, is a simple question.

I have an LED Strip Controller which ESP8266 based. 
This is working within the project FHEM as a [FHEM WifiLight](https://fhempi.fritz.box:8083/fhem/docs/commandref.html#WifiLight).
As the type "LD382A (FW 1.0.6+) in RGB mode" 
[Hardware @ Amazon](https://www.amazon.de/RGB-Kontroller-gesteuert-Fernbedienung-Controller/dp/B075KKCS5L/ref=pd_lpo_sbs_107_img_0?_encoding=UTF8&psc=1&refRID=J1WN3NTV017H1VBC3Y7N)

Is it possible to add such a device in the Emulator?

Thanks,
Markus

**Comment by mariusmotea** [comment]
Hi,

I believe you will need to flash the light firmware with one provided here, but only if is native esp8266 device, with no other additional pwm chip. I believe FHEM can connect to hue emulator and import the light again from there once will not be able to connect to it directly

**Comment by MarkusH1975** [comment]
@mariusmotea 
Thanks for the fast answer.
I don't like to flash the LED Strip Controller.

**Comment by mariusmotea** [comment]
I can add support for it only if the api is public and it accept http requests, otherwise the integration become complicated and impossible to do it if i don' have the device to test it.

**Comment by MarkusH1975** [comment]
@mariusmotea 
It seem to be a binary protocol you can have a look at the project: [https://github.com/budachst/ld382](https://github.com/budachst/ld382)

**Comment by mariusmotea** [comment]
i found that library while searching for LD382 and i don't find it very documented and easy to implement. Because of lack of free time and because i currently work on improving the compatibility of hue functions i will leave this opened for somebody with skills.

**Comment by cheesemarathon** [comment]
I have had a look at the linked library and it doesn't seem to provide a way to discover existing lights. This will make it challenging to implement. Therefor, I suggest that the ESP8266 controller is flashed with firmware provided already by this project in order to use it with diyHeu. If someone wishes to add support for the FHEM firmware, feel free to re-open this issue.
