### ISSUE TITLE
SSDP listener address in use

### ISSUE THREAD

**Issue by StyleTec** [mariusmotea/diyHue#254]
On systems, where ssdp listeners are already present, you can not start the emulator. Please consider adding the SO_REUSEADDR option for the ssdp socket.

**Comment by mariusmotea** [comment]
I will try to implement SO_REUSEADDR. Did not know exactly what is the parameter for shared port listening, but not i know.

**Comment by mariusmotea** [comment]
I implement SO_REUSEADDR, but in my test i did not had a second ssdp service on local host so i don't know if is a real improvement.
