### ISSUE TITLE
SSDP listener is missing packets

### ISSUE THREAD

**Issue by StyleTec** [mariusmotea/diyHue#255]
Sometimes, if timing of M-SEARCH requests is unfavorable, the listening socket will miss them and will not send his informations out to the world. In my situation this can be fixed with removing the sleep funtion.

**Comment by mariusmotea** [comment]
I believe the sleepnis good. But need to in range 0.1 - 1.0 seconds

**Comment by mariusmotea** [comment]
With the commit https://github.com/mariusmotea/diyHue/commit/65430a9bf32fe10632cfe398fc36630bfa51b126 i apply this change
