### ISSUE TITLE
Philips Hue Go not detected (ZigBee Device ID: 0x0210, LLC020)

### ISSUE THREAD

**Issue by brianmaher84** [mariusmotea/diyHue#256]
Product Name | Device ID (Type) | Model ID | Color Gamut | Hue / Friends of Hue
-- | -- | -- | -- | --
Hue Go | 0x0210 (Extended Color Light) | LLC020 | C | Yes

Extended Color light (ZigBee Device ID: 0x0210), same as Color light, but which supports additional setting of color temperature

Info taking from the list of supported devices:
https://www.developers.meethue.com/documentation/supported-lights

**Comment by brianmaher84** [comment]
It is missing from the light_types JSON var in the python file.

I tried duplicating an item and adding the Model ID but it didn't resolve the issue for me.

My bridge is up and running and apps can detect it without issues, it just cannot find the Philips Hue Go I have unfortunately.
I don't know enough about how a light is supported to resolve on my own.

**Comment by mariusmotea** [comment]
How you added this light, using deconz?

**Comment by brianmaher84** [comment]
Oh I didn't know about deconz :)
