### ISSUE TITLE
Yeelight issue

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#257]
It is impossible to turn off whole room if there is yeelight in it. I can change color or scene for the whole room but if I try to turn whole room off, only yeelight bulbs turn off but all other lights remain on. I have to turn the remaining lights off one by one.

**Comment by mariusmotea** [comment]
Can you provide script output when you turn off the light?

**Comment by mcer12** [comment]
Hi, sorry for late reply since I was on vacation. Turns out it wasn't caused by the yeelight. Interestingly enough, I removed the room from the app and re-created it again, added all the lights back and it works OK. I don't know what might've caused it but I have added and removed several lights in this room before that might've filled the json with redundant data that wasn't cleared properly when the lights were removed. I close this issue since it was somewhat resolved but still might be worth looking into. I dont have the older json so it might be very diffidult to resolve though :(
