### ISSUE TITLE
Any one have screenbloom working?

### ISSUE THREAD

**Issue by cheesemarathon** [mariusmotea/diyHue#258]
As the title states. Does anyone have screenbloom working with diyHue? When i try to connect it to the hub all I get is:
> Something went wrong with the connection, please try again...

It looks like screenbloom hasn't got the entertainment API to work yet so it cant be that.

**Comment by mariusmotea** [comment]
To see were pair process is stopping i need to see the logs of hue emulator. Stop hue-emulator service and start HueEmulator3.py process manually with sudo.

**Comment by cheesemarathon** [comment]
There don't seem to be any useful errors. All I get is the entry bellow when I activate the link button. It looks like screenbloom never even connects... Shall I open an issue with screenbloom and see if they can shed some light?
`192.168.1.102 - - [07/Jun/2018 11:53:09] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -`

**Comment by mariusmotea** [comment]
Wired, normally we must see an ssdp M-SEARCH request on the network from screenbloom and hue-emulator will reply to that one. Maybe you can find the detection method used by screenbloom by asking them. In general the hue applications use the ssdp search method and so far all applications are working fine. Another method is to check all ip's in the network for port 80/http and then try the normal pair method, this one also works. One method that is not working is by fetching an public url provided by philips, if the request come from same ip address that one hue bridge is already connected to remote services, it will return an json with serial number and private ip of the bridge. This is an easy detection method, but is working only if internet access is in place and you are using a real hue bridge.

**Comment by cheesemarathon** [comment]
Ok, so the error I had originally had has now gone and screenbloom automatically redirects me to the /manual page where I can enter the IP of my diyHue. So I'm not sure what was going on there. After that, it pairs and works perfectly. As for autodiscovery, the guy at screenbloom told me:

> [Here's the registration logic](https://github.com/kershner/screenBloom/blob/master/app/modules/registration.py#L73), definitely one of the shittiest parts of the codebase haha.
> You can see that function is passed an IP, [which is obtained via this function](https://github.com/kershner/screenBloom/blob/master/app/modules/utility.py#L33).
> I'm guessing there might be some kind of a problem there.

So I assume it's an issue with the way that he gets the IP of the hub. Is that something that can be fixed here or can I suggest an alternative method to the screenbloom author? Thanks for your help!

**Comment by mariusmotea** [comment]
```
     requests.packages.urllib3.disable_warnings()
     url = 'https://www.meethue.com/api/nupnp'
      r = requests.get(url, verify=False).json()
```
so is using the Philips cloud services (meethue.com) that works only for original Hue Bridge. Luckily there is also the manual mode.

**Comment by mariusmotea** [comment]
The good news is that today i ordered an Philips Hue Bridge that i will use to study how is communication with cloud servers, maybe i will be able to emulate the same.

**Comment by cheesemarathon** [comment]
Ah fantastic, it's amazing how much you have emulated without it! I'm sure that will help with this and maybe with the entertainment API. Good Luck, you can close this for now then and reopen it if you make any progress :-)
