### ISSUE TITLE
Complete n00b failing miserably...

### ISSUE THREAD

**Issue by aheywood89** [mariusmotea/diyHue#259]
Hey all,

I'll start by apologising profusely that i really am a n00b at all this and am probably doing something so obviously wrong that its a time waste but... I really need help...

I have installed the emulator to my Pi Zero W and have linked to my Hue bridge, I'm able to see the bridge in the Hue app and i can control the lights that already exist on the network.

I have a Wemos D1 mini and have uploaded the WS2812BHueStrip.ino to it which it seems happy to accept; but then i cant seem to see it on the Hue app. I have checked my DHCP Table but it doesn't appear.

Arduino IDE is up-to-date, the libraries have all been installed as well as the ESP8266 board management + the NeoPixel libraries. I have uninstalled the IDE + files + libraries, i've flashed the EEPROM, i've followed the other threads, i've tried // the WiFiManager and replaced it with the manual information... I just don't know what i have missed...

So its a MASSIVE ask but does a video exist on all of the installation processes or at least one that shows how to get a Wemos working on the emulated bridge?

I would appreciate any help that anyone can offer..
Regards,
Ads.

**Comment by mariusmotea** [comment]
Hi, just to be clear, after you follow the wifi manager wizard, select you network and put your wifi password the device don't show in dhcp table of your router? You have just one wemos board or more?

**Comment by cheesemarathon** [comment]
Something that may help to debug your issues:
After line 319 `void setup() {` add `Serial.begin(115200);`
Then before your Wemos starts, open the serial monitor with the baud rate set to 115200
WiFiManager will then report what it's doing in the serial monitor

**Comment by aheywood89** [comment]
Thanks for the quick reply guys ;) 

Not actually sure what i did but the Wemos finally appeared in the wifi list and it accepted the SSID/Pass. So it has finally connected...

Again really appreciate your help (told you, complete n00b issue 😄)

Ads.
