### ISSUE TITLE
Service doesn't work after easy or manual install

### ISSUE THREAD

**Issue by Lakitna** [mariusmotea/diyHue#263]
Pretty much what it says on the tin:

I've installed diyHue on my Raspberry Pi 3 model B using the easy install [described in the wiki](https://github.com/mariusmotea/diyHue/wiki/1.-Getting-started). When I try to set up my Tradfri gateway the following message appears in the syslog
```
HueEmulator3.py[19072]: sh: 0: getcwd() failed: No such file or directory
HueEmulator3.py[19072]: /bin/sh: 1: ./coap-client-linux: not found
```

Besides this problem I found a discrepancy between the install locations of easy_install and manual install, one has probably been updated while the other was forgotten.

While typing this issue some more FileNotFoundErrors appeared, I'll try the manual installation method and will report back with the results shortly.

**Edit:** Things go a lot smoother after running `HueEmulator3.py` directly. There is a GUI now (even though it has issues too, more on that elsewhere). I've changed the title blaming the service implementation instead of `coap-client-linux`.

Relevant information:
Hardware: Raspberry Pi 3 model B
OS: Debian
Python: v3.5.3
diyHue: Current master branch (cloned on 16-06-2018)

**Comment by Lakitna** [comment]
It does, now that I'm running `HueEmulator3.py` directly (via `python3 HueEmulator3.py`) things are working fine. But things don't work via the service.

**Comment by mariusmotea** [comment]
Better edit HueEmulator3.py and instead of relative path for coap client binary file, put the real path /opt/hue-emulator/coap-client-linux. In systemd file the working directory is /opt/hue-emulator, but in your case something is not working right.
