### ISSUE TITLE
Hyperion 

### ISSUE THREAD

**Issue by Purzel84** [mariusmotea/diyHue#265]
Does anyone use this system in conjunction with Hyperion ambilight? Is that even possible or only with original philips hue?

**Comment by mariusmotea** [comment]
Hi,

Find if Hyperion is using the new hue entertainment protocol, that is not implemented currently in this hue emulator. If is not using this protocol very likely it will work fine.

**Comment by Purzel84** [comment]
Ok, i will test it today.  Is there a way to create a "User id" like the api/newdeveloper Method for the original hue?     Hyperion couldnt create a id with the linkbutton Method

**Comment by mariusmotea** [comment]
Yes you can. But did you follow the documentation to enable the pairing for 30 seconds?

**Comment by juanesf** [comment]
Hello, some time could run hyperion in khadas Vim with Ubuntu on my TV with 100 leds running on Arduino nano v3 and nodemcu v3 with Wifi, before added Hue Bridge user copying in the config.json
