### ISSUE TITLE
Bridge not visible in Casambi App 

### ISSUE THREAD

**Issue by davidaday** [mariusmotea/diyHue#266]
The Casambi app (iOS, Android) is able to add local Hue bridges (with and without cloud access), but the emulated bridge isn't recognized. The diybridge log shows the GET description, but no subsequent requests. What steps should I take in troubleshooting?

**Comment by mariusmotea** [comment]
Can you post here entire log during pairing?

**Comment by mariusmotea** [comment]
I installed this application and i don't find any detection requests on ssdp. I believe it is using the cloud detecton method and this cannot be fixed.
