### ISSUE TITLE
WS2811

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#268]
Hi everyone, I'm having an issue with WS2811 strips from BTF-LIGHTING. The thing is, I have several ESP12 boards, Wemos D1 minis and one nodemcu v2. And these strips only works with NodeMCU. No matter what I do, it won't work with any other ESP I have, not even D1 mini which I consider the most reliable. I wonder what the issue might be. I tried to up the voltage of esp12 to 3.8v but it didnt help. I also have a WS2811 strip from different seller and it works OK with any esp. Has anyone experienced something like that? The faulty strips have chips labeled Worldsemi, the working strips have noname chips.

**Comment by mariusmotea** [comment]
Hi,

There are not too many reasons why this will not work will all boards, so i will write here:
- interferences on rx pin with the usb to serial adapter. Here you can use another pin on esp, even if you lose hardware support it will work ok in software mode.
- the voltage of singling is too low. WS2811 works with 5V and in general 3.3V devices provide enough voltage for WS2811, but maybe this strip is different. You can build this simple circuit made from one diode and one resistor located here http://blog.lincomatic.com/?p=1972

**Comment by mariusmotea** [comment]
I still believe option 2 may be the reason and i sugest to try that simple circuit.

**Comment by mcer12** [comment]
I will try it out maybe it will actually help thanks!

**Comment by mariusmotea** [comment]
Did you manage to fix the problem?

**Comment by mcer12** [comment]
Hi sorry for late reply. The suggested solution didn't work but I hacked my way around it. I cut a piece of my working strip and soldered it at the beginning of the not working one and it somewhat works. The small bit of the working strip works flawlessly and the rest of the strip works also, just the animation is not completely smooth. I think it skips frames while animating but I can live with that.

**Comment by mcer12** [comment]
Just for anyone who has similar issues.
This strip works for me:
https://www.aliexpress.com/item/best-price-5m-DC12V-ws2811ic-5050-RGB-SMD-individually-addressable-ws2811-led-pixels-strip/32488661808.html?spm=a2g0s.9042311.0.0.27424c4dB2KsrX
This does not:
https://www.aliexpress.com/item/5m-DC12V-Black-PCB-30-48-60-leds-m-10-16-20-ws2811-ic-meter-10/2000165819.html?spm=a2g0s.9042311.0.0.27424c4dB2KsrX

I've bought several BTF-LIGHTING strips and I dont find them very reliable even though the reviews say otherwise. This WS2811 might have some problem with timings and I bought WS2813 strip from them before and the whole strip died out withing a year probably from overheating.

**Comment by mariusmotea** [comment]
These strips are working on 12V and i believe the one that is not working for you is expecting 12v signaling. By putting first one led that works with ESP low voltage signaling and then use the output of this led that must be in 12v area you manage to solve this problem.
