### ISSUE TITLE
Hue Emulator crashes after adding Deconz Ikea remote

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#269]
I recently discoverd that my Tradfri remotes stopped working.
After a fresh setup the Hue Emulator keeps crashing after i add the Tradfri remotes.
Heres the output:

Config loaded
register new TRADFRI remote control
register new TRADFRI remote control
Traceback (most recent call last):
  File "HueEmulator3.py", line 1477, in <module>
    scanDeconz()
  File "HueEmulator3.py", line 886, in scanDeconz
    bridge_config["sensors"][new_sensor_id] = {"config": deconz_sensors[sensor]["config"], "manufacturername": deconz_sensors[sensor]["manufacturername"], "modelid": deconz_sensors[sensor]["modelid"], "name": deconz_sensors[sensor]["name"], "state": deconz_sensors[sensor]["state"], "swversion": deconz_sensors[sensor]["swversion"], "type": deconz_sensors[sensor]["type"], "uniqueid": deconz_sensors[sensor]["uniqueid"]}
KeyError: 'swversion'

Hope someone can help

**Comment by oleg2204** [comment]
Removing the Tradfri Remote with missing swversion and adding it again doesnt help :/

**Comment by mariusmotea** [comment]
I believe you need to update the firmware of that remote (sensor id 4). With tradfri gateway is easy but with deconz you will need to perform some manual steps

**Comment by oleg2204** [comment]
I dont own a tradfri gateway...  Do you have some tutorial for deconz?

**Comment by mariusmotea** [comment]
I never did it, just tried one time and i saw i already have latest firmware so i give up. I know you need to execute one python script that will download all tradfri firmwares from ikea servers, then you need to upload the firmware from deconz gui (not webgui), so for this reason you will need an environment with gui. I don't know if this was simplified with new releases.

**Comment by mariusmotea** [comment]
Better ask on deconz git page why you don't have the swversion key and if they will say that firmware is outdated ask for procedure. I have 9 or 10 tradfri remotes in my home and i remember i faced issues with one because firmware version was 1.1.xxx, but i don't remember if it was the same issue.

**Comment by oleg2204** [comment]
I got it fixed. I downloaded and ran the python script. Restarted the deconz service. Removed the Tradfri Remote and added it back again. Now both got "swversion":"1.2.214" field.

**Comment by mariusmotea** [comment]
@oleg2204 i end up with the same issue with more remotes and motions sensors while performing a factory reset to deconz. How did you manage to fix it more exactly? I pair one remote several times, every time the swversion is missing. I'm sure i have same firmware version on all so this is not the issu.
