### ISSUE TITLE
List of supported devices

### ISSUE THREAD

**Issue by mariusmotea** [mariusmotea/diyHue#27]
This is not an issue, i create this topic so the users can write what devices they where able to use with this Hue emulator to specify them in README file. For devices that are not working will be better to have separate issue opened.

**Comment by mariusmotea** [comment]
kurniawan77 write in a comment that this is working with Domoticz, so i will add this to the list.

**Comment by kurniawan77** [comment]
Works with Home Assistant. 
Scenes will not be loaded and doesn't seem to respond when calling "hue_activate_scene" service with corresponding "group_name" and "scene_name". 
Groups will be loaded when "allow_hue_groups: true" is in configuration. However it's better to create your own groups in Home Assistant self. The groups that are being loaded from the hue will only toggle in Home Assistant and doesn't get the status from the Hue bridge.
The above is an issue in Home Assistant imo and not in diyHue.
What I discovered is that when controlling a light in the light setup webui, this doesn't post it's status back to the emulated bridge, so it's not in sync then with Home Assistant (or even Domoticz). Same goes for the "start up"  configuration. It doesn't post it's status after powering up.

**Comment by erazor666** [comment]
I was on the virge of creating an issue for this, sort of. Wouldnt a Wiki of some sort be nice for this project?
I've only been using it for a few days, but i'm very impressed with it. A wiki could have howtos, wiring diagrams, supported devices, reviews. I think its worthy of having a wiki and maybe even a forum, a community is always a good thing. Depends on what aims the developer has with his project of course, i'm sure there are peope willing (including me) to document and maintain a wiki and even a forum.

**Comment by mariusmotea** [comment]
Hi,

So far i was focused just to improve the compatibility and the bridge emulation of this project, but for sure a wiki will be required. README page don't contain all the details and is already very big, so when i will have some time i will start to create the wiki (no experience with this so far). Can you tell me where you encored problems while deploying this? For me is hard to have the perspective of a new user because of the many changes added.

**Comment by erazor666** [comment]
Hello,
I do a lot of stuff with nodemcu's and such, home assistant, lots of flashing/testing etc. For me the biggest problem was the issue #47 deal. I can read code somewhat, but debugging and writing code skills are limited. So call me intermediately experienced with these kinds of things, i always get it sorted, its more about the time it takes. A Wiki would be a natural step up from a readme.md that gets crowded very fast. And a wiki can cover a lot of topics in a whole different way.
I'm loving the project so far and i have lots of applications for it in my home, i have a ton of stuff on order from Ali. 
It can have a decent WAF (wife acceptance factor) when implemented in conjunction with home assistant and some.
From my point of view it wasnt a lot of work to get it going or hard to grasp at least.

Cudos on creating a great project!

**Comment by mariusmotea** [comment]
Hi!

If is not working we will make it work. Do you have such device? i believe @Konnichy can confirm if he was able to pair the Logitech Harmony remote with this emulator.

Marius.

**Comment by Mataru** [comment]
Ah yes I found the thread started by @Konnichy. This is very close to what I want to achieve, except I do not need to control any 433 MHz devices, just my IKEA tradlos lights which seems to already be supported. I am completely new to home automation but this project seems very promising. I do not yet have a Logitech harmony as I wanted to look into the possibility of being able to use without investing in the expensive Hue system before buying one (as it is pretty expensive aswell).

**Comment by Konnichy** [comment]
Hello,

I can confirm the Logitech Harmony Hub works well with diyHue. Once both are installed/running on the same LAN, just launch the automatic device detection on the Harmony software, and diyHue is found as a Philips Hue Hub. Easy!

But with only that, no lamp will be found. You'll have to configure diyHue appropriately for that, pointing it to the lamps' IP addresses. Then the Harmony software will find them and let you associate them to buttons.

HOWEVER, I don't have any information about those IKEA lamps. Are they fully compatible with Philips Hue (RF frequency+protocol and HTTP API) ? If not (as it was in my case), you'll have to emulate Philips Hue lamps as well and find a way to make those emulated lamps send the radio frequencies. That's what I did with a small Python script which commands an RF transmitter.

**Comment by mariusmotea** [comment]
IKEA and Philips lamps use ZigBee communication protocol, in order to control them you need Raspbee module (what i'm using right now) or to use the Ikea Gateway (previously used) or original Hue Bridge. Custom wifi lights are automatically discovered if they are binding on port 80, if is binding on different port then the manual procedure used by Konnichy must be applied. ZigBee lights are also automatically added if gateway is paired.
Marius.

**Comment by jsb5151** [comment]
Marius, any plans on supporting ZigBee USB sticks such as the Nortek HUSBZB-1?

**Comment by mariusmotea** [comment]
No plans, i already invest time and money in Raspbee module and i will remain with this one for the moment.

**Comment by sjgoalie** [comment]
I'm getting mixed results with the android app Hue Pro.  I have hue lights and it seems to switch a random number when I attempt to switch a large group of them, usually missing 5-7 lights.

**Comment by Mevel** [comment]
> I'm getting mixed results with the android app Hue Pro. I have hue lights and it seems to switch a random number when I attempt to switch a large group of them, usually missing 5-7 lights.

I have 1 LED Strip (WS2812b) and assigned 6 seperate Lights to it.  When switching all of them at once (Scene), sometimes it takes very long or even misses some Lights to update. Thought it was a transition animation (delay).
One single Strip with only one Light gets update instantanious. 
Might be a seperate Topic though.

**Comment by mariusmotea** [comment]
Hi,

The problem is that both esp and original hue bridge can be overloaded by a huge number of requests. If i'm not wrong there is currently a very short delay (0.1 - 0.2 seconds) setup between requests. Solution is to increase this until the device had enough time to process the request. I will come back with more details when i will be at my computer.

**Comment by mariusmotea** [comment]
I made a commit in develop branch to send light requests one by one. Possible issue is in case one light is unreachable the others in group will wait until this will timeout, then go to next one. Current timeout is 3 seconds, it can be set to a lower value if you are sure the wifi network is running very stable.

https://github.com/mariusmotea/diyHue/raw/develop/BridgeEmulator/HueEmulator.py

**Comment by sjgoalie** [comment]
Great, I'll try it out tonight and get back to you.

**Comment by sjgoalie** [comment]
I tried that version (there were some syntax issues, specifically a lot of "sendLightRequest(light, put_dictionary **]**)" to fix.)  It didn't seem to fix the issue.  I looked into the config file to see if there was something interesting about the specific lights that were not changing (i.e. maybe they were all at the beginning/end of your list, or something like that) but there's nothing obvious.   I'll take some time to dig into the code myself, but probably wont have time until tomorrow evening to do much more than quick tests.

**Comment by mariusmotea** [comment]
I see, i made a mistake. i will update now again.

**Comment by sjgoalie** [comment]
That seems to fix it, it turns on a group of 17 lights in around 15-17 seconds.

**Comment by sjgoalie** [comment]
Ok, I think this falls under the same topic, is there a way (web page/rest call) to fake the "press the button" and make the bridge do what it needs to do (I assume it broadcasts or something).  I'm trying to pair this with Samsung Smartthings which uses in-the-house control over the hue, not external API, but it's looking for that button press event.

**Comment by sjgoalie** [comment]
Sorry for the delay, busy week.   I started a new issue for this so we can stop boring the others in this thread.    https://github.com/mariusmotea/diyHue/issues/95

**Comment by juanesf** [comment]
in android works: 
All 4 Hue, Hue Dance, Hue Halloween, Hue Hello, Sleep as Android.

computer: 
Hyperion Ambilight in amlogic s905x with Armbian from Balbes150, Homeassistant.

I have modified the WS2812BHueStrip.ino file and supports the models: HueLightStrip (LST001) and HueBulb (LCT015). I have a capture of both lights in application.

**Comment by juanesf** [comment]
I'm sorry, I've named the modified file WS2812BHueBulb.ino :-)
greetings thank you...

**Comment by mgrzyb16** [comment]
Hello Guys,
So I have the hue bridge emulator running smoothly, mobile app connected and I am looking for some wifi bulb (rgb/rgbw/rgbww) that will be compatible with that. Can you throw some link for something that will be ready to "plug and play" with that setup since my soldering station is down and I can't modify anything.
Thanks for amazing job!

**Comment by mariusmotea** [comment]
Unfortunately there are no commercial lights that come with these firmwares and i'm unaware of OTA procedure for any provider. Feican bulbs come with ESP8266 module, but you will still need to connect serial wires to flash the firmware and without  soldering station it will be hard.

**Comment by shbatm** [comment]
Wanted to share this, I plan to make one when I return home from business:
If you have access to a 3d printer, or can order printed parts, you can make a clip for programming ESP8266 chips without soldering additional connectors to the boards (you will have to solder the wires on the clip the first time).

[ESP8266 In-Circuit Programming Clip](https://www.thingiverse.com/thing:2039755)
[Original DIP Programmer (for reference pictures)](https://www.thingiverse.com/thing:708397)

**Comment by mcer12** [comment]
I don't know if this was mentioned already anywhere but there are many Sonoff devices usable with the emulator that are running esp8266. I already have working Sonoff S20 smart plug (this one is really awesome and simple to use) and Sonoff Basic running slightly modified on/off sketch.

Here is a nice list of available Sonoff devices:
https://github.com/arendst/Sonoff-MQTT-OTA-Arduino

Article about S20 socket:
http://tinkerman.cat/s20-smart-socket/

Might be worth mention in wiki since these are really handy devices.

**Comment by mariusmotea** [comment]
Sonoff S20 is very interesting product. Do you remember the gpio pin used, i just order one now?

**Comment by mcer12** [comment]
If youre ordering one and you have EU outlets in your country, pay attention to choose correct socket type. See image below.
http://dl.itead.cc/S20/S20_EU_1.jpg

If the type is not specified by the seller, it should be type E.

**Comment by mariusmotea** [comment]
Done.

**Comment by cheesemarathon** [comment]
The [LYT8266 RGBW](https://authometion.com/shop/en/home/13-lyt8266.html) bulb can be used with some slight modifications to the Generic_RGBW_Light.ino
Lines 21 to 27 need to be:
```
uint32 io_info[PWM_CHANNELS][3] = {
  // MUX, FUNC, PIN
  {PERIPHS_IO_MUX_MTDI_U,  FUNC_GPIO12, 13},
  {PERIPHS_IO_MUX_MTCK_U,  FUNC_GPIO13, 12},
  {PERIPHS_IO_MUX_MTMS_U,  FUNC_GPIO14, 14},
  {PERIPHS_IO_MUX_GPIO5_U, FUNC_GPIO5 ,  2},
};
```
This should be inserted after line 304:
```
pinMode(15, OUTPUT);
digitalWrite(15,HIGH);
````
I can create a PR if that's easier or you can make the changes yourself

**Comment by cheesemarathon** [comment]
Please create a new issue or pull request (if required) to request adding a device to the supported list. Either that or message us on Slack.

**Comment by JDF1** [comment]
Homeseer with JowiHue plugin works. Only the lights in Homeseer do not update if you change the color with the Hue app.

**Comment by taobyebye** [comment]
how can I use a philips hue bluetooth lamp ?
I can connect my smartphone with the diyHue but than i can not find the light.

**Comment by mariusmotea** [comment]
Bluetooth lamps are not supported.

**Comment by mjn138** [comment]
Anyone had any success with the https://www.brilliant.tech/home?tab=control controls?  I previously had it running using the HASS emulated hue plugin (https://github.com/hass-emulated-hue/core) but it seemed to stop working with some sort of update to the Brilliant devices in the past few weeks.  I have a workaround by syncing the Hue lights via diyHue to Smartthings, but I hate having to rely on multiple devices like that, so would be nice to have this working directly.

**Comment by bassrock** [comment]
@mjn138 I started having similar issues.
