### ISSUE TITLE
MQTT Support?

### ISSUE THREAD

**Issue by At-M** [mariusmotea/diyHue#271]
Hi :)
I've just started adding the MQTT Protocol to my DIY Smarthome, does diyHue support mqtt and if so, how? :)

I'm using Mosquitto by the way

**Comment by mariusmotea** [comment]
Hi,

I wanted to implement MQTT in the past for lights control, but in the end i give up because it required new dependencies and i wanted to keep this project as simple as possible. Also lights control are working very good with current http protocol.

**Comment by cheesemarathon** [comment]
If you want to use MQTT to control the lights, I suggest using a 3rd party hub solution such as Home Assistant. This will allow you to add the lights from the emulated bridge and control them using MQTT via the Home Assistant Hub. There is plenty of documentation on this on the Home Assistant website.
