### ISSUE TITLE
How do multiple lights on one strip work?

### ISSUE THREAD

**Issue by Wqrld** [mariusmotea/diyHue#272]
See title, in your esp ws2812B sketch there is a setting
```
#define lightsCount 4
#define pixelCount 20
```
how does this work? i can only seem to control the first 20 lights.

**Comment by mariusmotea** [comment]
Delete the existing light and perform new light search. 4 new lights will be detected. Ever light will control 5 leds (20 / 4)

**Comment by Wqrld** [comment]
Oh thanks, that's a nice feature.

**Comment by Wqrld** [comment]
My hue app can not find any thoer lights than hue strip lst001 1 and going to the light ip it only controls the first 30 leds,
```
#define lightsCount 3
#define pixelCount 30
```

**Comment by Wqrld** [comment]
/detect
shows that there are indeed 3 lights
{"hue": "strip","lights": 3,"name": "lucs strip","modelid": "LST001","mac": "86:4:da:7f:cf:5c"}

**Comment by mariusmotea** [comment]
Until you don't delete all related lights to this esp in hue emulator, on every light scan will not add the new lights but only update the ip address of the existing light with the current one detected.

**Comment by mariusmotea** [comment]
BTW you can delete the lights from hue application directly
