### ISSUE TITLE
How to discover in Hue app with NodeMCU

### ISSUE THREAD

**Issue by fietstasss** [mariusmotea/diyHue#280]
Hi all, 
I'm using the WS2812B example to drive some WS2812B's from a NodeMCU. 
The setup is working through the web interface, but won't get discovered by the Hue apps. 
How am I able to fix this? (Without a Linux pc)

Thanks in advance.

**Comment by fietstasss** [comment]
Well, i'm programming the NodeMCU with the Arduino IDE on windows, if that's what you mean? 
How does 'manually adding the lights' work? Can't seem to find anything about that

**Comment by mariusmotea** [comment]
Is not a problem to use Arduino IDE on windows. Please perform the check that i specified here #274

**Comment by fietstasss** [comment]
How should I install the 'nmap package' ? Is this a windows thing? 
I'm sorry for my lack of knowledge in this, I'm very eager on learning more about this subject! 

Thanks in advance.

**Comment by mariusmotea** [comment]
You will need also to emulate the Hue Bridge. For this the best thing is to have an RaspberryPi or something similar. There you execute the command from wiki to automatically install this application. If you have the original hue bridge it will not work with this king of light because of different protocol (zigbee vs wifi)

**Comment by fietstasss** [comment]
Ok, I've got a Raspberry Pi installed now (as described in the 'Getting started' chapter of the Wiki). 
Two questions: 
How to start the Hue service after a reboot? 
The Hue emulator is found in the Hue app, but when trying to configure it (requiring the link-button) the link-button page (http://192.168.x.xxx/hue/linkbutton) doesn't seem to work. I do get in the 'login page' where I can enter the username and password (Hue:Hue), but after pressing 'Activate', the app won't link to the Hue. 

Any ideas about this? 

Thanks in advance!

**Comment by mariusmotea** [comment]
Try to press activate button right after detection. I had same issue but if you insist it will work. Same thing happened to me with original Hue Bridge. The service must start automatically at boot, check in syslog what is the error during the startup of HueEmulator.

**Comment by cheesemarathon** [comment]
@fietstasss Has this issue been solved? Do you need more help? If everything is now working, can you close this issue?

**Comment by cheesemarathon** [comment]
@fietstasss I'm going to close this issue for now. If you still need help, feel free to re-open the issue.
