### ISSUE TITLE
Hue Entertainment not working with Ikea Light

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#282]
My Ikea RGB Bulb don't work :(
The official Hue App says that the bulbs need a update...

Can we fix that somehow?

**Comment by mariusmotea** [comment]
Hue app is aware of the capabilities of Ikea bulbs with current firmware version and don't allow them to be used in hue entertainment. You can expose a fake Philips hue bulb with newer firmware, but unfortunately Deconz don't support a high rate of requests per seconds to take full advantages of hue entertainment protocol so i limit this to one request per second. You can optimize this value until you get the maximum rate possible. To fake the Philips bulb stop hue-emulator service, backup config.json and then open and edit following ikea bulb parameters:

```
"modelid": "LCT015",
"type": "Extended color light",
 "swversion": "1.29.0_r21169"
```
save and start the hue-emulator service

In order increase or decrease the frame interval edit:
`if fremeID == 24 : #24 = every seconds, increase in case the destination device is overloaded`
in HueEmulator3.py

Currently only ESP lights with latest firmware can be used in hue entertainment at maximum frame rate.

**Comment by cheesemarathon** [comment]
@oleg2204 Can you close this? I don't think much more can be said for now.

**Comment by cheesemarathon** [comment]
If this is still an issue, feel free to re-open @oleg2204

**Comment by AntiHeld889** [comment]
Hello, is it faster with Huebridge and faked Philips hue bulb or same "high rate of requests" problem like Deconz?
