### ISSUE TITLE
WS2812 RGB Mode Change

### ISSUE THREAD

**Issue by Marmi86** [mariusmotea/diyHue#283]
Hi,
can I change the RGB (GBR,.....)mode in the sketch, because I have the problem with my ws2812 light, when I select green in the hue app the strip lights red and red when I select green
Marco

**Comment by mariusmotea** [comment]
Hi,
Yes, check the sketch, when neopixel library is initializated it is done in grb mode. Just reverse to needed color mode.

NeoPixelBus<NeoGrbFeature........

**Comment by Marmi86** [comment]
Thanks
Looks Great
