### ISSUE TITLE
WS2811_Adjustable Blue and Green Channels swapped

### ISSUE THREAD

**Issue by cheesemarathon** [mariusmotea/diyHue#285]
Hi again,
I have the WS2811_Adjustable code running and it is able to control the LEDs however, the green and blue channels are swapped. For example, when I set the light in the app to be green it will actually turn blue, and when I set it to blue it will turn green. The red channel is working correctly. How can this be fixed?

**Comment by mariusmotea** [comment]
Check #283

**Comment by cheesemarathon** [comment]
Thanks, all sorted now.
