### ISSUE TITLE
Licensing This Repo

### ISSUE THREAD

**Issue by dfloer** [mariusmotea/diyHue#288]
Hi, this project looks great, and I'd love to be able to use it, but not everything has a license. Could you add a license to it?

Certain files (almost everything in the /Lights directory) are already under the GPL license due to being derived works incorporating GPL'd code.

However, the main HueEmulator3.py file (and other associated files) don't have a license attached to them. I'd suggest the Apache License or GPLv3 for the code and CC-By-SA for the documentation and pictures.

**Comment by dfloer** [comment]
Because technically it's illegal to do so. (: And because licenses are an important and often forgotten part of open source software and documentation that's easy to fix.

**Comment by dfloer** [comment]
Any update on this? I'd love to be able to use this. If you want, I can submit a PR with suggested licensing.

**Comment by mariusmotea** [comment]
yes, please, if you can made PR will be great.

**Comment by dfloer** [comment]
Opened PR #292 with an included license. If you'd like my rationale for the licenses I chose, please let me know.

**Comment by dfloer** [comment]
Thanks for the merge. Closing this issue.
