### ISSUE TITLE
Webcontrol doesnt respond to changes

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#290]
Hi, I'm having issues with the webcontrol throught bridge IP. When I try to switch any light on/off it simply doesnt do anything.  Doesnt switch the lights. Simply put, I click the on/of slider, nothing happends.

**Comment by mariusmotea** [comment]
I had same issue, it was very strange because i don't remember to do anything to fix it and now is working. Try to delete web-ui folder from /opt/hue-entertainment and place the one from the repo.

**Comment by mcer12** [comment]
I cloned the git again, replaced the whole directory (except config.json) and it stil doesn't work... Maybe config is the cause somehow? I will create another config json when I get home so I can test it on mobile app.

**Comment by mcer12** [comment]
@mariusmotea So I replaced config.json with the default one but web control still doesn't respond. Must be some bug in it...

**Comment by mcer12** [comment]
Last update fixed the issue, thank you.
