### ISSUE TITLE
Unable to discover ESP8266 lights

### ISSUE THREAD

**Issue by poison-apple** [mariusmotea/diyHue#293]
I have previously had this setup working, but since reinstalling diyHue, I can't find my ESP8266 LED strip from within the Hue app.

I have successfully connected the Hue app to the bridge emulator, which is connected to my Hue bridge and my two Philips bulbs are working. I am able to control the LED strip from the web interface, but they can't be found from within the Hue app.

I am able to ping the lights from the emulator host, receive the detection json, and discover the host with nmap.

I'm happy to provide any information that may help solve this issue, thank you.

**Comment by mariusmotea** [comment]
Hi,

for the sake of Hue Entertainment i change the modelid. Please Flash again the ESP with latest firmware located here, or replace in HueEmulator script LST002 with LST001

```
marius@XPS-13:~$ curl 192.168.10.30/detect
{"hue": "strip","lights": 3,"name": "WS2812 Strip Pat","modelid": "LST002","mac": "ce:9:4:a6:20:a0"}
```
very likely on your curl output the modelid is LST0001

**Comment by poison-apple** [comment]
Yes, it does return LST001, so that's probably the issue. I'll try that, thanks for the quick response!

**Comment by hiramvillarreal** [comment]
Hello same problem here, I had to change branch to "develop" to skip app asking for press bridge buttom after switching branch the HUE app discover the Hub on the pi but after load the ESP8266 ino and change the LST from both HueEmulator or the .ino even swtching branch the app can not find my esp :(

**Comment by mariusmotea** [comment]
Hi, there was a big problem with https certificate that currently is solved in master branch. Just deploy the app from skratch, also reset the data on your mobile application.
