### ISSUE TITLE
Hue Emulator fails to find lights on larger than /24 subnet.

### ISSUE THREAD

**Issue by dfloer** [mariusmotea/diyHue#294]
My home network uses a /22 for various reasons, and one of them is that I've got my IoT devices on a different /24 than the raspberry pi 3 that's running the Hue emulator. I've got several ESP8266 test devices running, and the emulator can't find any of them due to only scanning the /24 it's on.

I've written a potential solution in the netmask branch of my fork at: https://github.com/dfloer/diyHue/blob/netmask/BridgeEmulator/HueEmulator3.py
However, I haven't opened a pull request because it requires a package to be installed from pypi (unless you're on a system with it packaged), `netifaces`. I chose this one because it claims to be cross platform (I tested it on Windows and Arch Linux).

**Comment by mariusmotea** [comment]
Hi,

in the past i found a way to get the subnet details from bash with no dependencies, i will check that once i will have time some time.

**Comment by dfloer** [comment]
There's ways to do it in pure Python, but they unfortunately only seem to work on Linux and I was looking at this with an eye to portability.

**Comment by mariusmotea** [comment]
Anyway this application is made to run on linux. To run it on Windows there are lot of things that need to be changed and i don't believe it worth to focus on Windows

**Comment by dfloer** [comment]
Fair. I'll update this for Linux only accordingly.

**Comment by cheesemarathon** [comment]
Has this been fixed @mariusmotea 
I understand a fix will only work on Linux

**Comment by dfloer** [comment]
I haven't had much time to look at this again, but I was having a hard time finding something as robust as this solution for systems with "strange" network configurations.

**Comment by cheesemarathon** [comment]
I'll close this for now then and add it to the Suggested Features project board so it can be worked on in the future.
