### ISSUE TITLE
Using 'Zengge' or FluxLed style lightbulbs...

### ISSUE THREAD

**Issue by triphoppingman** [mariusmotea/diyHue#295]
Hello Marius:

Thanks for the project - I am going to dive in here.   I wanted to also know if you had any plans to integrate with the 'Zengge' style bulbs.   These are wifi bulbs with a simple binary profile (https://github.com/beville/flux_led).   These bulbs are fairly widespread.   My own python code to integrate with these bulbs is found here (https://github.com/triphoppingman/rgbledcontrol.py)

regards
Bruce

**Comment by mariusmotea** [comment]
Hi,

I will take a look buy i don't promise anything. It may be hard to implement or it can require too many attempts without the bulb, until there will be a successful implementation.

**Comment by triphoppingman** [comment]
Fair enough - let me spend some time trying to get diyhue running in my environment.

**Comment by mariusmotea** [comment]
from my findings these bulbs are esp8266 based witch means the firmwares provided by me can be flashed in order to have full support of all hue capabilities (most of the bulbs don't accept transitiontime and fast rates for entertainment).

**Comment by mariusmotea** [comment]
I request the api to Flux Led and i received, but the documentations has some lack of information, i don't know if i will be able to release a version that will work.

**Comment by triphoppingman** [comment]
GitHub.com/beville/flux_led

This code is excellent and complete.   Most everyone refers to this.

**Comment by mariusmotea** [comment]
I prefer native support for optimal integration. This use udp protocol and may work with hue entertainment mode and if data flow is not smooth the cpu will be overloaded during the process of fast frames.

so far i made this:

```
        elif bridge_config["lights_address"][light]["protocol"] == "flex": #Flex bulb
            checksum = b'\x00'
            if "on" in data:
                dataByte = b'\x24' # default off
                checksum = b'\xa4'
                if data["on"]:
                    dataByte = b'\x23'
                    checksum = b'\xa3'
                sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) # UDP
                sock.sendto(b'\x71' + dataByte + '\x0F' + checksum, (bridge_config["lights_address"][light]["ip"], 48899))
            if bridge_config["lights"][light]["state"]["colormode"] == "xy":
                bri = data["bri"] if "bri" in data else bridge_config["lights"][light]["state"]["bri"]
                xy = data["xy"] if "xy" in data else bridge_config["lights"][light]["state"]["bri"]
                rgb = convert_xy(xy[0], xy[1], bri)
                checksum = hex(0x40 + rgb[0] + rgb[1] + rgb[2])[2:]
                sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) # UDP
                sock.sendto(b'\x41' + bytes(rgb[0]) + bytes(rgb[1]) + bytes(rgb[2]) + b'\x00\xf0\x0f' + checksum, (bridge_config["lights_address"][light]["ip"], 48899))
```
not tested, if you have some knowledge maybe you can test and tune.

**Comment by triphoppingman** [comment]
Yes - I will test.   I am out this weekend but will get on this next week
monday.

**Comment by mariusmotea** [comment]
I made something now i will push this in develop branch. Using dummy udp server i receive the bytes i expect.

**Comment by cheesemarathon** [comment]
@triphoppingman Are you still able to test this?

**Comment by triphoppingman** [comment]
Marius - I have not had the time.   My work schedule is v. busy at this
time.   What I can do is buy you one of these lights.

**Comment by cheesemarathon** [comment]
@triphoppingman I don't think any of us have time to test this right now o im going to close this. If and when you have time to test, please re-open this issue. If anyone else in the mean time requests it, they can open this and do the testing.

**Comment by legovaer** [comment]
I am willing to refactor this change and test it again!
