### ISSUE TITLE
Support PlatformIO

### ISSUE THREAD

**Issue by fireboy1919** [mariusmotea/diyHue#3]
Right now, you aren't in any way documenting what kind of device you're compiling with.

Since ESP8266s are fragile and prone to frying when you give them the wrong compile type, this is actually important information.

If you switch from using the Arduino UI to using PlatformIO, that information will all be included in your repository.

Then other people will be able to build your code too and ALSO, create builds for other kinds of chipsets.

**Comment by mariusmotea** [comment]
Hi,

Is first time when i hear about PlatformIO. I'm open to new ideas and i will give a try.

Thanks,
Marius.

**Comment by fireboy1919** [comment]
Take a look at the available boards:
http://docs.platformio.org/en/latest/platforms/espressif8266.html

You can also specify other options besides board type.

**Comment by mariusmotea** [comment]
This seems to be straightforward, yesterday i manage to compile and upload the code to an Wemos D1 mini connected to a strip of SK6812 leds and it work. The only change that i need to do is to move lightEngine function above loop(), with Arduino the order seems to not be a problem, with c++ it is. I will update this repo with PlatformIO projects for lights today.

Marius.

**Comment by fireboy1919** [comment]
Awesome!

**Comment by mariusmotea** [comment]
PlatformIO projects where uploaded.
