### ISSUE TITLE
HomeAsisstnant and diyHue

### ISSUE THREAD

**Issue by pickeld** [mariusmotea/diyHue#30]
is it possible to control the lights using HomAssisntant.io?
if so.. how?
thank you

**Comment by mariusmotea** [comment]
Not sure, maybe using Bridge emulator as proxy? HomAssisntant must be able to control the bridge vie hue api.

**Comment by pickeld** [comment]
bridge emulator like HABridge? 
i think MQTT implementation is needed. it will be much easier i think
what do you think?

**Comment by mariusmotea** [comment]
I made a deep analysis to switch light to MQTT, but in the end i come to conclusion that i will only make the things a little bit more complicated without any benefit.

**Comment by tbrasser** [comment]
You can just add this bridge as an official Philips Hue bridge to home-assistant, it works perfectly. No MQTT needed.

**Comment by mariusmotea** [comment]
Thank you Thomas. I will close this now.
