### ISSUE TITLE
Hue Entertainment updates all lights, regardless of if they are in the entertainment area

### ISSUE THREAD

**Issue by jdrucey** [mariusmotea/diyHue#300]
I have two split WS2812BHueStrips, one is split into three lights and is set up in an entertainment area.

And the other is split into 5 lights but not included in an entertainment area.

However, when an entertainment area is actively syncing, it is updating the states of all lights across both strips at `/api/__id__/lights`.

It isnt pushing updates to the non included lights, just incorrectly setting the local state.

This causes odd behaviour in the hue app, with non included rooms flashing like they are active, when they may not even be on.

**Comment by mariusmotea** [comment]
I will try to replicate this. Teoretically the virtual lights are isolated, but maybe here there is a bug.

**Comment by mariusmotea** [comment]
Can you provide more details, i made a simple test with one strip, i create a new entertainment area with only 2 lights from a strip with 3. Playing with Hue Sync on mac it update only the two lights, with no touch on 3rd one. When you access internal webgui the entertainment are is displayed like a new group, how many lights you see in that group? There i can see only two, exactly like i setup in Hue app.

**Comment by mariusmotea** [comment]
Video?

**Comment by jdrucey** [comment]
Brilliant idea. I've caught it perfectly on video!

So see that only the "TV" lights are in the entertainment area, but they all get turned on when i press "start light sync" (even though the kitchen lights dont physically turn on).

And you can see that all the icons change color, when it should only be the TV ones!

https://www.youtube.com/watch?v=e1NU7JJwYgk

Maybe this is linked to https://github.com/mariusmotea/diyHue/issues/299 ?

**Comment by jdrucey** [comment]
So as mentioned in https://github.com/mariusmotea/diyHue/issues/299 this seems to have magically fixed itself.

Appreciate you looking at this, and apologies for any time spent on it.
But in case someone comes across the same problem, at least there is an issue logged.

Glad i got a video so you know im not dreaming this up haha
