### ISSUE TITLE
New Inclusion Of NGINX Clashes With Existing Apache Install

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [mariusmotea/diyHue#301]
I am running DIYHue on an Ubuntu server (running lots of services) and have recently been following and contributing to the issue thread regarding the new Hue app not being able to pick up DIYHue.

A fix for this was put in place which implements NGINX which runs on port 80.

As Apache needs port 80 to do standard routing, I can only run one of the services (Hue Emulator or Apache2)

Is there a way to run the two in harmony, or is the hue app hard wired to look for the bridge (or service) on port 80?

Thanks!

**Comment by mariusmotea** [comment]
can you use nginx as primary service for routing? It is quite simple to create the forwarding rules.

Currently i use this:

```
pi@raspberrypi:/etc/nginx $ cat apiv1.conf 
# forward invalid methods (includes OPTIONS) to bridge application
error_page 405 =200 @ipbridge;

location /static/ {
        root /opt/hue-emulator/web-ui/;
        autoindex off;
}

# Proxy /api to the bridge application
location /{
    proxy_pass http://ipbridge;
}
```

you can to something like this:
```
location /api/ {
    proxy_pass http://ipbridge;
}

location /description.xml{
    proxy_pass http://ipbridge;
}

location /hue/ {
    proxy_pass http://ipbridge;
}
```
these are critical components. then depending on your needs, maybe you need to forward also /deconz/ or for tradfri /tradfri/, then add your rules for other applications like:

```
location / {
    proxy_pass http://127.0.01:8080;
}
```
this will forward all traffic that don't match previews rules to 127.0.01:8080

**Comment by mariusmotea** [comment]
check #302 if you really want to get rid of nginx (in future it will not be used)

**Comment by mariusmotea** [comment]
Nginx is not needed anymore, closing.
