### ISSUE TITLE
Color Issue red/blue

### ISSUE THREAD

**Issue by UniCizin** [mariusmotea/diyHue#307]
After the newest updates, the colors are wrong.

Green is perfect

Blue and Red are purple

**Comment by UniCizin** [comment]
okay, now its wierd ..
green is perfect
red is still purple..
and blue : 
   from green to blue -> blue is light-purple
   from red/white to blue  -> blue does not change at all

but its not persisant. sometimes blue changes to purple, sometimes it does nothing.

maybe this helps
https://pastebin.com/4M2jaysM

**Comment by mariusmotea** [comment]
I need more output to see exactly what data was send in POST request because "json.loads(self.data_string.decode('utf8'))" show me that the application tried to post an illegal json. Also Hue Entertainment don't use http api so i don't understand from were these request are coming.

**Comment by UniCizin** [comment]
okay, i tried it again..
0.27 is my PC with hue sync and entertainment mode
0.22 is my mobile phone where i used the color wheel to set colors (they are correct).

the issue is only within the entertainment mode


https://pastebin.com/dieTx4uN

**Comment by mariusmotea** [comment]
Ok, i see no errors, so the problem is only how the colors are generated, right?

**Comment by UniCizin** [comment]
the error is the output of the light

the preview in Hue Sync app shows correct blue or red ..
but the LED Strip glows purple  or does not change at all

i guess it's a calculation/calibration error?

**Comment by mariusmotea** [comment]
I made new commit in debug branch with a few print lines that show the received rgb data and computed int for yeelight. Can you perform new test and show me the output?

**Comment by UniCizin** [comment]
here you go

https://pastebin.com/qCiPDbuL

**Comment by mariusmotea** [comment]
Found one problem and fix it.

**Comment by UniCizin** [comment]
now it works great !
the colors are correct

transitions are a bit "unsmooth" though, but thats another "issue"
and as i said.. razer integration works perfect too.

**Comment by mariusmotea** [comment]
Fell free to perform optimisations to following values:

`msg = json.dumps({"id": 1, "method": "set_rgb", "params": [r * 65536 + g * 256 + r, "smooth", 100]}) + "\r\n"`

that 100 reflect the number of miliseconds of transition. I put 100ms, but as you said is not perfect, so you can tune it.

also you can increase the update frames by editing this line:

`if fremeID == 24 or fremeID == 48:`

with:

`if fremeID == 16 or fremeID == 32 or fremeID == 48:`

Yeelight bulbs are software limited on number of request and this can go below this limit with made the bulb to not respond.

Don't forget to tell us if you find better values so i will update the project.

**Comment by UniCizin** [comment]
Color issue is solved,

you can close this :)

**Comment by mariusmotea** [comment]
100ms is fine for transition?

**Comment by UniCizin** [comment]
i didn't have time to play with the transition times.. will do this soon.
