### ISSUE TITLE
Entertainment Mode - Brightness Settings

### ISSUE THREAD

**Issue by UniCizin** [mariusmotea/diyHue#309]
In Entertainment mode, the brightness setting (Hue Sync App f.e.) doenst work.

In dark scenes the lights (yeelight led strip) stays at full brightness.

**Comment by mariusmotea** [comment]
This is something wired, if you look at the debugging rgb data that i insert last tine you see small values sent by hue sync? For example full red is 255,0,0 full green 0,255,0 . Do you see values like 2,0,0 for low red level, etc and the bulb is still at full brightness?

**Comment by UniCizin** [comment]
this is the debug output for switching from red to a black image

entertainment debug: r: 254, g: 0, b: 0
entertainment debug: computed rgb int: 16646144
entertainment debug: r: 254, g: 0, b: 0
entertainment debug: computed rgb int: 16646144
entertainment debug: r: 254, g: 0, b: 0
entertainment debug: computed rgb int: 16646144
entertainment debug: r: 254, g: 0, b: 0
entertainment debug: computed rgb int: 16646144
entertainment debug: r: 15, g: 4, b: 1
entertainment debug: computed rgb int: 984065
Sending M-Search response to 192.168.0.35
192.168.0.27 - - [04/Aug/2018 16:32:30] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
entertainment debug: r: 0, g: 0, b: 0
entertainment debug: computed rgb int: 0
entertainment debug: r: 0, g: 0, b: 0
entertainment debug: computed rgb int: 0
entertainment debug: r: 0, g: 0, b: 0
entertainment debug: computed rgb int: 0
entertainment debug: r: 0, g: 0, b: 0
entertainment debug: computed rgb int: 0


the bulb doenst change the color (stays on red in this case as i switched from red)

**Comment by UniCizin** [comment]
Wegen i picture a light Red, it is indeed a light Red Light .. but a dark Red ist Always R 255 f.e.

And the bulb never switches Off (or on on First start) 

If it helps : the brigthness Slider in Hue Sync App has no function .

**Comment by mariusmotea** [comment]
ok, i made some tests and i confirm everything you said. The rgb mode despite contain the level of every color will not allow to setup the brightness. I will perform a new fix for this.

**Comment by UniCizin** [comment]
now i got a "light is not reachable" and an exception is happening

https://pastebin.com/WndEg8gu

**Comment by mariusmotea** [comment]
The POST request that generate the error has nothing to do with hue api. Searching on Google for
`/mistats/v2` i found something like:

**Comment by UniCizin** [comment]
i rebooted everything and now it runs without exception.
When i play a game with hue sync app running, the light gets dark and bright.. but no color changes anymore .

the MiStat could be an error because i tested the Phillips Hue App on my Xioami Mi

**Comment by mariusmotea** [comment]
Ok, let me check what can be the problem with the colors.

**Comment by mariusmotea** [comment]
I made new change in develop branch. Please note that i push all my local changes not only the hue entertainment part, but i don't expect to have any problems (most of them are improvements). Regarding the entertainment changes i made live test with Yeelight color bulb. I saw that 100ms is not a smooth transition and i increase this to 300ms. The method to send one time the brightness and another time the color generate in some cases almost 2 second of latency between the screen and the light so i change this to store the previews brightness and if this don't change with more than 50 (range is 1 - 255) i will not update it. For me watching some youtube clips show to be a good approach, the brightness request was send after every 5-7 color requests.

**Comment by UniCizin** [comment]
okay, now the colors AND the brightness are working.. 
but i noticed:
when you switch from blue to black -> lights go out..
and then from black to red -> light gets blue for a sec and then switches to red

i guess this is a question of the update sequence?

**Comment by mariusmotea** [comment]
Check what color is send by hue sync, the issue may be related to the position of the lights you set in entertainment room. I can fix only if hue sync send one color and the bulb is displaying different color.

**Comment by UniCizin** [comment]
okay, after making a clean install (and having problems with generating a new certificate and so on...)
i tried your newest dev build and during a game .. it just looks great :)

The brightness gets set as it should, even if the color needs some finetuning i guess (but this depends on the bulb)

you can close this issue.
