### ISSUE TITLE
Esp milight support

### ISSUE THREAD

**Issue by aycgit** [mariusmotea/diyHue#31]
Does this project support a esp8266 milight hub with the code [here](https://github.com/sidoh/esp8266_milight_hub)

**Comment by aycgit** [comment]
And/or the hue emulator shown [here](https://github.com/probonopd/ESP8266HueEmulator)

**Comment by mariusmotea** [comment]
Exactly, first you need to build that circuit and pair the bulbs with build in GUI. Theoretically bulbs need to be paired with one remote code (ex 0x1234) and one remote channel (from 1 to 4). Then open the GUI of bridge emulator and complete the form with these values that you must know.
P.S. i convert my milight rgbw bulbs to esp8266 and now transitiontime and autodiscover are working also.

**Comment by mariusmotea** [comment]
No, the emulator is the one from this repo, check the code, is a python script.

**Comment by aycgit** [comment]
i ment that according to the readme picture its this -> hub -> lights so would you still need the hub part or how does that work?

**Comment by mariusmotea** [comment]
Milight bulbs are not wifi devices. They use a custom 2.4 ghz communication protocol, so the only way to talk with them is to build that circuit that will basically act like a bridge from your local network to MiLight bulbs. For example if you will use your phone to control the lights with milight bulbs will be this way: mobile phone => Bridge Emulator => MiLight Hub => MiLight bulb

**Comment by aycgit** [comment]
Okay thanks
