### ISSUE TITLE
Entertainment Mode not working properly  (yeelight led strip)

### ISSUE THREAD

**Issue by Benutzer-0815** [mariusmotea/diyHue#310]
In entertainment mode I am able to set up an entertainment area and add my yeelight led strip. Unfortunately when I press "test" and/or use the entertainment function, the colors of the led strip don't match the colors shown on screen. 
E.g blue instead of green; also it doesn't change as fast as the screen, always keeps a color for about 5 seconds.
When using the "test sync" function in the Hue app/ Entertainment Area, the small bulb on the screen is pulsing four times while yeelight changes color only once, therefore it changes between green and violet only.

**Comment by mariusmotea** [comment]
Please test the release from develop branch because there are improvements made there. Just copy the HueEmulator3.py  over the one in /opt/hue-emulator folder and made it executable

**Comment by Benutzer-0815** [comment]
It's working very well now using the file from develop branch, thank you!
Your program together with hue sync is just what I was looking for!

By the way, do you know any way of running this on android or how to install it on mac? I don't have a raspberry pi or something similar, so I'm currently running it on ubuntu in virtualbox on mac ;)

**Comment by mariusmotea** [comment]
For python script you need python3 and few python modules (maybe only request module you need). The challenge is to compile the hue entertainment dtls server binary on mac using the info from wiki.
