### ISSUE TITLE
how to link to amazon skill(there isno bridge in your network) (V3.0.0 andriod work)the rest works okey

### ISSUE THREAD

**Issue by haymaan** [mariusmotea/diyHue#312]
hello,
ive instald diyhue on the app it's found bridge but when i click setup ask me to press link on the bridge,,,,

when i try to access my bridge http://{IP_ADRESS}/hue/linkbutton or http://{IP_ADRESS}/hue
it's ask me for user name and pww i inter Hue Hue but keep telling me inter again ...?
please any help ,i want to link milight hub to it ...?
thanks

**Comment by mariusmotea** [comment]
Hi,

is really wired because default username and password are Hue/Hue. I will try to test it, maybe there is a bug in latest version.

**Comment by mariusmotea** [comment]
Is working, what platform are you using? did you deploy it with automatic script?

`curl -s https://raw.githubusercontent.com/mariusmotea/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin`

**Comment by haymaan** [comment]
Hello,
I'm using latest version of raspbain on Pc ...

I've used the automatic link from the site... I've install it on fresh
installed version....
Shall delete it and install it all over again???? Still getting the same
problem???


And on the app is found new bridge but ask to press a button on the bridge
which can't do it?
Thanks

**Comment by haymaan** [comment]
okey friend ive delet the folder and sudo reboot it and install it
again,know i can log in ,and it's told me you have 30 sec i found the
bridge in the app but no link ,one more help please
Hue LinkButton
Username
Password
Click on Activate button to allow association for 30 sec.

You have 30 sec to connect your device

**Comment by haymaan** [comment]
what ive notis ive delet the app (android 3.1) and install the old App V1 and it's link direct,


know how to link app 3.1 android...how to add milight Hub to the bridge ..?

**Comment by haymaan** [comment]
okey ive download older version hue V3.0.0 and that find my bridge,

how to link milight hub ?
how to link to amazon skill

**Comment by mariusmotea** [comment]
I use the version 3.3 and is working fine
