### ISSUE TITLE
correct XY-RGB calculations?

### ISSUE THREAD

**Issue by andyman1222** [mariusmotea/diyHue#313]
I am currently using this function to convert the XY values from the Hue bridge emulator sent to my emulated Hue LED strips using this function found from Philips Hue documentation:

```
def convert_xy(self):
        x = self.lightstate["xy"][0] #from app
        y = self.lightstate["xy"][1] #from app
        z = 1.0 - self.lightstate["xy"][0] - self.lightstate["xy"][1]
        Y = self.lightstate["bri"]/255.000 #"bri" 0-255
        X = (Y / y) * x
        Z = (Y / y) * z
        
        r =  X * 1.656492 - Y * 0.354851 - Z * 0.255038
        g = -X * 0.707196 + Y * 1.655397 + Z * 0.036152
        b =  X * 0.051713 - Y * 0.121364 + Z * 1.011530

        r = 12.92 * r if r <= 0.0031308 else (1.0 + 0.055) * pow(r, (1.0 / 2.4)) - 0.055
        g = 12.92 * g if g <= 0.0031308 else (1.0 + 0.055) * pow(g, (1.0 / 2.4)) - 0.055
        b = 12.92 * b if b <= 0.0031308 else (1.0 + 0.055) * pow(b, (1.0 / 2.4)) - 0.055
        print(str(r) + " " + str(g) + " " + str(b))

        r = 0 if r < 0 else r
        g = 0 if g < 0 else g
        b = 0 if b < 0 else b
        self.lightstate["rgb"] =  [r*100, g*100, b*100] #output: r, g, and b with range 0-100
```

The only problem is that this equation sets my r, g, and b values beyond the maximum 100 for rpi GPIO. I've seen the equation used in i=diyHue, but it doesn't set the white color to max brightness and doesn't handle the values well when they go over 100, so the colors end up being a blend of all 3 colors instead of what it looks like in the app.

That said, is there an equation that properly calculates the RGB values from Philips Hue's irritating XY system?

**Comment by mariusmotea** [comment]
you may add new conditions at the end, ex:

```
r = 0 if r < 0 else r
g = 0 if g < 0 else g
b = 0 if b < 0 else b

r = 1 if r > 1 else r
g = 1 if g > 1 else g
b = 1 if b > 1 else b
```

**Comment by andyman1222** [comment]
Actually I think I had those previously, but there might have been a code
sync mixup. However, this still won't fix the incorrect color output, like
if I go towards pure red, the green and blue values won't be at zero, and
the color will result in more of a pink/light red rather than vivid red,
for example. I think this issue has more to do with the algorithm itself.
Any idea on how to reduce the smaller color values so it outputs the right
color? In diyHue it's algorithm just divides by the max value, but that's
not enough. I was also experimenting with some other equations, but nothing
really worked accurately.

If only Philips Hue wouldn't use their own xy color scheme...

On Aug 11, 2018 12:29 AM, "Motea Marius" <notifications@github.com> wrote:

you may add new conditions at the end, ex:

r = 0 if r < 0 else r
g = 0 if g < 0 else g
b = 0 if b < 0 else b

r = 1 if r > 1 else r
g = 1 if g > 1 else g
b = 1 if b > 1 else b

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mariusmotea/diyHue/issues/313#issuecomment-412257642>,
or mute the thread

**Comment by mariusmotea** [comment]
Every led has is own conversion formula, this is just the standard one that consider the reproduction of the 3 colors is equal. From my experience issues may happen with certain model of leds and improper pwm. For example ws2812b leds produce exactly the color selected in hue application, others not.

**Comment by cheesemarathon** [comment]
I think with the wide range of lights this project supports it would be impossible to get perfect color recreation on all lights without a conversion formula for each light. Current conversion is very good for the vast majority of lights so i'll close this issue. If you wish to suggest different formulas, can I suggest chatting in our slack group?

**Comment by andyman1222** [comment]
Yeah, I've actually been using my LEDs in conjuntion with Razer Synapse, which outputs RGB instead of XY, although I would like to suggest an RGB-based light type in diyHue that could work with devices that aren't as compatible with an XY or CT system.
