### ISSUE TITLE
Hue app won't connect

### ISSUE THREAD

**Issue by JakobGrine** [mariusmotea/diyHue#315]
I installed the latest version of diyHue. In the Hue app I had to manually enter the IP address and it found the bridge. Then I clicked on "Set up" and the app asked me to press the push-link button but I don't know which button to press or what to do.
Please help me.

**Comment by mariusmotea** [comment]
Read wiki => get started for all details

**Comment by JakobGrine** [comment]
Still not working.
When I go to /hue/linkbutton and press the "Activate" button the app still behaves the same and doesn't connect to the bridge,

**Comment by mariusmotea** [comment]
What device did you use? It has more than one interface?

`curl https://127.0.0.1/api/nouser/config -v -k` what output give?

**Comment by JakobGrine** [comment]
I'm using a NanoPi Fire 3 with a debian based operating system.
This is the output of the command:
`*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /api/nouser/config HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx 
< Date: Sun, 12 Aug 2018 18:49:10 GMT
< Content-type: application/json
< Content-Length: 227
< 
* Connection #0 to host 127.0.0.1 left intact
{"datastoreversion":70,"apiversion":"1.24.0","name":"Philips hue","bridgeid":"3ED190FFFE5DB666","swversion":"1806051111","mac":"3e:d1:90:5d:b6:66","replacesbridgeid":null,"modelid":"BSB002","starterkitid":"","factorynew":false}`

**Comment by mariusmotea** [comment]
Perform curl on https, not http. New application use https now.

**Comment by JakobGrine** [comment]
It's now working but I don't know why. Thank you for your help.
