### ISSUE TITLE
WS2811 Adjustable Entertainment Not Working

### ISSUE THREAD

**Issue by cheesemarathon** [mariusmotea/diyHue#316]
Hi
I have a few issues with the WS2811 strip code. I have it set to 3 lights each with 11 pixels. Normal control works fine but hue entertainment does nothing. I can add the lights but when trying to set them up the test functions does nothing and music or movie sync does nothing. Hue entertainment does work as I can add my generic esp8266 bulb and that works perfectly. Any suggestions as to why this is not working? Is this related to #287?

**Comment by mariusmotea** [comment]
WS2811 Adjustable was not added by me and i add entertainment udp service just to light created by me. I will try to have a look, maybe i will understand how is working and i will add the udp service for entertainment

**Comment by cheesemarathon** [comment]
It's working now, thanks
