### ISSUE TITLE
Question about hardware.

### ISSUE THREAD

**Issue by aro28** [mariusmotea/diyHue#317]
Hi All,
I've already configured GassistPi and my Google Assistant(GA) works fine. Now i'm planing to control Philips Hue lights via GA.  Currently i have Philips Bridge and bulbs. 
Before i never had experience with NodeMCU/ESP devices.

Could you please advise what kind of NodeMCU/ESP devices should i buy for this project? 
I've purchased this ESP8266 devices. Is it enough for that project?
https://www.amazon.com/gp/product/B010O1G1ES/ref=od_aui_detailpages00?ie=UTF8&psc=1

Thanks in advance!
![image](https://user-images.githubusercontent.com/25077676/44005719-d334088c-9e99-11e8-987d-7ec82ad9d410.png)

**Comment by mariusmotea** [comment]
If the size is not a problem, then is ok. I preffer wemos d1 mini because is smaller.

**Comment by aro28** [comment]
Hi,
Noted.  I ordered Wemos d1 mini. 
Thank you !!!

**Comment by Mevel** [comment]
I have exactly the same. Working nice!

**Comment by cheesemarathon** [comment]
Hey guys! As this isn't an issue so to speak, how about joining the slack channel [here](https://join.slack.com/t/diyhue/shared_invite/enQtNDE1NjgwNDE3NTQwLWNhM2YwMzg2MzYwMzBiZmQxYjZkMDljMjRjNGY2MGZiZTQyMWIwNDg4MTYwYWU0MGI4YjE3ODkzMzJjNzk0NTg) and chatting in the hardware channel!? Then close this issue?

**Comment by aro28** [comment]
Thanks! Yes. At this moment this is not an issue :-)

**Comment by cheesemarathon** [comment]
@aro28 As you opened this, you should be able to close it. The close button is next to the green comment button.
