### ISSUE TITLE
Breakout / Adapter Board - Useful?

### ISSUE THREAD

**Issue by Mevel** [mariusmotea/diyHue#318]
Hey!

I am currently designing a PCB that fits under the NodeMCU.
I want to make the PCB multipurpose so that you have one design and multiple use cases.

So far it supports:

- Input: 12V DC / 5V DC 
- Generic RGBW with 4 MOSFETs
- 433Mhz Transmitter
- WS2812B LED Strips

Any Ideas welcome!
Work in Progress, this is not the final Design. Just so you get the idea =)

![pcb1](https://user-images.githubusercontent.com/4347330/44028599-a3167426-9efa-11e8-8654-27fd2c902ff6.JPG)

PS: Mechanical Engineer here --> First PCB Design =)

**Comment by cheesemarathon** [comment]
Your MOSFETs are switching either ground or 12v connection for the Led's. If you have room I suggest adding 4 terminals for ground or 12v (whichever your not switching). This will allow you to switch 4 strings of white LEDs (instead of rgbw) with the same board a bit easier for example. Would save you trying to wire 4 ground wires to the same terminal. 

Perhaps add an adjustable voltage regulator for the power to the Led strips so that various voltage LEDs can be used?

**Comment by Mevel** [comment]
Thank you for the Feedback.

The MOSFET are Switching Ground.
Will try to fit two "lm2576" for LED Power and Microcontroller Power.
Good hint on the Screw Terminal. Will see if i can fit them between the Node and PCB.
My Goal is to have a flat bottom or at least keep the most parts "inside" the two PCB.

**Comment by mariusmotea** [comment]
If we create a new pcb will not be good to include also the module esp12-e with header for serial adapter?

**Comment by Mevel** [comment]
NodeMCU uses the esp12-e Chip.?! You want a complete new Solution (PCB) with esp12-e chip?
or just add a header for serial connection?

**Comment by mariusmotea** [comment]
Yes, nodemcu use esp-12e, if you will add the step down power supply then no other components are needed. I believe most of us have an serial adapter home and don't need direct usb port, just the serial header for initial flash. To put the esp in flash mode gpio 0 must be connected to ground during the start, so is needed to add a contact of this pin near a ground zone to facilitate flashing process.

**Comment by jamesarm97** [comment]
I have been using the following and it works pretty well for hacking. If someone is designing a new board they should look at this to get something similar.

https://goo.gl/images/x7FJJc <https://goo.gl/images/x7FJJc>
http://tinkerman.cat/closer-look-h801-led-wifi-controller/ <http://tinkerman.cat/closer-look-h801-led-wifi-controller/>

**Comment by Mevel** [comment]
Excellent! Will give it a try!

Motea Marius <notifications@github.com> schrieb am Mo., 13. Aug. 2018,
17:58:

**Comment by mcer12** [comment]
I have designed several boards for different esp8266 and esp8285 types. They are very simple and suitable only for addressable strips but they are super small and I also have designed little boxes for them to 3D print. I can post them here if that's not a problem. 

Btw is nodemcu rated for 12v input? I was under impression its only about 10v max.

**Comment by Mevel** [comment]
>Btw is nodemcu rated for 12v input? I was under impression its only about 10v max.
It is 10V Max correct!


>I have designed several boards for different esp8266 and esp8285 types.[...]

This might be a good topic over here. #319

**Comment by Mevel** [comment]
Since we now have a Slack workspace i will close this as it is offtopic.
