### ISSUE TITLE
Google WiFi integration?

### ISSUE THREAD

**Issue by FezVrasta** [mariusmotea/diyHue#329]
Google WiFi allows to pair a Philips Hue Bridge so that it then gets exposed to the on.here interface. It doesn't seem to find the Emulated Bridge, ideas?

**Comment by mariusmotea** [comment]
Very likely is using remote api for communication and require some workarouds (maybe home assistant?)

**Comment by FezVrasta** [comment]
What do you mean by Home Assistant? I have it already, what should I do with it?

**Comment by mariusmotea** [comment]
https://github.com/mariusmotea/diyHue/issues/73#issuecomment-388537104

**Comment by FezVrasta** [comment]
I see, unfortunately there's not any way to integrate Home Assistant entities into on.here :-/

**Comment by cheesemarathon** [comment]
@FezVrasta Sorry that there was no solution here. Are you happy to close this issue for now? It can be reopened if anyone feels they have found a solution.

**Comment by FezVrasta** [comment]
yes sure
