### ISSUE TITLE
Windows WSL

### ISSUE THREAD

**Issue by XfableX** [mariusmotea/diyHue#334]
I have the program running on windows sub system for linux but the app cannot connect to the WSL instance. The website and razer see it but the app is having trouble. Do i need to open ports other than 80?

Edit: It shows up in the app but i cant push the link button

**Comment by cheesemarathon** [comment]
You must forward 4 ports I believe:
80 and 443 TCP
1900 and 2100 UDP

**Comment by XfableX** [comment]
I forwarded these ports but unfortunately, the problem persists, how does the activate button send the message to the app?

**Comment by cheesemarathon** [comment]
@mariusmotea will be the one to answer this however, I recommend posting your logs. Run HueEmulator3.py manually and then try to connect. Then paste the output here.

**Comment by XfableX** [comment]
@cheesemarathon Thanks for the help anyway! I ran it manually and noticed an error at the start? ```
`d050997d8f2b`
Config loaded
starting ssdp...
start ssdp broadcast
sync with lights
Starting httpd...
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "HueEmulator3.py", line 1675, in run
    ctx.load_cert_chain(certfile="./cert.pem")
FileNotFoundError: [Errno 2] No such file or directory

10.0.0.238 - - [21/Aug/2018 18:36:12] "GET /api/nouser/config HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2018 18:36:26] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -
Sending M-Search response to 10.0.0.3
```

**Comment by cheesemarathon** [comment]
Ah looks like you don't have a cert. Can you look in the directory that contains HueEmulator3.py and see if there is a file in there called cert.pem

**Comment by XfableX** [comment]
@cheesemarathon there isnt, this was git cloned though? Where should i get this then?

**Comment by cheesemarathon** [comment]
It wont be in the git repo as it has to be generated as it depends on the hosts MAC address. The following should generate you a cert. Replace `YOUR_MAC_HERE` with the MAC address of your host. Then just run HueEmulator3.py again.
`curl "http://mariusmotea.go.ro:9002/gencert?mac=YOUR_MAC_HERE" > /opt/hue-emulator/cert.pem`

**Comment by mariusmotea** [comment]
Ensure you run the scrip from /opt/hue-emulator/ location because it is looking for certificate in the same directory. If you cannot pair it then provide the output of the command `curl https://127.0.0.1/api/nouser/config -v -k`

**Comment by XfableX** [comment]
Thanks! It connects no error!

**Comment by cheesemarathon** [comment]
No problem! Glad it's working. Have fun!
