### ISSUE TITLE
Pairing emulated bridge with phone app crashes the app

### ISSUE THREAD

**Issue by GandalfD** [mariusmotea/diyHue#336]
Whenever I launch the Phillip's Hue app on my phone, it is able to detect the emulated bridge. I was able to successfully connect the first time but then the app kept crashing when trying to pair with my lights.

I uninstalled the app and tried re-pairing, but now the app keeps crashing whenever I hit the "Activate" button on the bridge pairing page. 

I looked at the logcat on my phone to see what was making it crash and it was due to this:
`08-22 22:58:00.020 20180 20180 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.philips.lighting.hue2.HuePlayApplication: java.lang.IllegalStateException: lightPoint.lightState must not be null
`

I know you guys didn't write the app but the app only crashes when I hit activate on the emulated bridge

**Comment by mariusmotea** [comment]
What type or lights are you using. Try to start again from skratch, by erasing hue app data. Erase /opt/hue-emulator/config.json file and download again the one from this repo.

**Comment by vandalon** [comment]
I have the same issue, script is not giving any errors with the hue app, last line:

192.168.1.202 - - [24/Aug/2018 10:28:40] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:28:40] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:28:40] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:28:49] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:28:49] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:28:49] "GET /api/<api key> HTTP/1.1" 200 -

(I've removed my api key, but tested it in my browser by browsing to /api/<api key> and confirmed correct output)

**Comment by vandalon** [comment]
Also i've tested wit iconnecthue app (ios) and that crashes with the following error in diyHue:

`192.168.1.202 - - [24/Aug/2018 10:31:08] "GET /api/83a83a3876c64c33f66f33c54f1869ed/lights/new/ HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:31:08] "GET /api/83a83a3876c64c33f66f33c54f1869ed/sensors/new/ HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:31:08] "GET /api/83a83a3876c64c33f66f33c54f1869ed/ HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:31:08] "GET /api/83a83a3876c64c33f66f33c54f1869ed/lights/new/ HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:31:08] "GET /api/83a83a3876c64c33f66f33c54f1869ed/sensors/new/ HTTP/1.1" 200 -
192.168.1.202 - - [24/Aug/2018 10:31:08] "GET /api/83a83a3876c64c33f66f33c54f1869ed/capabilities/ HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.202', 54694)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 420, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 386, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
`

**Comment by mariusmotea** [comment]
You don't provide the needed information details, like when the issue strike, what type of lights/devices are you using, on what device you run the emulator.

**Comment by vandalon** [comment]
In my case it's running on a 64bits x86 ubuntu install. Using only deconz with hue/innr/ikea lights. The issue is right after install.

**Comment by mariusmotea** [comment]
In previews cases the issue was caused by deconz non standard keys in Ikea Remotes. Are you sure the issue did not strike after importing deconz lights and sensors?

**Comment by vandalon** [comment]
You are right, I did connect deconz. Is there any work around for the non standard keys in ikea remotes?

**Comment by mariusmotea** [comment]
Yes, you can fix this. First you need to find the device that cause you issues, and you can start by removing devices one by one. I don't believe the issue is with the lights but with the sensors.
 - cd /opt/hue-emulator
 - backup config.json
 - remove one sensor at a time and start emulator service with `sudo ./HueEmulator3.py`
 - once hue app will not crush anymore it means the previews removed sensor has a property that hue app don't like.
 - add that sensor back and play with uniqueid key or swversion until the hue app again will not crash.
 - add all sensors back (and fix them if necessary)

Hot to remove one sensors:
deconz sensors index is locate in config.json => deconz => sensors

for every sensor there you have also the bridgeid key that tell you the location of the sensor in main configuration.

example config:
```
       "sensors": {
            "1": {
                "bridgeid": "18",
                "modelid": "PHDL00",
                "type": "Daylight"
            },
            "10": {
                "bridgeid": "6",
                "modelid": "TRADFRI remote control",
                "opmode": "SCENE",
                "room": "1",
                "type": "ZHASwitch"
            },
            "11": {
                "bridgeid": "19",
                "modelid": "TRADFRI remote control",
                "opmode": "CT",
                "room": "1",
                "type": "ZHASwitch"
            },
```
so if you want to detele the deconz senzor "11" you need to delete this area:

```
            "11": {
                "bridgeid": "19",
                "modelid": "TRADFRI remote control",
                "opmode": "CT",
                "room": "1",
                "type": "ZHASwitch"
            }, 

```

plus the key "19" from config.json => sensors

I forget something important, stop deconz import on startup:

 ```
   "deconz": {
        "enabled": true,
        "lights": {
            "1": {
                "bridgeid": "1",
                "modelid": "TRADFRI bul
```
put "enabled": false , otherwise on every script execution the sensors will be reimported.

**Comment by mariusmotea** [comment]
I cannot help you with iconnecthue, i'm using Android. The differences between original hue bridge and emulated bridge are small, but even so there are applications that expect every bit in http output to be identical with original hue bridge.

**Comment by vandalon** [comment]
Yeah I thought something like that :)

**Comment by cheesemarathon** [comment]
@GandalfD @vandalon do you still need help with this issue?

**Comment by GandalfD** [comment]
@cheesemarathon I played around with config.json to no avail and I've given up on it for now. Maybe I'll try playing around with it once again if I get more time.

As of now though, this issue is pretty much closed for me. Thanks for helping out @mariusmotea
