### ISSUE TITLE
support for local pwm on the Raspberry pi

### ISSUE THREAD

**Issue by xjazzor** [mariusmotea/diyHue#340]
I'd love to use this in combination with sarfats pi-blaster pwm control on my raspberry pi. Is there a way to integrate the local pwm as a rgb light?

**Comment by Mevel** [comment]
we have a Slack Workspace to discuss things like feature request and support. you might want to describe what you trying to achieve over there. 


https://join.slack.com/t/diyhue/shared_invite/enQtNDE1NjgwNDE3NTQwLWNhM2YwMzg2MzYwMzBiZmQxYjZkMDljMjRjNGY2MGZiZTQyMWIwNDg4MTYwYWU0MGI4YjE3ODkzMzJjNzk0NTg

Kind regards

**Comment by cheesemarathon** [comment]
@mariusmotea Could you create a simple python example script that would use the raspberry pi GPIO to control and RGB LED? I think this would enable others to more easily create lights that were connected to the pi hosting diyHue, or any pi for that matter, as their are a couple of issues open at the moment regarding lights on the pi. It would just require some adaptation on the users part to get it to work with their hardware.

**Comment by mariusmotea** [comment]
My raspberry pi is mounted in the wall, i don't have access very easy to it. I will search for my old Raspberry Pi2, hope it still has SD card inside.

**Comment by cheesemarathon** [comment]
Thanks Marius!

**Comment by cheesemarathon** [comment]
@mariusmotea any progress here?
