### ISSUE TITLE
Hue Entertainement not working with SK6812 Led Strips

### ISSUE THREAD

**Issue by UnReal933** [mariusmotea/diyHue#344]
**Describe the bug**
Hue Entertainement don't change the lights color during the test after setting up an area. While placing them, the color is changing perfectly, but during the test, the color never change. It's the same with Windows Hue App.

**To Reproduce**
Setting a Hue Entertainement Area with SK6812 LED Strip.

**Comment by mariusmotea** [comment]
I need to perform one test home, maybe i introduce one error in last commit. Now only by looking at the code i cannot find the problem.

**Comment by UnReal933** [comment]
I will try to update it again to see if it work. I will try when I'm at home.

**Comment by UnReal933** [comment]
Okay, it seems to work correctly with the last update, thanks you !

Do you know if there is a way to extend Hue Entertainement area to more than 10 lights ?

**Comment by mariusmotea** [comment]
What limit you to max 10 lights? in lights sketch the `byte packetBuffer[64];` limit you to 16 lights, you can increase if you need more but i cannot confirm if other issues may apear.

**Comment by cheesemarathon** [comment]
For me the app enforced a limit of 10 lights per entertainment area. I don't Think that's something that the emulated bridge can change

**Comment by UnReal933** [comment]
@mariusmotea  it's what @cheesemarathon is saying. Currently Hue app is limited by 10 lights. Is there a way to bypass that ? (Maybe by setting up Hue Entertainement area and replicate it to other light with the bridge ?)

**Comment by cheesemarathon** [comment]
I'm going to close this issue is it seems to be fixed. I'll open another regarding increasing the light limit for entertainment areas.
