### ISSUE TITLE
Make it work with Hue Disco app

### ISSUE THREAD

**Issue by cooltom** [mariusmotea/diyHue#356]
**Is your feature request related to a problem? Please describe.**
Would be cool make it work with Hue Disco App. This company have lot of fun apps like Hue Halloween etc.
App is searching, find the bridge, but when u click on pair button it say connection error.

**Describe the solution you'd like**
Just be able connect my Miligt behind ESP bridge and use them with this Hue emulation bridge controling by best music driven app Hue Disco. App hueManic work fine, but doesnt have so much setup as Hue Disco.

**Additional context**
If i can I would help sniff something or do something make it work. Just dont know what and how :)

**Comment by mariusmotea** [comment]
I will check this tomorrow.

**Comment by mariusmotea** [comment]
In this case please start the script manually and provide the output during detection.

```
cd /opt/hue-emulator
sudo ./HueEmulator3.py

```
Please try to avoid any other application so we will not have unnecessary output.

**Comment by cooltom** [comment]
Apps say Locating bridges Ssdp .. than show bridge and if i click on it, ask to pusk button and if i click on Activate on https://IP/hue/linkbutton?username=&password=&action=Activate app sais Bridge connect Error!

Log from script only repeating 'sending M-search response to MOBILE PHONE IP'

starting ssdp...
start ssdp broadcast
sync with lights
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1696, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 57, in entertainmentService
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 98] Address already in use

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1683, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Sending M-Search response to 192.168.**
Sending M-Search response to 192.168.**
Sending M-Search response to 192.168.**
Sending M-Search response to 192.168.**
Sending M-Search response to 192.168.**
Sending M-Search response to 192.168.**
Sending M-Search response to 192.168.**

**Comment by mariusmotea** [comment]
Please stop first the hue-emulator service with sudo systemctl stop hue-emulator, because from output the ports were already in use

**Comment by cooltom** [comment]
ups, ok, sorry. When log say "success" thats the time when app say Bridge connect Error!

b827ebb4ccf3
Config loaded
starting ssdp...
start ssdp broadcast
sync with lights
Starting httpd...
Starting ssl httpd...
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:31] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:31] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
Sending M-Search response to 192.168.*
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:41] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:41] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
Sending M-Search response to 192.168.*
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:42] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:42] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
sync with lights
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:43] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:43] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
Sending M-Search response to 192.168.*
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:44] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:44] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
sync with lights
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:54] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:02:54] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
192.168.168.104 - - [30/Aug/2018 20:03:02] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:02] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:02] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
MOBILE IP - - [30/Aug/2018 20:03:03] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:03] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:03] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
MOBILE IP - - [30/Aug/2018 20:03:04] "POST /api HTTP/1.1" 200 -
in post method
**/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'**
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:04] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:04] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -
sync with lights
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:05] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
MOBILE IP - - [30/Aug/2018 20:03:05] "GET /description.xml HTTP/1.1" 200 -
MOBILE IP - - [30/Aug/2018 20:03:05] "GET /description.xml HTTP/1.1" 200 -
MOBILE IP - - [30/Aug/2018 20:03:05] "GET /description.xml HTTP/1.1" 200 -
MOBILE IP - - [30/Aug/2018 20:03:05] "POST /api HTTP/1.1" 200 -
in post method
**/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
[
    {
        "success": {
            "username": "a7161538be80d40b3de98dece6e91f90"
        }
    }
]**
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:05] "GET /api/web-ui-55075/groups HTTP/1.1" 200 -
DESKTOP WITH WEB GUI IP - - [30/Aug/2018 20:03:05] "GET /api/web-ui-55075/lights HTTP/1.1" 200 -

**Comment by mariusmotea** [comment]
Looks like a successful pair with ssdp detection following by http requests, and after you press the activate button it receive  the username. What the application is showing after it receive the username?

**Comment by cooltom** [comment]
**App:** Locating bridges Ssdp
**Script:**
Sending M-Search response to 192.168.*
....
repeat few times
....
....
**App:** show bridge in list (Philips hue bridge 2015) and I tap on it
**App:** waiting to push button
Script (I click activate): 
[30/Aug/2018 20:03:05] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
[30/Aug/2018 20:43:12] "GET /description.xml HTTP/1.1" 200 

few times

[30/Aug/2018 20:49:31] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'

and than 


[30/Aug/2018 20:49:44] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
[
    {
        "success": {
            "username": "a7161538be80d40b3de98dece6e91f90"
        }
    }
]

**App:** Bridge connect Error!

**Comment by cooltom** [comment]
Just clear log 

Sending M-Search response to MOBILE WITH APP IP
Sending M-Search response to MOBILE WITH APP IP
Sending M-Search response to MOBILE WITH APP IP
MOBILE WITH APP IP - - [30/Aug/2018 21:04:35] "GET /description.xml HTTP/1.1" 200 -
MOBILE WITH APP IP - - [30/Aug/2018 21:04:35] "GET /description.xml HTTP/1.1" 200 -
MOBILE WITH APP IP - - [30/Aug/2018 21:04:35] "GET /description.xml HTTP/1.1" 200 -
MOBILE WITH APP IP - - [30/Aug/2018 21:04:44] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:46] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:47] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:48] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:49] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:50] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:51] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:53] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:54] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:55] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:56] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:57] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
MOBILE WITH APP IP - - [30/Aug/2018 21:04:59] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
192.168.123.2 - - [30/Aug/2018 21:05:00] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
MOBILE WITH APP IP - - [30/Aug/2018 21:05:00] "POST /api HTTP/1.1" 200 -
in post method
/api
b'{\n  "devicetype": "HueDiscoV3#SomeDevice"\n}'
[
    {
        "success": {
            "username": "a7161538be80d40b3de98dece6e91f90"
        }
    }
]
MOBILE WITH APP IP - - [30/Aug/2018 21:05:01] "GET /description.xml HTTP/1.1" 200 -
MOBILE WITH APP IP - - [30/Aug/2018 21:05:01] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
sync with lights

APP say: Bridge connect Error!

**Comment by mariusmotea** [comment]
Wired, because logs show a normal pair process, but something application did not like. For example is possible that the application perform a check to Hue Cloud services and at this step it fail because there is no original hue bridge, etc. I believe only a debug on application side can show what is the real problem here. Because is a paid application, maybe you can ask for support to developer.

**Comment by cooltom** [comment]
Thank you, I sent them email, so lets see.

**Comment by cooltom** [comment]
Actually I tested older version of Hue Disco app (2.12|C206) and it works good. So they must added some "improvements" into new version (as they write on Google Play store: "Hello there, we have a brand new version of the app online! This should improve your Disco experience a lot!")

**Comment by cooltom** [comment]
Do you have any recommendation how to setup ESP milight bridge, to be more responsive? What parameters to play with? If the mobile app is sending light changes fast (like sound sync app or mood app) diyHue is sending it all, but I guess ESP Milight brigbe get overloaded and can not manage send all the commands to more bulbs. I was testing it wit 8 Milights and it run for while and than slow down and than freeze on last colors or change like every minute. Or operate more ESP Milight Bridges?

**Comment by mariusmotea** [comment]
In HueEmulator3.py script you will find some lines with `sleep(0.2)`. Try to increase until you will have bettter results (ex: `sleep(0.3)`)

**Comment by cooltom** [comment]
Oh cool. I will try. Thnx

**Comment by cheesemarathon** [comment]
Closing this as older version of Hue Disco App can be used.
