### ISSUE TITLE
Add Name Variable for each diyHue Light

### ISSUE THREAD

**Issue by Mevel** [mariusmotea/diyHue#357]
**Is your feature request related to a problem? Please describe.**

Keeping track of Devices getting more complex

**Describe the solution you'd like**

1. Adding `WiFi.hostname("myLight"); ` in Setup() will show a clear name in your Router. Making it easier to seperate multiple diyHue lights.
2. Adding Name to WebGui `<title>`
`http_content += "<title>Light Setup ";
    http_content += myLight;
    http_content += " </title>";`

**Describe alternatives you've considered**
--.--

**Additional context**
--.--

**Comment by mariusmotea** [comment]
Good ideas!

**Comment by mariusmotea** [comment]
Added!
