### ISSUE TITLE
Exception if i search for new lights

### ISSUE THREAD

**Issue by Animii** [mariusmotea/diyHue#366]
**Describe the bug**
If i search for new lights, i get an exception.
I tested is with the all4hue app on android, the phillips hue app on android and with Huetro on Windows.

**To Reproduce**
1. Search for new lights.

**Expected behavior**
Find new Lights(in my case esp8266).

**Logs**

> Exception happened during processing of request from ('192.168.0.38', 37379)
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
>     self.handle()
>   File "/usr/lib/python3.5/http/server.py", line 422, in handle
>     self.handle_one_request()
>   File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
>     method()
>   File "./HueEmulator3.py", line 1309, in do_POST
>     post_dictionary = json.loads(raw_json)
>   File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Additional context**
HueEmulator is installed on Raspberry pi 3.
I installed it yesterday through the script: 
> curl -s https://raw.githubusercontent.com/mariusmotea/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin

The esp8266 light is accessible through the webinterface.

**Comment by mariusmotea** [comment]
Did you put some strange characters in light name that broke json format? What is the output for http://{light ip}/detect

**Comment by Animii** [comment]
> {"hue": "strip","lights": 3,"name": "WS2812 Hue Strip","modelid": "LST002","mac": "0:0:0:0:0:0"}

**Comment by Animii** [comment]
Im no a python guys, but i tried to print the json_raw with `logging.warning(json_raw)`
i get this: 

> WARNING:root:

Looks like an empty json.

**Comment by Animii** [comment]
`logging.warning(self.data_string)`
results in:

> WARNING:root:b''

**Comment by mariusmotea** [comment]
You figured right that there is a problem with json decoding. To see the post message to this:

```
            raw_json = self.data_string.decode('utf8')
            raw_json = raw_json.replace("\t","")
            raw_json = raw_json.replace("\n","")
```

add extra line:
```
            raw_json = self.data_string.decode('utf8')
            raw_json = raw_json.replace("\t","")
            raw_json = raw_json.replace("\n","")
           print(raw_json)
```

**Comment by Animii** [comment]
`print(raw_json)` gives me just an empty line.
If raw_json is empty, it's clear that the decoding is throwing an exception.

**Comment by Animii** [comment]
`print(raw_json.path)` gives me 

> /api/a7161538be80d40b3de98dece6e91f90/lights

I don't know if this information will help you.

**Comment by mariusmotea** [comment]
Can you revert HueEmulator3.py file to a few commits back to this version?
https://github.com/mariusmotea/diyHue/blob/86c17a61abde1e4cdcab15a375be48ac7fcd78d1/BridgeEmulator/HueEmulator3.py

**Comment by mariusmotea** [comment]
> print(raw_json) gives me just an empty line.
> If raw_json is empty, it's clear that the decoding is throwing an exception

`self.data_string = b"{}" if self.headers['Content-Length'] is None else self.rfile.read(int(self.headers['Content-Length']))` this line ensure that if the application don't post any data, it will convert the message to empty json `{}`. Maybe for some reason the `self.headers['Content-Length']` is not `None`

**Comment by Animii** [comment]
`self.headers['Content-Length']` is `0`.

**Comment by mariusmotea** [comment]
ok, i will update to fix it

**Comment by mariusmotea** [comment]
I made the commit https://github.com/mariusmotea/diyHue/commit/0bf318eab6d2c8b1bda4c88610a5f72497a570cb con you test it?

**Comment by Animii** [comment]
Didn't fixed it!

**Comment by Animii** [comment]
`print((self.headers['Content-Length'] == 0)) ` prints `false` python magic?!

**Comment by mariusmotea** [comment]
`self.data_string = b"{}" if self.headers['Content-Length'] < 1 else self.rfile.read(int(self.headers['Content-Length']))`

try this? Same error?

**Comment by Animii** [comment]
`self.data_string = b"{}" if self.headers['Content-Length'] is None or self.headers['Content-Length'] == '0' else self.rfile.read(int(self.headers['Content-Length']))` fixed it.

**Comment by mariusmotea** [comment]
So the fix applied to master branch works? I don't see any differences from my commit and what you paste.

**Comment by Animii** [comment]
No master is: `self.headers['Content-Length'] == 0`
My fix is: `self.headers['Content-Length'] == '0'`
char vs number
