### ISSUE TITLE
Yeelight 2 Colours Incorrect

### ISSUE THREAD

**Issue by lamepenguins** [mariusmotea/diyHue#367]
I own a Yeelight YLDP06YL and everything is fine except the colours seem to be restricted to "warm whites". 

Setting warm white colours don't seem to be very accurate, but still good enough. Brightness and on/off works fine.

Changing to any RGB colours shows in app that the bulb is "Unreachable" and that reverts back to original colour. The bulb does not change colour at all.

**Comment by mariusmotea** [comment]
Can you check if with this version everything is working fine?

https://github.com/mariusmotea/diyHue/blob/86c17a61abde1e4cdcab15a375be48ac7fcd78d1/BridgeEmulator/HueEmulator3.py

Just replace this file (/opt/hue-emulator/HueEmulator3.py) and restart hue-emulator service

**Comment by lamepenguins** [comment]
This file worked! Thank you so much!
