### ISSUE TITLE
Change lights faster.

### ISSUE THREAD

**Issue by Animii** [mariusmotea/diyHue#368]
I have 6 lights in my setup and it can take up to 5sec to switch a scene.
This is even more annoying if you use the Hue Dico app.

This is the case because the lights are not changed in parallel.

My solution is to change line 1502 `sendLightRequest(url_pices[4], put_dictionary)`  
to
`Thread(target=sendLightRequest,args=[url_pices[4], put_dictionary]).start()`

Now the lights switch faster and you can use the Hue Dico App correctly.

**Comment by cheesemarathon** [comment]
Hi @Animii Would you be able to create a Pull Request with your suggested changes?

**Comment by cheesemarathon** [comment]
Closing as PR merged
