### ISSUE TITLE
I can not set the GPIO4

### ISSUE THREAD

**Issue by jimmyh98** [mariusmotea/diyHue#370]
First of all I would like to thank you @mariusmotea and everyone involved in this project, I have been following up for some time, and I have seen great advances, More, now I have a problem. When I set gpio4 the arduino IDE returns an error and does not compile the code. I bought a cheap light from china and wanted to replace her controller with an ESP12 so the red color is attached to gpio4. Any idea? (Sorry my English)

**Comment by mariusmotea** [comment]
What sketch are you using from lights folder? I believe there are compilation error because of local pwm library used. Try to use older esp8266 board library.

**Comment by cheesemarathon** [comment]
Also what board are you using. I know you mentioned a ESP12 but are you using a ESP12 based dev board such as a Wemos D1 Mini? I ask this because sometimes the pins numbers on the board do not match the number you need to enter in your code and this can cause errors!

**Comment by jimmyh98** [comment]
That's right @Cheesemarathon, I was trying to compile for the D1 mini because I was thinking about desoldering it and putting it in the lamp because I'm having difficulty programming a module with ftdi (I do not have much experience and the tutorials always change the schemas from one to another ) plus I thought even on a development board the pin would still be available. I'll try to compile with another library as well.
@mariusmotea I'm using RGBW. I do not know if and the board as the @Cheesemarathon mentioned or the pwm library since returning in the compilation log saw some errors like: pwm_start

**Comment by mariusmotea** [comment]
100% sure you need to replace current esp8266 board library with older one. Be aware that wifi manager last versions works only with latest esp8266 library so if errors change from pwm_start to something related to wifi manage try to downgrade also this library with 2-3 versions.

@cheesemarathon we need to get rid of pwm.c. When i develop this the internel pwm was very bad in esp8266, but maybe they did improvements and this 3rd party library is not needed anymore.

**Comment by cheesemarathon** [comment]
@jimmyh98 As you can see in the pic bellow, if you connect something to pin 7 on the Wemos, you need to refer to it as pin 13 in your code. If you are having issues with GPIO 4 try using GPIO 12, 13, 14 (pins 5,6,7 on Wemos).
![](https://escapequotes.net/wp-content/uploads/2016/02/esp8266-wemos-d1-mini-pinout.png)

@mariusmotea I'll have a crack at writing a version of Generic RGBW without pwm.c I have a light i can test it with.

**Comment by jimmyh98** [comment]
@mariusmotea I'll test when I go home (it may take a while).

@cheesemarathon I use the Generic RGB with these pins, plus I wanted to use the wemos card as programmer for the ESP12 (as I am having flash difficulty with ftdi) remove it and put in that lamp

https://imageshack.com/a/img924/7224/IxYLbB.jpg

it comes with this microcontroller, however in an attempt to flash without removing I ended up damaging a pin so I decided to remove and put a esp12. then I saw that gpio4 is bound to blue.

https://imageshack.com/a/img923/7114/zAItuU.jpg

**Comment by jimmyh98** [comment]
Okay thank you very much, it worked by returning the library from the esp8266 card to version 2.4.0rc-1. Just an information I tried to compile the Generic RGB-CCT file with the latest version of the esp8266 card library and also gave the same error with the pwm.c file. Thank you again.
