### ISSUE TITLE
Adding support for LiFX bulbs

### ISSUE THREAD

**Issue by huongminh** [mariusmotea/diyHue#374]
It would be great to have support for LiFX bulb. Any plan for that?

**Comment by mariusmotea** [comment]
I take a look on LiFX api and is not that easy to implement, for sure it require lot of test on the bulb.

**Comment by cheesemarathon** [comment]
Do you have a LiFX bulb marius?

**Comment by mariusmotea** [comment]
No, this is the reason why at this time there is no support for them.

**Comment by cheesemarathon** [comment]
Ok, i'll close this then but leave it in the suggested enhancemnets project baord so someone else can add support if they have a LiFX bulb to test with.
