### ISSUE TITLE
HAbridge (get hue items error undefined with status server error - 500)

### ISSUE THREAD

**Issue by haymaan** [mariusmotea/diyHue#377]
hello,
i've HAbridge 5.2.1 on synology ds218+,and a working Hue emulator on pi3 with milight light...i try to add it to HAbridge but get this error (get hue items error undefined with status server error - 500)i did the /linkbutton and restart nothing helps (Domoticz and other things works good with HAbidge) and Diyhue works very nice with Milight..
please help

**Comment by haymaan** [comment]
Domoticz works with UDP,but need it with Habridge please

**Comment by mariusmotea** [comment]
Prodecure to enable debug mode is ready
https://github.com/mariusmotea/diyHue/wiki/Debug

**Comment by haymaan** [comment]
ive been looking for  (modules import) line but i can find it in HueEmulator3.py

**Comment by mariusmotea** [comment]
For example add the lines after `
protocols = [yeelight]`

**Comment by cheesemarathon** [comment]
Just to confirm, add the code in between lines 31 and 33 @haymaan

**Comment by haymaan** [comment]
sorry for late reaction thanks it's works
