### ISSUE TITLE
adding 4 zone milight hub as one

### ISSUE THREAD

**Issue by haymaan** [mariusmotea/diyHue#380]
hello ,
ive 4 rgbcct Zone and they working throught the milight hub and olso diyhue is there any way i can add them like one zone ?when i make a room group on Hue app they tune on not together one by one (zone) ,when i choose all on the milight hub it's turn them on the same time ,is that olso possible with DiyHue ?
thanks

**Comment by mariusmotea** [comment]
Hi,

At this moment this future is missing from diyhue. What is the delay between the lights? Normally for all 4 lights must be 400ms.

**Comment by haymaan** [comment]
Okey , thanks for your fast answer..I've discovered them through Alexa and put them in one group, and when I ask Alexa to turn it on goes zone 2 and after 4 seconds zone 1 and 3,4...

**Comment by mariusmotea** [comment]
But if you turn on/off from webgui or from hue application it behave the same, with big delays?

**Comment by haymaan** [comment]
From the webgui olso not the same time few seconds difference

**Comment by cheesemarathon** [comment]
@mariusmotea Is this a bug or a feature request now?

**Comment by mariusmotea** [comment]
Can be a bug and for this reason i will switch milight requests to non thread mode.

**Comment by cheesemarathon** [comment]
@mariusmotea Issue fixed? Can this be closed?

**Comment by mariusmotea** [comment]
I made the change, @haymaan did you update and test it?

**Comment by haymaan** [comment]
Tomorrow will test it thanks for the update

**Comment by cheesemarathon** [comment]
@haymaan how did you get on?

**Comment by cheesemarathon** [comment]
@haymaan I'm closing this issue as it should be fixed. If your still having issues please feel free to re-open it.

**Comment by haymaan** [comment]
forgive my late testing ,was out awhile,ive update both hue on my pi3 and milight hub to lastset still can't add the four zone as one like the orginal bridge so i can controle all four zones with one On/Off?chaning color,

mabye there is an option ive seen it ,can you tell me how to add them please ..
thanks and forgive my late answer
