### ISSUE TITLE
Can't change esp8266 leds

### ISSUE THREAD

**Issue by XfableX** [mariusmotea/diyHue#384]
The bridge (raspberry pi 2), esp8266 and hue app are connected but the esp8266 (flashed with ws2812b hue strip) doesn't change colour or brightness through anything. I'm using the right pin because it plays the intro animation but am unable to proceed from there.

thanks in advance!

edited: sometimes i forget how to type

**Comment by cheesemarathon** [comment]
Make sure to turn the bulb on and off in the app, change its brightness and it's colour. I have found that sometimes it can get stuck.

**Comment by XfableX** [comment]
> Make sure to turn the bulb on and off in the app, change its brightness and it's colour. I have found that sometimes it can get stuck.

unfortunately doesn't appear to have worked, also it shows up 3 times??

**Comment by mariusmotea** [comment]
If you turn on/off from light internal webui is is working?

**Comment by Nikfinn99** [comment]
It shows up three times, because it emulates three separate devices as different sections of the ws2812 strip.
This allows for fancier animations in hue entertainment and also when selecting scenes.

**Comment by XfableX** [comment]
> It shows up three times, because it emulates three separate devices as different sections of the ws2812 strip.
> This allows for fancier animations in hue entertainment and also when selecting scenes.

Ah cool!

> If you turn on/off from light internal webui is is working?
unfortunately not


i cant wrap my around it and why it isnt working? LED count maybe? WEB requests not working?

**Comment by mariusmotea** [comment]
Do the light in the hue app is advertised as unreaclable? Can you acceess the webgui. Did you configure the network with wifi manager wizard?

**Comment by XfableX** [comment]
No, yes and yes.

Thanks guys I have to go to bed, I’ll try and solve it tomorrow!

**Comment by XfableX** [comment]
FIXED i changed the neopixelbus method because I was using gpio 2 instead of 3 and the one I used didn't work with the web requests, however, NeoEsp8266BitBang800KbpsMethod did! Thanks everyone!
