### ISSUE TITLE
Install on Virtual Maschine Entertaiment don't work

### ISSUE THREAD

**Issue by Marmi86** [mariusmotea/diyHue#386]
**Describe the bug**

i have now installed diyhue on a virtual machine (Proxmox 5.2.1) Debian Stretch OS(x86).

It goes so far except that when I create an Entertainemt area in the Hue App the message that the lamp is sync with the Hue Sync but I can not finish it and the Ambilght function does not respond

When I delete the Entertaiment area everything is back to normal

**Logs**
When I started DiyHue with sudo ./HueEmulator3.py:

Exception happened during processing of request from ('192.168.8.158', 56022)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 424, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1418, in do_PUT
    Popen(["killall", "entertainment-srv"])
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
**FileNotFoundError: [Errno 2] No such file or directory: 'killall'**

**Comment by mariusmotea** [comment]
You need killall command. Try apt install killall,or yum provides killall if you have redhat base distro.

**Comment by Marmi86** [comment]
I install killall and i can close the Hue Snyc but the Amiblight function don't work 

Log:
when i start Ambilight (hue Sync):
  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the server cert. and key... ok
  . Bind on udp://*:2100/ ... ok
  . Setting up the SSL/TLS structure... ok
  . Waiting for a remote connection ... ok
  **. Performing the SSL/TLS handshake... hello verification requested**
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok
    [ Protocol is DTLSv1.2 ]
    [ Ciphersuite is TLS-PSK-WITH-AES-128-GCM-SHA256 ]
    [ Record expansion is 37 ]
    [ Maximum fragment length is 16384 ]
  . Verifying peer X.509 certificate... ok

**Comment by Marmi86** [comment]
> Can you test in another Ubuntu 16.04 vm? I made all the tests with Ubuntu.

Yes i install a Ubuntu VM

**Comment by mariusmotea** [comment]
Server

**Comment by Marmi86** [comment]
Hello I install a fresh Ubuntu VM:

1.Killall issus fixed
2. The Entertaiment Function don't work



Log:
(Created new Entertaiment Area and starting Hue Sync App)

huebridge@Hue-Bridge:/opt/hue-emulator$ sudo ./HueEmulator3.py
192.168.8.132 - - [21/Sep/2018 18:28:08] "GET /description.xml HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:14] "GET /api/a7161538be80d40b3de98dece6e91                                                                                    f90/ HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:15] "GET /api/a7161538be80d40b3de98dece6e91                                                                                    f90/ HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:15] "PUT /api/a7161538be80d40b3de98dece6e91                                                                                    f90/groups/2 HTTP/1.1" 200 -
entertainment-srv: Kein Prozess gefunden
192.168.8.104 - - [21/Sep/2018 18:28:15] "PUT /api/a7161538be80d40b3de98dece6e91                                                                                    f90/groups/2 HTTP/1.1" 200 -

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the server cert. and key... ok
  . Bind on udp://*:2100/ ... ok
  . Setting up the SSL/TLS structure... ok
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... hello verification requested
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok
    [ Protocol is DTLSv1.2 ]
    [ Ciphersuite is TLS-PSK-WITH-AES-128-GCM-SHA256 ]
    [ Record expansion is 37 ]
    [ Maximum fragment length is 16384 ]
  . Verifying peer X.509 certificate... ok
192.168.8.104 - - [21/Sep/2018 18:28:21] "GET /api/a7161538be80d40b3de98dece6e91                                                                                    f90/ HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:28:25] "GET /description.xml HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:26] "GET /api/a7161538be80d40b3de98dece6e91                                                                                    f90/ HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:28:27] "GET /description.xml HTTP/1.1" 200 -
 connection was closed gracefully
  . Closing the connection... done
  . Waiting for a remote connection ...192.168.8.104 - - [21/Sep/2018 18:28:28]                                                                                     "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/2 HTTP/1.1" 200 -
 interrupted by SIGTERM (in net_accept())
  . Cleaning up... done.
192.168.8.132 - - [21/Sep/2018 18:28:29] "GET /description.xml HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:34] "PUT /api/a7161538be80d40b3de98dece6e91                                                                                    f90/groups/2/action HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:39] "PUT /api/a7161538be80d40b3de98dece6e91                                                                                    f90/groups/2/action HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:43] "GET /api/a7161538be80d40b3de98dece6e91                                                                                    f90/ HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:44] "PUT /api/a7161538be80d40b3de98dece6e91                                                                                    f90/groups/2/action HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:52] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/2/action HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:28:55] "GET /description.xml HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:28:57] "GET /description.xml HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:28:58] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:28:58] "GET /description.xml HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:28:59] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:28:59] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:00] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:00] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:00] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:00] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:02] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/1/action HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:02] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:02] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:04] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:06] "GET /api/a7161538be80d40b3de98dece6e91f90/capabilities HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:06] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:06] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:06] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:06] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:29:08] "GET /description.xml HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:09] "DELETE /api/a7161538be80d40b3de98dece6e91f90/groups/2 HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:09] "GET /api/a7161538be80d40b3de98dece6e91f90/capabilities HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:29:13] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:16] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:21] "PUT /api/a7161538be80d40b3de98dece6e91f90/lights/2/state HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:23] "PUT /api/a7161538be80d40b3de98dece6e91f90/lights/2/state HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:24] "PUT /api/a7161538be80d40b3de98dece6e91f90/lights/2/state HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:29:24] "GET /description.xml HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:29:25] "GET /description.xml HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:25] "PUT /api/a7161538be80d40b3de98dece6e91f90/lights/2/state HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:26] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:27] "PUT /api/a7161538be80d40b3de98dece6e91f90/lights/2/state HTTP/1.1" 200 -
192.168.8.132 - - [21/Sep/2018 18:29:27] "GET /description.xml HTTP/1.1" 200 -
192.168.8.104 - - [21/Sep/2018 18:29:28] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:28] "POST /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:29] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/2 HTTP/1.1" 200 -

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the server cert. and key... ok
  . Bind on udp://*:2100/ ... ok
  . Setting up the SSL/TLS structure... ok
  . Waiting for a remote connection ...192.168.8.158 - - [21/Sep/2018 18:29:29] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/                                  2 HTTP/1.1" 200 -
 interrupted by SIGTERM (in net_accept())
  . Cleaning up... done.
192.168.8.158 - - [21/Sep/2018 18:29:29] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:29] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.8.158 - - [21/Sep/2018 18:29:29] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/2 HTTP/1.1" 200 -

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the server cert. and key... ok
  . Bind on udp://*:2100/ ... ok
  . Setting up the SSL/TLS structure... ok
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... hello verification requested
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok
    [ Protocol is DTLSv1.2 ]
    [ Ciphersuite is TLS-PSK-WITH-AES-128-GCM-SHA256 ]
    [ Record expansion is 37 ]
    [ Maximum fragment length is 16384 ]
  . Verifying peer X.509 certificate... ok

**Comment by mariusmotea** [comment]
What type of lights are you using? Do you flash them with latest firmware? What software you use on pc for entertainment streaming?

**Comment by Marmi86** [comment]
I use Ws2812b with latest firmware and I use the official hue snyc from philips on windows pc

**Comment by Marmi86** [comment]
Hello , I update the newest light firmware and the Entertaiment function works fine 
Great 👍
