### ISSUE TITLE
WS8212 Lightstrip in single LED configuration does not work in entertainment mode

### ISSUE THREAD

**Issue by andiling** [mariusmotea/diyHue#390]
WS2812B Lightstrip has 3 segments in standard configuration.

I reconfigured the lights to 1.

#define lightsCount 1

compiled and uploaded to Nodemcu Module

The Lamp was found and can be controlled over the HueApp but in configured entertainment the Lamp
does not work!

I have found the problem in the entertainment() function in line 742!

if (lightsCount > 1)

This code was not executed in this configuration!

**Comment by cheesemarathon** [comment]
@mariusmotea I believe @andiling  is referring to the line [here](https://github.com/cheesemarathon/diyHue/blob/master/Lights/Arduino/WS2811_adjustable/WS2811_adjustable.ino#L773). However there is the else statement that should control strip if there is only one light.

**Comment by andiling** [comment]
why it works when i edit this line

if (lightsCount >= 1)

please look over the code in the else statement anything must be wrong.

**Comment by mariusmotea** [comment]
I bwlieve this is the correct fix. The light id must be 1 or higher, in currect formulanit must be 2 or higher

**Comment by cheesemarathon** [comment]
So @mariusmotea do we need to change the if statement to:
```
if (lightsCount >= 1)
```
Or do we need to add the command to update all LEDs to the else statement?

**Comment by mariusmotea** [comment]
No, i need tonadd the part that update pixels if is just one light

**Comment by andiling** [comment]
Can you make this configurable in source code? It would be the best solution!

I have a Lightstrip and the segmentet strit is great! also all lights can be used for entertainment

I have a Pyramid Light and i use it for a message in colored light segments in this lights but Entertain looks not good.

**Comment by mariusmotea** [comment]
I will solve this in a few hours

**Comment by mariusmotea** [comment]
@andiling i made a new commit, can you test it? For your Pyramid Light i recommend to use the WS8212 Ring sketch that allow you to set a custom number of leds per virtual light. In order to have entertainment service with basically just one light that control all leds you can use the entertainment function that i patch now and replace `if (lightsCount >= 1)` with `if (false)` to execute always the code part dedicated for only one light.

**Comment by andiling** [comment]
Thanks, i would test today at evening

**Comment by cheesemarathon** [comment]
@andiling have you tested this? What was the result?

**Comment by juanesf** [comment]
The correct way for a simple light is:

#define light_name "Downlight" //default light name
#define lightsCount 1
#define pixelCount 10

**Comment by juanesf** [comment]
Where pixelCount is the number of pixels and lightsCount is the number of lights to emulate

**Comment by juanesf** [comment]
I have a simple light on the ceiling with 10 pixel emulating only one and entertainment running both Armbian and OpenWrt

**Comment by andiling** [comment]
Ok, i've found time for testing and it works perfectly!
