### ISSUE TITLE
Emulator failed to start

### ISSUE THREAD

**Issue by jorisvanr** [mariusmotea/diyHue#391]
For some reason the emulator fails to start on my raspberry pi 3b. It works fine on my Pi2 (when connected to cable). Any ideas what this can be? 

When I run: _systemctl -l status hue-emulator.service_ I get the following error:

hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-09-20 12:58:57 UTC; 3h 35min ago
  Process: 2859 ExecStop=/usr/bin/curl http://127.0.0.1/save (code=exited, status=7)
  Process: 2846 ExecStart=/opt/hue-emulator/HueEmulator3.py (code=exited, status=1/FAILURE)
 Main PID: 2846 (code=exited, status=1/FAILURE)

Sep 20 12:58:57 raspberrypi systemd[1]: hue-emulator.service: Service hold-off time over, scheduling restart.
Sep 20 12:58:57 raspberrypi systemd[1]: Stopped Hue Emulator Service.
Sep 20 12:58:57 raspberrypi systemd[1]: hue-emulator.service: Start request repeated too quickly.
Sep 20 12:58:57 raspberrypi systemd[1]: Failed to start Hue Emulator Service.
Sep 20 12:58:57 raspberrypi systemd[1]: hue-emulator.service: Unit entered failed state.
Sep 20 12:58:57 raspberrypi systemd[1]: hue-emulator.service: Failed with result 'exit-code'.

**Comment by mariusmotea** [comment]
This output don't help. Start the script manually with the steps from [here](https://github.com/mariusmotea/diyHue/wiki/Debug). You can ignore step 3. My feeling is that another service is using the ports required for hue emulator.

**Comment by jorisvanr** [comment]
Hmm I tried that but I get an error when saving the file: 

""HueEmulator3.py" E212: Cannot open file for writing"

**Comment by cheesemarathon** [comment]
Edit the file with sudo:
`sudo nano HueEmulator3.py`

**Comment by jorisvanr** [comment]
This is being returned: 

2018-09-20 18:35:19,100 - root - DEBUG - b827eb1d5699
2018-09-20 18:35:19,106 - root - DEBUG - Config loaded
2018-09-20 18:35:19,137 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1
2018-09-20 18:35:19,142 - requests.packages.urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/config HTTP/1.1" 200 220
Traceback (most recent call last):
  File "./HueEmulator3.py", line 1593, in <module>
    scanDeconz()
  File "./HueEmulator3.py", line 921, in scanDeconz
    bridge_config["deconz"]["websocketport"] = deconz_config["websocketport"]
KeyError: 'websocketport'

**Comment by mariusmotea** [comment]
You activate deconz and now it cannot connect to it. You have an workaround, disable decons in config.json deconz=>enable switch to false

**Comment by jorisvanr** [comment]
Yes! This did the trick. 
I don't have sensors right now but I ordered a zigbee one. Can I use this now that Deconz is disabled?

**Comment by mariusmotea** [comment]
You can pair the diyhue with Deconz even if you don't have the sensors yet. What sensors you order?

**Comment by jorisvanr** [comment]
I ordered [This one](https://nl.aliexpress.com/item/Nieuwe-Bijgewerkte-Xiaomi-Aqara-Human-Body-Sensor-Smart-Lichaam-Beweging-Bewegingssensor-Zigbee-Verbinding-Mihome-App-Via/32863707345.html?spm=a2g0s.9042311.0.0.516e4c4dcqNnwu) . I am planning to buy ether the [Module](https://www.amazon.de/dp/B00E6300DO) or the [Usb Stick](https://www.amazon.com/NEW-gateway-compact-certified-operating/dp/B01FDWOIHK). Which one do you recommend? 

I must say I was a bit  surprised in the price of the modules 😨. But I could not find cheaper alternatives from China.

**Comment by mariusmotea** [comment]
i'm using the module now with RaspberryPi3, but at some point i was planned to create one vm and to pass the usb stick to that vm. With the module this can be done only if you convert it with one usb-serial adapter. For Xiaomi motion sensors be aware that are two versions, one contain also the light level sensor. Both will work with diyhue, but the one that don't have the light sensor will relay on internal light level sensor based on python astral library that calculate the sunset and sunrise. Your link looks to be the one with light sensor.
