### ISSUE TITLE
Do i need a real bridge for philips hue bulbs?

### ISSUE THREAD

**Issue by XfableX** [mariusmotea/diyHue#392]
I have a diyhue setup with an es8266 strip but want to use official bulbs for my room, is this feasible?

**Comment by Mevel** [comment]
Original hue lights, need official bridge. How ever, you can pair them with hue emulator.

**Comment by XfableX** [comment]
original? as in have they been super-ceded or are you talking about official ones

**Comment by Mevel** [comment]
I understood you want to use genuine Philips Hue Bulbs in combination with DiyHue

**Comment by cheesemarathon** [comment]
Currently, the only way to use genuine phillips hue bulbs with this project is via a genuine phillips hue bridge. So to answer your question in the title, yes, you do. Instructions on importing hue bulbs into diyHue can be found [here](https://github.com/mariusmotea/diyHue/wiki/Hue-Bridge-Lights)
