### ISSUE TITLE
Real Hue bridge and lightbulbs with razer synapse

### ISSUE THREAD

**Issue by XfableX** [mariusmotea/diyHue#393]
I have synced the lights from the real hue to diy hue but am unable to sync synapse with them, it just stays the previous colour

EDIT: Normal changing of the room works its just syncing with synapse

**Comment by cheesemarathon** [comment]
Hi @XfableX 
So are you saying that you want to control real Phillips Hue lights via diyHue with Razer Synapse? But it's not working?

**Comment by XfableX** [comment]
> Hi @XfableX
> So are you saying that you want to control real Phillips Hue lights via diyHue with Razer Synapse? But it's not working?

yeah and i have no clue why it won't work

**Comment by cheesemarathon** [comment]
Hmm hard for me to debug as i don't have colour Philips bulbs. Can you try and setup the sync and post the logs when the bulbs don't change colour. Also have you tried the hue sync desktop app with your real hue bulbs? https://www2.meethue.com/en-gb/entertainment/hue-sync
It may just be a bug in razer synapse.

**Comment by cheesemarathon** [comment]
Closing this as nothing has happened here in a while. Please reopen if you still need support @XfableX
