### ISSUE TITLE
Wiki improvement

### ISSUE THREAD

**Issue by philharmonie** [mariusmotea/diyHue#397]
I am very awkward in this topic, but I want to face the challenge. I want to build my own diyhue.
I suggest a wiki improvement:
I'm very new to the topic and after reading the whole wiki, I don't know what I need to get a LED strip working with wifi. Which stip, which controller, which power supply, how to connect.
I know, this repo is about the diyHue software itself, but it would be very helpful for beginners to have some hints or products and this will bring more users to the project, as well.

**Comment by Mevel** [comment]
we are working on a FAQ and improving the Wiki.

meanwhile you can ask for help at Slack [here](https://slackinvite.squishedmooo.com/)

very friendly and quick at troubleshooting

**Comment by mariusmotea** [comment]
I agree that some knowledges are required to build this, but are very general and can be found on lot of websites.  Strips that are working are specified, controller is in all cases ESP8266 (ESP8285 is the same only with 1MB flash built in), power supply depends on number of leds, 5V with 5A is enough for 300 leds, both the strip and ESP module work on 5V (ESP work with 3.3v but all modules contain a step down regulator 5V -> 3.3V). The strip has a data in pin that need to be connected to RX pin of the ESP. Thats all.
