### ISSUE TITLE
I need some help - RasPi 2model b. 1x hue light strip

### ISSUE THREAD

**Issue by Kimzer** [mariusmotea/diyHue#40]
So i bought the 2meter light strip and an extension of 1 meter.
Installed the software on the PI and downloaded the app to my phone. 
I was able to connect to the bridge but after that the app just crashes on my phone.
Am i missing something? Could you possible give a step by step for my setup?

**Comment by Kimzer** [comment]
Sending M Search response
192.168.1.42 - - [22/Aug/2017 12:13:09] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.42 - - [22/Aug/2017 12:13:09] "GET /api/470a0c52e89555f73b11904c84af61924c487816 HTTP/1.1" 200 -

This happens when the app dies

**Comment by mariusmotea** [comment]
Please check issue #20 to see if you miss something. There you will find all steps to a working solution.

**Comment by mariusmotea** [comment]
Close this if you fix the problem, or provide your config file to troubleshooting.
