### ISSUE TITLE
Capabilities timezones response is different than the Hue API

### ISSUE THREAD

**Issue by Thomas-Vos** [mariusmotea/diyHue#400]
The response for `/capabilities` is different than the Hue Bridge. The official Hue API returns an object `timezones`, with a nested array called `values`. The diyHue API just returns an array called `timezones`.

Request URL: `/api/USERNAME/capabilities`

Official Hue API response:
```
{
	"lights": {
		...
	},
	...
	"timezones": {
		"values": [
			"CET",
			"CST6CDT",
			"EET"
			...
		]
	}
}
```
diyHue API response:
```
{
	"lights": {
		...
	},
	...
	"timezones": [
		"CET",
		"CST6CDT",
		"EET"
		...
	]
}
```

Is this expected behaviour? Maybe it is better to return the same response as the Hue API, because apps written for the Hue API expect the response to be just like the official API. It isn't very difficult for me to support this difference in an app I'm creating, but I was just wondering why this is different.

**Comment by cheesemarathon** [comment]
I agree, output should match official hue api as close as we can. If your able, create a PR. If not I'm sure @mariusmotea will take a look at this and fix it.

**Comment by mariusmotea** [comment]
I will perform similar check on my hue bridge. If confirmed i will update fix this.

**Comment by mariusmotea** [comment]
Ahh, i forget about it. I will test this weekend on my real bridge.

**Comment by mariusmotea** [comment]
I test now and the bug is legit, i will update the default config. The script will require a fix for existing users

**Comment by mariusmotea** [comment]
Fix for current configurations is now in place.
