### ISSUE TITLE
Hue linkbutton not working

### ISSUE THREAD

**Issue by Haapavuo** [mariusmotea/diyHue#402]
**Description**
When I navigate to http://192.168.1.XX/hue/linkbutton, I am asked for the username & password. After I entered Hue and Hue, the site gives me an empty response (HTTP error). None of the external applications recognize the button as pressed.

How am I supposed to "press the link button"?

**To Reproduce**
1. Go to http://192.168.1.XX/hue/linkbutton
2. Enter Hue / Hue (username & password).
3. See error

**Expected behavior**
Link button should be in pressed state now and apps should recognize it.

**Comment by Haapavuo** [comment]
OSMC on Raspberry Pi 3. I think it used to work before (around half a year since I have last added the diy bridge to any app, on the same device and OS).

**Comment by Haapavuo** [comment]
I forgot to mention that I am using the latest diyHue host (upgraded using easy_install script).

ERR_EMPTY_RESPONSE when I navigate to the linkbutton site.

**Comment by mariusmotea** [comment]
Exactly. Better remove /opt/hue-emulator and execute again easyinstall script. If you have issues try to wipe hue application data on your phone.

**Comment by Haapavuo** [comment]
Re-installing diyHue host helped for this issue but I am still having problems where applications on my desktop PC do not find the diy bridge at all. My PC is on ethernet but the Raspberry Pi host is using WLAN. Both are connected to the same router but still no luck.

Anyway, that is a totally separate issue and I will try to figure it out if I have time later.

I close this issue since it has been solved.

**Comment by mariusmotea** [comment]
What app do you use on pc? If is hue sync just stop the sync service from phone hue app and then it will detect and pair.
