### ISSUE TITLE
Wrong gateway selection on non Class C networks

### ISSUE THREAD

**Issue by adyanth** [mariusmotea/diyHue#403]
In the code, there is a section to find gateway as 
`bridge_config["config"]["gateway"] = ip_pices[0] + "." +  ip_pices[1] + "." + ip_pices[2] + ".1"`

Which essentially assumes the gateway IP as *.1. But the problem arises when the network is not a class C.
I have which is a Class A network with device IP 10.3.14.15 and gateway 10.0.0.1 which makes it impossible to add lights after discovered by the Hue app. 
IMHO it is better to find the gateway by looking at the default routes rather than assuming a limited /24 network.

**Comment by cheesemarathon** [comment]
@adyanth Any suggestions for a fix? @mariusmotea Any ideas for a fix also? A quick google turned up [this](https://stackoverflow.com/a/6556951)!

**Comment by mariusmotea** [comment]
i gave a better idea on how to get the default gateway. I will add this to futures list.

**Comment by dfloer** [comment]
I think we need more robust networking here, I think we may need to pull in another dependency like I did for the discovery code I wrote in my fork and referenced in #294 .

**Comment by juanesf** [comment]
Will serve? 


ip a s|sed -ne '/127.0.0.1/!{s/^[ \t]*inet[ \t]*\([0-9.]\+\)\/.*$/\1/p}'

**Comment by adyanth** [comment]
> @adyanth Any suggestions for a fix? @mariusmotea Any ideas for a fix also? A quick google turned up [this](https://stackoverflow.com/a/6556951)!

This StackOverflow solution with python should work well. 
Or for reliability, [the next answer](https://stackoverflow.com/a/24026579) using netifaces would be good.

**Comment by cheesemarathon** [comment]
Closing this issue but adding it to the project board for future development. Please feel free to continue discussing solutions here or on slack
