### ISSUE TITLE
Current Android Hue App 3.6.1 does not link anymore

### ISSUE THREAD

**Issue by maberle** [mariusmotea/diyHue#404]
**Description**

With the current version 3.6.1 (6438) of the original Phlips Hue App linking to the bridge does not work anymore. Linking with the All4Hue app works fine but I assume, Philips changed something in the linking protocol.

In the log output no /api POST request is available, so maybe the connection will be tried with SSL and the certificate is not accepted? I even generated a new certificate since the old one was expired (It had only a lifetime of one month).

**To Reproduce**

1. Start the Hue App
2. Add Hue Bridge
3. Search the diyhue server
4. Connect
5. Call with the browser /hue/linkbutton?action=Activate
6. Timeout

**Logs**

192.168.0.72 - - [07/Oct/2018 11:08:43] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.0.22 - - [07/Oct/2018 11:08:49] "GET /hue/linkbutton?action=Activate HTTP/1.1" 401 -
192.168.0.22 - - [07/Oct/2018 11:08:51] "GET /hue/linkbutton?action=Activate HTTP/1.1" 200 -
192.168.0.22 - - [07/Oct/2018 11:08:52] code 404, message not found
192.168.0.22 - - [07/Oct/2018 11:08:52] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.72 - - [07/Oct/2018 11:16:55] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.0.22 - - [07/Oct/2018 11:17:41] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -

**Comment by hdhdu** [comment]
Hey there,
you mean Android App Version 3.6.1, right? Or ist 1.6.1 a different App?
I have installed everything last friday from scratch and it works fine. I had no Problems connecting to diyhue bridge. Using Android Hue App Version 3.6.1.

**Comment by maberle** [comment]
Hi,
yes i meant the Android app 3.6.1, it was a spelling mistake. I tried again with a clean installation (osmc with a Raspberry Pi 2) without success.

**Comment by mariusmotea** [comment]
On my phone i was able to pair on same hue app version. Try to reinstall the hue app.

**Comment by maberle** [comment]
The problem occures only, if the original Philips hue bridge was already paired with the app and diyhue will be added as second one. Pairing diyhue as first brigde works well.
