### ISSUE TITLE
Exception during MiLight state detection

### ISSUE THREAD

**Issue by maberle** [mariusmotea/diyHue#405]
**Environment**

diyhue with Philips hue bridge and esp-milight bridge 1.8.3 (nodemcuv2)

**Exception in syncWithLights()**

Okt 08 18:53:15 osmc HueEmulator3.py[17892]: ERROR:root:light 1 is unreachable
Okt 08 18:53:15 osmc HueEmulator3.py[17892]: Traceback (most recent call last):
Okt 08 18:53:15 osmc HueEmulator3.py[17892]:   File "/opt/hue-emulator/HueEmulator3.py", line 745, in syncWithLights
Okt 08 18:53:15 osmc HueEmulator3.py[17892]:     bridge_config["lights"][light]["state"]["xy"] = convert_rgb_xy(light_data["color"]["r"], light_data["color"]["g"], light_data["color"]["b"])
Okt 08 18:53:15 osmc HueEmulator3.py[17892]: KeyError: 'r'

**Configuration in esp-milight hub**
{"state":"OFF","status":"OFF","brightness":252,"level":99,"hue":31,"saturation":43,"color":{},"bulb_mode":"color"}

**Solution**
It seems to be possible to have a MiLight configuration, that contains "bulb_mode" and "color" but the color data r/g/b itself is missing. "hue" is available. The code should be prepared for this case.

**Comment by mariusmotea** [comment]
This is a bug in milight hub because the color key is empty now. `"color":{}`
I made new commit now to switch from rgb mode to hs mode. Please test it because i cannot perform any tests. To upgrade you can run the easy update script or simply replace HueEmulator3.py file from master this repo.

**Comment by maberle** [comment]
Excellent, the exception is gone. What a fast response!

Anyway the rgb code should not be removed from my point of view, since that configuration occurs also. Here are the configurations from my three MiLight groups:

**hue**
{"state":"ON","status":"ON","brightness":252,"level":99,"hue":31,"saturation":43,"color":{},"bulb_mode":"color"}

**rgb**
{"state":"ON","status":"ON","brightness":255,"level":100,"kelvin":100,"color_temp":370,"bulb_mode":"white","color":{"r":255,"g":255,"b":255}}

{"state":"ON","status":"ON","brightness":230,"level":90,"kelvin":98,"color_temp":366,"bulb_mode":"white","color":{"r":255,"g":255,"b":255}}

**Comment by mariusmotea** [comment]
It can happen to not have the hue and sat value while the bulb is in color mode?

**Comment by maberle** [comment]
No, I saw the bulp mode in my configuration (white) too late and was also afraid, that removing of the existing code could have negative effects to other valid configurations.

**Comment by cheesemarathon** [comment]
@shivasiddharth it looks like you have fixed this in your fork. Can you create a PR, it looks like your fork has alot of fixes and improvements.

**Comment by shivasiddharth** [comment]
@cheesemarathon I have strip down portions of the master to make it work with the Google Assistant Project. The reason, my integration would work is because, i have a separate json file for colors.

**Comment by cheesemarathon** [comment]
Ah I see @shivasiddharth thanks anyway! Is this fixed anyway @mariusmotea?

**Comment by mariusmotea** [comment]
This was fixed with recent commits.
