### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by thetemplar** [mariusmotea/diyHue#408]
**Describe the bug**

```
sudo /opt/hue-emulator/HueEmulator3.py
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 1605, in <module>
    updateConfig()
  File "/opt/hue-emulator/HueEmulator3.py", line 64, in updateConfig
    bridge_config["deconz"]["sensors"]["modelid"] = bridge_config["sensors"][bridge_config["deconz"]["sensors"][sensor]["bridgeid"]]["modelid"]
TypeError: string indices must be integers
```

**To Reproduce**
Using the lastest git version, on startup I get an exception.
I am using deconz, since then I encountered some problems.

**Comment by mariusmotea** [comment]
Please comment in HueEmulator3.py file the line `updateConfig()` located at the bottom of the script. This issue is with deconz, it is not providing "modelid" key for all devices right away. It need some time to fetch them. If you provide the config.json file i believe i can fix it for you.

**Comment by thetemplar** [comment]
Ok I fixed the config myself, ty :) Too bad I have to use deconz as a middleman between raspbee and diyhue
