### ISSUE TITLE
Latest iOS Hue App discovers bridge but requests button press

### ISSUE THREAD

**Issue by Riveloper** [mariusmotea/diyHue#409]
**Describe the bug**
The application sees the new bridge but requests that the button on the hub be pressed. There is no method I could find to simulate this action.

**To Reproduce**
1. Install
2. Open App and Search for Bridge
3. Try to connect

**Expected behavior**
Auto accept or ability to simulate button press on Hub.

**Comment by Mevel** [comment]
Hey. Have you tried this?

http://{ip of Hueemulator}/hue/linkbutton

username: Hue
pw: Hue

**Comment by iGodPhil** [comment]
Same issu here. Its the same with the app hue entertainment for mac or windows.
The activate button does nothing.

**Comment by iGodPhil** [comment]
But 3rd party apps can connect to the bridge.

**Comment by mariusmotea** [comment]
if you reinstall the hue emulator but did not preserve the previews certificate it will require to wipe the mobile phone application in order to pair again.

**Comment by iGodPhil** [comment]
I will try it. But how can i remove the hue-emulator?

**Comment by iGodPhil** [comment]
Hä? What i have to do now?

I dont understand  this part:

if you reinstall the hue emulator but did not preserve the previews certificate it will require to wipe the mobile phone application in order to pair again.

**Comment by cheesemarathon** [comment]
@iGodPhil Are you still having issues? If so can you open a new issue explaining whats going wrong for you. This issue has been answered. Head to `http://{ip of Hueemulator}/hue/linkbutton` to press the link button. This is explained in the wiki [here](https://github.com/mariusmotea/diyHue/wiki/Getting-started#pairing-diyhue-with-the-hue-app)

**Comment by iGodPhil** [comment]
No thanks. I will change to the original Philips system.
