### ISSUE TITLE
UPnp feature missing?

### ISSUE THREAD

**Issue by adyanth** [mariusmotea/diyHue#411]
Any chance the Hue Bridge actually uses UPnP along with the private API to find devices?
As mentioned [here](https://developers.meethue.com/content/wwwmeethuecomapinupnp) and [here](https://github.com/mariusmotea/diyHue/issues/1#issuecomment-427633195)
If so, then can you implement UPnP for this so that Alexa and the rest can use the meethue account?
[This](https://developers.meethue.com/content/cant-find-bridge-nupnp) may help.

_Originally posted by @adyanth in https://github.com/mariusmotea/diyHue/issues/1#issuecomment-427633195_

**Comment by mariusmotea** [comment]
Unfortunately Philips keep this closed and my investigation show private cloud is based on unique device authentication hash. If the hash is not registered in Philips database then device is not allowed to send any request to cloud servers. What i can do is to provide same json output from hue emulator service and with proper static dns in router devices can get the device details. The bad thing is that https is used and without philips certificate key the ssl will fail. Not sure how many devices perform ssh verification.

**Comment by adyanth** [comment]
Ohh, so no UPnP at all?
Implementing this would have made this complete. I hope Philips allows third-party developers with the API.

**Comment by mariusmotea** [comment]
> Ohh, so no UPnP at all?

There is SSDP service incorporated that is UPnP based and works fine. This is used by most of applications to detect the hue bridges.

**Comment by adyanth** [comment]
Yeah, that works.

**Comment by shbatm** [comment]
For those of us that have a physical Hue bridge also, is it possible to
clone the hash from the bridge? It would only work for people with a
bridge, but is it even a possibility?

**Comment by cheesemarathon** [comment]
@shbatm Potentially, but it would require hardware modifications to the hub to get root access to it. Not easy for an average user. Also we run the risk of pissing off Phillips at which point they could ban certain hashes from working or even try to shut down this project. I don't think it is worth the risk for such a small function that can be worked around in most cases.
