### ISSUE TITLE
Real Hue Bridge with raspberry behaves like a Hue Bulb

### ISSUE THREAD

**Issue by alelucc** [mariusmotea/diyHue#413]
Hi,
I'm searching a way to implement in a raspberry pi as a Hue Bulb that is visible by a real Hue Bridge and control via the Hue app a light that is phisically controlled by the raspberry.
I only found the way to implement a virtual bridge, not a virtual light controlled by a real Bridge.

**Comment by mariusmotea** [comment]
If you are very good in coding you can buy a cheap zigbee module and program it to expose data on serial port to raspberry pi.
