### ISSUE TITLE
Philips Hue app crashing on setup

### ISSUE THREAD

**Issue by Lukvaiks** [mariusmotea/diyHue#415]
Hey, after taking multiple attempts to make the bridge, i finally did it. But there is another problem. I'm trying to add 2 simple philips hue warm white bulbs. But when i add them, it crashes the app instantly and never works. Reinstalling app didn't fix this problem either. I read other comments to delete config file and replace with a new one. I did it. But after i set up my lights, it started to crash again. At this point i have no idea what to do. Also here's my config.json file

`{
    "alarm_config": {
        "mail_from": "your_email@gmail.com",
        "mail_password": "",
        "mail_recipients": [
            "first_recipient@mail.com",
            "second_recipient@mail.com"
        ],
        "mail_subject": "HUE ALARM TRIGGERED!",
        "mail_username": "",
        "smtp_port": 465,
        "smtp_server": "smtp.gmail.com"
    },
    "capabilities": {
        "groups": {
            "available": 64
        },
        "lights": {
            "available": 63
        },
        "resourcelinks": {
            "available": 64
        },
        "rules": {
            "actions": {
                "available": 400
            },
            "available": 200,
            "conditions": {
                "available": 400
            }
        },
        "scenes": {
            "available": 200,
            "lightstates": {
                "available": 2048
            }
        },
        "schedules": {
            "available": 100
        },
        "sensors": {
            "available": 63,
            "clip": {
                "available": 63
            },
            "zgp": {
                "available": 63
            },
            "zll": {
                "available": 63
            }
        },
        "timezones": [
            "CET",
            "CST6CDT",
            "EET",
            "EST",
            "EST5EDT",
            "HST",
            "MET",
            "MST",
            "MST7MDT",
            "PST8PDT",
            "WET",
            "Africa/Abidjan",
            "Africa/Accra",
            "Africa/Addis_Ababa",
            "Africa/Algiers",
            "Africa/Asmara",
            "Africa/Bamako",
            "Africa/Bangui",
            "Africa/Banjul",
            "Africa/Bissau",
            "Africa/Blantyre",
            "Africa/Brazzaville",
            "Africa/Bujumbura",
            "Africa/Cairo",
            "Africa/Casablanca",
            "Africa/Ceuta",
            "Africa/Conakry",
            "Africa/Dakar",
            "Africa/Dar_es_Salaam",
            "Africa/Djibouti",
            "Africa/Douala",
            "Africa/El_Aaiun",
            "Africa/Freetown",
            "Africa/Gaborone",
            "Africa/Harare",
            "Africa/Johannesburg",
            "Africa/Juba",
            "Africa/Kampala",
            "Africa/Khartoum",
            "Africa/Kigali",
            "Africa/Kinshasa",
            "Africa/Lagos",
            "Africa/Libreville",
            "Africa/Lome",
            "Africa/Luanda",
            "Africa/Lubumbashi",
            "Africa/Lusaka",
            "Africa/Malabo",
            "Africa/Maputo",
            "Africa/Maseru",
            "Africa/Mbabane",
            "Africa/Mogadishu",
            "Africa/Monrovia",
            "Africa/Nairobi",
            "Africa/Ndjamena",
            "Africa/Niamey",
            "Africa/Nouakchott",
            "Africa/Ouagadougou",
            "Africa/Porto-Novo",
            "Africa/Sao_Tome",
            "Africa/Tripoli",
            "Africa/Tunis",
            "Africa/Windhoek",
            "America/Adak",
            "America/Anchorage",
            "America/Anguilla",
            "America/Antigua",
            "America/Araguaina",
            "America/Aruba",
            "America/Asuncion",
            "America/Atikokan",
            "America/Bahia",
            "America/Bahia_Banderas",
            "America/Barbados",
            "America/Belem",
            "America/Belize",
            "America/Blanc-Sablon",
            "America/Boa_Vista",
            "America/Bogota",
            "America/Boise",
            "America/Cambridge_Bay",
            "America/Campo_Grande",
            "America/Cancun",
            "America/Caracas",
            "America/Cayenne",
            "America/Cayman",
            "America/Chicago",
            "America/Chihuahua",
            "America/Costa_Rica",
            "America/Creston",
            "America/Cuiaba",
            "America/Curacao",
            "America/Danmarkshavn",
            "America/Dawson",
            "America/Dawson_Creek",
            "America/Denver",
            "America/Detroit",
            "America/Dominica",
            "America/Edmonton",
            "America/Eirunepe",
            "America/El_Salvador",
            "America/Fort_Nelson",
            "America/Fortaleza",
            "America/Glace_Bay",
            "America/Godthab",
            "America/Goose_Bay",
            "America/Grand_Turk",
            "America/Grenada",
            "America/Guadeloupe",
            "America/Guatemala",
            "America/Guayaquil",
            "America/Guyana",
            "America/Halifax",
            "America/Havana",
            "America/Hermosillo",
            "America/Inuvik",
            "America/Iqaluit",
            "America/Jamaica",
            "America/Juneau",
            "America/Kralendijk",
            "America/La_Paz",
            "America/Lima",
            "America/Los_Angeles",
            "America/Lower_Princes",
            "America/Maceio",
            "America/Managua",
            "America/Manaus",
            "America/Marigot",
            "America/Martinique",
            "America/Matamoros",
            "America/Mazatlan",
            "America/Menominee",
            "America/Merida",
            "America/Metlakatla",
            "America/Mexico_City",
            "America/Miquelon",
            "America/Moncton",
            "America/Monterrey",
            "America/Montevideo",
            "America/Montserrat",
            "America/Nassau",
            "America/New_York",
            "America/Nipigon",
            "America/Nome",
            "America/Noronha",
            "America/Ojinaga",
            "America/Panama",
            "America/Pangnirtung",
            "America/Paramaribo",
            "America/Phoenix",
            "America/Port-au-Prince",
            "America/Port_of_Spain",
            "America/Porto_Velho",
            "America/Puerto_Rico",
            "America/Punta_Arenas",
            "America/Rainy_River",
            "America/Rankin_Inlet",
            "America/Recife",
            "America/Regina",
            "America/Resolute",
            "America/Rio_Branco",
            "America/Santarem",
            "America/Santiago",
            "America/Santo_Domingo",
            "America/Sao_Paulo",
            "America/Scoresbysund",
            "America/Sitka",
            "America/St_Barthelemy",
            "America/St_Johns",
            "America/St_Kitts",
            "America/St_Lucia",
            "America/St_Thomas",
            "America/St_Vincent",
            "America/Swift_Current",
            "America/Tegucigalpa",
            "America/Thule",
            "America/Thunder_Bay",
            "America/Tijuana",
            "America/Toronto",
            "America/Tortola",
            "America/Vancouver",
            "America/Whitehorse",
            "America/Winnipeg",
            "America/Yakutat",
            "America/Yellowknife",
            "America/Argentina/Buenos_Aires",
            "America/Argentina/Catamarca",
            "America/Argentina/Cordoba",
            "America/Argentina/Jujuy",
            "America/Argentina/La_Rioja",
            "America/Argentina/Mendoza",
            "America/Argentina/Rio_Gallegos",
            "America/Argentina/Salta",
            "America/Argentina/San_Juan",
            "America/Argentina/San_Luis",
            "America/Argentina/Tucuman",
            "America/Argentina/Ushuaia",
            "America/Indiana/Indianapolis",
            "America/Indiana/Knox",
            "America/Indiana/Marengo",
            "America/Indiana/Petersburg",
            "America/Indiana/Tell_City",
            "America/Indiana/Vevay",
            "America/Indiana/Vincennes",
            "America/Indiana/Winamac",
            "America/Kentucky/Louisville",
            "America/Kentucky/Monticello",
            "America/North_Dakota/Beulah",
            "America/North_Dakota/Center",
            "America/North_Dakota/New_Salem",
            "Antarctica/Casey",
            "Antarctica/Davis",
            "Antarctica/DumontDUrville",
            "Antarctica/Macquarie",
            "Antarctica/Mawson",
            "Antarctica/McMurdo",
            "Antarctica/Palmer",
            "Antarctica/Rothera",
            "Antarctica/Syowa",
            "Antarctica/Troll",
            "Antarctica/Vostok",
            "Arctic/Longyearbyen",
            "Asia/Aden",
            "Asia/Almaty",
            "Asia/Amman",
            "Asia/Anadyr",
            "Asia/Aqtau",
            "Asia/Aqtobe",
            "Asia/Ashgabat",
            "Asia/Atyrau",
            "Asia/Baghdad",
            "Asia/Bahrain",
            "Asia/Baku",
            "Asia/Bangkok",
            "Asia/Barnaul",
            "Asia/Beirut",
            "Asia/Bishkek",
            "Asia/Brunei",
            "Asia/Chita",
            "Asia/Choibalsan",
            "Asia/Colombo",
            "Asia/Damascus",
            "Asia/Dhaka",
            "Asia/Dili",
            "Asia/Dubai",
            "Asia/Dushanbe",
            "Asia/Famagusta",
            "Asia/Gaza",
            "Asia/Hebron",
            "Asia/Ho_Chi_Minh",
            "Asia/Hong_Kong",
            "Asia/Hovd",
            "Asia/Irkutsk",
            "Asia/Istanbul",
            "Asia/Jakarta",
            "Asia/Jayapura",
            "Asia/Jerusalem",
            "Asia/Kabul",
            "Asia/Kamchatka",
            "Asia/Karachi",
            "Asia/Kathmandu",
            "Asia/Khandyga",
            "Asia/Kolkata",
            "Asia/Krasnoyarsk",
            "Asia/Kuala_Lumpur",
            "Asia/Kuching",
            "Asia/Kuwait",
            "Asia/Macau",
            "Asia/Magadan",
            "Asia/Makassar",
            "Asia/Manila",
            "Asia/Muscat",
            "Asia/Nicosia",
            "Asia/Novokuznetsk",
            "Asia/Novosibirsk",
            "Asia/Omsk",
            "Asia/Oral",
            "Asia/Phnom_Penh",
            "Asia/Pontianak",
            "Asia/Pyongyang",
            "Asia/Qatar",
            "Asia/Qyzylorda",
            "Asia/Riyadh",
            "Asia/Sakhalin",
            "Asia/Samarkand",
            "Asia/Seoul",
            "Asia/Shanghai",
            "Asia/Singapore",
            "Asia/Srednekolymsk",
            "Asia/Taipei",
            "Asia/Tashkent",
            "Asia/Tbilisi",
            "Asia/Tehran",
            "Asia/Thimphu",
            "Asia/Tokyo",
            "Asia/Tomsk",
            "Asia/Ulaanbaatar",
            "Asia/Urumqi",
            "Asia/Ust-Nera",
            "Asia/Vientiane",
            "Asia/Vladivostok",
            "Asia/Yakutsk",
            "Asia/Yangon",
            "Asia/Yekaterinburg",
            "Asia/Yerevan",
            "Atlantic/Azores",
            "Atlantic/Bermuda",
            "Atlantic/Canary",
            "Atlantic/Cape_Verde",
            "Atlantic/Faroe",
            "Atlantic/Madeira",
            "Atlantic/Reykjavik",
            "Atlantic/South_Georgia",
            "Atlantic/St_Helena",
            "Atlantic/Stanley",
            "Australia/Adelaide",
            "Australia/Brisbane",
            "Australia/Broken_Hill",
            "Australia/Currie",
            "Australia/Darwin",
            "Australia/Eucla",
            "Australia/Hobart",
            "Australia/Lindeman",
            "Australia/Lord_Howe",
            "Australia/Melbourne",
            "Australia/Perth",
            "Australia/Sydney",
            "Europe/Amsterdam",
            "Europe/Andorra",
            "Europe/Astrakhan",
            "Europe/Athens",
            "Europe/Belgrade",
            "Europe/Berlin",
            "Europe/Bratislava",
            "Europe/Brussels",
            "Europe/Bucharest",
            "Europe/Budapest",
            "Europe/Busingen",
            "Europe/Chisinau",
            "Europe/Copenhagen",
            "Europe/Dublin",
            "Europe/Gibraltar",
            "Europe/Guernsey",
            "Europe/Helsinki",
            "Europe/Isle_of_Man",
            "Europe/Istanbul",
            "Europe/Jersey",
            "Europe/Kaliningrad",
            "Europe/Kiev",
            "Europe/Kirov",
            "Europe/Lisbon",
            "Europe/Ljubljana",
            "Europe/London",
            "Europe/Luxembourg",
            "Europe/Madrid",
            "Europe/Malta",
            "Europe/Mariehamn",
            "Europe/Minsk",
            "Europe/Monaco",
            "Europe/Moscow",
            "Europe/Nicosia",
            "Europe/Oslo",
            "Europe/Paris",
            "Europe/Podgorica",
            "Europe/Prague",
            "Europe/Riga",
            "Europe/Rome",
            "Europe/Samara",
            "Europe/San_Marino",
            "Europe/Sarajevo",
            "Europe/Saratov",
            "Europe/Simferopol",
            "Europe/Skopje",
            "Europe/Sofia",
            "Europe/Stockholm",
            "Europe/Tallinn",
            "Europe/Tirane",
            "Europe/Ulyanovsk",
            "Europe/Uzhgorod",
            "Europe/Vaduz",
            "Europe/Vatican",
            "Europe/Vienna",
            "Europe/Vilnius",
            "Europe/Volgograd",
            "Europe/Warsaw",
            "Europe/Zagreb",
            "Europe/Zaporozhye",
            "Europe/Zurich",
            "Indian/Antananarivo",
            "Indian/Chagos",
            "Indian/Christmas",
            "Indian/Cocos",
            "Indian/Comoro",
            "Indian/Kerguelen",
            "Indian/Mahe",
            "Indian/Maldives",
            "Indian/Mauritius",
            "Indian/Mayotte",
            "Indian/Reunion",
            "Pacific/Apia",
            "Pacific/Auckland",
            "Pacific/Bougainville",
            "Pacific/Chatham",
            "Pacific/Chuuk",
            "Pacific/Easter",
            "Pacific/Efate",
            "Pacific/Enderbury",
            "Pacific/Fakaofo",
            "Pacific/Fiji",
            "Pacific/Funafuti",
            "Pacific/Galapagos",
            "Pacific/Gambier",
            "Pacific/Guadalcanal",
            "Pacific/Guam",
            "Pacific/Honolulu",
            "Pacific/Kiritimati",
            "Pacific/Kosrae",
            "Pacific/Kwajalein",
            "Pacific/Majuro",
            "Pacific/Marquesas",
            "Pacific/Midway",
            "Pacific/Nauru",
            "Pacific/Niue",
            "Pacific/Norfolk",
            "Pacific/Noumea",
            "Pacific/Pago_Pago",
            "Pacific/Palau",
            "Pacific/Pitcairn",
            "Pacific/Pohnpei",
            "Pacific/Port_Moresby",
            "Pacific/Rarotonga",
            "Pacific/Saipan",
            "Pacific/Tahiti",
            "Pacific/Tarawa",
            "Pacific/Tongatapu",
            "Pacific/Wake",
            "Pacific/Wallis",
            "US/Pacific-New"
        ]
    },
    "config": {
        "UTC": "2018-10-19T13:26:17",
        "apiversion": "1.24.0",
        "backup": {
            "errorcode": 0,
            "status": "idle"
        },
        "bridgeid": "B827EBFFFE7A0C08",
        "datastoreversion": "70",
        "dhcp": true,
        "factorynew": false,
        "gateway": "192.168.1.1",
        "internetservices": {
            "internet": "connected",
            "remoteaccess": "connected",
            "swupdate": "connected",
            "time": "connected"
        },
        "ipaddress": "192.168.1.172",
        "linkbutton": false,
        "localtime": "2018-10-19T13:26:17",
        "mac": "b8:27:eb:7a:0c:08",
        "modelid": "BSB002",
        "name": "Philips hue",
        "netmask": "255.255.255.0",
        "portalconnection": "connected",
        "portalservices": true,
        "portalstate": {
            "communication": "disconnected",
            "incoming": false,
            "outgoing": true,
            "signedon": true
        },
        "proxyaddress": "none",
        "proxyport": 0,
        "replacesbridgeid": null,
        "starterkitid": "",
        "swupdate": {
            "checkforupdate": false,
            "devicetypes": {
                "bridge": false,
                "lights": [],
                "sensors": []
            },
            "notify": true,
            "text": "",
            "updatestate": 0,
            "url": ""
        },
        "swupdate2": {
            "autoinstall": {
                "on": false,
                "updatetime": "T14:00:00"
            },
            "bridge": {
                "lastinstall": "2018-06-08T19:09:45",
                "state": "noupdates"
            },
            "checkforupdate": false,
            "lastchange": "2018-06-09T10:11:08",
            "state": "noupdates"
        },
        "swversion": "1806051111",
        "timezone": "Europe/Bucharest",
        "whitelist": {
            "a7161538be80d40b3de98dece6e91f90": {
                "create date": "2018-10-19T13:23:03",
                "last use date": "2018-10-19T13:26:17",
                "name": "Hue 3#Samsung SM-G920F"
            }
        },
        "zigbeechannel": 25
    },
    "deconz": {
        "enabled": false,
        "lights": {},
        "port": 8080,
        "sensors": {}
    },
    "groups": {},
    "lights": {
        "1": {
            "deviceid": [
                "BF638D",
                "931B44"
            ]
        }
    },
    "lights_address": {},
    "linkbutton": {
        "lastlinkbuttonpushed": "1539955383",
        "linkbutton_auth": "SHVlOkh1ZQ=="
    },
    "resourcelinks": {},
    "rules": {},
    "scenes": {},
    "schedules": {},
    "sensors": {
        "1": {
            "config": {
                "configured": false,
                "on": true,
                "sunriseoffset": 30,
                "sunsetoffset": -30
            },
            "manufacturername": "Philips",
            "modelid": "PHDL00",
            "name": "Daylight",
            "state": {
                "daylight": null,
                "lastupdated": "none"
            },
            "swversion": "1.0",
            "type": "Daylight"
        }
    }
}`

**Comment by mariusmotea** [comment]
Hi,

Can you tell me more exactly what type of light are you using? The sketch folder if is ESP8266.

**Comment by Lukvaiks** [comment]
Hey, i'm trying to connect 2 Philips Hue White single bulb e27 warm white lights. In the config file, where's light section, there are 2 6-digit codes for the lights

**Comment by cheesemarathon** [comment]
I assume you have paired the bulbs with your real bridge successfully and have then followed the instructions [here](https://github.com/mariusmotea/diyHue/wiki/Hue-Bridge-Lights) to add them to your diyHue bridge? If so do the lights appear in the list when you browse to `http://{bridgeIP}/`

**Comment by cheesemarathon** [comment]
Ah so your trying to connect to Hue bulbs using a ZigBee module such as the Raspbee module? Is that supported @mariusmotea ?

**Comment by mariusmotea** [comment]
Philips Hue lights don't use wifi protocol, but ZigBee. In order to communicate with these bulbs a 3rd party device with this future is needed. You can use one real hue bridge or the Raspbee module if you use RaspberryPI. To reset the lights in general performing power cycle 5-6 times is enough.

**Comment by cheesemarathon** [comment]
Ah so you can use Deconz and the Raspbee module to control Genuine Hue bulbs. This needs adding to [this wiki page](https://github.com/mariusmotea/diyHue/wiki/Raspbee-module) then @mariusmotea. Can you follow the instructions in there to add the lights, as it only mentions sensors and remotes?

**Comment by Lukvaiks** [comment]
Is there another way around? Since both bridge and raspbee module are expensive. And if there's not, which would you suggest getting me? The bridge or raspbee?

**Comment by cheesemarathon** [comment]
I'll close this now as the issue has been identified. If you need any more help you can continue to comment here or you can join us on our Slack chat [here](https://slackinvite.squishedmooo.com/)
