### ISSUE TITLE
Possible to run the docker on windows?

### ISSUE THREAD

**Issue by dmratcliffe** [mariusmotea/diyHue#416]
My raspberry pi recently died and I need to get this back running quickly. 

When I run the docker found here: https://hub.docker.com/r/musfur/diyhuedocker/

(first pulling then running: `docker run -p 80:80 --name HueEmulator -i -t musfur/diyhuedocker`)

It gets stuck at "Starting httpd"

**Comment by mariusmotea** [comment]
Is too complicated to made it work on windows because there are linux based commands like nmap, cat, etc uset for lights detection and network parameters details. You you will have success with docker image ?

**Comment by cheesemarathon** [comment]
I'm afraid Marius is correct. Try docker for windows, make sure you set it up to run Linux docker images not windows docker images. Either that or look at running a virtual machine.

**Comment by mariusmotea** [comment]
You are right i reply from phone without to read very well. You ca try to open the shell in container, cd /opt/hue-enulator and the execute the python script by providing the ip and mac address as arguments.

**Comment by dmratcliffe** [comment]
Actually, my mistake. It is running, I just didn't realize theres no website setup to run the /, naving to the /hue/linkbutton seems to work

**Comment by mariusmotea** [comment]
On / you have the webui, but something is wot working well.

**Comment by dmratcliffe** [comment]
Oh, then maybe its not working :/

**Comment by mariusmotea** [comment]
Maybe the http files are missing, and are not crucial. You ca also try to start with ubuntu image and deploy like on raspberry pi. Last resort is vm with something like virtual box

**Comment by dmratcliffe** [comment]
Since I use docker to run other things, hyper-v is enabled and VMs won't run :(

**Comment by dmratcliffe** [comment]
I was actually able to get it to work, I modified the docker compose a little and it worked out. I have a different issue, but I will create a new issue and close this one.
