### ISSUE TITLE
Bridge Update hue app 3.8.0 Android 

### ISSUE THREAD

**Issue by Marmi86** [mariusmotea/diyHue#417]
Hello,
I installed the new version about hue app (3.8.0),today. When I started the app i see a notification new Update available,but I cannot Connect to hue bridge. 3rd Apps works fine

System :
Ubuntu Server 16.04 Proxmox VM with Diyhue
Android Phone with newest Hue App

**Comment by mariusmotea** [comment]
i push this version on updater. Please click again "Update Bridge" button.

**Comment by juanesf** [comment]
On line 1403 in OpenWrt I had to change the location to an absolute one but apparently it is missing a point before /

if self.path == "/updater":
