### ISSUE TITLE
More question

### ISSUE THREAD

**Issue by poudenes** [mariusmotea/diyHue#418]
Can you explain in wiki how many bulbs you can add?

Can you add as many Milight bulbs for example ? I know Milight have Remotes with groups etc.
Im now using a Milight Emulator. Can add as many virtual remotes, and get in every virtual remove 8 groups to put bulbs in (pairing)

**Comment by mariusmotea** [comment]
There is no such limitation on bridge emulator and on MiLight hub the number of light addresses is very big. The more serious limitation may be on the official Hue App, i never face it but on real hue bridge we can see in capabilities remaining available lights, and this is 64 when no light is paired. If Hue app have any hardcoded limitation is hard for me to say.

**Comment by cheesemarathon** [comment]
Question answered so i'm closing this issue. For more questions, please join slack and ask there. Thanks :smile:
