### ISSUE TITLE
opposite temperature rgbcct ledstrip controller

### ISSUE THREAD

**Issue by kurniawan77** [mariusmotea/diyHue#42]
Hi, there again.

I have made the ESP Mi-light hub for my older milight rgbw bulbs (fut014) and rgbcct led strip controller (fut039).

with the rgbcct led controller the color temperature works in the opposite waywith the hue app as with the rf remote and with the ESP Mi-light web ui.

**Comment by mariusmotea** [comment]
Hi, do you use latest firmware for milight hub? I know this was a reported bug on milight hub, not sure if was fixed until i add support or after. Anyway this is the code line:

```payload["color_temp"] = int((500 - value) / 1.6 + 153)```

as you can see i add (500 - value) to reverse the ct (i guess this fixed the old bug that currently was fixed). Try to replace with  ```int(value / 1.6 + 153)```. If is working you can create a PR or at last confirm so i can fix.

**Comment by mariusmotea** [comment]
Hi!

i cannot create the PR from your fork, did you undo the changes? What is the correct ct conversion formula `int((500 - value) / 1.6 + 153)` or `int(value / 1.6 + 153)`?

Thanks,
Marius.

**Comment by kurniawan77** [comment]
Just tested it. works now as it should
