### ISSUE TITLE
Remove trailing slashes

### ISSUE THREAD

**Issue by grywnn** [mariusmotea/diyHue#420]
The iOS app "iconnecthue" is putting a trailing slash behind most of the requests, ex:

192.168.209.202 - - [26/Oct/2018 09:28:29] "PUT /api/<user key>/lights/15/state/ HTTP/1.1" 200 -

...this leads to diyHue getting the count wrong in various places in "class S(BaseHTTPRequestHandler)" when trying to figure out what to do with the request.

Replacing

url_pices = self.path.split("/");

with

url_pices = self.path.rstrip("/").split("/");

in 4 places in this class fixed this for me.

**Comment by mariusmotea** [comment]
Thanks, If you want you can create a pull request. If not i will add this fix. For GET requests i put something like `if len(url_pices) == 3 or (len(url_pices) == 4 and url_pices[3] == "")` but this is less efficient than your example.

**Comment by grywnn** [comment]
I'll try, but this will take me a day or two (git noob here, but I need the practice....)

btw i'm working on another issue with this iOS app: They still use "time" instead of "localtime" in schedules, so i'm introducing a fallback to time if localtime is missing in the POSTed JSON. I will add this into the pull request too.

**Comment by grywnn** [comment]
https://github.com/mariusmotea/diyHue/pull/421
Enjoy :-)

**Comment by mariusmotea** [comment]
Yes, i read in the hue api that "time" value is deprecated and in future they will leave just "localtime", for this reason i did not implement it.
