### ISSUE TITLE
Hue Sync for PC suddenly not find my Hue Bridge Emulator!

### ISSUE THREAD

**Issue by andiling** [mariusmotea/diyHue#424]
I have nothing done on my installation! The Hue Sync has worked perfectly but suddenly the software does not find the emulated bridge! I have it the Hue Emulator restartet and then updated but nothing works. The original Bridge was found from Hue Sync perfectly but Hue Emulator.... - not found!
Please help!

**Comment by mariusmotea** [comment]
Not sure if is the same issue, but in my problems with HueSync were caused by service remain started on entertainment room. Just open hue application on you phone and stop entertainment broadcast from previews session.

**Comment by andiling** [comment]
Ok. Just done! It works! Thank you!
