### ISSUE TITLE
More info on the diy Hue tap/dimmer switch

### ISSUE THREAD

**Issue by beukhof1** [mariusmotea/diyHue#425]
Could you please add a more detailed wiring schematic and/or a close up picture of your prototype from the other side?

Thanks for all your cool work man!

**Comment by mariusmotea** [comment]
Please join slack channel where currently is done some development for it. I start a new prototype and user mcer12 has already build some pcb's he will share soon also the schematic.

**Comment by beukhof1** [comment]
> Please join slack channel where currently is done some development for it. I start a new prototype and user mcer12 has already build some pcb's he will share soon also the schematic.

Nice! i will! do you have a inv link?

**Comment by cheesemarathon** [comment]
@beukhof1 [In case you couldn't find it!](https://slackinvite.squishedmooo.com/)
