### ISSUE TITLE
Hue Entertainment Not Working ,Docker & WS2811

### ISSUE THREAD

**Issue by ScottParkin83** [mariusmotea/diyHue#427]
Hi
The Hue entertainment function doesn't seem to be working using the docker and Wemo D1 with WS2811 Led Strips 

It works when setting up the entertainment area in the hue app but it won't work in any app I've tried  including IConnectHue

**Comment by ScottParkin83** [comment]
Hi,

Yes I did , I even reset the the container and the esp8266 to make sure it wasn't been held open 

I've tried it in both host and bridge mode , It is a unraid docker it that makes a difference

**Comment by cheesemarathon** [comment]
Give me a few mins. I'll spin up a container on my unRAID system and see if I have the same issue

**Comment by cheesemarathon** [comment]
Ok, looks like it doesn't want to play ball over VPN so ill have another look when I get home from work tonight.

**Comment by cheesemarathon** [comment]
Ok, so I got it working on my unraid machine and added an ESP based rgbw bulb and an Esp8266 with a Ws2812 strip. Both of which worked when I ran the test entertainment area function in the app. I'm yet to be able to test if any desktop apps work. Which ones have you tried?

**Comment by ScottParkin83** [comment]
The only desktop app i’ve tested is  hue dynamic which will work when not using hue entertainment mode ,I couldn’t get hue sync to connect to my diyhue
iPad apps iconnnect hue will not work in hue entertainment mode but light DJ seems to work intermittently 

Could it be the version of the arduino library’s I’m using as I’m using the latest

**Comment by cheesemarathon** [comment]
Hmm, OK. I did update the Arduino sketches used fairly recently but probably not the libraries so I will look into that and test some desktop entertainment apps tonight.

**Comment by mariusmotea** [comment]
> I couldn’t get hue sync to connect to my diyhue

just open Hue app on your phone and stop existing hue entertainment broadcast. After this it will pair with no issues. All my tests were done with Hue Sync.

**Comment by ScottParkin83** [comment]
I've managed to get it to work with hue sync , I had an update for the docker image so i recreated it from scratch and after i unplugged my genuine bridge it picked it up fine ,Unfortunately its the only program it seems to work with at the minute

**Comment by ScottParkin83** [comment]
The 2 main apps are
IConnectHue connects fine and works with normal scenes but animations and discotainment doesn’t work, I get an error occurred with animations and with discotaiment the lights just dont respond 

ILightShow won’t connect at all 

I’ve also tried huedynamic for windows which works when I select normal group but the lights don’t respond if I select an entertainment group

**Comment by mariusmotea** [comment]
Debug code will help to understand what is going on. I don't use iphone and i cannot reproduce.

**Comment by cheesemarathon** [comment]
@ScottParkin83 Are you able to provide debug output when the error occurs for us to see what the issue is with running these apps. [Instructions on how to do that are here!](https://github.com/mariusmotea/diyHue/wiki/Debug)

**Comment by ScottParkin83** [comment]
Hi yeah sure , I was going to ask if you know a way to run the debugging in a docker as I’m still a novice with docker at the moment

**Comment by cheesemarathon** [comment]
It's a feature that is sitting in a PR at the moment, however I have a test image you can use. Your on unRAID right?

**Comment by ScottParkin83** [comment]
Thanks , i got a quick debug log 

Starting Discotainment(Hue Entertainment in IconnectHue)
**. Seeding the random number generator... ok
. Loading the CA root certificate ... ok (0 skipped)
. Loading the server cert. and key... ok
. Bind on udp://*:2100/ ... ok
. Setting up the SSL/TLS structure... ok
. Waiting for a remote connection ... ok
. Performing the SSL/TLS handshake... hello verification requested
. Waiting for a remote connection ... ok
. Performing the SSL/TLS handshake... ok
[ Protocol is DTLSv1.2 ]
[ Ciphersuite is TLS-PSK-WITH-AES-128-GCM-SHA256 ]
[ Record expansion is 37 ]
[ Maximum fragment length is 16384 ]
. Verifying peer X.509 certificate... ok**
Then just stops here with no errors in the app

Then When Stopped
**connection was closed gracefully
. Closing the connection... done
. Waiting for a remote connection ... interrupted by SIGTERM (in net_accept())
. Cleaning up... done.**

I have noticed animations are now working as it used to just give a unable to start error

**Comment by chrisdata** [comment]
@ScottParkin83 did you get iConnecthue disco to work now?

**Comment by Pronown** [comment]
Did we ever get it to work on HueDynamic? My bridge syncs no problem but it only does white instead of colors. =(
