### ISSUE TITLE
Yeelight not discovered again...

### ISSUE THREAD

**Issue by purplehazezzz** [mariusmotea/diyHue#428]
So I added a zigbee unit and reainstalled my diyhue. No again it doesnt find the yeelight. If I check the debug, i can tell diyhue bridge only discovers the ip adresses on the wired lan not on the Wifi.

DIYHUE is installed on a pi model b (no wifi) so its wired. Is this a config setting? Iprange of the wifi and lan is the same

**Comment by purplehazezzz** [comment]
no thats not it. My TV is on wifi and is discovered.

**Comment by purplehazezzz** [comment]
Will pull a debug later, maybe I'm missing something

**Comment by purplehazezzz** [comment]
Installed a third party app on my phone, just to check of that discovers the yeelight in lan mode. This works, so the light is lan enabled and should be found bij diyhue

**Comment by purplehazezzz** [comment]
I get the idea that the search is to short? The searching through the hue app on the original bridge takes 3 times as long.. Below my debug after search.

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Oct 31 10:13:42 2018
pi@DIYHUE:~ $ cd /opt/hue-emulator
pi@DIYHUE:/opt/hue-emulator $ sudo systemctl stop hue-emulator
pi@DIYHUE:/opt/hue-emulator $ sudo ./HueEmulator3.py
2018-10-31 10:16:41,967 - root - DEBUG - b827eb721fb6
2018-10-31 10:16:41,985 - root - DEBUG - Config loaded
2018-10-31 10:16:42,011 - root - DEBUG - starting ssdp...
2018-10-31 10:16:42,017 - root - DEBUG - start ssdp broadcast
2018-10-31 10:16:42,049 - root - DEBUG - sync with lights
2018-10-31 10:16:42,088 - root - DEBUG - Starting httpd...
2018-10-31 10:16:42,115 - root - DEBUG - Starting ssl httpd...
192.168.178.53 - - [31/Oct/2018 10:16:42] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:42] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:42] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:43] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:43] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:44] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:44] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:45] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:45] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:46] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:46] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:47] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:47] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:48] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:48] "GET /api/a7161538be80d40b3de98dece6e91f90 HTTP/1.1" 200 -
2018-10-31 10:16:48,543 - root - DEBUG - Sending M-Search response to 192.168.178.172
192.168.178.53 - - [31/Oct/2018 10:16:48] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:48] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:48] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:48] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:49] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:49] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:49] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:49] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:49] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:50] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:50] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:50] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:50] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:50] "POST /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
2018-10-31 10:16:50,878 - root - DEBUG - in post method
2018-10-31 10:16:50,883 - root - DEBUG - /api/a7161538be80d40b3de98dece6e91f90/lights
2018-10-31 10:16:50,890 - root - DEBUG - b'{}'
192.168.178.53 - - [31/Oct/2018 10:16:51] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:51] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
2018-10-31 10:16:52,025 - root - DEBUG - Sending M-Search response to 192.168.178.53
192.168.178.53 - - [31/Oct/2018 10:16:52] "GET /description.xml HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:52] "GET /description.xml HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:52] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:52] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:53] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:53] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
2018-10-31 10:16:53,919 - root - DEBUG - Yeelight search end
2018-10-31 10:16:53,941 - root - DEBUG - Sending M-Search response to 192.168.178.53
192.168.178.53 - - [31/Oct/2018 10:16:54] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:54] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
2018-10-31 10:16:55,356 - root - DEBUG - Sending M-Search response to 192.168.178.53
192.168.178.53 - - [31/Oct/2018 10:16:55] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:55] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
2018-10-31 10:16:56,771 - root - DEBUG - Sending M-Search response to 192.168.178.53
192.168.178.53 - - [31/Oct/2018 10:16:56] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:56] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:57] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:57] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:57] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:58] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:58] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:58] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
2018-10-31 10:16:58,487 - root - DEBUG - Sending M-Search response to 192.168.178.172
192.168.178.248 - - [31/Oct/2018 10:16:58] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:58] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:58] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:58] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:58] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:58] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:16:59] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
2018-10-31 10:16:59,088 - root - DEBUG - sync with lights
192.168.178.53 - - [31/Oct/2018 10:16:59] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:16:59] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
2018-10-31 10:17:00,598 - root - DEBUG - Sending M-Search response to 192.168.178.248
192.168.178.248 - - [31/Oct/2018 10:17:00] "GET /description.xml HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:00] "GET /description.xml HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:00] "GET /description.xml HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:00] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:00] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:00] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:00] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:01] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:01] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:02] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:02] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:02] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:03] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:03] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:03] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
192.168.178.53 - - [31/Oct/2018 10:17:04] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:04] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:05] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:05] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:05] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:05] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:06] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:06] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:07] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:07] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:07] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:07] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:08] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:08] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:09] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:09] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:09] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
2018-10-31 10:17:09,723 - root - DEBUG - Sending M-Search response to 192.168.178.172
192.168.178.53 - - [31/Oct/2018 10:17:09] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:09] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:10] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:10] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:11] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:11] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
2018-10-31 10:17:11,532 - root - DEBUG - Sending M-Search response to 192.168.178.172
192.168.178.53 - - [31/Oct/2018 10:17:11] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:11] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:12] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:12] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
2018-10-31 10:17:13,140 - root - DEBUG - Sending M-Search response to 192.168.178.172
192.168.178.248 - - [31/Oct/2018 10:17:13] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:13] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:13] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:13] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:14] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:14] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
2018-10-31 10:17:15,473 - root - DEBUG - Sending M-Search response to 192.168.178.172
192.168.178.248 - - [31/Oct/2018 10:17:15] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:15] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:15] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:15] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:16] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:16] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:17] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:17] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:17] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:17] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:18] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:18] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:19] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:19] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:19] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:19] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.178.248 - - [31/Oct/2018 10:17:19] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:20] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:20] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:21] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:21] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
2018-10-31 10:17:22,037 - root - DEBUG - Sending M-Search response to 192.168.178.172
192.168.178.53 - - [31/Oct/2018 10:17:22] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:22] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:23] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:23] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
2018-10-31 10:17:23,846 - root - DEBUG - Sending M-Search response to 192.168.178.172
192.168.178.53 - - [31/Oct/2018 10:17:24] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:24] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
2018-10-31 10:17:24,877 - root - DEBUG - [
    "192.168.178.1",
    "192.168.178.99",
    "192.168.178.193",
    "192.168.178.199",
    "192.168.178.45"
]
2018-10-31 10:17:25,131 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.1
2018-10-31 10:17:25,308 - root - DEBUG - Sending M-Search response to 192.168.178.172
2018-10-31 10:17:25,324 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.1:80 "GET /detect HTTP/1.1" 302 None
2018-10-31 10:17:25,420 - requests.packages.urllib3.connectionpool - DEBUG - Resetting dropped connection: 192.168.178.1
2018-10-31 10:17:25,620 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.1:80 "GET /index.html HTTP/1.1" 302 None
2018-10-31 10:17:25,721 - requests.packages.urllib3.connectionpool - DEBUG - Resetting dropped connection: 192.168.178.1
192.168.178.53 - - [31/Oct/2018 10:17:25] "GET /api/web-ui-31439/lights HTTP/1.1" 200 -
192.168.178.53 - - [31/Oct/2018 10:17:25] "GET /api/web-ui-31439/groups HTTP/1.1" 200 -

**Comment by purplehazezzz** [comment]
I gave the yeelight a fixed ip 192.168.178.60

**Comment by mariusmotea** [comment]
You must have connectivity issues with the bulb. If you are using RaspberryPi3 on wifi, switch to cable because lot of connectivity issues are generated by the poor implementation of wifi on Raspberry.

**Comment by cheesemarathon** [comment]
@mariusmotea I think the first post states the use of a wired connection for the Pi. Can you ping the bulb from the Pi @purplehazezzz ? It looks like your WiFi devices and Wired devices are on the same subnet right?

**Comment by purplehazezzz** [comment]
Yeah correct, and its wired also. 

pi@DIYHUE:~ $ ping 192.168.178.60
PING 192.168.178.60 (192.168.178.60) 56(84) bytes of data.
64 bytes from 192.168.178.60: icmp_seq=1 ttl=255 time=4.55 ms
64 bytes from 192.168.178.60: icmp_seq=2 ttl=255 time=5.63 ms
64 bytes from 192.168.178.60: icmp_seq=3 ttl=255 time=405 ms
64 bytes from 192.168.178.60: icmp_seq=4 ttl=255 time=2.71 ms
64 bytes from 192.168.178.60: icmp_seq=5 ttl=255 time=4.15 ms
^C
--- 192.168.178.60 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4004ms
rtt min/avg/max/mdev = 2.714/84.415/405.023/160.306 ms
pi@DIYHUE:~ $

**Comment by purplehazezzz** [comment]
ping seems to work

**Comment by purplehazezzz** [comment]
would be nice if it could be added by ipadress. Just like adding the gateway

**Comment by purplehazezzz** [comment]
I Moved the bulb near the router, first pin stays 401ms...

pi@DIYHUE:~ $ ping 192.168.178.60
PING 192.168.178.60 (192.168.178.60) 56(84) bytes of data.
64 bytes from 192.168.178.60: icmp_seq=1 ttl=255 time=401 ms
64 bytes from 192.168.178.60: icmp_seq=2 ttl=255 time=2.46 ms
64 bytes from 192.168.178.60: icmp_seq=3 ttl=255 time=3.93 ms
64 bytes from 192.168.178.60: icmp_seq=4 ttl=255 time=3.76 ms
64 bytes from 192.168.178.60: icmp_seq=5 ttl=255 time=4.96 ms
64 bytes from 192.168.178.60: icmp_seq=6 ttl=255 time=2.63 ms
^C
--- 192.168.178.60 ping statistics ---
7 packets transmitted, 6 received, 14% packet loss, time 6009ms
rtt min/avg/max/mdev = 2.463/69.828/401.218/148.204 ms

**Comment by mariusmotea** [comment]
Try to change wifi channel, for me the ssdp search for yeelight works very good so i still believe there is a problem related to your router (firewall) or wifi network.

**Comment by purplehazezzz** [comment]
Ok, will give it a go. But still seems strange that this other app finds no problems what sowever.

**Comment by purplehazezzz** [comment]
Tried different channels, still nothing

**Comment by purplehazezzz** [comment]
no it does'nt :(


pi@DIYHUE:~ $ gssdp-discover -i eth0 --timeout=3
Using network interface eth0
Scanning for all resources
Showing "available" messages
resource available
  USN:      uuid:60d1d388-dcdd-4862-939e-7bb34d1da853::upnp:rootdevice
  Location: http://192.168.178.45:8080/description.xml
resource available
  USN:      uuid:2f402f80-da50-11e1-9b23-b827eb721fb6::upnp:rootdevice
  Location: http://192.168.178.45:80/description.xml
resource available
  USN:      uuid:2f402f80-da50-11e1-9b23-b827eb721fb6
  Location: http://192.168.178.45:80/description.xml
resource available
  USN:      uuid:2f402f80-da50-11e1-9b23-001788278af5::upnp:rootdevice
  Location: http://192.168.178.99:80/description.xml
resource available
  USN:      uuid:2f402f80-da50-11e1-9b23-001788278af5
  Location: http://192.168.178.99:80/description.xml

**Comment by cheesemarathon** [comment]
hmm in theory that would work but I don't have any YeeLights to test with. @mariusmotea does the command i posted discover your YeeLights? If not is there a command we can run to detect the bulb? That way we can decide if its the ssdp function or the network that's the issue.

**Comment by purplehazezzz** [comment]
One more thing, I also got Hyperion and domoticz running with hue stuff on it (both on different pi). could this be an issue?

**Comment by cheesemarathon** [comment]
Unlikely, but its possible. Try disabling them temporarily and see if there is any change.

**Comment by mariusmotea** [comment]
Try to temporary stop all other services on bridge host and shutdown other devices from network. yeelight use ssdp service but on a different port, so for this reason will not be detected by ssdp scanners, hue hue emulator use that port and it need to detect it. If this is still not woking i propose to manually add is to config.json file. 
Very important, backup current config.json, than you need to append to lights and lights_address key something like:
```
    "lights": {
        "1": {
            "manufacturername": "Philips",
            "modelid": "LCT015",
            "name": "YeeLight id 052bdc23",
            "state": {
                "alert": "select",
                "bri": 199,
                "colormode": "xy",
                "ct": 447,
                "effect": "none",
                "hue": 0,
                "on": false,
                "reachable": false,
                "sat": 0,
                "xy": [
                    0.46389,
                    0.451194
                ]
            },
            "swversion": "1.29.0_r21169",
            "type": "Extended color light",
            "uniqueid": "4a:e0:ad:7f:cf:15-1"
        }
 ```
```
    "lights_address": {
        "1": {
            "id": "0x00000000052bdc23",
            "ip": "192.168.0.78",
            "protocol": "yeelight"
        }

```
Notice here the light id is "1", this is an incremental number, and you need to put "1" like in my example only if you currently have 0 lights.
Do the changes with service hue-emulator stopped other your changes will be overtired.

**Comment by purplehazezzz** [comment]
Allright, this is crazy. Picked the project op this morning. Been resetting/rewirering my network, and did a couple of reboots on the router and other devices. And now it just appeared in the app. Didn't do a light search. Dunno what's happening anymore. But it works :)

Does it search for lights on boot or something?

**Comment by mariusmotea** [comment]
No, light search is performed only on demand.

**Comment by cheesemarathon** [comment]
Looks like this is solved for now. Root cause unknown but if your experience the safe fault again @purplehazezzz please re-open this

**Comment by jameh** [comment]
I seem to be having this issue too, pinging the light also results in a few slow responses:

```
ping 192.168.1.145
PING 192.168.1.145 (192.168.1.145) 56(84) bytes of data.
64 bytes from 192.168.1.145: icmp_seq=2 ttl=254 time=550 ms
64 bytes from 192.168.1.145: icmp_seq=3 ttl=254 time=4.72 ms
64 bytes from 192.168.1.145: icmp_seq=4 ttl=254 time=3.09 ms
64 bytes from 192.168.1.145: icmp_seq=6 ttl=254 time=408 ms
64 bytes from 192.168.1.145: icmp_seq=7 ttl=254 time=3.11 ms
64 bytes from 192.168.1.145: icmp_seq=8 ttl=254 time=2.51 ms
64 bytes from 192.168.1.145: icmp_seq=10 ttl=254 time=420 ms
64 bytes from 192.168.1.145: icmp_seq=11 ttl=254 time=36.5 ms
^C
--- 192.168.1.145 ping statistics ---
11 packets transmitted, 8 received, 27.2727% packet loss, time 10188ms
rtt min/avg/max/mdev = 2.512/178.493/549.672/221.308 ms

```

I tried changing the wifi channel without luck.

The Yeelight app says the bulb has a -64dB signal

The diyhue logs only mention yeelight in one line:

```
2021-08-09 14:13:57,803 - root - DEBUG - Yeelight search end
```

I've tried scanning from the Hue Essentials app as well as at `homeassistant/scan` in a web browser (I am running diyhue containerized as an addon to HA)

**Comment by jameh** [comment]
I've moved the yeelight close to the wifi router, now the Yeelight app reports -43dB signal strength. There's still some slow pings when I ping it:

```
ping 192.168.1.145
PING 192.168.1.145 (192.168.1.145) 56(84) bytes of data.
64 bytes from 192.168.1.145: icmp_seq=1 ttl=254 time=5.65 ms
64 bytes from 192.168.1.145: icmp_seq=2 ttl=254 time=3.35 ms
64 bytes from 192.168.1.145: icmp_seq=3 ttl=254 time=27.1 ms
64 bytes from 192.168.1.145: icmp_seq=4 ttl=254 time=3.82 ms
64 bytes from 192.168.1.145: icmp_seq=5 ttl=254 time=3.01 ms
64 bytes from 192.168.1.145: icmp_seq=6 ttl=254 time=407 ms
64 bytes from 192.168.1.145: icmp_seq=7 ttl=254 time=2.75 ms
64 bytes from 192.168.1.145: icmp_seq=8 ttl=254 time=3.35 ms
64 bytes from 192.168.1.145: icmp_seq=9 ttl=254 time=6.78 ms
64 bytes from 192.168.1.145: icmp_seq=10 ttl=254 time=4.69 ms
^C
--- 192.168.1.145 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9015ms
rtt min/avg/max/mdev = 2.746/46.787/407.366/120.392 ms
```

And diyhue is still unable to find it. 

btw, same subnet for everything, LAN control on

**Comment by mariusmotea** [comment]
Be aware that you cannot discovery the Yeelight's if you use docker and network mode is not `host`.
