### ISSUE TITLE
Documentation of switch (or other possible) REST-API

### ISSUE THREAD

**Issue by hdhdu** [mariusmotea/diyHue#429]
Hey,
first of all, thank you for your great project! It works really good! I would like to use my 433MHZ Switches. I used them in my old milight setup bevor I switched to your diyHue project! They communicate with a little node server. The server receives the signal and then sends REST-Calls depending on the signal, which can be defined by me. So I think, this should work perfectly with the switch api of diyHue. But I just found a few examples in the wiki, and not the entire documentation. My idea is, that the server register itself with his mac-address at the diyHue emulator. 
I would be very happy, if you can send me more information about that (or another possible) api that could fit to my plan.

**Comment by mariusmotea** [comment]
Hi,
Hope your switches have 4 or more buttons. The api is very basic and you will not have any issues to implement it. 
Device registration is done with following http GET request
`/switch?devicetype={type of the switch}&mac={mac address of the device};`
for Hue Dimmer Switch {type of the switch} is `ZLLSwitch`, for Hue Tap Switch  it is `ZGPSwitch`

 ### Button Events
http GET request
`/switch?mac={mac address of the device}&button={button code}`
 #### Hue Dimmer switch button codes
1000 = ON/Next Scene
2000 = Dim UP
2001 = Fast Dim UP (long press)
3000 = Dim Down
3001 = Fast Dim down (long press)
4000 = OFF

#### Hue Tap switch button codes
34 = big button (entire base)
16 = button 1
17 = button 2
18 = button 3

You can play with curl to test this. Once you register a device you will need to configure it from hue app

**Comment by cheesemarathon** [comment]
@hdhdu I hope Marius' answer is what you were looking for. Can I suggest that if you would like more info, you [join our Slack group](https://slackinvite.squishedmooo.com/) and chat to us there :smile: Thanks for your enthusiasm for this project, we are glad you like it. I'll look at adding Marius' answer to the wiki
