### ISSUE TITLE
Toggling Bulbs with Alexa is really slow and not all Bulbs toggle

### ISSUE THREAD

**Issue by hdhdu** [mariusmotea/diyHue#430]
I use the diyHue project with a milightHub. Everything works really great! But if I would like to toggle all Bulbs of one room with alexa, some bulbs remain on/off and don't toggle. If I toggle them with the official Hue App, all bulbs toggle on/off really fast. With alexa they are really slow and not all bulbs of one room toggle. I have to tell Alexa to turn the lights on/off two or three times until all bulbs are toggled. 
I don't know if this is just a problem with the milight hub or if it is a general problem. As mentioned, there are no problems when I use the Hue-App.

**Comment by mariusmotea** [comment]
Normally hue app must behave like Alexa, command to group with state "on": false, so i don't understand how is possible to have different behavior. Maybe i'm wrong and you can check this running the script in debug mode that show all requests received. From previews issues i know there are issues with milight hub and one user claim to improve this by adding some isolation between 2.4ghz and esp8266 board. Also is possible to increase the latency between requests to bulbs (even if you send request to one group on milight hub will be one request / light )

**Comment by cheesemarathon** [comment]
I think this is probably a Mi-Light issue as I have me genuine hue bulbs controlled via diyHue with Alexa and there is no lag and all bulbs turn off at once. Sometimes I have to ask Alexa twice but I think that's an issue with Alexa as I have always had that issue, even before using diyHue. Have a look through #382 That's the issue Marius mentioned and there are several options in there that could fix it.

**Comment by hdhdu** [comment]
Hey! 
Thank you for your reply. I have now activated the Debug-Flag, and there is a difference in the communication of alexa and the hue app!
This is the stack, when I toggle the Room with the hue app:
`192.168.178.89 - - [01/Nov/2018 21:24:10] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/2/action HTTP/1.1" 200 -
request to light 17
192.168.178.94 - - [01/Nov/2018 21:24:10] "GET /api/web-ui-79149/groups HTTP/1.1" 200 -
192.168.178.94 - - [01/Nov/2018 21:24:10] "GET /api/web-ui-79149/lights HTTP/1.1" 200 -
request to light 4
request to light 5
request to light 9
request to light 8
`

This is the stack, when I toggle the same room with Alexa:
`192.168.178.83 - - [01/Nov/2018 21:25:17] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/8/state HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:17] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5/state HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:17] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/4/state HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:17] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/9/state HTTP/1.1" 200 -
192.168.178.94 - - [01/Nov/2018 21:25:17] "GET /api/web-ui-79149/groups HTTP/1.1" 200 -
192.168.178.94 - - [01/Nov/2018 21:25:17] "GET /api/web-ui-79149/lights HTTP/1.1" 200 -
192.168.178.94 - - [01/Nov/2018 21:25:19] "GET /api/web-ui-79149/groups HTTP/1.1" 200 -
192.168.178.94 - - [01/Nov/2018 21:25:19] "GET /api/web-ui-79149/lights HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:19] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:19] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/4 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/8 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/9 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/8 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/9 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/4 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/9 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/4 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/8 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/9 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/4 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/8 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/9 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/4 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/8 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/9 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/4 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/8 HTTP/1.1" 200 -
192.168.178.83 - - [01/Nov/2018 21:25:20] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5 HTTP/1.1" 200 -`

So, there happens a lot more communication. Not just 4 put requests (I have 4 bulbs configured for this room) but also a lot of get requests for each bulb (sometimes repeating for the same bulb). 
I think this could be too much for the Rapsberry Pi 3, couldn't it?

**Comment by mariusmotea** [comment]
Interesting, Alexa control individual lights, not the group like hue app. Did you notice how fast were the PUT requests from Alexa? If these were very fast (almost instant) for sure the milight hub is overloaded. You may try also to flash again the milight hub but with the cpu set to 160Mhz (default is 80Mhz).

**Comment by mariusmotea** [comment]
Raspberry is able to heandle big number of requests, the issue is with milight hub that is not that powerfull. Maybe alexa send requests one by one and because the raspberry respond fast we see all requests in the same second. This cand be fixed by adding the same delay from groups to lights. I will provide tomorrow sample script that youn can test.

**Comment by hdhdu** [comment]
Perfect! Thank you so much for your support!

**Comment by hdhdu** [comment]
For your Information. Some Weeks ago, I tested the Script that was in your Develop-Branch with the Delay for the groups. But I found out, that i didn't need it this modification, because the group toggeling via Hue-App works perfectly and all bulbs toggles nearly simultaneously. So I switched back to the master branch version. 
That is the point, why I can hardly believe, that the problem is the milight hub. But i am looking forward to test your script modifiaction on the weekend! :)

**Comment by cheesemarathon** [comment]
So in short @hdhdu...
- Toggle mi-light groups with the app works
- Toggle mi-light groups with Alexa is slow / fails / only toggles some lights

Is this correct?

**Comment by hdhdu** [comment]
In Short:
the Alexa App cannot discover the hue groups, just the bulbs. So you have to add groups manually and map the bulbs to that group. 
So:
- Alexa toggles each bulb of one alexa group. This is slow an does not toggle all lights, if there are more than two bulbs in the alexa group.
- Togginling Hue-Groups in the hue app with the same bulbs in the Group is fast and stable.

**Comment by cheesemarathon** [comment]
@hdhdu did you manage to test Marius' changes?

**Comment by hdhdu** [comment]
Sorry for my delayed reaction. As mentioned in the other issue, I crashed my config.json while debugging with HueEmulator3.py. On stopping the program with ctrl+c while it was writing the config.json, I only had a few entries in the json. So I had to setup everything from scratch and had Problems with the hue app after that. 
But know everything is working and I was able to debug again and test the two line of code.
The good thing of the whole procedure last weekend was, that I figured out something interesting:
When searching for devices via alexa.amazon.com, it found every bulb twice with to different bulb types: "Hue Light" and "Royal Philips Electronics intelligentes Gerät". When I use the type "Hue Light", I just can control switching on/off and dimm the light. When choosing "Royal Philips Electronics intelligentes Gerät", I also can change the color and tell Alexa to set the bulb (or room) color to "warm white" or "green" etc.  
<img width="736" alt="bildschirmfoto 2018-11-11 um 09 29 40" src="https://user-images.githubusercontent.com/43926658/48312998-d9760880-e5b6-11e8-811b-1f69b49b6e99.png">

The type "Hue Light" performs a little bit better. With the other type, there are a lot of Messages, that the bulb is not compatible with all the functions, and the app says sometimes, that the bulb is not reachable, but everything seems to work. 
![screenshot_20181111-134054](https://user-images.githubusercontent.com/43926658/48313139-535ac180-e5b8-11e8-99e9-ba7afe6fcf6d.jpg)

Then I debugged toggling the lights with Alexa and I found out, that there are two ways, Alexa is toggling the bulbs.
On the first screen in the Alexa App, there is the possibility to toggle the whole group at once:
![screenshot_20181111-134124](https://user-images.githubusercontent.com/43926658/48313156-9a48b700-e5b8-11e8-93a7-25fd064caa9c.jpg)
Toggling the bulbs with this switch is really fast and without problems. The debug-log shows, that for each bulb, alexa requests the state of the bulb, then sends the request to toggle ist. After that, it requests the state of the second bulb and toggles it, and so on. 
`2018-11-11 10:34:29,648 - root - DEBUG - Sending M-Search response to 192.168.178.89
192.168.178.92 - - [11/Nov/2018 10:34:47] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/6/state HTTP/1.1" 200 -
2018-11-11 10:34:47,833 - root - DEBUG - in PUT method
2018-11-11 10:34:47,835 - root - DEBUG - /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/6/state
2018-11-11 10:34:47,837 - root - DEBUG - b'{"on": true}'
2018-11-11 10:34:47,839 - root - DEBUG - {"status": true}
2018-11-11 10:34:47,856 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.119
192.168.178.92 - - [11/Nov/2018 10:34:47] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/6 HTTP/1.1" 200 -
2018-11-11 10:34:48,027 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.119:80 "PUT /gateways/0x0C59/rgb_cct/3 HTTP/1.1" 200 102
2018-11-11 10:34:48,035 - root - DEBUG - LightRequest: http://192.168.178.119/gateways/0x0C59/rgb_cct/3
2018-11-11 10:34:48,039 - root - DEBUG - [
    {
        "success": {
            "/lights/6/state/on": true
        }
    }
]
192.168.178.92 - - [11/Nov/2018 10:34:48] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/10/state HTTP/1.1" 200 -
2018-11-11 10:34:48,176 - root - DEBUG - in PUT method
2018-11-11 10:34:48,178 - root - DEBUG - /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/10/state
2018-11-11 10:34:48,179 - root - DEBUG - b'{"on": true}'
2018-11-11 10:34:48,181 - root - DEBUG - {"status": true}
2018-11-11 10:34:48,198 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.119
192.168.178.92 - - [11/Nov/2018 10:34:48] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/10 HTTP/1.1" 200 -
2018-11-11 10:34:48,475 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.119:80 "PUT /gateways/0x0C59/rgb_cct/4 HTTP/1.1" 200 85
2018-11-11 10:34:48,483 - root - DEBUG - LightRequest: http://192.168.178.119/gateways/0x0C59/rgb_cct/4
2018-11-11 10:34:48,486 - root - DEBUG - [
    {
        "success": {
            "/lights/10/state/on": true
        }
    }
]
...`

[debuglog_working.txt](https://github.com/mariusmotea/diyHue/files/2569377/debuglog_working.txt)

 When I open the page of the room in the app, I can see all single bulbs of the group, and I am also able to toggle all bulbs at once.
![screenshot_20181111-134154](https://user-images.githubusercontent.com/43926658/48313267-1db6d800-e5ba-11e8-9ccd-fb56419af141.jpg)

Doing this, results in the same failures, as toggling via alexa voice command. 
The debug log shows, that in this way, alexa first requests the states of all bulbs in that group and then send the request to toggle all bulbs at once. Then the log shows "Request error". 
`192.168.178.92 - - [11/Nov/2018 10:33:39] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/10/state HTTP/1.1" 200 -
2018-11-11 10:33:39,529 - root - DEBUG - in PUT method
2018-11-11 10:33:39,530 - root - DEBUG - /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/10/state
2018-11-11 10:33:39,531 - root - DEBUG - b'{"on": true}'
2018-11-11 10:33:39,533 - root - DEBUG - {"status": true}
192.168.178.92 - - [11/Nov/2018 10:33:39] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/7/state HTTP/1.1" 200 -
2018-11-11 10:33:39,552 - root - DEBUG - in PUT method
192.168.178.92 - - [11/Nov/2018 10:33:39] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/1/state HTTP/1.1" 200 -
2018-11-11 10:33:39,557 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.119
2018-11-11 10:33:39,558 - root - DEBUG - /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/7/state
2018-11-11 10:33:39,559 - root - DEBUG - in PUT method
2018-11-11 10:33:39,563 - root - DEBUG - b'{"on": true}'
2018-11-11 10:33:39,565 - root - DEBUG - /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/1/state
2018-11-11 10:33:39,566 - root - DEBUG - {"status": true}
192.168.178.92 - - [11/Nov/2018 10:33:39] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/10 HTTP/1.1" 200 -
2018-11-11 10:33:39,567 - root - DEBUG - b'{"on": true}'
2018-11-11 10:33:39,576 - root - DEBUG - {"status": true}
2018-11-11 10:33:39,609 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.119
2018-11-11 10:33:39,617 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.119
192.168.178.92 - - [11/Nov/2018 10:33:39] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/7 HTTP/1.1" 200 -
192.168.178.92 - - [11/Nov/2018 10:33:39] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/1 HTTP/1.1" 200 -
192.168.178.92 - - [11/Nov/2018 10:33:39] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/6/state HTTP/1.1" 200 -
2018-11-11 10:33:39,668 - root - DEBUG - in PUT method
2018-11-11 10:33:39,670 - root - DEBUG - /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/6/state
2018-11-11 10:33:39,671 - root - DEBUG - b'{"on": true}'
2018-11-11 10:33:39,673 - root - DEBUG - {"status": true}
2018-11-11 10:33:39,691 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.119
192.168.178.92 - - [11/Nov/2018 10:33:39] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/6 HTTP/1.1" 200 -
192.168.178.92 - - [11/Nov/2018 10:33:39] "PUT /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5/state HTTP/1.1" 200 -
2018-11-11 10:33:39,764 - root - DEBUG - in PUT method
2018-11-11 10:33:39,766 - root - DEBUG - /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5/state
2018-11-11 10:33:39,767 - root - DEBUG - b'{"on": true}'
2018-11-11 10:33:39,768 - root - DEBUG - {"status": true}
2018-11-11 10:33:39,789 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.119:80 "PUT /gateways/0x0C59/rgb_cct/4 HTTP/1.1" 200 85
2018-11-11 10:33:39,791 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.119
192.168.178.92 - - [11/Nov/2018 10:33:39] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights/5 HTTP/1.1" 200 -
2018-11-11 10:33:40,046 - root - DEBUG - Sending M-Search response to 192.168.178.89
2018-11-11 10:33:41,450 - root - DEBUG - Sending M-Search response to 192.168.178.89
2018-11-11 10:33:41,918 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.119:80 "PUT /gateways/0x0002/rgb_cct/1 HTTP/1.1" 200 101
2018-11-11 10:33:41,925 - root - DEBUG - LightRequest: http://192.168.178.119/gateways/0x0002/rgb_cct/1
2018-11-11 10:33:41,928 - root - DEBUG - [
    {
        "success": {
            "/lights/7/state/on": true
        }
    }
]
2018-11-11 10:33:42,079 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.119:80 "PUT /gateways/0x0C59/rgb_cct/1 HTTP/1.1" 200 102
2018-11-11 10:33:42,086 - root - DEBUG - LightRequest: http://192.168.178.119/gateways/0x0C59/rgb_cct/1
2018-11-11 10:33:42,089 - root - DEBUG - [
    {
        "success": {
            "/lights/1/state/on": true
        }
    }
]
2018-11-11 10:33:42,118 - root - DEBUG - LightRequest: http://192.168.178.119/gateways/0x0C59/rgb_cct/4
2018-11-11 10:33:42,120 - root - DEBUG - [
    {
        "success": {
            "/lights/10/state/on": true
        }
    }
]
2018-11-11 10:33:42,700 - root - DEBUG - request error
2018-11-11 10:33:42,703 - root - DEBUG - [
    {
        "success": {
            "/lights/6/state/on": true
        }
    }
]
2018-11-11 10:33:42,804 - root - DEBUG - request error
2018-11-11 10:33:42,806 - root - DEBUG - [
    {
        "success": {
            "/lights/5/state/on": true
        }
    }
]
2018-11-11 10:33:43,254 - root - DEBUG - Sending M-Search response to 192.168.178.89
2018-11-11 10:33:44,958 - root - DEBUG - Sending M-Search response to 192.168.178.89`

[debuglog_not_working.txt](https://github.com/mariusmotea/diyHue/files/2569379/debuglog_not_working.txt)

I played around with the script of @mariusmotea . But it doesn't change anything. I raised the sleep value up to 0.8. But then there came timeout errors in the debug log. 

So I thing, @mariusmotea is right and I have to speed up the milight-hub. But I can't test it until know, because I have to setup the sdk for changing the prgram. I used a precompiled bin file, and flashed the mcu with that binary. 
But I ordered the "newer" ESP32 which has a better MCU than the ESP8266. I will try to get Milight-hub running on that board. And hopefully the problems are gone :)

I hope, that my debugging and detailed description is helping anyone with the same problems.

I will report if the new board solves the problem, but I will be able to test it in two weeks, because I have to travel a lot the next days.

**Comment by cheesemarathon** [comment]
@hdhdu Thanks for the info, I'll wait for your update on the ESP32 :smile:
