### ISSUE TITLE
Expecting property name enclosed in double quotes: line 1306 column 21 (char 41005)

### ISSUE THREAD

**Issue by NedSin** [mariusmotea/diyHue#432]
Hello, 
i love this emulator and want to make my house complete smart with this to controll everything over hue app. 

Used is:

Raspberry Pi 3B+ 
RaspBee Modul with Deconz
This Hue Emulator
hdmi screen 

Yesterday evening i try to connect diyhue with Alexa
The Alexa app take me to meethue and (i was totally wondering) it works to connect the skill ... 
After that nothing works anymore ...

Here is the log from HueEmulator3.py:

`pi@raspberrypi:/opt/hue-emulator $ python3 HueEmulator3.py
ERROR:root:CRITICAL! Config file was not loaded
Traceback (most recent call last):
  File "HueEmulator3.py", line 253, in <module>
    bridge_config = json.load(fp)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1306 column 21 (char 41005)
`

And here the log from systemctl status hue-emulator:

`pi@raspberrypi:/opt/hue-emulator $ sudo systemctl status hue-emulator
 hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-11-01 22:50:26 UTC; 1 day 1h ago
  Process: 2368 ExecStop=/usr/bin/curl http://127.0.0.1/save (code=exited, status=7)
  Process: 2321 ExecStart=/opt/hue-emulator/HueEmulator3.py (code=exited, status=1/FAILURE)
 Main PID: 2321 (code=exited, status=1/FAILURE)

Nov 01 22:49:56 raspberrypi systemd[1]: hue-emulator.service: Unit entered failed state.
Nov 01 22:49:56 raspberrypi systemd[1]: hue-emulator.service: Failed with result 'exit-code'.
Nov 01 22:50:26 raspberrypi systemd[1]: hue-emulator.service: Service hold-off time over, scheduling restart.
Nov 01 22:50:26 raspberrypi systemd[1]: Stopped Hue Emulator Service.
Nov 01 22:50:26 raspberrypi systemd[1]: hue-emulator.service: Start request repeated too quickly.
Nov 01 22:50:26 raspberrypi systemd[1]: Failed to start Hue Emulator Service.
Nov 01 22:50:26 raspberrypi systemd[1]: hue-emulator.service: Unit entered failed state.
Nov 01 22:50:26 raspberrypi systemd[1]: hue-emulator.service: Failed with result 'exit-code'.
`

Before i install all new perhaps someone have an fix for me ... 

thank you for reading ...

Ned

**Comment by NedSin** [comment]
Hello,
Thank you for your idea...
When I come from work I try it and Report Here. 

When it is a corrupted json I have to Set everything New? 

I so no Backup in This three days :(
But This is my problem..  

Thank you...

Best Greetings 
Ned

**Comment by mariusmotea** [comment]
Check what is missing from corrupted config. If you have the lights and the groups thrn you can copy them in fresh config. Scenes and rules can be re created

**Comment by NedSin** [comment]
Hey together, 
the problem is solved it was the config json. 
After i put a new one it works perfekt. 

I configured all new, but this was no problem.
Now i`m on the same problem like before: Alexa !!! 

I think i will find the way and do a stupid mistake by reading the wiki ... 

Thank you for your help. 

This problem is Solved ... 

Greetings 
Ned
