### ISSUE TITLE
Cannot add rooms and devices

### ISSUE THREAD

**Issue by petjek** [mariusmotea/diyHue#436]
After successfully installing the bridge on a raspberry pi zero I can add the bridge using the v2 Hue app but no rooms or lights can be found. 
I configured one of my tasmota devices to emulate a hue light. 
Tried iOS and Android app

**Comment by cheesemarathon** [comment]
There will not be any rooms by default. These will have to be created in the app. Which Tasmota device are you using. Have you flashed it with the firmware in this repo?

**Comment by petjek** [comment]
I tried a Shelly 1 on 6.2.1.18 and a Sonoff basic on 5.11.1. Both flashed with firmware from Theo‘s repository. 
Adding a room using the Hue app is exactly what fails. I can see the device but after entering a name and room type the process just starts over and over again.

**Comment by mariusmotea** [comment]
I don't believe you are using this emulator, for this reason you faced this issue. In order to use this you need the emulator on one device (Linux device like Raspberry PI) and then you need to flash the firmware's from here, not from other repository on the Sonoff device.

**Comment by petjek** [comment]
This is even going weirder. Using my iPhone the Hue app doesn't find a device. Doing the same using my Android tablet finds a device but will not let me add a room due to an error message like "cannot add standard scene. the bridge is full". The message is in German and this is a rough translation. Means I have to delete some scenes where there are no scenes yet?

**Comment by mariusmotea** [comment]
From what i know tasmota firmware has its own hue bridge emulator that lack several functions. Very likely you pair your app with that device. In the history of this emulator nobody complain about rooms creations or scenes creation.

**Comment by petjek** [comment]
@mariusmotea where to find a tasmota FW here?

**Comment by mariusmotea** [comment]
This has nothing to do with tasmota firmware. Is a project with his own firmwares.
