### ISSUE TITLE
QUESTION:  Hue Bulbs

### ISSUE THREAD

**Issue by ryancasler** [mariusmotea/diyHue#447]
If you have a zigbee module, can this act as a HueBridge for regular Hue bulbs?  Or do you also need a regular hue bridge to connect the Hue bulb to?

**Comment by mariusmotea** [comment]
If you have the Raspbee/Conbee module you don't need additional bridge. That device act as ZigBee coordinator like Hue Bridge/Ikea Gateway, etc.

**Comment by ryancasler** [comment]
Thanks!
