### ISSUE TITLE
Stips are Linked in Hue app and DIYHue page

### ISSUE THREAD

**Issue by ryancasler** [mariusmotea/diyHue#455]
I have created two separate LED strips with ESP8266 boards.  They are totally separate from each other.  However, the Hue app and the DIYHue webpage, always link them together.  When I turn on one, it reports that the other is turned on as well, even though it is not.  I do not want them linked at all.  I want them to be controlled separately.  Why can't I do that? It does not appear to be a bug in the board software but in the hub-emulator.  Do I need to have a hub emulator for every light that I am going to add?  Is there any way to correct this?

**Comment by mariusmotea** [comment]
You may use https://github.com/probonopd/ESP8266HueEmulator but the project remain out of support and is not maintained. I don't believe this is an issue with hue-emulator, it cannot receive a request for one light and forward this in a loop to more lights. Must be a totally different issue and you can identify this if you enable debug mode and see requests flow.

**Comment by mariusmotea** [comment]
> Do I need to have a hub emulator for every light that I am going to add? Is there any way to correct this?

Sorry, i miss this, you need only one device that act as hue emulator, then you may use as many lights as you want.

**Comment by ryancasler** [comment]
I used the WS2812BHueStrip.ino file in your repo.  I thought that was your implementation?  What do i have to erase from my RPi to clear all the current synced lights?  I think it might be a problem that they are linked as an artifact that I had them in the same room previously, even though they are now in separate rooms.

**Comment by ryancasler** [comment]
That's very odd....it seems that stopping and starting the service got them unlinked.  They no longer reflect each other in the hue app or anywhere else.  That's very odd.  But hey, don't argue with a working thing, right?  Thanks for your help.
