### ISSUE TITLE
Config.json How to set a device with on and off cmd?

### ISSUE THREAD

**Issue by fellnermedia** [mariusmotea/diyHue#460]
Hey Guys,

how can i set a device in the config file with a on and off command like /root/433/send 12354 4 1 ?
Is this possible?

**Comment by Mevel** [comment]
Do you try to use 433mhz devices?

**Comment by Mevel** [comment]
Not sure what your goal is here...

**Comment by Mevel** [comment]
In conclusion from your previous post, I think you want to control 433mhz devices.

Have a look at the 433mhz sketch and schematic. In the end you will have multiple virtual lights in your app that will control one channel each of your 433mhz device group.

Hope that helped

**Comment by fellnermedia** [comment]
i would like to config a hue device in the config file to toggle as a switch. 
if the device is configured. than logitech harmony can toggle the 433Mhz Power Switch.
but how can i create a virtual light for a 433Mhz Switch?

**Comment by Mevel** [comment]
So you want to use your harmony to control a real 433mhz power socket via Diyhue?

**Comment by fellnermedia** [comment]
yeees

**Comment by Mevel** [comment]
You need a 433mhz transmitter to translate the hue commands to 433mhz protocol. View sketch and pictures in lights section.

**Comment by Mevel** [comment]
Solved? Or do you neet more help? Let us know

**Comment by cheesemarathon** [comment]
Closing for now, re-open if you need more help @fellnermedia
