### ISSUE TITLE
Yeelight with Motion sensors?

### ISSUE THREAD

**Issue by j0nasjuul** [mariusmotea/diyHue#463]
I've have ordered a few Yeelight RGB bulbs that I want to emulate as Philip Hue bulbs with this project. I have the Philips Hue starter kit with a v2.0 bridge and 3x original hue bulbs. I want to control both the original bulbs and the yeelight bulbs with the emulated bridge and keep the hue bridge when software needs to be updated.

I really want to include some motion sensors in my setup but I'm confused if the only option is to use Philips' own hue motion sensors for my setup? Been reading a little about the IKEA Trådfri sensors but they can't be paired with a hue bridge only with the Trådfri bulbs itself.

What options do I have for motion sensors with this setup?

**Comment by mariusmotea** [comment]
With what you have will not work because original hue bridge don't export the motion sensor events to 3rd party services. Only solution for you is Rasbee module that can eliminate your original hue bridge totally,

**Comment by cheesemarathon** [comment]
Question answered, can be closed. If further info is required, please open a new issue at the new repo [here](https://github.com/diyhue/diyHue)
