### ISSUE TITLE
Hue app wanting to update DiyHue

### ISSUE THREAD

**Issue by patrol420** [mariusmotea/diyHue#468]
hey guys, got the Diyhue setup on a labtop running debian. 
when i try to pair the bridge to hue app it wants to update the emulator? any suggestions version says 1810251352

**Comment by cwildfoerster** [comment]
@patrol420 Did you find a solution for this?

**Comment by patrol420** [comment]
Yes i did. I restarted the diyhue server and reinstalled hue apps, works great now not sure what caused it

**Comment by At-M** [comment]
This still problem persists, i updated diyhue and even stopped/started the service, reinstalled hue apps and it didn't help.
Hue always tells me to install the v1 app, but that app wants me to update my bridge.

**Comment by mariusmotea** [comment]
probably you don't have internet on bridge. In this care you need to manually stop the service and change swversion under "config" to 1934129020

**Comment by mariusmotea** [comment]
BTW you use legacy brench. Diyhue was moved here https://github.com/diyhue/diyHue
