### ISSUE TITLE
[Hue Entertainment]Create area needs light update on WS2812B

### ISSUE THREAD

**Issue by xfader2018** [mariusmotea/diyHue#471]
Trying out Hue Entertainment for the first time with latest Hue Emulator and WS2812B ino.

When creating area in the Philips Hue app (v3.11.0 10308) on iOS it wants to update lights first. Choosing update results in looking for update loop.

The led strip is currently using 1.46.13_r2612

**Comment by mariusmotea** [comment]
Fixed, just update the program exactly like you install it.

**Comment by xfader2018** [comment]
Confirmed working! Thanks for this fast fix!

**Comment by mariusmotea** [comment]
Welcome. I was the one that cause the issue by updating also this to newest firmeare version while this is not applicable to strips.
