### ISSUE TITLE
Raspbee module does not work / can't open webconfigpage for Raspbee module

### ISSUE THREAD

**Issue by braini1511** [mariusmotea/diyHue#473]
After working through the installation steps i am not able to load the config-page for the Raspbee module to add the zigbee lights. 

serialport is on; loginshell is off
deconz.service was change as shown in the getting-started-guide with port 8080 upnp=0 and ws-port to 8081

safari shows just can't establish connection to server, seems to be offline.
the normal hue-brigade-emulator-site works fine, can be opened and lights can be switched and so on.

Any hints or tips for getting this work? Is this more a DIYHUE Issue or should i get the people from Dresden-electronics involved?

**Comment by Mevel** [comment]
you could try to make a direct API call and see if you get some Json data back

`http://IPofRaspberry:8080/api/myApiKey`

even without a valid api key, you should get a "error" json feedback

**Comment by mariusmotea** [comment]
For me this looks to be a problem with Deconz. You may have the serial pins broken also on you PI.

Try following command that will reset the Rasbee module in case it is detected:

```
pi@raspberrypi:~ $ sudo GCFFlasher_internal -r
rmmod: ERROR: Module ftdi_sio is not currently loaded
rmmod: ERROR: Module usbserial is not currently loaded
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
no device specified use RaspBee (/dev/ttyS0)
reset target SUCCESS

```

**Comment by braini1511** [comment]
@Mevel your hint docs not work, it comes the same error in Safari, saying Safari is not able to connect to the server

@mariusmotea  Your Reset worked, the feedback looked exactly the same like yours, but didn't work to.
I don't think the UART is broken, because the PI is completely new and the Raspbee module too.

Any other ideas? :/

**Comment by braini1511** [comment]
when i check the bootleg i find this here more than one item...
Dec 22 12:00:16 raspberrypi deCONZ-update2.sh[253]: no database file (zll.db) found
But this can be normal, because i didn't finished the configuration....

**Comment by Mevel** [comment]
Did you run it with root privileges?

sudo systemctl start deconz.service

It says authentication failed, access denied.

**Comment by braini1511** [comment]
@Mevel right! after starting the service by hand via sudo systemctl start Deconz.service it works!
So maybe the service is not in autostart?

**Comment by braini1511** [comment]
So connection could now be established, but there comes then a search fat Phoscon Gateways. Not sure what i i expected, but it feels wrong. It searches multiply times for any Gateways from Dresden Electronics instead giving me the chance to add any Zigbeelights...

**Comment by mariusmotea** [comment]
Maybe deconz is running fine with no rasbee module detected. Check the command i provide that is doing low level detection of the Rasbee module. Maybe you have friends with rasberry pi so you can check the module on another one to exclude your gpio pins are not working.

**Comment by Mevel** [comment]
@braini1511 write to me on slack and I can provide you with some German support if you want. Once we find the solution we can post it here.

**Comment by braini1511** [comment]
I never worked with slack. I created a channel.
https://join.slack.com/t/dyihuehelpdesk/shared_invite/enQtNTEyNjI2MTg3OTczLTE0NjkyNTExNTBlNGVjOTcyNDEyOWEyN2NkZDBhNjVmMDk0ODViNDJlZjBmYTRhMmI5MGE4MDhlNjlkNWM1YzM

Pass is 1234567890!

**Comment by braini1511** [comment]
Ok after chatting with Dresden electronics the Problem is Safari. i used now Chrome and everything is fine.

Thanks for your help!

**Comment by Mevel** [comment]
@braini1511 we already have a slack group. Diyhue.slack.com

**Comment by braini1511** [comment]
@Mevel 
could you please send me an invite?

**Comment by Mevel** [comment]
https://slackinvite.squishedmooo.com/
