### ISSUE TITLE
Hue Ring - Only Center Lights up?

### ISSUE THREAD

**Issue by robotica72** [mariusmotea/diyHue#474]
Been playing with this for some time today and the web server on the ESP lights up all the lights, and the initial sequence looks good, lights - lights spin starting from the inner to the outer and are white, then red, then green.

The emulator also lights up only the center LED if I turn it on from the webpage - Im using the Docker version if that has any impact on the issue.

Hue sees the ring but any setting is only turning on the single center LED in the ring?   Not sure what to look at to make it light up the entire ring?

**Comment by mariusmotea** [comment]
Check if:

1. Did you properly set the number of leds per every ring in sketch header.
2. Did you set the number of the lights to the number of rings?
3. If you changed the number of lights is mandatory to delete current virtual lights registered from this esp device and perform new light search.

**Comment by robotica72** [comment]
Thanks for the reply.   Im using the sketch from the ring example, so I assumed it wouldnt need any modifications?   Its set for:

#define light_name "WS2812 Hue Ring"  //default light name
#define lightsCount 3
#define pixelCount 61
uint16_t pixelStart[lightsCount + 1] = {0, 1, 21, pixelCount};

But using the Hue app it only lights up the singe light in the middle (1 LED) - Using the web page direct to the ESP and turning it on will turn on all the lights (So I thought that would confirm the sketch settings??)

**Comment by mariusmotea** [comment]
How many lights were detected, one or three? From what you explain is jut one that represent the center pixel. If this is the case try to delete the light and search again for new lights.

**Comment by robotica72** [comment]
Thanks for the help - I deleted the exising light and it did then detect 3 lights now and they all work :)

Thanks for the sketches and the emulator - Great work!
