### ISSUE TITLE
Cant get the Hue app to see the diyhue bride 

### ISSUE THREAD

**Issue by GeminatedEntropy** [mariusmotea/diyHue#477]
Hi 

Im sorry if this has been asked a lot. i cant get the Hue App to connect to the Diyhue. 
i  have a 3b+ and have follow the steps on the below host install link 
https://github.com/diyhue/diyHue/wiki/Host-Install

when it come to connect the diyhue bridge, the Hue app see the new bridge but i cant seam to login when going to the diyhue bridges IP 

Have a missed a step out, very new to all this, i can follow instruction well but i know zero code  

Thanks

**Comment by Mevel** [comment]
Hey and Welcome!

Did you follow the instructions on the [Getting Started](https://github.com/diyhue/diyHue/wiki/Getting-started) Page?

You need to "push" the Pairing Button on diyHue in order to allow pairing between APP and diyHue?

You can find it here: `http://{IP_ADDRESS}/hue/linkbutton` Credentials: `Hue:Hue`

**Comment by GeminatedEntropy** [comment]
Hi Mevel 

Thank and  thanks for the response
Im stack at that point, i have put in the Hue and Hue details, moved to the next screen 
I cant get passed activation. my app see the new bridge, do i leave this page blank or do i fill in my details ?

Thanks

**Comment by Mevel** [comment]
You only need to push the "activate" button and then you have 30 seconds to search and connect your hue smartphone app

**Comment by GeminatedEntropy** [comment]
any suggestion on how to trouble shoot the problem?

**Comment by mariusmotea** [comment]
In wiki we have debug. With 3b you may have the issue if you connect both the wired and wireless interfaces. Provide the curl command output described in debug page to see what you have there

**Comment by GeminatedEntropy** [comment]
Hi Mariusmotea

perfect all sorted now, i just started again with connecting the Ethernet cable :) 

Thanks both of you for all you help :)
