### ISSUE TITLE
Use with ESP-01

### ISSUE THREAD

**Issue by quorle** [mariusmotea/diyHue#480]
I have a question. I tried to use the whole thing with an ESP-01 (LED-Stripes WS2812b). However, the whole thing does not work. what could be the problem? or is this only possible with a Wemos d1 Mini?

**Comment by mariusmotea** [comment]
- Ensure you select the proper flash type 
 -  and size when you write this in Arduino. 
 - Choose to wipe entire flash. 
 - Avoid beta libraries

**Comment by quorle** [comment]
Unfortunately does not work

3,3V —> VCC
3,3V —> CH_PD
0V    —> gnd
LED‘s —> Tx

**Comment by quorle** [comment]
Unfortunately, I have now 5 hours trying to get it to work, unfortunately without success. actually I wanted to integrate in your project a MQTT with pubsubclient to publishen, unfortunately, is not. But I do not want to use two wemos for a light sensor, motion sensor and LED stripes.

**Comment by mariusmotea** [comment]
From my point of view the only limitation may be with the spi flash. It may be too small. The esp chip is the same on all boards. I faced same issue with one chinese rgbw bulb, i fix that by replacing just the spi chip with the one from a broken wemos.

**Comment by cheesemarathon** [comment]
@quorle I'm closing this as we have provided you with what we feel to be the issue. If your still having problems, feel free to open a new issue at our active repo [here](https://github.com/diyhue/diyHue)

**Comment by GHBLoos** [comment]
Quorle,

You still need help with this? I have a working example. 

Gaston
