### ISSUE TITLE
ConBee Philips Play light bar - Entertainment

### ISSUE THREAD

**Issue by davidreher** [mariusmotea/diyHue#482]
**Describe the bug**
I bought a Play light bar and coupled the lights through PhosCon/DeCONZ, as I don't have a hue bridge. After sucessfully linking the lights and assigning them to a seperate room, I wanted to create an entertainment area which does not work (Update required).

**To Reproduce**
1. Go to DeCONZ
2. Link newly bought Play light bar
3. Create a new room in Philips Hue App
4. Add the lights to the new room
5. Create a new entertainment area
6. Add the lights from the newly created room

**Expected behavior**
The lights can be added to the entertainment area without an update.

**Logs**

**Additional context**
Here are the config entries:
deconz.lights:
```
            "2": {
                "bridgeid": "2",
                "modelid": "LCT024",
                "type": "Extended color light"
            },
            "3": {
                "bridgeid": "3",
                "modelid": "LCT024",
                "type": "Extended color light"
            }
```
lights:
```
  "2": {
            "ctmax": 500,
            "ctmin": 153,
            "etag": "7e165064320127437ddd1861bf908eb6",
            "hascolor": true,
            "manufacturername": "Philips",
            "modelid": "LCT024",
            "name": "Light 3",
            "state": {
                "alert": "none",
                "bri": 254,
                "colormode": "ct",
                "ct": 366,
                "effect": "none",
                "hue": 8418,
                "on": true,
                "reachable": true,
                "sat": 140,
                "xy": [
                    0.457343,
                    0.410025
                ]
            },
            "swversion": "1.30.4_r23032",
            "type": "Extended color light",
            "uniqueid": "00:17:88:01:04:2e:4f:71-0b"
        },
        "3": {
            "ctmax": 500,
            "ctmin": 153,
            "etag": "7e165064320127437ddd1861bf908eb6",
            "hascolor": true,
            "manufacturername": "Philips",
            "modelid": "LCT024",
            "name": "Light 2",
            "state": {
                "alert": "none",
                "bri": 254,
                "colormode": "ct",
                "ct": 366,
                "effect": "none",
                "hue": 8418,
                "on": true,
                "reachable": true,
                "sat": 140,
                "xy": [
                    0.457343,
                    0.410025
                ]
            },
            "swversion": "1.30.4_r23032",
            "type": "Extended color light",
            "uniqueid": "00:17:88:01:04:fb:e8:8c-0b"
        }
```
There is no update available in deconz

The lights show Firmware 1.30.4_r23032 in DeCONZ.

I also found #282 but didn't know what to apply for light bars ... How can i modify the files in docker setup?

**Comment by mariusmotea** [comment]
I have a bad news. Entertainment is custom zigbee function and last time i check Deconz did not support it. The reason you see the lights as outdated is probably becase the firmware version is not the last one. You can manually update this in config.json file as the entertainment protocol will still not work and you can use them via hue emulator entertainment function that drop ~80% frames until you get about one update / second. It will be lazy but for music will be ok

**Comment by mariusmotea** [comment]
Plan B that i don't recommend unles you are an expert that really know what he is doing, replace the zigbee module in the light bar with an esp board like wemos d1 mini. Entertainment will work like expected.

**Comment by davidreher** [comment]
How about plan C: Add a hue bridge into the system? Can I control it through diyHue?

**Comment by mariusmotea** [comment]
Reverse the order, that should be the plan B. Diyhue is able to control the lights behind a hue bridge. Hue entertainment don't work, but you can pair apps lile hue sync directly to original bridge.
