### ISSUE TITLE
After Updating everything Discover new light doesnt work with SK6812

### ISSUE THREAD

**Issue by recepg89** [mariusmotea/diyHue#483]
I Have updated to a new RGBW Strip (which works nice). But After the update, the other lights (3 SK6812 with different leights wont get discovered.

I already reinstalled HueEmulator with fresh Raspbian Lite
I tried a complete new ESP8266 (Wemos) to upload the code. The same behavior.

These 3 wont get discovered. 
{"hue": "strip","lights": 1,"modelid": "LST002","mac": "B4:E6:2D:15:xx:xx"}
{"hue": "strip","lights": 1,"modelid": "LST002","mac": "60:01:94:49:xx:xx"}
{"hue": "strip","lights": 1,"modelid": "LST002","mac": "B4:E6:2D:23:xx:xx"}

As you can see they dont have a name. I tried using different names and the default name without any changes.

This one works just fine.
{"hue": "bulb","lights": 1,"modelid": "LCT015","name": "Hue RGBW Light","mac": "B4:E6:2D:23:xx:xx"}

I hope there is a easy explanation how to solve this. Thanks for all the awesome work.

**Comment by mariusmotea** [comment]
Flash the Wemos by selecting SPIFFS storage , ex 4M with 3M SPIFFS or other sizes but ensure you have at last 512KB of SPIFFS.

**Comment by recepg89** [comment]
![Unbenannt](https://user-images.githubusercontent.com/15050815/55820358-41dffc00-5afb-11e9-995f-2c901995f170.png)

It already is.

**Comment by recepg89** [comment]
I have just seen that i was using an old version of ESP8266 (boards)
will try with the updated version

**Comment by recepg89** [comment]
Updated everything Arduino Software based. Uploaded the code. Still no name, will not be recognized

**Comment by mariusmotea** [comment]
Please use the lights from here: https://github.com/diyhue/Lights

this repo is outdated.

**Comment by recepg89** [comment]
Thank you very much... Now i am feeling dumb... it works fine...
