### ISSUE TITLE
Raspberry Pi2 SD-Disk-Image possible?

### ISSUE THREAD

**Issue by lightrunner86** [mariusmotea/diyHue#484]
Hello, I'd like to hook some DIY&WLED ESP8266 bulbs to PhilipsTV Ambilight/Hue. As i see this is possible with rasp.2. (Sorry I'm not firm with Linux that much (win10x64)) 
Can i somehow create a sd-disk-image and install it via win32diskimager, for example, like "Kodi- Mediacenter" & just plug the SD-Card?.
.....Sorry if this question is somehow nooobiee^^

**Comment by cheesemarathon** [comment]
Unfortunately not, we don't provide a preconfigured disk image. I cant realy think of any alternative. I'd just suggest following the instructions and asking for help on our slack chat if you need it.

**Comment by lightrunner86** [comment]
ok, after some hours i got docker running.... is there a way to copy&paste this here: 
docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' diyhue/core:latest

into the vm??? -
Typing isn't really working, cause i'm not finding a way to tell the Docker VM that my laptop is having German Keyboard-Layout. :-/ 

anyone pls having a chance telling me how to get that image to the SD-Card?
thanks very much.

**Comment by mariusmotea** [comment]
But is very easy to install official Raspbian image, ssh with default credentials (use putty, ip can be retrieved from your router) and paste the below command. 

`curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin`

At the end you will have the bridge emulator ready. Remember that every reinstallation of the bridge require to reinstall the hue app.

**Comment by lightrunner86** [comment]
Hello, i already treied this way , the App find's the "emulated" Bridge,
but then it wants me to Press the Button in the middle (but Raspberry Pi
hast no Button for pairing)?
Must i execute a command in the same time?
Regards

Motea Marius <notifications@github.com> schrieb am Sa., 18. Mai 2019, 00:09:

**Comment by mariusmotea** [comment]
Open with any browser the ip of the bridge emulator. There you have "Link Device" in menu. The default creentials are Hue/Hue
