### ISSUE TITLE
No ESP8266 WiFi

### ISSUE THREAD

**Issue by bLIZZo87** [mariusmotea/diyHue#486]
Hi mariusmotea, thanks for this incredible Project. I Love the Hue System but i hate this idiot LED-Strips from Philips, Innr etc.

Now i found your Project and i want set the Generic_WS2812_Strip on my Wemos d1 mini. But i never had a WiFi after Flash. I have tried many different Strips but it has worked only the WS2811_adjustable with a WiFi SSID

I used 
- ArduinoJson  6.10.0
- WiFiManager 0.14.0

Am I the only one with these problems?
I hope someone can tell me what I'm doing wrong. I would love to start your project

Sorry for my bad English, i understand it but i cant speak or write it.

bLIZZo

**Comment by mariusmotea** [comment]
Hi,

On of most common mistakes a user can do is to flash the esp board (Wemos in your case) without choosing SPIFFS storage. I recommend 2MB SPIFFS for a 4MB ESP board (like Wemos D1 Mini). This option is located under [board menu](https://2.bp.blogspot.com/-lYn-TiglzT8/WbVTjqC8qTI/AAAAAAAAN7U/wY72gMqeVn0WCyLwNFXFSa32hWUeI6ihgCLcBGAs/s1600/1.png). Also is good to select to wipe entire flash (option available also under board menu)

**Comment by bLIZZo87** [comment]
Thanks my Friend, it works now.
You are my Hero!
Can i giv you a donate for your great work?

**Comment by mariusmotea** [comment]
@bLIZZo87 you can donate to any local charity organisation. I sustain the organisations that help kids with autism.
