### ISSUE TITLE
Issue with HUE SYNC (Latest Version)

### ISSUE THREAD

**Issue by MopheusDG** [mariusmotea/diyHue#487]
I was able after some fighting to get my RPi3 Bridge working (Using Docker image on RPi3) and also tried just installing on the RPi3 via Autoinstall (Without luck there), but the Docker works fine. I can see now the IP of the Bridge, my ESP8266 lamp and everything works fine except from HUE SYNC from my PC.

What I can see:
- The Bridge via web shows the Entertainment Area lights fine, they even switch colors inside the web.
- The Hue Sync syncs with no problem, the color match what I can see on the bridge lamp colors.

But:
- The Wemos ESP8266 light does not mimic the colors, just does nothing. I can change the color via the Philips HUE App on my cell, i can change the color via the webpage of the Lamp, but does not sync with HUE Sync for some reason.

Any ideas ? I can provide logs with some assistance.

Thanks.

**Comment by strohapfel** [comment]
hi,
I´ve just run into the same problem. 
Everything works like a charm, accept for all services, that use hue entertainment. Have you found any soulution, to fix this issue, yet?

Best Regards.
