### ISSUE TITLE
Original Hue Bridge + WS2812B + Wemos D1 Mini Question

### ISSUE THREAD

**Issue by CloudChaser07** [mariusmotea/diyHue#490]
Hi 

I have a general question I have already assembled my hardware 
( Hardware: Original Hue Bridge ( New Gen ) a Wemos D1 mini and a WS2812B Strip.) 

Can I run the strip in the constelation or do I need something else?

**Comment by Mevel** [comment]
You need the hue emulator software. In general you don't need a hue bridge if you don't use genuine bulbs.

All you need is:

Raspberry pi or any other computer running 24/7 with hue emulator
Esp8266 based controller like the wemos d1 mini and leds like the ws2812
