### ISSUE TITLE
Bugs in lightengine of Generic_Dimmable_Light.ino

### ISSUE THREAD

**Issue by Solibas** [mariusmotea/diyHue#491]
Description: 
- Code controls set not the right pins in lightengine-function. Only the value of 'i' will be set (line 79 and 88):
analogWrite(i, (int)(current_bri[i])); -> analogWrite(pins[i], (int)(current_bri[i]));
- The new hue-bridge-emulator need the 'name'-option, so there is a bug in line 295:
server.send(200, "text/plain", "{\"hue\": \"bulb\",\"lights\": " + (String)LIGHTS_COUNT + ",\"modelid\": \"LWB010\",\"mac\": \"" + String(mac[5], HEX) + ":"  + String(mac[4], HEX) + ":" + String(mac[3], HEX) + ":" + String(mac[2], HEX) + ":" + String(mac[1], HEX) + ":" + String(mac[0], HEX) + "\"}");
->
server.send(200, "text/plain", "{\"hue\": \"bulb\",\"lights\": " + (String)LIGHTS_COUNT + ",\"modelid\": \"LWB010\",\"name\": \"GenDimLight\",\"mac\": \"" + String(mac[5], HEX) + ":"  + String(mac[4], HEX) + ":" + String(mac[3], HEX) + ":" + String(mac[2], HEX) + ":" + String(mac[1], HEX) + ":" + String(mac[0], HEX) + "\"}");

**Comment by mariusmotea** [comment]
Hi,

Please note that this repo is legacy. I take a look in the new one located [here](https://github.com/diyhue/Lights/blob/master/Arduino/Generic_Dimmable_Light/Generic_Dimmable_Light.ino) and the fix seams to be in place.

**Comment by Solibas** [comment]
Ok, sry. Thx, for the answer and a great project!
