### ISSUE TITLE
I can't connect Hue emulator to meethue

### ISSUE THREAD

**Issue by Ceri48** [mariusmotea/diyHue#492]
Hi all
To begin I want to clarify that I am French and my English is bad. Im sorry and i hope you understand me anyway: D

I need help, i can't connect hue emulator to meethue, and https://www.meethue.com/api/nupnp return me "[]".

I can find the emulate bridge with app Hue on my phone (iOs) and use it.
I config static IP and i open port 80 and 443 on my router.
I try add the bridge with the sharing connection on my Phone but i fail too.
I install on my raspberry pi 3b+ with docker and i try install my raspberry nano on host install with command
"curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin" i fail too.

I'm starting to wonder if it's possible to connect the bridge emulate with the phillips account. if you have a solution it would be great :)

**Comment by Mevel** [comment]
Hello and welcome!

No you can not pair diyHue with philips account.
In short: it is secured by Philips.
diyHue Bridge Emulates a real Bridge. Thats why other Platforms can connect to it and control your selfbuild or genuine Lights from other manufactures.

if you have more questions you can Join our Slack channel and get live support.

[Join Slack](http://joinslack.diyhue.org/)
