### ISSUE TITLE
Motion Sensor with Hue Emulation

### ISSUE THREAD

**Issue by Xorfee** [mariusmotea/diyHue#494]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A clear and concise description of what you want to happen. If you can provide an example solution then even better!

**Describe alternatives you've considered**

**Additional context**

**Comment by mariusmotea** [comment]
I will close this if not info is provided.

**Comment by Xorfee** [comment]
Setup:
Hue Bulbs + Bridge + Motion Sensor
Raspberry Pi4 (HueEmu) + WS2811 + ESP8266 + Motion Sensor for ESP

I have now two bridges, since i dont have raspbee module on my Raspberry, all lights are connected in my living room.
My biggest issue right now is, i cant connect my Hue Motion Sensor to my Hue Emulator and control all my lights, my hue motion sensor is just connected to my hue bridge and i am just able to control the original hue bulbs. I know i need a raspbee module in order to control mixed zigbee bulbs with esp8266 bulbs together. But since i bought a motion sensor for my esp8266 i am not able to sketch my motion sensor to the hue emulator, because the script is just for the original hue bridge?

**Comment by mariusmotea** [comment]
The original bridge has no method to trigger external services like the hue emulator in case of sensor state change. One method can be the bridge pooling every 1-2 seconds for entire bridge config but is not implemented and may not be reliable.
