### ISSUE TITLE
Zigbee stick

### ISSUE THREAD

**Issue by coolcoons** [mariusmotea/diyHue#496]
@mariusmotea You said in this other issue https://github.com/diyhue/diyHue/issues/305 that you would be testing USB Zigbee hubs from brands other than Conbee. When you test them could you let me know if they work?

**Comment by mariusmotea** [comment]
Unfortunately at the moment of purchase the only method available for firmware flashing was using was using the CCdebug tool, so i give up and now i don't find it anymore. I will search better this weekend.

**Comment by coolcoons** [comment]
Ok, thank you.

**Comment by coolcoons** [comment]
https://github.com/diyhue/DiyLeaf These look intersting. Do you have a guide on how to put them together and use them?

**Comment by coolcoons** [comment]
Any more results on the zigbee stick?

**Comment by mariusmotea** [comment]
I found the CC2530 module. I think is the same only without the usb interface. I will try to flash this one.

**Comment by coolcoons** [comment]
https://www.ebay.com/itm/CC-Debugger-Emulator-CC2531-Sniffer-USB-Dongle-BTool-Downloader-Cable-Programm/174088984286?_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D20160908105057%26meid%3Dd6996088712d4e1d80c00a912d842cfb%26pid%3D100675%26rk%3D2%26rkt%3D15%26sd%3D264451467213%26itm%3D174088984286%26pmt%3D1%26noa%3D1%26pg%3D2380057&_trksid=p2380057.c100675.m4236&_trkparms=pageci%3A2f31865f-2b64-11ea-9002-74dbd1805c72%7Cparentrq%3A5958c59a16f0acc737a30a59ffa3c83c%7Ciid%3A1 

Is this the right thing to buy? They have an option to choose from called ALL. It looks like all I would need if you have the firmware to flash on it.

**Comment by mariusmotea** [comment]
Yes, but you don't need the CC Debugger Emulator, you can flash it using any arduino board.

**Comment by coolcoons** [comment]
How would you code it with an arduino board?

**Comment by mariusmotea** [comment]
Look here https://www.zigbee2mqtt.io/information/alternative_flashing_methods.html

**Comment by coolcoons** [comment]
I understand now. I don't have an Arduino or esp8266 board. Should I just buy the cc debugger emulator instead or is there a better option?

**Comment by mariusmotea** [comment]
currently i have no idea how this is working.

**Comment by coolcoons** [comment]
I will do more research but I think the Arduino board and the cc debugger emulator are the only options for flashing the firmware.

**Comment by coolcoons** [comment]
Looks like the raspberry pi can also be used but I don't have that.

**Comment by coolcoons** [comment]
https://www.ebay.com/itm/254277294957
I have this thing PL2303TA that has been sitting around the house awhile. Would this code a USB Zigbee sniffer or is it used for something else?

**Comment by coolcoons** [comment]
(Most of the product descriptions have this and I think zigbee usb interface is probably the right thing)
Product Applications:
Single-chip upgrade solution for Legacy RS232 devices to USB interface
USB to RS232 converters/cables/dongles
Healthcare/Medical USB Interface Data Transfer Cable
Personal Infotainment/Media Player Docking USB Interface
Cellular/PDA USB Interface Data Transfer Cable
Serial-over-IP Wireless Solution
USB Barcode/Smart Card Readers
GPS/Navigation USB Interface
Point-of-Sale (POS) Terminals/Printers
PC Docking Station/Port Replicators
Industrial/Instrumentation/Automation Control USB Interface
**USB Modem/Wireless/Zigbee USB Interface**
Set-Top Box (STB) / Home Gateway USB Interface
BatteryCharger Application
MCU-based devices to USB interface

**Comment by coolcoons** [comment]
https://www.aliexpress.com/item/4000244277624.html?spm=a2g0o.productlist.0.0.104a587d5ZC5Te&algo_pvid=ccf35026-65c6-4470-99d1-727b40b91250&algo_expid=ccf35026-65c6-4470-99d1-727b40b91250-11&btsid=b03a03c6-7747-4294-8f90-5944915a86c6&ws_ab_test=searchweb0_0,searchweb201602_8,searchweb201603_53
I found the cc debugger emulator on aliexpress. I will order that because it is a good price but I am sure the PL2303TA will find use elsewhere.
