### ISSUE TITLE
LOHAS Smart Bulb A19

### ISSUE THREAD

**Issue by jbeck22** [mariusmotea/diyHue#502]
I purchased [these](https://www.amazon.com/gp/product/B07T7W7ZMW/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) bulbs from Amazon.  I was able to flash them using Tasmota 8.2.0.  Is there a way I can get these into DIY Hue?  I was able to get my Yeelight strip in no problem and it is working GREAT, so thank you for all the hard work!

**Comment by mariusmotea** [comment]
Tasmota lights are supported. If this bulb is a generic esp8266 one you can also flash the firmware provided by us. I don't recommend to try this if you don't have electronics skills.
