### ISSUE TITLE
Can't find Buld with custom Firmware or ESPHome Firmware

### ISSUE THREAD

**Issue by Paul595** [mariusmotea/diyHue#505]
**Describe the bug**
I am using diyHue on a Raspberry Pi 3B+ which has Nmap installed on it. I am also able to connect the Philips Hue App to it. 
Then I flashed a NodeMCU with the custom Firmware for a standard switch from this rep. After this I was able to open it's webpage and control it from there. When I went into the App to try connecting to it I couldn't. After that I tried it with Hue Essentials but no Luck either.
So I decided to try the HomeESP Firmware and flashed the NodeMCU with it and tried controlling it. It connects to my Wifi but I can't control in any way.

**To Reproduce**
1. Go to Philips Hue App
2. Click on Add Lights
3. Error: No devices Found

**Expected behavior**
It is expected that the Hue App can find the NodeMCU.

**Logs**
In both cases test via sudo ./HueEmulator3.py --debug and NodeMCU found via Advanced IP Scanner on Windows
Test with custom Firmware: https://pastebin.com/x1hdc2Qj
Test with ESPhome: https://pastebin.com/zj1QN5nG

**Comment by Mevel** [comment]
Try to ping the bulb from pc while searching in hue app. Did the trick for me with one bulb that didn't want to be found.

**Comment by Paul595** [comment]
I tried it with different package sizes but it didn't work sadly.

**Comment by mariusmotea** [comment]
Is the ip of the light listed during port 80 scan of the network?
from logs: 
```
   "192.168.0.3:80",
    "192.168.0.4:80",
    "192.168.0.151:80",
    "192.168.0.239:80"
```

**Comment by Paul595** [comment]
Sorry for the late response, my PC broke and I didn't have another way to answer.
When I scan the network with map or another tool outside of diyHue it detects the ESP.
I can also connect to it via the web interface of the specific ESP
