### ISSUE TITLE
I can connect to Philips TV but not working

### ISSUE THREAD

**Issue by Quentin-Cloos** [mariusmotea/diyHue#508]
**Describe the bug**
Hello, I can connect my Philips Ambilight TV to diyHue, I can change/test brightness (it's working), but then after configuration nothing work (the light stay white) and the hub appear to be "IP address 0.0.0.0" on the TV (instead of 192.168.0.X).

**Expected behavior**
The lights have to sync with the Ambilight.

**Logs**
The logs don't show any error.

**Docker Info (please complete the following information):**
 - Architecture: ARM
 - Docker image version: latest
 - Hardware: Raspberry Pi 4

**Additional context**
Tested with and without internet.

**Comment by mariusmotea** [comment]
What lights are you using? Yeelight bulbs?

**Comment by Quentin-Cloos** [comment]
I use Tradfri and some Tuya bulbs, I have finally a working emulated hub but with the Home Assistant integration (working like a charm with my TV).
