### ISSUE TITLE
Color Changing

### ISSUE THREAD

**Issue by danielukm8** [mariusmotea/diyHue#509]
Hello
I have a lightbulb witch is connected to diyhue via zigbee2mqtt and the problem is i can't control the colors via hue app or hue essentials. i asked for help at zigbee2mqtt but they said the config its ok because when i send commands via mqtt explorer to change the colors, it changes and then i can see a palette changer in the hue app until i try to change the color. 
When the lightbulb is conected via the original hue bridge there is no problems in changing the colors.

**Comment by Mevel** [comment]
Can you please add the corresponding config for that light? It might be that the bulb has the wrong light type in the config (e.g. Only warm or cold white bulb)

**Comment by Mevel** [comment]
Also: this repo is deprecated, just so you know 😉

**Comment by danielukm8** [comment]
`        },
        exposes: [e.power(), e.current(), e.voltage(), e.switch()],
    },
	
	// PROLIGHT E27 WHITE AND COLOUR

    // Prolight
    {
        zigbeeModel: ['PROLIGHT E27 WHITE AND COLOUR'],
        model: 'PROLIGHT E27 WHITE AND COLOUR',
        vendor: 'PROLIGHT',
        description: 'PROLIGHT E27 WHITE AND COLOUR',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
        model: '5412748727388',
        vendor: 'Prolight',
        description: 'E27 white and colour bulb',
        extend: preset.light_onoff_brightness_colortemp_colorxy,
    },
];
`

**Comment by mariusmotea** [comment]
You have the obtions to change the color or color temperature? How did you installed diyhue (docker/ host install)?
