### ISSUE TITLE
Port 22: Broken pipe

### ISSUE THREAD

**Issue by schroepfer** [mariusmotea/diyHue#51]
Hello diyHue runs perfect.
But after some minutes i couldn'd get a connection to emulated bridge and the HueEmulator.py stoped with the following error:
.....
192.168.178.63 - - [14/Sep/2017 22:18:03] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/groups HTTP/1.1" 200 -
192.168.178.63 - - [14/Sep/2017 22:18:05] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/lights HTTP/1.1" 200 -
192.168.178.63 - - [14/Sep/2017 22:18:06] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/groups HTTP/1.1" 200 -
**packet_write_wait: Connection to 192.168.178.82 port 22: Broken pipe**

The start looks like this:
pi@raspy-82:~/diyHue/BridgeEmulator $ sudo ./HueEmulator.py 
Config loaded
LightRequest: http://192.168.178.50/api/2ypxD3CNUB4CZUmQ1oJ5Jslj7ChKhmxMbixxn4LH/lights/1/state
update status for light 1
LightRequest: http://192.168.178.33/set?light=1&on=False&bri=144&ct=447
update status for light 2
starting ssdp...
start ssdp broadcast
Starting httpd...
192.168.178.51 - - [15/Sep/2017 08:35:36] "GET /description.xml HTTP/1.1" 200 -
192.168.178.51 - - [15/Sep/2017 08:36:36] "GET /description.xml HTTP/1.1" 200 -

**Comment by mariusmotea** [comment]
Hi,

It seams that you don't use a startup method, and execute the script manually. When your ssh session will timeout all your started applications will be closed. You can use a [systemd script](https://www.raspberrypi-spy.co.uk/2015/10/how-to-autorun-a-python-script-on-boot-using-systemd/) to make it run like a service, or just add it to rc.local like i write here #10

**Comment by schroepfer** [comment]
O, thank you. Yes i started the app over SSH. 
I will test it with an autostart.

**Comment by mariusmotea** [comment]
I added in the [wiki](https://github.com/mariusmotea/diyHue/wiki/Getting-started) how to create systemd service file. If you solve it please close this issue.
