### ISSUE TITLE
Synapse/Hue Entertainment & Effects Lag

### ISSUE THREAD

**Issue by l1berate** [mariusmotea/diyHue#510]
Hi, 

Short summary, whenever I use effects from the Hue Essentials app or try to sync Razer Synapse's profiles with my lights, I get really noticeable lag to the point it's not usable.

My setup, I have two Gledopto 6W light bulbs and one 6 ft Gledopto light strip. These are Hue knockoffs that still connect to the official Hue bridge over Zigbee. I have that Hue Bridge hooked directly into my modem using a short cat 5e ethernet cord. Then I have my brand new Raspberry Pi 4 by my tv, hooked up to the modem with a long cat 6 ethernet cord. I installed diyHue using the host install method and installed the entertainment center according the instructions. (diyHue is also the only thing I've installed other than doing a sudo apt update, etc.) My PC is also hooked up to the modem using a long cat 6 cable and all of my razer stuff is there too. 
Out of the box, I wasn't actually able to get the entertainment center setup so I had to change the config.json file's manafacturername and modelid for each light from 'GLEDOPTO' and 'GL-B-007ZS' to 'Philips' and 'LCT015' respectively. Otherwise, I was hit with the 'only official hue bulbs can be used' message.

So, long description of my issues.. First off, I'll say that changing the lights color, brightness, on/off, and everything work great and it's snappy through the official Hue app or the Hue Essentials app. The only issues I start to notice is when I try to use Effects or the Entertainment Center with Razer Synapse. They will run, and the lights will change, but it's very spotty. Spectrum Cycling on Razer synapse sort of works but the colors are always one color behind the Razer peripherials. Effects are actually worse and run way slower. 

Please let me know what I can do to try to fix this issue. Short of buying different lights or trying the raspberry pi zigbee module, I'm out of ideas and I don't really want to drop any more money into this.

**Comment by mariusmotea** [comment]
Hi,

Unfortunately all requests to original Hue Bridge are send using http hue api, and the webserver on the Hue Bridge is not that powerfull to handle all the requests in realtime. In order to improve this i added in flask branch a verification of frames and if the difference is not noticiable it will bypass the request. There is hope also with Zigbe2mqtt, see https://github.com/Koenkk/zigbee2mqtt/issues/4771
