### ISSUE TITLE
Can't connect to Philips Hue App

### ISSUE THREAD

**Issue by kn01a** [mariusmotea/diyHue#512]
After diyHue installation I tried to pair it with the Philips Hue App. When searching for new bridges the app says "1 new bridge found" only for a part of a second, then the screen "jumps" to "No new Hue bridges found" and all I can do is to search again (with the same result). 

I already searched for past issues but only found issues regarding the not working "link button function" - but my problem occurs even before that.

With HueEssentials and All4hue the searching and the pairing works flawlessly.

**Comment by mariusmotea** [comment]
The issue is with the certificate, generation of this certificate failed or you have multiple interfaces and the certificate was generated for wrong interface, or you replace the certificate without to reinstall the Hue app.

**Comment by mariusmotea** [comment]
Check in documentation HTTPS certificate debug

**Comment by deejayves** [comment]
Hi,
I do have the same issue.  Certificate is correct.* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=b827ebfffe5b92b7
*  start date: Apr  8 19:24:33 2021 GMT
*  expire date: Apr  6 19:24:33 2031 GMT
*  issuer: C=NL; O=Philips Hue; CN=b827ebfffe5b92b7
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

enxb827eb5b92b7: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.118  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::4885:7e2f:f690:69b1  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:5b:92:b7  txqueuelen 1000  (Ethernet)

Any idea's ?

Regards
