### ISSUE TITLE
Hue App detects as V1 Bridge, V1 App wants to update the Bridge

### ISSUE THREAD

**Issue by ma-mod** [mariusmotea/diyHue#513]
**Describe the bug**
First: Ive upgraded all plugins on my linux host and also removed and using the newest docker image (Additional Content). 
When I open the Hue App and try to connect the emulated Bridge, I get the message that it cant connect to a V1 Bridge and I have to use another App. If I use the recommended Hue V1 App, it will tell me that I have to update my bridge (which is not possible)

**To Reproduce**
1. Open Hue App and try to connect Bridge
2. It will fail and say that it cant connect to V1 Bridge and you have to use V1 App Version
3. V1 App Version will tell an update is needed
4. update is not possible

**Expected behavior**
to be able to connect it to Hue App

**Logs**
If applicable, provide output logs. These can be obtained via running `docker logs diyHue`

**Docker Info (please complete the following information):**
 - Architecture: [x64, debian10]
 - Docker image version: [latest]
 - Hardware: [VM]

**Additional context**

> root@srv-diyhue: docker images       
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE  
> diyhue/core         latest              1111513e9d5b        9 days ago          143MB

> root@srv-diyhue: docker rmi d6954666a2c9  
> Untagged: diyhue/core:latest  
> Untagged: diyhue/core@sha256:65bcd46dfcff3cff55e445f9b100e1cb8e4d80e4a212103ed2c3cbd8652dc48b  
> Deleted: sha256:d6954666a2c9dd1fc53a86b07c2cd41744a1584adfcc0863b0b7b5b8cff5eb73  
> Deleted: sha256:9bb6b8c86561260619daee066fb599b1e66048c9cf7a78cba87e9d7efd4d5226  
> Deleted: sha256:f540f52fbe62aba6a85e916c66dacde17b5036ff75d5a3f8e8980e3653c22128  
> Deleted: sha256:9e2911f89f0444551c4dcb5068b039b40ca0d7e0fe9d6b9c2e06cbceede05ef9  
> Deleted: sha256:694694bc034ce8604baeff00350e033ac55349edd604aff60209126ee3686855  
> Deleted: sha256:ca1a8d8f7ba46bc985ed82402d5bd28ffb63d29581f2d3e942c9f68b97d78d91  
> Deleted: sha256:c93e99d048e006a5811ab1472001ecef3746831615767d3d6e07f5650972f672  
> Deleted: sha256:8ad1802a42f6257be1884f38669ac5fab00b95b2eb954a2401fa4fdf4e118495  
> Deleted: sha256:9539b2be211270894f2c3c196532a961be869a42d39c5e4b1d994cd264f7bb7f  
> Deleted: sha256:b2b8d2214c1379c3f0a97aca46b36941a2a9520a668ce09e38b572ef18aa1224  
> Deleted: sha256:6da7920b4e77e3320a982093af94c4aecc75865985180484dadc7493c7ec58e7  
> Deleted: sha256:87c8a1d8f54f3aa4e05569e8919397b65056aa71cdf48b7f061432c98475eee9  
> root@srv-diyhue: docker run -d --name diyHue --restart=always --network=host -v /mnt/hue-emulator/export:/opt/hue-emulator/export diyhue/core:latest  
> Unable to find image 'diyhue/core:latest' locally  
> latest: Pulling from diyhue/core  
> 6f28985ad184: Pull complete   
> c5e6af41f309: Pull complete   
> 167f00b80fae: Pull complete  
> d22cc8d21aa0: Pull complete  
> d33a10af94af: Pull complete  
> 9c3f04d622e9: Pull complete  
> e9b9ab7a51fc: Pull complete  
> bf0c77e20c14: Pull complete  
> 25a1075e0df8: Pull complete  
> 1cf46356de35: Pull complete  
> 1e0d9b12c6b1: Pull complete  
> Digest: sha256:545a1e4d2fca0f928753921b97aa2cb4d05eb1bef11a4c20471afb80bd4cb7da  
> Status: Downloaded newer image for diyhue/core:latest  
> bb26a51a5449dfcf72b97beba33e425cc3de1e6e415a6dbeeb4cddde13f79b91  
> root@srv-diyhue:~#

**Comment by ma-mod** [comment]
I am sorry, i am incapable to format it correct...

**Comment by Mevel** [comment]
Hey!
This might solve your issue.

https://diyhue.discourse.group/t/app-requires-update-of-hue-bridge-update-fails/233/1


Also this repo is deprecated.

Find the new repo [here](https://github.com/diyhue/diyHue)
