### ISSUE TITLE
Is the certificate server down?

### ISSUE THREAD

**Issue by ToracX** [mariusmotea/diyHue#534]
My cert.pem is empty. Trying to manually create a certificate using 

curl "http://mariusmotea.go.ro:9002/gencert?mac=XX:XX:XX:XX:XX:XX"

Gives a timeout:

curl: (7) Failed to connect to mariusmotea.go.ro port 9002: Timed out

Any clues or tips how to fix it?

Also using this command curl https://192.168.178.101/api/nouser/config -v -k

*   Trying 192.168.178.101...
* TCP_NODELAY set
* connect to 192.168.178.101 port 443 failed: Connection refused
* Failed to connect to 192.168.178.101 port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.178.101 port 443: Connection refused

**Comment by mariusmotea** [comment]
Hi,

I will recover this service later today. Will update here once it is ready.

**Comment by ToracX** [comment]
> Hi,
> 
> I will recover this service later today. Will update here once it is ready.

Okay great. please let me know.

**Comment by mariusmotea** [comment]
I think it is fixed and updated (with faketime enabled).

**Comment by Jokeronomy** [comment]
This service might be down again. I recently upgraded my DiyHue install, my cert.pem is missing, and while the curl command does not error out I also do not get any output from the command. No file downloaded either. Trying https gives this error:
`curl: (35) OpenSSL/3.1.4: error:0A00010B:SSL routines::wrong version number`

Thanks in advance for any help you can provide

**Comment by mariusmotea** [comment]
your browser force https connection because i also have an https server on that host. Try to get the certificate with curl https://reqbin.com/curl

**Comment by mariusmotea** [comment]
found an issue after reboot of the service and fix it.
