### ISSUE TITLE
IKEA Tradfri

### ISSUE THREAD

**Issue by SteenAndreassen** [mariusmotea/diyHue#54]
This is not an issue !!
In the Tradfri Wiki part is says: http://{bridgeIP}/tradfri
Which "tradfri" is going to be installed for the intergration with the bridge?
There are many tradfri applications here on github
BR Steen

**Comment by mariusmotea** [comment]
Tradfri support is build in, in that page you must set the Tradfri Gateway ip and the security code, then all lights connected to your Tradrfi Gateway will be added to Hue bridge emulator and also can be controlled from hue applications. Communication with Tradfri Gateway is made with coap protocol, and for this is used the binary file diyHue/BridgeEmulator/coap-client-linux. This is compiled for ARM devices like Raspberry pi.
