### ISSUE TITLE
Compatibility with ESPurna

### ISSUE THREAD

**Issue by cad435** [mariusmotea/diyHue#56]
can the ESPurna (https://bitbucket.org/xoseperez/espurna) Software be used to control ESP8266 Lights (eg. https://www.itead.cc/sonoff-b1.html) based on this software or using the Sonoff Switches (http://www.exp-tech.de/itead-studio-sonoff-touch-luxury-glass-panel-touch-led-light-switch) with it?

The switches would be really neat to use...

**Comment by mariusmotea** [comment]
I don't believe i can add support for them because will require to have the device for testing and i don't want to invest more in hardware as currently my entire house is full of smart lights and sensors.

**Comment by cad435** [comment]
Ok, yes thats understandable.

thx anyway :)
