### ISSUE TITLE
Dimmed parts of the lights "flash" black on fadeout

### ISSUE THREAD

**Issue by cad435** [mariusmotea/diyHue#57]
Hey,

So, I noticed, when sending an "off" signal to the lamp, the dimmed parts of it went completely dark (or sometimes they go on full brighness) for lets say 50ms to 100ms, then go back to normal brightness and fade out like expected.

I use A ESP8266-01 for an RGBW light and mapped the pins like this:

> //define pins
> uint32 io_info[PWM_CHANNELS][3] = {
>   // MUX, FUNC, PIN
>   {PERIPHS_IO_MUX_MTDI_U,  FUNC_GPIO12, 1}, //R
>   {PERIPHS_IO_MUX_MTCK_U,  FUNC_GPIO13, 0}, //G
>   {PERIPHS_IO_MUX_MTMS_U,  FUNC_GPIO14, 3}, //B
>   {PERIPHS_IO_MUX_GPIO5_U, FUNC_GPIO5 ,  2},//W
> };

I guess it may be the soft-PWM? but im not really sure.
Maybe you have an idea what I can do about this (beside waiting for my ESP8266-12 to arrive)

Ah yeah and all other things are working as expected :)

cad435

**Comment by mariusmotea** [comment]
Hi!

This is because the light state is saved in eeprom when "last state" is selected in light webgui.

**Comment by cad435** [comment]
Wow, that was quick and kinda solve the issue!

Thank you, Cool!!
