### ISSUE TITLE
Speed up PWM frequency to 17kHz

### ISSUE THREAD

**Issue by cad435** [mariusmotea/diyHue#58]
Hey,

is it possible to speed up the PWM from 5kHz to over 17kHz?

Its absolut fine in visual aspects, but actually i can hear a slight 5kHz tone and thats really annoying...

Every increase in speed is really appreciated even if the resolution will decrease...

Or maybe a define were you can select a speed mode...

Will be very cool!
cad435

**Comment by mariusmotea** [comment]
Hi,

But are you sure the noise is generated by led drivers? Usually the noise come from power supply coils and this is a sign that something is not working right (bad caps?). I have such issue with a neopixel strip where pwm is not used, and is happening only when i increase the brightness because will increase the load on power supply. Is possible to increase the pwm frequency but it can have negative visual impact, just let me know if you are sure the noise is generated by pwm.

**Comment by cad435** [comment]
Hey,
The LED-Drivers are HF ones, with switch-frequencys about 50-100kHz so it SHOULD not be the Supply...

The noise shuts of if the LEDs are on full brighness, so i guess its the 5kHz...
On the oszilloscope i can see that on full brightness it is always HIGH, there is no LOW Spike, another point that it is caused by the Controller switching

Maybe you can make a branch to test it out?
(Uploading a new sketch via OTA is much simpler than unmount the light from the ceiling)

But indeed, maybe it can be fixed with Hardware

I will add a 47000uF cap to the 12V supply and additional supply caps directly beide the MOSFETS maybe that will fix it...

cad435

**Comment by cad435** [comment]
So, I Attachés various decoupling capacitors and reduced the noise, but its not gone...

What I guess is its some backtalking from the controller to the Power supply...

It may be reduced more by adding a Inductance but I'd rather Test a 17kHz Version first, because adding a not proper dimensioned Inductance always is a bit wanky (Voltage Spikes etc)

cad435

**Comment by mariusmotea** [comment]
Try this:

`const uint32_t period = 1024; `change to `const uint32_t period = 4098;`
and
`pwm_set_duty((int)(current_rgbw[color] * 4), color);` to `pwm_set_duty((int)(current_rgbw[color] * 16), color);`

This way you will increase the frequency by 4 times. Not sure if the light will remain smooth, but at last you can debug. 

P.S. try to glue the coils on you circuit.

**Comment by cad435** [comment]
Hey,

Thx for the code, I'll try it when I'm At home...

Yeah, thought about glueing the coils, usually I'll cover them in resin, but I'm currently out of resin...


PS: I converted 2 of my lamps into HUE-Style, if you want pictures for your Images-folder let me know and I'll make a pull request

**Comment by mariusmotea** [comment]
Hi,

Yes, please create PR to merge them.

Thanks.
