### ISSUE TITLE
Unable to link existing Hue bridge

### ISSUE THREAD

**Issue by Cheddaru** [mariusmotea/diyHue#62]
I am very exited about this project, and got it working to some extent (succesfully connected a ESP8266 RGB PWM ledstrip), but I have an issue with linking my existing Hue bridge. When I go to http://[BridgeEmulatorIP]/hue Firefox gives me an error:

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

And Chrome just displays the html code with no functionality. I am running the emulator on a Raspberry pi 1 model B with Raspbian stretch lite.

**Comment by mariusmotea** [comment]
my bad, i made a change without proper testing. i will fix in 5 minutes, check the HueEmulator.py file.
Maarius.
