### ISSUE TITLE
Incompatible with new Hue App

### ISSUE THREAD

**Issue by TimTower01** [mariusmotea/diyHue#65]
Today there was a new release of the official phillips hue app. Sadly it requires to update the bridge otherwise it wont work. If you just updated the app you are just able to control your current setup but not to edit it. If you reinstall the app you are premittet to enter the app because you cannot update the bridge. Can you please make the changes necessary to support the official hue app again?

Thank you in advance
~Tim
 
P.S. Has someone not updated the app and is able to provide me with the old version off the app? (You could use something like the App ApkExtractor.The version of the old Phillips Hue app should should be 2.15.0)

This is how it looks when i updated the app: (everything exept the controlpage of the rooms is blocked)
![screenshot_20171011-233127](https://user-images.githubusercontent.com/31222710/31468058-79795714-aedc-11e7-9f6d-a741bc72c6e5.png)

And this us how it looks when i do a fresh install of the app: (App is unusable due to unskippable update notification)
![screenshot_20171011-231903](https://user-images.githubusercontent.com/31222710/31468156-e03f7898-aedc-11e7-8c55-e137d731d1db.png)

Hope you can understand the screenshot even if they are in german.

**Comment by mariusmotea** [comment]
Just replace in config.json the software version and restart hue service. Look here:
https://github.com/mariusmotea/diyHue/commit/c2fcda1e98a812381013bb0f9f093282d47d43fc

Marius.

**Comment by TimTower01** [comment]
Thank you for the fast commit. It seems to work properly for now but I am going into deeoer investigation tomorrow when I am able to pair it with a few lamps. Btw how did you figured out which software version it has to be ?

**Comment by mariusmotea** [comment]
I just search the hue api forum. Usually somebody ask what is new with every firmware update. In this case was this thread:
https://developers.meethue.com/content/new-bridge-firmware-api-v1210
