### ISSUE TITLE
syncWithLights not wokring!

### ISSUE THREAD

**Issue by hcnnet** [mariusmotea/diyHue#66]
192.168.XX.XXX - - [12/Oct/2017 19:42:37] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/lights HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.XX.XXX', 44158)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, `self)`
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./HueEmulator.py", line 1078, in do_GET
    syncWithLights()
  File "./HueEmulator.py", line 580, in syncWithLights
    bridge_config["lights"][light]["state"].update(light_data["state"])
TypeError: list indices must be integers, not str
----------------------------------------

**Comment by mariusmotea** [comment]
Please provide a link with entire config.json file. I believe somehow you end with a bad/corrupted config.

**Comment by hcnnet** [comment]
Here - 
[config.json.txt](https://github.com/mariusmotea/diyHue/files/1380694/config.json.txt)

**Comment by mariusmotea** [comment]
I will try to find the problem, until then you can disable this function (is used to update the emulator bridge lights status in real time from hue bridge, if changes where made directly there)
remove the flowing two lines:
```
                    if url_pices[3] == "lights": #add changes from IKEA Tradfri gateway to bridge
                        syncWithLights()
```
in last version are located at lines 1077 and 1078. 
Restart hue emulator

**Comment by mariusmotea** [comment]
Please provide the output of the following command:
```
curl "http://192.168.22.172/api/H7e34Wb1N8Q37Z0Bs0e6wQd5lvJG4aXsEwl6lWG-/lights"
```
One of the lights provide an unexpected output and i need to see this output. Can you tell me exactly when and what triggered this this error?

Marius.

**Comment by hcnnet** [comment]
Halloe Marius .. Thnx - log is here ..
[curl_dump.log](https://github.com/mariusmotea/diyHue/files/1383759/curl_dump.log)

**Comment by mariusmotea** [comment]
Hi!

I analyse your log and i believe i know what is the problem. In emulator config where loaded some lights that are not present on Hue Bridge when you performed curl command (ex: light 21). I update the code and now if there are missing lights or other errors it will only mark the light as unreachable.

Marius.

**Comment by hcnnet** [comment]
Thnx Matuis .. testing - and all works again ..

Regards /HC
