### ISSUE TITLE
hue app wants to update the bridge

### ISSUE THREAD

**Issue by daaf84** [mariusmotea/diyHue#72]
But it won't do it...
Tried the old app, but cannot connect with esp lights.

Also having trouble with that, The appear directly in my personal Wifi. Can see the settings for on/of and so on, but No SSID is broadcasted.

**Comment by mariusmotea** [comment]
Hi,

I guess you use an older version. Please try this:
 - stop the hue emulator service / process
 - look in the config.json file to see what value is under config->swversion . Value must be 1709131301, if is not this, the replace. Save the file and start back the hue emulator.

Look here to commit with this fix, maybe will help you to understand what you need to change:
https://github.com/mariusmotea/diyHue/commit/c2fcda1e98a812381013bb0f9f093282d47d43fc

Same issue opened was #65

Marius.

**Comment by daaf84** [comment]
Found out that nmap is stated wrong in the 'How to begin' page, there is typed namp

**Comment by mariusmotea** [comment]
@gbotti fixed this 3 hours ago with PR #71

**Comment by daaf84** [comment]
nmap is also stated wrong in the wiki page 'Getting Started'

**Comment by mariusmotea** [comment]
Fixed, thanks.
