### ISSUE TITLE
Unable to link with Google Home

### ISSUE THREAD

**Issue by t3chguy** [mariusmotea/diyHue#73]
to link with Google Home it needs to be able to be linked with account.meethue.com/link-bridge which asks me to `Push the big button on the middle of your bridge. The one you've always wanted to push. Go on.`

Is this possible in any way shape or form or not?

Thanks

(partial continuation of #20)

**Comment by mariusmotea** [comment]
Hi,

I don't have Google Home, but i read about pairing issues on ha-bridge README page. The Hue remote api is not public, so we cannot use account.meethue.com portal. As a workaround i believe you can use older Google Home application.

> ISSUE: Google Home now seems to not support local connection to Philips Hue Hubs and requires that it connect to meethue.com. Since the ha-bridge only emulates the local API, and is not associated with Philips, this method will not work. If you have an older Google Home application, this may still work. YMMV.

https://github.com/bwssytems/ha-bridge/issues/764

Marius.

**Comment by bardoup** [comment]
The workaround with the older app doesn't works any more. 
So Google home + habridge is not working at the moment.

**Comment by FezVrasta** [comment]
For anyone wondering, your best bet is to use Home Assistant and its Google Assistant component.

Doing so you can use the diyHue to control lights with the Hue app, and Google Assistant to control them by voice.

**Comment by mariusmotea** [comment]
I will close this as it is available the workaround with Home Assistant.
