### ISSUE TITLE
Use diyHue with a custom device

### ISSUE THREAD

**Issue by Konnichy** [mariusmotea/diyHue#74]
Hello,

My project is to control devices normally controlled by a 433 MHz remote with my Logitech Harmony Hub.

I already have a Raspberry Pi with a 433 MHz module and I can successfully control devices via the a Python script. Now, it seems according to my researches that the easiest way to make the Harmony Hub control something via a network API (i.e. not via infrared) would be to emulate a Philips Hue bridge. This is how I arrived here, wanted to build something like this:

Harmony Hub ---(LAN)---> diyHue ---(exec script? API?)---> my 433 MHz Python script

Is this something that could be done with diyHue? Could my Python script be easily controlled by diyHue?

Thank you,

**Comment by mariusmotea** [comment]
Hi,

Yes, you can use this to control your devices. The best (and easy method) is to integrate an web server in you script that bind on a custom port (other than 80), then create virtual lights with address localhost:{custom port}. I've provide example script on this issue #28 . After this you will receive requests on your webserver like this:

```
http://localhost/set?light=1&on=true
http://localhost/set?light=1&on=false
http://localhost/set?light=2&bri=255
http://localhost/set?light=3&ct=400
http://localhost/set?light=3&x=0.2&y=0.4
```
light argument is best to use for every device you want to control, other you can be used for actions.

Marius

**Comment by Konnichy** [comment]
Thank you very much! I could make it work already!!

The difference with the other topic is that the file 'lights_address.json' doesn't exist anymore, but by reading the code I found the similarly-named section in 'config.json' and used this instead.

**Comment by Mevel** [comment]
@Konnichy maybe the new 433Mhz Lights Firmware is working for you? #87

**Comment by Konnichy** [comment]
Thanks for the notification.
I seems developed for Arduino. Would it work with Raspberry Pi as well?

**Comment by Mevel** [comment]
Yes! Connect the Transmitter to GPIO of the Raspberry and send control Commands via Shell Script.

https://github.com/sui77/rc-switch
