### ISSUE TITLE
HueSensorStandardLightSwitch -> connect to hue bridge

### ISSUE THREAD

**Issue by ottelo9** [mariusmotea/diyHue#75]
I uploaded your "HueSensorStandardLightSwitch" to my ESP8266. Buttons and connection is working. But how to pair the "Hue Tap" to my Philips Hue Bridge? Via iOS App it cannot find my ESP. If I type manually into my browser: "http://192.168.178.19/switch?mac=A0:20:A6:1A:FA:D3&devicetype=ZLLSwitch" -> It shows: "Bad URL in request response"

**Comment by ottelo9** [comment]
Ahh now I see my problem. I cannot connect to the Original philips hue bridge. I need your software on an Raspberry.

**Comment by mariusmotea** [comment]
Yes, this is a custom sensor firmware made specially for this emulator. Original Philips devices use ZigBee communication, not WiFi, you cannot create any devices with ESP8266 for them.
