### ISSUE TITLE
Dimmed single color output on different pins as different bulbs

### ISSUE THREAD

**Issue by southsteam** [mariusmotea/diyHue#77]
Hi, First of all, great project! Love it! 

I would like to use a ESP module as a diyHue but with just singel output for a mosfet, like a generic SingelColor output but with the option as multiple lights on the same module on different pins. 

Specific I would like to connect ESP module to 6 channels output as 6 different emulated lights, as in the neopixel version "light count". Could you guide me or make a version of this?

**Comment by mariusmotea** [comment]
Hi!

Yes, this can be done, currently on Neopixel leds you can setup as many lights as you want per strip, and this can be done also with pwm output. There are two tasks here:
1. create the ESP software. This will be low to medium as complexity (basicaly a merge between neopixels and generic lights)
2. add support in HueEmulator for dimmable lights. This is optionally but is nice go have it as currently all detected lights will be added as being color and in Hue application you will have the option to change the colors, color temperature, witch is not the case for a dimmable light. I will perform some changes, but i don't have time to test, maybe you can help?

Marius.

**Comment by mariusmotea** [comment]
Try this:

https://github.com/mariusmotea/diyHue/tree/develop/Lights/Arduino/Generic_Dimmable_Light

**Comment by TimTower01** [comment]
So i am going to hijack this thread. Is there a way to remove the dimm feature so that i can control a relay with the esp and control my undimmable roomlight?

**Comment by mariusmotea** [comment]
yes, some progress is made but untested. 
Check this:
https://github.com/mariusmotea/diyHue/tree/develop/Lights/Arduino/Generic_ON_OFF_device

What i need to do is to is to customize this lights, now they are added like there where color bulbs. 
Working on this...

**Comment by southsteam** [comment]
Thanks! 
The lights are recognized as color bulbs yes, is it possible to change to white dimmable only? Where is it defined what type of lamp it is? 
It works with the two pins that are defined almost. The Light can not be turned off, it can be dimmed to 1% but not turned off. How would you add more than just this two?

**Comment by mariusmotea** [comment]
Yes, you can use as many as you want, just edit these lines:
```
#define devicesCount 2
uint8_t devicesPins[devicesCount] = {4, 5};
```
second part is the gpio pin number. For ON_OFF lights or relays we must not be able to change the bri, ct or hue, but because the emulated light is not setup properly we have this issue. You can manually edit config.json to alter the light modelid and to remove the bri, ct, xt, hue, sat and colormode parameters.

Found one example:

```
         "state":{  
            "on":true,
            "alert":"none",
            "reachable":true
         },
         "type":"On/Off plug-in unit",
         "name":"Steckdose",
         "modelid":"Plug 01",
         "manufacturername":"OSRAM",
         "uniqueid":"84:18:26:00:00:0a:1a:01-03",
         "swversion":"V1.04.12"
      },
```

**Comment by southsteam** [comment]
Sorry, I was talking about the dimmer version. In the app it also says "Unreachable". With both on/off and the dimmer version.

**Comment by mariusmotea** [comment]
"Unreachable" flag is set when http request to light fail. Reasons:
 - bad ESP chip with poor wifi signal
 - light ip was changed (i recommend to use ip reservation), this can be fixed by performing a new light search from application.
 - possible bug in firmware, both are not well tested

**Comment by mariusmotea** [comment]
@southsteam can you please check develop branch i update both lights and emulator and now must work as expected.
@TimTower01 this update must fix also your issue, ON_OFF lights/relays will be emulated like Osram Plug and you must not be able to change brightness or other color values.

Marius.

**Comment by mariusmotea** [comment]
@southsteam was very busy when you write first time and only now i understand your problem. I made a new PR with 6 pins, so you can use 6 lights. Regarding power on/off i was not able to find the issue by reading again the code, but i believe i will find out tomorrow. Please confirm that so far everything is working fine except on/off function.

Marius.

**Comment by southsteam** [comment]
Great! The 6 pin works and it is recognized correctly as dimmed one channel! The part of turning it off (just off, on is working) is still not working and the lights still gets the "unreachable".

**Comment by mariusmotea** [comment]
same problem if you turn off the light from internal webgui?

**Comment by southsteam** [comment]
Yes it is the same with the web gui. Will test the new commit!

**Comment by mariusmotea** [comment]
Fixed also turn off bug, check last commit on develop branch (better download again entire file). What i don't like is the transition

**Comment by southsteam** [comment]
It works just fine now! With the on/off and the unreachable lights are gone! The transition is ok but optimal would be to have it as a setting!

**Comment by mariusmotea** [comment]
i try to fix also transition. This is default 4, you can find it in sketch and can be override by providing transitiontime parameter

**Comment by mariusmotea** [comment]
I fix also the transition bug. I stop my tests here and will count on you to report other bugs. If you don't report any in a few days i will merge this to master branch.

Marius.
