### ISSUE TITLE
Not able to connect to the bridge

### ISSUE THREAD

**Issue by finnbennet** [mariusmotea/diyHue#78]
I firstly followed the steps of the ['Getting started' page on the GitHub wiki](https://github.com/mariusmotea/diyHue/wiki/1.-Getting-started), started the emulator, but then the status says following:
`● hue-emulator.service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; enabled; vendor pre
   Active: failed (Result: exit-code) since Sun 2017-10-29 14:27:14 CET; 3min 28
  Process: 15617 ExecStart=/home/pi/HueEmulator.py (code=exited, status=203/EXEC
 Main PID: 15617 (code=exited, status=203/EXEC)

Oct 29 14:27:14 raspberrypi systemd[1]: Started hue-emulator.service.
Oct 29 14:27:14 raspberrypi systemd[1]: hue-emulator.service: Main process exite
Oct 29 14:27:14 raspberrypi systemd[1]: hue-emulator.service: Unit entered faile
Oct 29 14:27:14 raspberrypi systemd[1]: hue-emulator.service: Failed with result
lines 1-10/10 (END)...skipping...
● hue-emulator.service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-10-29 14:27:14 CET; 3min 28s ago
  Process: 15617 ExecStart=/home/pi/HueEmulator.py (code=exited, status=203/EXEC)
 Main PID: 15617 (code=exited, status=203/EXEC)

Oct 29 14:27:14 raspberrypi systemd[1]: Started hue-emulator.service.
Oct 29 14:27:14 raspberrypi systemd[1]: hue-emulator.service: Main process exited, code=exited, status=203/EXEC
Oct 29 14:27:14 raspberrypi systemd[1]: hue-emulator.service: Unit entered failed state.
Oct 29 14:27:14 raspberrypi systemd[1]: hue-emulator.service: Failed with result 'exit-code'.`

Thanks for your help!

**Comment by mariusmotea** [comment]
Hi,

Please execute manually HueEmulator.py script (with sudo in front) and provide the output.

Marius.

**Comment by finnbennet** [comment]
Hey,
thanks a lot. It works after manually executing the script.

Finn

**Comment by mariusmotea** [comment]
Must work also as service, please ensure you put the correct path in systemd file, because the script try to load config.json file from that location, if is not specified it will not find.

Marius.

**Comment by finnbennet** [comment]
Sorry but I am quite new in this stuff. What do you mean with putting the correct path in the systemd file? Now, after I executed the script, I have the problem that I have to keep my pc connected via ssh. If I close putty, the bridge gets offline.

Finn

**Comment by mariusmotea** [comment]
```
Description=Hue Emulator Service
After=multi-user.target

[Service]
Type=idle

WorkingDirectory=/home/pi
ExecStart=/home/pi/HueEmulator.py

[Install]
WantedBy=multi-user.target
```

This is the systemd example file and it is woking if you put the script in /home/pi directory
if is in a different directory you need to change these:
`WorkingDirectory=`
and 
`ExecStart=`

in syslog you can see the error why this service fail, and this can help to debug also.

**Comment by hcnnet** [comment]
- some new issue, when I try to connection theg Bridge i get this in the output log!!

192.168.22.103 - - [01/Nov/2017 00:08:37] "GET /api/nouser/config HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.22.103', 49573)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./HueEmulator.py", line 1077, in do_GET
    if url_pices[2] in bridge_config["config"]["whitelist"]: #if username is in whitelist
KeyError: 'whitelist'
----------------------------------------

**Comment by mariusmotea** [comment]
You have a corrupted config.json file. whitelist key is mandatory to be present and in your configuration is missing. Download again the initial config.json file from this repository and after you configure the rooms, lights, sensors and/or routines made a backup of this file.

Marius.

**Comment by hcnnet** [comment]
Delete config.json - restart service - 
Setup Philips Hue - OK
Setup Tradfri - this in the log

````
----------------------------------------
Exception happened during processing of request from ('192.168.22.171', 54341)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_nobloc                     k
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./HueEmulator.py", line 932, in do_GET
    tradri_devices = json.loads(check_output("./coap-client-linux -m get -u \"Cl                     ient_identity\" -k \"" + get_parameters["code"][0] + "\" \"coaps://" + get_param                     eters["ip"][0] + ":5684/15001\"", shell=True).split("\n")[3])
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
----------------------------------------

````

**Comment by mariusmotea** [comment]
ok, ensure coap-client-linux file is in same location as HueEmulator.py and it has execution rights (you can do this with command `chmod +x coap-client-linux` ). All commands executed successfuly by coap-client-linux must return a json, in this case "No JSON object could be decoded" is telling us that the return was not a json. you can execute manually coap-client-linux to check communication with Tradfri Gateway with this command:
```
./coap-client-linux -m put -u "Client_identity" -k "fKWgOqcoOZuoDZGV" -e '{ "3311": [{ "5850": 0 }] }' "coaps://192.168.22.144:5684/15001"
```
Marius.

**Comment by hcnnet** [comment]
´´´´´
v:1 t:CON c:PUT i:85b6 {} [ ]
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 4 bytes cleartext
4.01

´´´´

**Comment by mariusmotea** [comment]
Sorry, instead of put it must be get, look this url :  
```
coap-client -m get -u "Client_identity" -k "1a2b3c4d5e6f7g8h" "coaps://192.168.0.10:5684/15001/65537"
```
Here is the url: https://learn.pimoroni.com/tutorial/sandyj/controlling-ikea-tradfri-lights-from-your-pi

This way you will ensure the communication to Tradfry gateway and secret key is correct.

Marius.

**Comment by hcnnet** [comment]
Thnx!! Veryfied the key 3 times - I will dig into the tutorial ..

**Comment by hcnnet** [comment]
https://community.home-assistant.io/t/hass-io-error-while-connecting-to-ikea-tradfri-gateway/31217

**Comment by mariusmotea** [comment]
oops, seams ikea gateway changed the api. I will try to fix it tonight or in this weekend. Currently i use Raspbee module for Raspberry pi to control Ikea devices and my tradfry gateway was decommissioned.

Marius.

**Comment by mariusmotea** [comment]
i made a first try to implement the new login api to tradfri gateway, but this is with informations from internet, nothing tested.

https://github.com/mariusmotea/diyHue/blob/develop/BridgeEmulator/HueEmulator.py

**Comment by mariusmotea** [comment]
I test this now and it seems to work, however there is a problem to add future lights but i will try to fix also this.

**Comment by hcnnet** [comment]
I will try' ..

**Comment by richardtrip** [comment]
Still working on this? I would be very pleased if I could also use my tradfri setup.

**Comment by mariusmotea** [comment]
I made some work on develop branch, but is not tested. I don't recommend this to be tested by regular users because it try to create the user hue-emulator (or something like that), if something goes wrong, the user remain created and you cannot start again from scratch because tradfri gateway don't allow you to create same user two times. As a secondary option this user can be renames in my script, but i'm not sure if a regular search and replace in script will allow you to rename the user in all functions and to start again from beginning. Secondary option is much worst, you will need to factory reset the tradfri gateway.

**Comment by mariusmotea** [comment]
Can you tell me if your MQTT broker is located on RPI, and if it has other options to publish the updates, others than MQTT protocol?

**Comment by richardtrip** [comment]
Ok, tested it (by editing the username) and it correctly detected my 4 bulbs. For now i'm happy and it will be no problem when adding extra bulbs.
