### ISSUE TITLE
Hue strips displayed as Bulbs

### ISSUE THREAD

**Issue by TimTower01** [mariusmotea/diyHue#79]
Can you change that neopixels are displayed as as an led strip in the lights overview in the app  instead of being diplaxed as a generic rgb ligt or add the ability to change the type of light in the script?

**Comment by mariusmotea** [comment]
Somehow i insert a bug, or new app version changed this, because this was already implemented. I check now my mobile phone and is true, my strips are displayed like bulbs. Will try to fix this.

**Comment by mariusmotea** [comment]
I fix this with last commit in develop branch. Please note that you must update also the lights firmware. Let me know if everything was working fine for you.

Marius.

**Comment by mariusmotea** [comment]
Fixed with last commit
