### ISSUE TITLE
Adding light on Wemos D1 mini not working

### ISSUE THREAD

**Issue by on4akh** [mariusmotea/diyHue#81]
Hi,

When in the HUE app I scan for lights, I get this problem:

192.168.1.114 is a hue bulb
is a new device
192.168.1.114 is unknow device 'modelid'
192.168.1.184 is unknow device HTTP Error 404: Not Found

Do I need to set a model id in the sketch ? If so, where an what ?

Thanks

**Comment by mariusmotea** [comment]
There was a major update, now hue modelid is set in lights firmware. You need to update HueEmulator.py if you want to use latest lights firmware.

**Comment by on4akh** [comment]
Hi, thanks for response. I think the problem is that in some of the lights firmware the modelID is not added as a response to 'detect' from the emulator. For example in Generic_RGB.

**Comment by mariusmotea** [comment]
True, i update now the Generic_RGB_light sketch.
Thanks for reporting this issue.

Marius.
