### ISSUE TITLE
Guide for modifying MiLight Bulbs

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#82]
Hi i tried to follow your guide and could get the bridge and a WS2812b LED-Stripe working. Works all perfect, great work.

Now i want to head over to build some Bulbs. Im interested in the MiLight bulb but i cant rly follow the instructions u gave. Could you maybe make a step by step guide with some more Pictures? Would be rly helpfull.

THX

**Comment by mariusmotea** [comment]
Hi,

I will try to take more pictures to my bulb today.

Marius.

**Comment by mariusmotea** [comment]
Can you provide a picture with PCB of your bulb. i will edit with points where you need to solder gpio  pins. Mine have the power supply and esp8266 glued and you cannot see the solder points. I recommend to use a ps like [this](https://www.aliexpress.com/snapshot/0.html?spm=a2g0s.9042647.6.2.hzXtoj&orderId=85796203212277&productId=32765853201) to avoid thermal issues

**Comment by oleg2204** [comment]
I dont have ordered one yet. I will first try with the AiLight (ordering tomorrow).
