### ISSUE TITLE
AiLight Support

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#83]
I stumbled across this AiLight Bulb  (infos here; http://tinkerman.cat/ailight-hackable-rgbw-light-bulb/)

Its a esp8266 Based Bulb which can be easily flashed. Maybe we can add some sketch for this particular bulb? I wasnt able to find the pins for RGBW yet...

**Comment by mariusmotea** [comment]
I take a look and it seams there is secondary chip for pwm output named MY9291QD, and there is a library available too. I will take a look tonight if is possible to implement it.

**Comment by oleg2204** [comment]
I digged a bit deeper into this topic and noticed a nice feature of that bulb. It is possible to upload a new sketch from arduino "over the air". So no need to connect any cables :=)

The Codepiece that seems to enable this feature is here:
https://github.com/stelgenhof/AiLight/blob/master/src/_ota.ino

Maybe this can be implemented for the lights too? This way it would be easy to make updates.

**Comment by mariusmotea** [comment]
Open arduino while the light is connected on the network and see if the ip appear under Tools -> Port. As you can see i enable Arduino OTA also and lights firmware updates can be applied also over the air (i always use this method after initial flash).

**Comment by oleg2204** [comment]
Oh sry i didnt try it actually :/   My bad

Great Work

**Comment by patjenl** [comment]
Has anyone had any success to put the MY92XX_RGBW_Light sketch on the AILight ? I have tried to flash this onto a AILight and the whole thing will not come alive (wifi and light not working).

**Comment by mariusmotea** [comment]
Is any output on serial console after firmware flash?

**Comment by patjenl** [comment]
It looks like it gets into a boot loop:
----
 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
----

I have tried flashing with different Arduino IDE settings but I'm not sure what the right settings are regarding "Flash Size". I tried all the default ones coming from the ESP8266 Board package.
Also added the "1M (NO Spiffs)".

Just flashed the Tasmota firmware again to check if the bulb is ok, that is working fine so does not look like a hardware failure.

**Comment by mariusmotea** [comment]
I don't have any AiLight bulbs, because it was requested i develop new sketch based on MY92XX library, but it was never tested. On the variables of this libraries are the connection pins, did you find out the ESP8266 pins where this chip is connected?

**Comment by patjenl** [comment]
I got this from [http://tinkerman.cat/ailight-hackable-rgbw-light-bulb/#lightbox-gallery-zPOw/12/]

#define MY92XX_DI_PIN       13
#define MY92XX_DCKI_PIN     15

**Comment by mariusmotea** [comment]
i will try to take a better look on this sketch, maybe i can find the problem.

**Comment by patjenl** [comment]
That is great. I'm using DIYhue to contol ws2812 strips and I must say .. great project !

Not sure if this will help ... but using below test sketch with the my9xx lib files works.

#include "my92xx.h"

#define MY92XX_MODEL    MY92XX_MODEL_MY9291
#define MY92XX_CHIPS    1                       // No daisy-chain
#define MY92XX_DI_PIN   13                      // DI GPIO
#define MY92XX_DCKI_PIN 15                      // DCKI GPIO

my92xx _my92xx = my92xx(MY92XX_MODEL, MY92XX_CHIPS, MY92XX_DI_PIN, MY92XX_DCKI_PIN, MY92XX_COMMAND_DEFAULT);

void setup() {
    _my92xx.setChannel(0, 255); // assume channel 0 is RED
    _my92xx.setState(true);
    _my92xx.update();
}

void loop() {}

**Comment by mariusmotea** [comment]
Based on your example i create this sketch https://pastebin.com/mmmR8Uea 
Can you test and confirm if is working or not?

**Comment by patjenl** [comment]
I'm afraid it is throwing the same error.

**Comment by bob808** [comment]
Does anyone know how to enable 12-16 bit operation on my92xx library? 8 bit is too low. I'm trying to calibrate the colors, and I need to run blue at about 1/7 from max output. During fading I have just a few tens of steps on blue and I can notice it.

**Comment by mariusmotea** [comment]
8 bit means 256 steps on every color, are you sure this is the problem? I can fell the difference only on very low brightness. Did you saw [this](https://github.com/xoseperez/espurna/issues/841)?

**Comment by bob808** [comment]
0-255 is the max range. If I want to calibrate the colors, I need to keep the one with the lowest intensity at full current (red), and dim green by 50%, and dim blue by 85%. This way I can get the best crossfading colors, because for our eyes that's they way it looks best.
15% of 256 is 38 steps. I can definitely notice 5bit on blue.
I know about esp8266 and led pwm but in this situation the leds are controlled by my9291, and that's a 16bit device. I don't thing there's anything about esp8266 and pwm involved here.

**Comment by cheesemarathon** [comment]
Has this progressed any further anyone?

**Comment by cheesemarathon** [comment]
Closing this for now, as it's not progressing anywhere. I have added the issue to the Suggested Features project board so it can be picked up in the future.
