### ISSUE TITLE
Which GPIO corresponds to which color generic RGBW

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#84]
Hello, finally some long awaited parts have arrived and i made a quick test build of a RGBW strip controller. However the colors dont seem correct at first glance. I found the GPIOs to use in the sketch, but as far as i could see there wasn't any guidance on which color corresponds to which GPIO?

On a related question, are the sketches pre tuned/calibrated? I have another build with a ws2812b strip and it behaves correctly, just that the colors are kinda "dull". I've used the same strip in other builds so i know it can be more intense. If so, any simple way to make the sketch neutral again for testing purposes?

**Comment by mariusmotea** [comment]
Hi,
Red = 1st pin in gpio pin array
Green = second pin
Blue = 3rd pin
White  = 4th pin

There is no calibration, each led type require is own conversion formula for proper color reproduction, what is currently used is the default formula from wikipedia. BTW this was changed one month ago in order to have more powerfull colors.

**Comment by erazor666** [comment]
Hi again, thanks for your fast reply as always.
Is there any way GPIO15 (D8 on my wemos) can be used instead of GPIO5 (D1 on wemos)? I'm making a PCB and it would simplify the design a whole lot. I know on other boards that not all GPIOs are pwm capable and some can even share pwm channel. So this may turn out to be more of a Wemos question maybe(?) I'm planing on using Wemos D1 minis for this project.

**Comment by mariusmotea** [comment]
Yes, it can be used, but keep in mind that there is a 10kohm resistor to ground on gpio 15. Check dimming sketch to see how it was used.

Marius.
