### ISSUE TITLE
Startup Systemd File Retry on Fail modification

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#85]
I came across some problems with the Service file.
My Raspberry takes a bit to get a dhcp ip from my router. Meanwhile the service starts and fails at "getIpAddress()". I modified the Service File to try to restart the Service after a fail.

Here my modified version:

Description=Hue Emulator Service
After=multi-user.target

[Service]
Type=idle
Restart=always
RestartSec=30
StartLimitInterval=200
StartLimitBurst=5

WorkingDirectory=/home/pi
ExecStart=/home/pi/HueEmulator.py

[Install]
WantedBy=multi-user.target

It retrys to start the service after a fail 5 times with a delay of 30 seconds each time. Maybe add this to the Wiki?

**Comment by mariusmotea** [comment]
Thanks, this looks very good. I will update the wiki with it.

Marius.

**Comment by mariusmotea** [comment]
wiki updated
