### ISSUE TITLE
Generic_Dimmable_Light building

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#88]
Hi again,
I'm trying to build the "Generic Dimmable Light" as far as i understand this would be for dimming a led strip that has only one color?

Looking at the sketch there are 2 GPIO's defined. Are you supposed to use both? 
I would think you run the GPIO to a mosfet with a resistor to ground like "usual" (?)

The sketch doesnt seem to bring up the wifimanager "new hue light" access point like the RGBW one does.

The serial monitor outputs this (over and over)

> ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> 
> load 0x4010f000, len 1384, room 16 
> tail 8
> chksum 0x2d
> csum 0x2d
> v3de0c112
> ~ld

**Comment by mariusmotea** [comment]
You can use up to 6 lights for every esp. If you want to use just one then leave there only one gpio pin (comment the rest) and set lightsCount variable to 1. After you setup the wifi networking then you must perform a light search from hue application and the light must be detected. Ensure you use latest version because i change something a few weeks ago in lights firmware and HueEmulator.py (modelid to emulate dimmable lights as dimmable, previews all where emulated as color lights).

**Comment by erazor666** [comment]
My gateway is latest version. I recently built the rgbw one and it works great. I'm planing to make a guide for this commuinty with how i made the pcb, what parts to use and pictures.

The problem is that i cant get the esp to make its accesspoint "new hue light" that i'm used to. Looking at the sketch it was possible to set ip manually. It says enable these 3 lines and 72. On 72 is in the middle of a block of code and nothing commented out.
This was a brand new wemos d1 mini out of the box. Sketch verifies in arduino ide and everything looks good. The light on the esp will blink every second or so after flashing, dont think the RGBW one behaved like this.

**Comment by mariusmotea** [comment]
I don't use this so far, but i remember i test it. i will check in a few hours when i will arrive home, but somebody else already used this and confirm that is working.

**Comment by mariusmotea** [comment]
//WiFi.config(strip_ip, gateway_ip, subnet_mask);

This si the line that need to be added to use static ip, but i doubt this will solve the problem

**Comment by erazor666** [comment]
All i could find was the serial monitor output and it didnt mean much to me. Is the sketch fundamentally different from the rgbw one, or could i possibly comment away all but one gpio from that one?

**Comment by mariusmotea** [comment]
Serial monitor will not help because there are no debugging serial.print commands.  The sketch is a hybrid between neopixel sketch and pwm sketch. From neopixel was used the function to declare and use multiple lights, but the control is made using pwm library instead of neopixel by Makuna.

**Comment by mariusmotea** [comment]
I recommend you to to try this:
Wipe entire spi flash on esp, because wifi credentials are stored at the end of the flash, even if you write the firmware again it will still use the previews wifi credentials. After this you must see ssid "New Hue Light". Configure your wifi network and check if esp will join in a few seconds after reboot. If join, it will request ip from dhcp server. If ip is set open in browser that ip to see light webgui. Try to turn on/off the light.

**Comment by erazor666** [comment]
I see. I will try this later today. However, it was as said a new wemos that never had a sketch in it and I never got to input any credentials in the first place :)

**Comment by Mevel** [comment]
@mariusmotea wifi Manager does print on serial Port even without explicit print commands. Enabling serial in setup is all it needs.

**Comment by erazor666** [comment]
This isnt strictly related to the problem but if you set lightsCount 1 the sketch doesnt compile for me

> error: too many initializers for 'uint32 [1][3] {aka unsigned int [1][3]}'
> 
>  };
> 
>  ^
> 
> hue-ww-dim:26: error: too many initializers for 'uint32 [1] {aka unsigned int [1]}'
> 
>  uint32 pwm_duty_init[lightsCount] = {0, 0};
> 
>                                           ^

> 
> exit status 1
> too many initializers for 'uint32 [1][3] {aka unsigned int [1][3]}'
>

**Comment by mariusmotea** [comment]
here you find a real issue that need to be fixed.
Put `uint32 pwm_duty_init[lightsCount] = {0};`

because you have just one value. i will update with a for loop to apply automatically to all lights.

**Comment by erazor666** [comment]
This makes it compile again, correct
> #define lightsCount 1 

> // initial duty: all off 
> uint32 pwm_duty_init[lightsCount] = {0};

I doubt it fixes the wifi problem however :)

**Comment by mariusmotea** [comment]
Please close this issue if you will not find any other issue. commit https://github.com/mariusmotea/diyHue/commit/7da9bca8e743a475df52f8709641c17e76f6fa43 must fix it.
