### ISSUE TITLE
HTTP Control of lights

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#92]
I'm trying to control a light via the HTTP syntax in the wiki

` http://10.0.0.175/set?light=1&r=255&g=0&b=0&transistiontime=2000`
Should turn it on and red color to max, nothing happens to the light and i get the reply: 
`OK, x: 0.46, y:0.41, bri:77, ct:500, colormode:0, state:0`

`http://10.0.0.175/set?light=1`
still no light and reply:
`OK, x: 0.46, y:0.41, bri:77, ct:500, colormode:0, state:0`

Something i'm not doing correctly? Both a ws2812b based strip and a regular WW strip tested, they both work in official hue app etc.

**Comment by mariusmotea** [comment]
The light seams to be tuned off. Try to turn on first. I believe if you change the brightness it will automatically turn on.

**Comment by erazor666** [comment]
Well doesnt the set?light=1 turn it on?
If not whats the "turn on" syntax? http://10.0.0.175/?on=false (or true) like the webpage for the light will generate?

I'm trying a lightswitch approach with EspEasy, it can send http commands for instance when a GPIO gets grounded.

**Comment by mariusmotea** [comment]
if you check HueEmulator output you can see the url requests to lights:

`http://10.0.0.175/set?light=1&on=true`
`http://10.0.0.175/set?light=1&on=true&ct=200&bri=50`

**Comment by erazor666** [comment]
When i try to access the gateway (diyhue) on its ip adress like described on hue webpage:
`http://10.0.0.208/debug/clip.html`
i get
`[{"error": {"type": 1, "description": "unauthorized user", "address": "/debug/clip.html"}}]`

anything i missed, do i have to authenticate with the gateway somehow?

**Comment by mariusmotea** [comment]
I will provide you more info. First to control the gateway you need an user. Every hue app create his own user and you can use the hash of any to control the hue emualtor. Open config.json and copy one hash from config-> whitelist
then:
```
curl -X PUT -d '{"on": true, "ct": 200}' http://10.0.0.208/api/123sdafajhk3jhsajgasdhgashjaasdas/lights/1
```
`123sdafajhk3jhsajgasdhgashjaasdas` is one whitelist from config, choose one random.
`lights/1` you will tell to apply this just to light with id 1. If you want to apply this to a group of lights use `groups/1` instead.
