### ISSUE TITLE
Lightstrip dont remembers last State

### ISSUE THREAD

**Issue by oleg2204** [mariusmotea/diyHue#93]
On powercycle the lightstrip dont shows the last state it was in.

For example:  I use the official Hue app and set a color. Than i power off the light strip. Power it back on. Now the lightstrip stay off. Shouldnt it load the old state and turn on the same color again?

Also when i turn on the "Room" in the official Hue app the lightstrips dont turn on and i need to set the brightness to full to make them turn on. Thats a bit annoying

**Comment by mariusmotea** [comment]
Hi,

The lights (all) don't store the color change in flash or eeprom so in case of power loos to know what was exactly the last state. While is possible, it will damage light flash, becase all flash memory don't support infinite writes. But there are options that i believe you did not discover so far. Every light has an internal webgui. From there you can choose the power on behavior and there are three options:
 - On = the light will turn on to the selected scene (all default hue scenes are stored in light firmware)
 - Off = default, light will remain off
 - Last state = if light was on last time, it will turn on to the default selected scene, it was off it will remain off. Here for pwm lights there is a bug, every on/off operation write this in eeprom, and there will be a short flash when this happen.
