### ISSUE TITLE
"Press the hue button" not always working.

### ISSUE THREAD

**Issue by sjgoalie** [mariusmotea/diyHue#95]
As we were discussing in another thread, I'm having trouble with some apps saying "press the button".  I moved the discussion here to get out of that other thread.

Here is my log, this run I started fresh, waited a moment then ran the Smartthings app and told it to add a device.  The app mentions pressing the button on the hue hub, but I never get a response from the emulator.

[out_11_17.txt](https://github.com/mariusmotea/diyHue/files/1483469/out_11_17.txt)

**Comment by mariusmotea** [comment]
Ok, so basicaly i see the pair stop at `GET /description.xml`.
the pair process is made of 3 steps:
1. ssdp discover - most complex, this pass
2. request /description.xml - most basic step, but somehow this fail)
3. POST to /api to register a new user. Here if the "button" is not pressed it will ask to press the button, but we dont arrive here

Can you try to run ha-bridge to see if this emulator will be detected? This way i will see the differences and made the correction.

Marius.

**Comment by sjgoalie** [comment]
Yes, it sees the ha-bridge within about 2 seconds.

**Comment by mariusmotea** [comment]
Ok, i will compare the output and i will fix this.

**Comment by mariusmotea** [comment]
Check develop branch, i update the content of description.xml and now is almost identical with ha-bridge (only serial number is different).
The commit is this https://github.com/mariusmotea/diyHue/commit/6a35a039e2a3581598f1ed72a3c09a6b31314d93

**Comment by mariusmotea** [comment]
Any feedback?

**Comment by sjgoalie** [comment]
Sorry, I have guests in town for the holidays, I'll try it this afternoon

**Comment by sjgoalie** [comment]
Still behaving the same, here's the latest log.


[out.11_21.txt](https://github.com/mariusmotea/diyHue/files/1493537/out.11_21.txt)

**Comment by mariusmotea** [comment]
ok, same issue, remain stuck at description.xml . i will go forward, maybe is looking also to serial number that must have unique prefix because is generated from mac address, and if this is not the expected one, it fail.

**Comment by mariusmotea** [comment]
I push a new update:
https://raw.githubusercontent.com/mariusmotea/diyHue/develop/BridgeEmulator/HueEmulator.py

**Comment by sjgoalie** [comment]
No change in the Smartthings app.  new log...

[out.11_24.txt](https://github.com/mariusmotea/diyHue/files/1501007/out.11_24.txt)

**Comment by subnoize417** [comment]
Any progress on this issue? Can't get my smartthings to pick up the emulator either, no issues discovering it with other apps. I did change the MAC of the virtual machine running the emulator to start with 00:17:88 like my real bridge v2, that made no apparent difference. If there's something you need tested let me know, I'll upload logs, packet captures, anything that may help.

**Comment by mariusmotea** [comment]
Hi,

did you tested with latest commit made last days in master?

Marius.

**Comment by subnoize417** [comment]
Yes, 100% up to date with master. Copied down the logs, as well as a wireshark capture of the smartthings hub and emulator's communication. Had to add .txt to attach it.
for reference 192.168.10.191 is your emulator, 192.168.10.138 is smartthings

[wireshark between smartthings hub and emulated bridge.pcap.txt](https://github.com/mariusmotea/diyHue/files/1537128/wireshark.between.smartthings.hub.and.emulated.bridge.pcap.txt)

[12-6-17-1722.txt](https://github.com/mariusmotea/diyHue/files/1537125/12-6-17-1722.txt)

**Comment by mariusmotea** [comment]
can you provide me the output of your real hue bridge when you perform curl -v http://x.x.x.x/description.xml ?

**Comment by sjgoalie** [comment]
*   Trying X.X.X.X...
* TCP_NODELAY set
* Connected to X.X.X.X (X.X.X.X) port 80 (#0)
> GET /description.xml HTTP/1.1
> Host: X.X.X.X
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-type: text/xml
< Connection: Keep-Alive
* no chunk, no close, no size. Assume close to signal end
<
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://X.X.X.X:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Philips hue (X.X.X.X)</friendlyName>
<manufacturer>Royal Philips Electronics</manufacturer>
<manufacturerURL>http://www.philips.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2012</modelName>
<modelNumber>929000226503</modelNumber>
<modelURL>http://www.meethue.com</modelURL>
<serialNumber>00XXXXXXXX</serialNumber>
<UDN>uuid:2f40XXXX-XXXX-XXXX-XXXX-00178XXXXXX</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>
* Curl_http_done: called premature == 0
* Closing connection 0

**Comment by mariusmotea** [comment]
i believe the output was truncated, it must be a valid xml like the one from here: https://github.com/SteveyO/Hue-Emulator/blob/master/resources/description.xml

**Comment by subnoize417** [comment]
curl output attached
[deecription.xml.txt](https://github.com/mariusmotea/diyHue/files/1545036/deecription.xml.txt)

**Comment by sjgoalie** [comment]
`*   Trying 10.1.2.32...
* TCP_NODELAY set
* Connected to 10.1.2.32 (10.1.2.32) port 80 (#0)
> GET /description.xml HTTP/1.1
> Host: 10.1.2.32
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-type: text/xml
< Connection: Keep-Alive
* no chunk, no close, no size. Assume close to signal end
<
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://10.1.2.32:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Philips hue (10.1.2.32)</friendlyName>
<manufacturer>Royal Philips Electronics</manufacturer>
<manufacturerURL>http://www.philips.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2012</modelName>
<modelNumber>929000226503</modelNumber>
<modelURL>http://www.meethue.com</modelURL>
<serialNumber>001788114876</serialNumber>
<UDN>uuid:2f402f80-da50-11e1-9b23-001788114876</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>`

**Comment by subnoize417** [comment]
@mariusmotea mine is still not working, would you like me to open a separate issue? Wish I knew python better so I could help more and figure this out

**Comment by mariusmotea** [comment]
ok, open new issue. I believe i will be able to fix this with our help, because you have a real hue bridge and we can see where is the difference. So far i saw the discover is stuck at description.xml

**Comment by mariusmotea** [comment]
i push a new update in develop branch to have identical description.xml like your hue bridge (except ip and serial number)
