### ISSUE TITLE
Any tips for decent/budget wifi bulbs?

### ISSUE THREAD

**Issue by erazor666** [mariusmotea/diyHue#97]
Wondering what bulbs people have tested from ali express and such places
ESP8266 based preferably.

**Comment by mariusmotea** [comment]
I have 3 x [Feican 7W bulbs](https://www.aliexpress.com/store/product/AC85-240V-5W-7W-9W-RGBW-WIFI-LED-Bulb-Light-Colorful-Dimmable-LED-Light-Support-IOS/1293050_32785628736.html?spm=2114.12010608.0.0.79172d1f1ER1Qw), but i'm not that impressed. I convert one MiLight FUT15 (8W) to esp8266 and for me this is perfect. If you have led ceiling lamps you can convert them to esp8266 very easy with [this](https://www.aliexpress.com/item/KINLAMS-2-4G-Remote-Control-Driver-36W-round-Aluminum-plate-Magnetic-ceiling-Light-LED-Board-Panel/32824171287.html?spm=a2g0s.9042311.0.0.7dcPSO) (I see now is very expensive, i buy one with 17$)  
These are the only wifi bulbs that i have, now i buy also some IKEA zigbee ones, that are not expensive.

**Comment by kurniawan77** [comment]
How about the sonoff B1. A nice review over here, http://tinkerman.cat/sonoff-b1-lights-and-shades/

They have cold white and warm white, which i find more important, but too bad the colors are too weak. 

Here's an comparison with other wifi bulbs... http://tinkerman.cat/yet-another-wifi-light-bulb/
 too bad the rest lacks the warm white channel....

**Comment by erazor666** [comment]
I have some sonoff i ordered, the problem is there is a new model board or something. They wouldnt flash, lots of other people reported the same problem with them. (These were on/off sonoffs, the simplest model). Seems things need a WW channel, tried with RTBW strips, thinking that you can always add yellow to make it warm, was not happy with the result, they go into green before they get warm. Have rgbww strips on order now :)

**Comment by mariusmotea** [comment]
> They wouldnt flash, lots of other people reported the same problem with them

I was believed the same for Feican bulbs, but was only me that made the wrong connection. I believe it will work if you pay attention to connect GPIO0 to groung. On boot esp check the state of this pin, if is connected to ground it will enter in flash mode. If you connect gpio0 to ground after you power on the bulb, then you must perform a reset with short GND to RST pin, then the device will enter in FLASH mode. From here everything is simple, connect TX, RX, GND, VDD to serial adapter and flash the chip. Must pay attention of flash size, if it has just 512kb, then remove from sketch Arduino OTA and maybe the internal webgui static content so it can fit on 512kb flash.

**Comment by oleg2204** [comment]
I ordered the AiLight of Tinker. Here is a link to some nice pricing: https://www.ebay.de/itm/282493181154
My order will arrive tomorow. I will try to adjust the lightbulb sketch to work with the bulb and try to get it working. I report back once its finished.

**Comment by mariusmotea** [comment]
The challenge is to implement MY9291 library.

If this example will work, then it will be easy:

```
#include &amp;amp;amp;lt;my9291.h&amp;amp;amp;gt;
 
#define MY9291_DI_PIN   13
#define MY9291_DCKI_PIN 15
 
my9291 _my9291 = my9291(
    MY9291_DI_PIN, 
    MY9291_DCKI_PIN, 
    MY9291_COMMAND_DEFAULT
);
 
void setup() {
    _my9291.setColor((my9291_color_t) { 255, 0, 0, 0 });
    _my9291.setState(true);
}
 
void loop() {}
```

**Comment by oleg2204** [comment]
I found this better documented library: https://github.com/mertenats/AI-Thinker_RGBW_Bulb
I will take a look today after work.

**Comment by kurniawan77** [comment]
Or try this one https://github.com/stelgenhof/AiLight/blob/master/README.md

Has a great webui and works well with Home-Assistant

**Comment by mariusmotea** [comment]
Hi,
Based on the library from [here](https://github.com/xoseperez/my92xx) that seems to be most up to date , i  upload a sketch in develop branch. This is compiling but for sure it require some work, all pins need to be correctly specified. Fell free to update this with pull requests.

**Comment by cad435** [comment]
Anyone can say something about this bulb?

ARILUX® E27 7W RGBW WIFI
https://banggood.app.link/Cj3CZr5FkI

I have a Milight wich i get running with a MilightHub, but they are not really statisfying...

I may concert Thema to ESP8266 but since its the 6W Milight its not much room...

Can someone tell me if any Milight-bulb has the same "controller board" in it?

I may layout a fitting PCB to solder them directly...

**Comment by cad435** [comment]
Ok, I searched around a bit and found this post:
http://tinkerman.cat/yet-another-wifi-light-bulb/

So, it seems Arilux, Sonoff, Noduino Open Light and AiLight Wifi bulbs are all based ESP8266 and use the MY9291 driver, so I strongly support the implementation of the MY9291 Driver :)

I guess I'll order a AI-Light today...

**Comment by mariusmotea** [comment]
Once arrived you can test [this](https://github.com/mariusmotea/diyHue/tree/develop/Lights/Arduino/MY92XX_RGBW_Light)  but only after you setup the pins variables, now there are some default values.
```
#define MY92XX_CHIPS        1
#define MY92XX_DI_PIN       12
#define MY92XX_DCKI_PIN     14
uint8_t PWM_PINS[PWM_CHANNELS] = {4, 3, 5, 6}; //RGBW order
```

**Comment by oleg2204** [comment]
My AILight still didnt arrive  -.-  i will test as soon as i got it

**Comment by mariusmotea** [comment]
Still no news about AILight bulbs?

**Comment by cad435** [comment]
I converted my MiLight successfully to a ESP-based one, so I have no need to buy a AI-light anymore...

What I'll do, If I order a new batch of PCBs I'll order some prototype boards for controlling LED-strips with a ESP-12 and some mosfets...
I'll report back if they are here, I guess I will have some spare I may sell them...

Don't know yet, I'll see... 

If you guys have intrest, I can order a few more :)

**Comment by oleg2204** [comment]
My AILight arrived and i started soldering. At the 3.3v connection i killed the bulb :( the solderpad just went of.... These solderpads are way to tiny to solder anything. Cant recommend the ailight :( I will order a milight and try that

**Comment by ZaxCZ** [comment]
Any updates? What are the best value bulbs? Are the IKEA bulbs worth it?

Sorry for asking here, I just found about this project after researching RGB bulbs and I am considering getting some. Can't decide though.

**Comment by mariusmotea** [comment]
Hi,

Ikea bulbs are good, but you will need Raspbee module (or Conbee) for communication with zig bee devices. I have 8 Ikea tradfri bulbs but the main reason why i buy the raspbee module was for ikea sensors and remotes. If you are looking for wifi bulbs, i used Feican ones, but i was not so happy because of the low light  (for 7W bulb). The only wifi lights that i use currently is a [ceiling light ](https://www.aliexpress.com/item/KINLAMS-2-4G-Remote-Control-Driver-36W-round-Aluminum-plate-Magnetic-ceiling-Light-LED-Board-Panel/32824171287.html?spm=a2g0s.9042311.0.0.iJlsH0) (that is great),  milight FUT15 (converted to wifi also great) and several WS8212 strips.

**Comment by ZaxCZ** [comment]
Thanks, I'm going to order one 9W Feican to start with. Then I might get one IKEA bulb to compare it to before investing in the zigbee module. Offtopic: Do you consider WiFi a viable option in the future of led bulbs? ZigBee seems better to me in terms of range, but it's more expensive. Will we ever see a ZigBee compatible device not licensed by them?

**Comment by mariusmotea** [comment]
Be aware about the size of the 9W Feican bulb, 7W is the regular size, 9W for sure is bigger and may not fit in all lamps. You will need an serial adapter to flash the firmware. If you are skilled i recommend to replace the flash chip inside the bulb with the one from another ESP board (pre flashed) because the default one will not allow future firmware upgrades over the air. However firmware releases  are rare and in general not mandatory.

More details you have here #26

**Comment by ZaxCZ** [comment]
Thanks for the info. I already have serial adapter and several ESPs lying around, my soldering isn't stellar but I might be able to do it. Unfortunately the Feican bulbs are no longer available on [aliexpress](https://www.aliexpress.com/item/AC85-240V-5W-7W-9W-RGBW-WIFI-LED-Bulb-Light-Colorful-Dimmable-LED-Light-Support-IOS/32785628736.html) and I can't find them elsewhere.

**Comment by mariusmotea** [comment]
if you have ESPs then converting MiLight FUT15 (CCT-RGB) to ESP is not that hard. I upload one image. Proper conversion is done with micro buck converter to 3,3v to power the esp, the internal ps provide just 30mA, but until i received the buck converter it was working just fine with an extra 47uF capacitor.

**Comment by Lhonco** [comment]
@mariusmotea and @cad435
Do you have some more details on how to convert a Milight bulb to Esp8266?
How to power it, what to look for, safety measurements for heat issuses etc.
I would like to convert mine, but I’m not very confident in how to do it and don’t want to set my house on fire...

**Comment by Lhonco** [comment]
Thank you for this extensive answer, I might try it some time!

**Comment by cheesemarathon** [comment]
Hi @erazor666 
Can you close this for now? I'll create a channel in slack for further conversation on lights.
