### ISSUE TITLE
Lights won't work with some nodemcu / d1s

### ISSUE THREAD

**Issue by mcer12** [mariusmotea/diyHue#98]
I can't wrap my head around this. Everything looks OK, lights show in hue app, status led makes white and green wave, server works. I can even restart the light module and status led blinks again. But the lights just won't come up. Doesn't matter if i switch it from the app or directly through IP address. I should also mention that the status led blinks through all of the strip leds, so its not a ws2812 problem.

Sketch works on one NodeMCU, but doesnt work on others.

**Comment by Mevel** [comment]
How many LEDs do you try to Power on?
Had some trouble powering 137 LEDs through the USB Port. The traces didn't like that much current. (getting hot) 
Solution was cutting the USB cable and making a small pcb connecting the Power to Vin and the WS2812 in combination with a 10uF capacitor.

**Comment by mcer12** [comment]
I don't power it through usb, it has its own 5v power source. It's has 100 leds and it runs just ok on full brightness. I should add that I also tried this with one single led powered from usb with same result. I also tried other neopixelbus methods on different pins, none of which made any difference :(

**Comment by mcer12** [comment]
Sample neopixelbus sketches and my own sketches work flawlessly.

**Comment by mariusmotea** [comment]
What version of neopixel bus are you using? What version or Arduino?

**Comment by mariusmotea** [comment]
How much flash memory have your board, some come with 512kb and require to remove OTA update future to fit.

**Comment by mcer12** [comment]
Its all 4MB, I think nodemcus dont even come with smaller memory anymore.
Arduino 1.8.2
Neopixelbus 2.2.8
I try to update it and post the result after.

**Comment by Mevel** [comment]
Make sure serial.begin(Baud) is before strip.begin in setup Function as it uses RX pin of esp8266 and serial.begin reconfigures the Pins if placed after strip.begin

**Comment by mcer12** [comment]
OK so I updated neopixel lib and arduino IDE and no change.

@Mevel There is no serial in the sketch, I use the library sketch for WS28112B as it is, only with NeoEsp8266UartWs2813Method since i have WS2813s. Please bear in mind that my other sketches work OK with the strip so I don't think its an issue with strip itself.

**Comment by mariusmotea** [comment]
Ok, so i just upgrade my Arduino from 1.8.1 to 1.8.2, Neopixelbus was already 2.2.8 and my Wemos D1 mini with 60 WS28112B are still working fine. I use the sketch directly from [here](https://raw.githubusercontent.com/mariusmotea/diyHue/develop/Lights/Arduino/WS2812BHueStrip/WS2812BHueStrip.ino)

Even if i don't have any serial prints in my code, some library have this by default. I believe WiFi manager is one of them, but this is initialized first.

What you can try:
Compile the sketch from different OS. I did from Linux now, but OSX was always working from me. Erase entire flash before to upload the sketch.

**Comment by mcer12** [comment]
@mariusmotea @Mevel I think I found the cause. Looks like the Uart method doesnt work with your sketch OR it might be something with the GPIO2 on Wemos D1 (possibly other nodemcu boards too). 
I found this topic that might be relevant: https://github.com/mtongnz/ESP8266_ArtNetNode_v2/issues/29
Luckilly I had GPIO3 available, so I just resoldered it in my setup. Might be worth checking out but I consider it solved.

Thank you guys for the effort to help!

**Comment by mariusmotea** [comment]
In my sketch RX pin must be used because only this one has hardware support. Other gpio pins will work but everything is done software.

**Comment by Mevel** [comment]
As Marius said. You need to use GPIO3 or RX due to hardware limitations.

From NeoPixelTest.ino
>For Esp8266, the Pin is omitted and it uses GPIO3 due to DMA hardware use.  
There are other Esp8266 alternative methods that provide more pin options, but also have
other side effects.
NeoPixelBus<NeoGrbFeature, Neo800KbpsMethod> strip(PixelCount);

**Comment by mcer12** [comment]
Thanks, closing.
